# Generated by Django 5.2.5 on 2025-09-02 11:51

import apps.products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('sort_order', 'name'), 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productbundle',
            options={'ordering': ('name',), 'verbose_name': 'Product Bundle', 'verbose_name_plural': 'Product Bundles'},
        ),
        migrations.AlterModelOptions(
            name='productbundleitem',
            options={'ordering': ('created_at',), 'verbose_name': 'Product Bundle Item', 'verbose_name_plural': 'Product Bundle Items'},
        ),
        migrations.AlterModelOptions(
            name='productprice',
            options={'ordering': ('billing_period', 'amount_cents'), 'verbose_name': 'Product Price', 'verbose_name_plural': 'Product Prices'},
        ),
        migrations.AlterModelOptions(
            name='productrelationship',
            options={'ordering': ('sort_order', 'created_at'), 'verbose_name': 'Product Relationship', 'verbose_name_plural': 'Product Relationships'},
        ),
        migrations.AlterField(
            model_name='product',
            name='meta',
            field=models.JSONField(blank=True, default=dict, help_text='Additional product metadata', validators=[apps.products.models.validate_json_field]),
        ),
        migrations.AlterField(
            model_name='product',
            name='module_config',
            field=models.JSONField(blank=True, default=dict, help_text='Module-specific configuration for provisioning', validators=[apps.products.models.validate_product_config]),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Tags for filtering and search (as JSON array)', validators=[apps.products.models.validate_json_field]),
        ),
        migrations.AlterField(
            model_name='productbundle',
            name='meta',
            field=models.JSONField(blank=True, default=dict, validators=[apps.products.models.validate_json_field]),
        ),
        migrations.AlterField(
            model_name='productbundleitem',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Product configuration within bundle', validators=[apps.products.models.validate_json_field]),
        ),
        migrations.AlterField(
            model_name='productrelationship',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Relationship-specific configuration', validators=[apps.products.models.validate_json_field]),
        ),
    ]
