# Generated by Django 5.2.12 on 2026-03-11 15:11

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Campaign name for identification', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Campaign description and purpose')),
                ('audience', models.CharField(choices=[('all_customers', 'All Customers'), ('active_customers', 'Active Customers'), ('inactive_customers', 'Inactive Customers'), ('overdue_payments', 'Overdue Payments'), ('trial_expiring', 'Trial Expiring'), ('custom_filter', 'Custom Filter')], default='active_customers', help_text='Target audience for this campaign', max_length=20)),
                ('audience_filter', models.JSONField(blank=True, default=dict, help_text='Custom filter criteria for audience selection')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='draft', help_text='Current campaign status', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='When to send this campaign (leave blank for immediate)', null=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='When campaign sending actually started', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When campaign sending completed', null=True)),
                ('total_recipients', models.PositiveIntegerField(default=0, help_text='Total number of recipients')),
                ('emails_sent', models.PositiveIntegerField(default=0, help_text='Number of emails successfully sent')),
                ('emails_failed', models.PositiveIntegerField(default=0, help_text='Number of emails that failed to send')),
                ('is_transactional', models.BooleanField(default=False, help_text='Transactional emails (billing, service) vs. marketing')),
                ('requires_consent', models.BooleanField(default=True, help_text='Requires explicit customer consent (GDPR compliance)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Campaign',
                'verbose_name_plural': 'Email Campaigns',
                'db_table': 'notification_email_campaigns',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('to_addr', models.EmailField(help_text='Recipient email address', max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('from_addr', models.EmailField(blank=True, help_text='Sender email address (if different from default)', max_length=254)),
                ('reply_to', models.EmailField(blank=True, help_text='Reply-to email address', max_length=254)),
                ('template_key', models.CharField(blank=True, help_text='Template used to generate this email', max_length=100)),
                ('subject', models.CharField(help_text='Actual email subject sent', max_length=255)),
                ('body_text', models.TextField(blank=True, help_text='Plain text version of email body')),
                ('body_html', models.TextField(blank=True, help_text='HTML version of email body')),
                ('body_encrypted', models.BooleanField(default=True, help_text='Whether body fields are encrypted at rest')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('bounced', 'Bounced'), ('soft_bounced', 'Soft Bounced'), ('complained', 'Complained'), ('failed', 'Failed'), ('rejected', 'Rejected')], default='queued', help_text='Current delivery status', max_length=20)),
                ('provider', models.CharField(default='smtp', help_text='Email service provider (smtp, sendgrid, mailgun, etc.)', max_length=50)),
                ('provider_id', models.CharField(blank=True, help_text="Provider's unique message ID", max_length=255)),
                ('provider_response', models.JSONField(blank=True, default=dict, help_text='Raw provider response for debugging')),
                ('sent_at', models.DateTimeField(auto_now_add=True, help_text='When email was queued/sent')),
                ('delivered_at', models.DateTimeField(blank=True, help_text='When email was confirmed delivered', null=True)),
                ('opened_at', models.DateTimeField(blank=True, help_text='When email was first opened (if tracking enabled)', null=True)),
                ('clicked_at', models.DateTimeField(blank=True, help_text='When email links were first clicked', null=True)),
                ('meta', models.JSONField(blank=True, default=dict, help_text='Additional email metadata (variables used, campaign info, etc.)')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', help_text='Email priority level', max_length=10)),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'db_table': 'notification_email_logs',
                'ordering': ('-sent_at',),
            },
        ),
        migrations.CreateModel(
            name='EmailPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transactional', models.BooleanField(default=True, help_text='Receive transactional emails (invoices, receipts)')),
                ('billing', models.BooleanField(default=True, help_text='Receive billing notifications (payment reminders)')),
                ('service', models.BooleanField(default=True, help_text='Receive service notifications (provisioning, changes)')),
                ('security', models.BooleanField(default=True, help_text='Receive security alerts (login attempts, 2FA)')),
                ('marketing', models.BooleanField(default=False, help_text='Receive marketing emails (requires explicit consent)')),
                ('newsletter', models.BooleanField(default=False, help_text='Receive newsletter (requires explicit consent)')),
                ('product_updates', models.BooleanField(default=True, help_text='Receive product update notifications')),
                ('marketing_consent_date', models.DateTimeField(blank=True, help_text='When marketing consent was given', null=True)),
                ('marketing_consent_source', models.CharField(blank=True, help_text='How consent was obtained (signup, preference_center, etc.)', max_length=100)),
                ('global_unsubscribe', models.BooleanField(default=False, help_text='Globally unsubscribed from all non-essential emails')),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('unsubscribe_reason', models.CharField(blank=True, max_length=255)),
                ('notification_frequency', models.CharField(choices=[('immediate', 'Immediate'), ('daily_digest', 'Daily Digest'), ('weekly_digest', 'Weekly Digest')], default='immediate', help_text='How often to receive non-urgent notifications', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Preference',
                'verbose_name_plural': 'Email Preferences',
                'db_table': 'notification_email_preferences',
            },
        ),
        migrations.CreateModel(
            name='EmailSuppression',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_hash', models.CharField(db_index=True, help_text='SHA-256 hash of the suppressed email address', max_length=64, unique=True)),
                ('email_encrypted', models.TextField(blank=True, help_text='Encrypted original email (for support requests)')),
                ('reason', models.CharField(choices=[('hard_bounce', 'Hard Bounce'), ('soft_bounce_threshold', 'Soft Bounce Threshold Exceeded'), ('complaint', 'Spam Complaint'), ('unsubscribe', 'User Unsubscribed'), ('manual', 'Manually Suppressed'), ('invalid', 'Invalid Email Address')], help_text='Reason for suppression', max_length=30)),
                ('suppressed_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When suppression expires (null = permanent)', null=True)),
                ('bounce_count', models.PositiveIntegerField(default=1)),
                ('last_bounce_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, max_length=50)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Email Suppression',
                'verbose_name_plural': 'Email Suppressions',
                'db_table': 'notification_email_suppressions',
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(help_text="Template identifier (e.g., 'invoice_issued', 'payment_reminder')", max_length=100)),
                ('locale', models.CharField(default='ro', help_text='Language/locale code (ro, en)', max_length=10)),
                ('subject', models.CharField(help_text='Email subject line (supports variables)', max_length=255)),
                ('body_html', models.TextField(help_text='HTML email body (supports Django template syntax)')),
                ('body_text', models.TextField(blank=True, help_text='Plain text fallback (auto-generated if empty)')),
                ('description', models.TextField(blank=True, help_text='Description of when this template is used')),
                ('variables', models.JSONField(blank=True, default=dict, help_text='Available template variables and their descriptions')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is available for use')),
                ('version', models.PositiveIntegerField(default=1, help_text='Template version for change tracking')),
                ('category', models.CharField(choices=[('billing', 'Billing & Invoices'), ('dunning', 'Payment Reminders'), ('provisioning', 'Service Provisioning'), ('support', 'Support & Tickets'), ('welcome', 'Welcome & Onboarding'), ('renewal', 'Service Renewals'), ('suspension', 'Service Suspension'), ('termination', 'Service Termination'), ('domain', 'Domain Management'), ('security', 'Security Alerts'), ('maintenance', 'Maintenance Notifications'), ('marketing', 'Marketing & Promotions'), ('compliance', 'Legal & Compliance'), ('system', 'System Notifications')], default='system', help_text='Template category for organization', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'db_table': 'notification_email_templates',
                'ordering': ('category', 'key', 'locale'),
            },
        ),
        migrations.CreateModel(
            name='UnsubscribeToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Email address this token was generated for', max_length=254)),
                ('template_key', models.CharField(help_text='Template key that triggered this email', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, help_text='When this token was consumed', null=True)),
            ],
            options={
                'verbose_name': 'Unsubscribe Token',
                'verbose_name_plural': 'Unsubscribe Tokens',
                'db_table': 'notification_unsubscribe_tokens',
            },
        ),
    ]
