# Generated by Django 5.2.5 on 2025-09-13 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_initial'),
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this campaign', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Customer this email was sent to (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='sent_by',
            field=models.ForeignKey(blank=True, help_text='User who triggered this email (if manual)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_emails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this template', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_email_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='template',
            field=models.ForeignKey(help_text='Email template to use for this campaign', on_delete=django.db.models.deletion.PROTECT, to='notifications.emailtemplate'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['to_addr', '-sent_at'], name='email_log_to_addr_9eaa4c_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['customer', '-sent_at'], name='email_log_custome_8deb83_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['template_key', '-sent_at'], name='email_log_templat_61c477_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['status', '-sent_at'], name='email_log_status_f8e839_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['provider', '-sent_at'], name='email_log_provide_8afd8a_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['-sent_at'], name='email_log_sent_at_3d6302_idx'),
        ),
        migrations.AddIndex(
            model_name='emailtemplate',
            index=models.Index(fields=['key', 'locale'], name='email_templ_key_460ddb_idx'),
        ),
        migrations.AddIndex(
            model_name='emailtemplate',
            index=models.Index(fields=['category', 'is_active'], name='email_templ_categor_f080c1_idx'),
        ),
        migrations.AddIndex(
            model_name='emailtemplate',
            index=models.Index(fields=['created_at'], name='email_templ_created_ca9757_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='emailtemplate',
            unique_together={('key', 'locale')},
        ),
        migrations.AddIndex(
            model_name='emailcampaign',
            index=models.Index(fields=['status', '-created_at'], name='email_campa_status_043842_idx'),
        ),
        migrations.AddIndex(
            model_name='emailcampaign',
            index=models.Index(fields=['scheduled_at'], name='email_campa_schedul_35c73d_idx'),
        ),
        migrations.AddIndex(
            model_name='emailcampaign',
            index=models.Index(fields=['-created_at'], name='email_campa_created_922a27_idx'),
        ),
    ]
