# Generated by Django 5.2.12 on 2026-03-11 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_initial'),
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this campaign', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_email_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Customer this email was sent to (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='sent_by',
            field=models.ForeignKey(blank=True, help_text='User who triggered this email (if manual)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_emails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailpreference',
            name='customer',
            field=models.OneToOneField(help_text='Customer these preferences belong to', on_delete=django.db.models.deletion.CASCADE, related_name='email_preferences', to='customers.customer'),
        ),
        migrations.AddIndex(
            model_name='emailsuppression',
            index=models.Index(fields=['reason'], name='notificatio_reason_cfa3f6_idx'),
        ),
        migrations.AddIndex(
            model_name='emailsuppression',
            index=models.Index(fields=['suppressed_at'], name='notificatio_suppres_201b47_idx'),
        ),
        migrations.AddIndex(
            model_name='emailsuppression',
            index=models.Index(fields=['expires_at'], name='notificatio_expires_65d8e7_idx'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this template', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_email_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='template',
            field=models.ForeignKey(help_text='Email template to use for this campaign', on_delete=django.db.models.deletion.PROTECT, to='notifications.emailtemplate'),
        ),
        migrations.AddIndex(
            model_name='unsubscribetoken',
            index=models.Index(fields=['email', '-created_at'], name='notificatio_email_d6b831_idx'),
        ),
        migrations.AddIndex(
            model_name='unsubscribetoken',
            index=models.Index(fields=['-created_at'], name='notificatio_created_e3798f_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['to_addr', '-sent_at'], name='notificatio_to_addr_1630df_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['customer', '-sent_at'], name='notificatio_custome_330ff2_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['template_key', '-sent_at'], name='notificatio_templat_a1935a_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['status', '-sent_at'], name='notificatio_status_b3473f_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['provider', '-sent_at'], name='notificatio_provide_966008_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['-sent_at'], name='notificatio_sent_at_c7caf6_idx'),
        ),
        migrations.AddIndex(
            model_name='emailtemplate',
            index=models.Index(fields=['key', 'locale'], name='notificatio_key_9515a3_idx'),
        ),
        migrations.AddIndex(
            model_name='emailtemplate',
            index=models.Index(fields=['category', 'is_active'], name='notificatio_categor_bfdf7e_idx'),
        ),
        migrations.AddIndex(
            model_name='emailtemplate',
            index=models.Index(fields=['created_at'], name='notificatio_created_85e95a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='emailtemplate',
            unique_together={('key', 'locale')},
        ),
        migrations.AddIndex(
            model_name='emailcampaign',
            index=models.Index(fields=['status', '-created_at'], name='notificatio_status_4a0385_idx'),
        ),
        migrations.AddIndex(
            model_name='emailcampaign',
            index=models.Index(fields=['scheduled_at'], name='notificatio_schedul_944a21_idx'),
        ),
        migrations.AddIndex(
            model_name='emailcampaign',
            index=models.Index(fields=['-created_at'], name='notificatio_created_e8d4f3_idx'),
        ),
    ]
