# Generated by Django 5.2.11 on 2026-02-09 12:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_initial'),
        ('notifications', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcampaign',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this campaign', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_email_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EmailPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transactional', models.BooleanField(default=True, help_text='Receive transactional emails (invoices, receipts)')),
                ('billing', models.BooleanField(default=True, help_text='Receive billing notifications (payment reminders)')),
                ('service', models.BooleanField(default=True, help_text='Receive service notifications (provisioning, changes)')),
                ('security', models.BooleanField(default=True, help_text='Receive security alerts (login attempts, 2FA)')),
                ('marketing', models.BooleanField(default=False, help_text='Receive marketing emails (requires explicit consent)')),
                ('newsletter', models.BooleanField(default=False, help_text='Receive newsletter (requires explicit consent)')),
                ('product_updates', models.BooleanField(default=True, help_text='Receive product update notifications')),
                ('marketing_consent_date', models.DateTimeField(blank=True, help_text='When marketing consent was given', null=True)),
                ('marketing_consent_source', models.CharField(blank=True, help_text='How consent was obtained (signup, preference_center, etc.)', max_length=100)),
                ('global_unsubscribe', models.BooleanField(default=False, help_text='Globally unsubscribed from all non-essential emails')),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('unsubscribe_reason', models.CharField(blank=True, max_length=255)),
                ('notification_frequency', models.CharField(choices=[('immediate', 'Immediate'), ('daily_digest', 'Daily Digest'), ('weekly_digest', 'Weekly Digest')], default='immediate', help_text='How often to receive non-urgent notifications', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(help_text='Customer these preferences belong to', on_delete=django.db.models.deletion.CASCADE, related_name='email_preferences', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Email Preference',
                'verbose_name_plural': 'Email Preferences',
                'db_table': 'email_preference',
            },
        ),
        migrations.CreateModel(
            name='EmailSuppression',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_hash', models.CharField(db_index=True, help_text='SHA-256 hash of the suppressed email address', max_length=64, unique=True)),
                ('email_encrypted', models.TextField(blank=True, help_text='Encrypted original email (for support requests)')),
                ('reason', models.CharField(choices=[('hard_bounce', 'Hard Bounce'), ('soft_bounce_threshold', 'Soft Bounce Threshold Exceeded'), ('complaint', 'Spam Complaint'), ('unsubscribe', 'User Unsubscribed'), ('manual', 'Manually Suppressed'), ('invalid', 'Invalid Email Address')], help_text='Reason for suppression', max_length=30)),
                ('suppressed_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When suppression expires (null = permanent)', null=True)),
                ('bounce_count', models.PositiveIntegerField(default=1)),
                ('last_bounce_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, max_length=50)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Email Suppression',
                'verbose_name_plural': 'Email Suppressions',
                'db_table': 'email_suppression',
                'indexes': [models.Index(fields=['reason'], name='email_suppr_reason_01c303_idx'), models.Index(fields=['suppressed_at'], name='email_suppr_suppres_43954d_idx'), models.Index(fields=['expires_at'], name='email_suppr_expires_e4b0df_idx')],
            },
        ),
    ]
