# Generated by Django 5.2.11 on 2026-03-06 15:44

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_clear_encrypted_notification_bodies'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnsubscribeToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Email address this token was generated for', max_length=254)),
                ('template_key', models.CharField(help_text='Template key that triggered this email', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, help_text='When this token was consumed', null=True)),
            ],
            options={
                'verbose_name': 'Unsubscribe Token',
                'verbose_name_plural': 'Unsubscribe Tokens',
                'db_table': 'unsubscribe_token',
                'indexes': [models.Index(fields=['email', '-created_at'], name='unsubscribe_email_8f8d4a_idx'), models.Index(fields=['-created_at'], name='unsubscribe_created_c1b108_idx')],
            },
        ),
    ]
