# Generated by Django 5.2.11 on 2026-03-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_add_body_encrypted_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='body_encrypted',
            field=models.BooleanField(default=True, help_text='Whether body fields are encrypted at rest'),
        ),
    ]
