# Generated by Django 5.2.5 on 2025-09-06 19:05

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_id', models.IntegerField(help_text='ID from platform service', unique=True)),
                ('code', models.CharField(help_text='ISO 4217 currency code', max_length=3, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(blank=True, max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('decimal_places', models.PositiveIntegerField(default=2)),
                ('last_synced', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'db_table': 'portal_currency',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_id', models.IntegerField(help_text='ID from platform service', unique=True)),
                ('customer_id', models.IntegerField(help_text='Customer ID from platform service')),
                ('number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('void', 'Void'), ('refunded', 'Refunded')], default='draft', max_length=20)),
                ('exchange_to_ron', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('subtotal_cents', models.BigIntegerField(default=0)),
                ('tax_cents', models.BigIntegerField(default=0)),
                ('total_cents', models.BigIntegerField(default=0)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('bill_to_name', models.CharField(default='', max_length=255)),
                ('bill_to_tax_id', models.CharField(blank=True, max_length=50)),
                ('bill_to_email', models.EmailField(blank=True, max_length=254)),
                ('bill_to_address1', models.CharField(blank=True, max_length=255)),
                ('bill_to_address2', models.CharField(blank=True, max_length=255)),
                ('bill_to_city', models.CharField(blank=True, max_length=100)),
                ('bill_to_region', models.CharField(blank=True, max_length=100)),
                ('bill_to_postal', models.CharField(blank=True, max_length=20)),
                ('bill_to_country', models.CharField(blank=True, max_length=2)),
                ('efactura_id', models.CharField(blank=True, max_length=100)),
                ('efactura_sent', models.BooleanField(default=False)),
                ('efactura_sent_date', models.DateTimeField(blank=True, null=True)),
                ('efactura_response', models.JSONField(blank=True, default=dict)),
                ('pdf_file', models.CharField(blank=True, help_text='PDF file path', max_length=500)),
                ('xml_file', models.CharField(blank=True, help_text='XML file path', max_length=500)),
                ('created_by_id', models.IntegerField(help_text='User ID from platform service', null=True)),
                ('converted_from_proforma_id', models.IntegerField(blank=True, null=True)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.currency')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'db_table': 'portal_invoice',
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_id', models.IntegerField(help_text='ID from platform service', unique=True)),
                ('kind', models.CharField(choices=[('service', 'Service'), ('setup', 'Setup Fee'), ('credit', 'Credit'), ('discount', 'Discount'), ('refund', 'Refund'), ('misc', 'Miscellaneous')], max_length=20)),
                ('service_id', models.IntegerField(blank=True, help_text='Service ID from platform', null=True)),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=12)),
                ('unit_price_cents', models.BigIntegerField(default=0)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=5)),
                ('line_total_cents', models.BigIntegerField(default=0)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.invoice')),
            ],
            options={
                'verbose_name': 'Invoice Line',
                'verbose_name_plural': 'Invoice Lines',
                'db_table': 'portal_invoice_line',
            },
        ),
        migrations.CreateModel(
            name='ProformaInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_id', models.IntegerField(help_text='ID from platform service', unique=True)),
                ('customer_id', models.IntegerField(help_text='Customer ID from platform service')),
                ('number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('converted', 'Converted to Invoice'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('subtotal_cents', models.BigIntegerField(default=0)),
                ('tax_cents', models.BigIntegerField(default=0)),
                ('total_cents', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('bill_to_name', models.CharField(default='', max_length=255)),
                ('bill_to_tax_id', models.CharField(blank=True, max_length=50)),
                ('bill_to_email', models.EmailField(blank=True, max_length=254)),
                ('bill_to_address1', models.CharField(blank=True, max_length=255)),
                ('bill_to_city', models.CharField(blank=True, max_length=100)),
                ('bill_to_country', models.CharField(blank=True, max_length=2)),
                ('converted_to_invoice_id', models.IntegerField(blank=True, null=True)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.currency')),
            ],
            options={
                'verbose_name': 'Proforma Invoice',
                'verbose_name_plural': 'Proforma Invoices',
                'db_table': 'portal_proforma_invoice',
            },
        ),
        migrations.CreateModel(
            name='ProformaLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_id', models.IntegerField(help_text='ID from platform service', unique=True)),
                ('kind', models.CharField(choices=[('service', 'Service'), ('setup', 'Setup Fee'), ('credit', 'Credit'), ('discount', 'Discount'), ('misc', 'Miscellaneous')], max_length=20)),
                ('service_id', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=12)),
                ('unit_price_cents', models.BigIntegerField(default=0)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=5)),
                ('line_total_cents', models.BigIntegerField(default=0)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('proforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.proformainvoice')),
            ],
            options={
                'verbose_name': 'Proforma Line',
                'verbose_name_plural': 'Proforma Lines',
                'db_table': 'portal_proforma_line',
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['customer_id', '-created_at'], name='portal_invo_custome_979424_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', '-due_at'], name='portal_invo_status_9c2831_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['number'], name='portal_invo_number_84ff7f_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['platform_id'], name='portal_invo_platfor_b64d7a_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceline',
            index=models.Index(fields=['service_id'], name='portal_invo_service_da35c1_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceline',
            index=models.Index(fields=['invoice', 'kind'], name='portal_invo_invoice_8bed31_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceline',
            index=models.Index(fields=['platform_id'], name='portal_invo_platfor_8d8962_idx'),
        ),
        migrations.AddIndex(
            model_name='proformainvoice',
            index=models.Index(fields=['customer_id', '-created_at'], name='portal_prof_custome_70b51c_idx'),
        ),
        migrations.AddIndex(
            model_name='proformainvoice',
            index=models.Index(fields=['status'], name='portal_prof_status_4e343f_idx'),
        ),
        migrations.AddIndex(
            model_name='proformainvoice',
            index=models.Index(fields=['number'], name='portal_prof_number_511403_idx'),
        ),
        migrations.AddIndex(
            model_name='proformainvoice',
            index=models.Index(fields=['platform_id'], name='portal_prof_platfor_96f466_idx'),
        ),
        migrations.AddIndex(
            model_name='proformaline',
            index=models.Index(fields=['service_id'], name='portal_prof_service_59f767_idx'),
        ),
        migrations.AddIndex(
            model_name='proformaline',
            index=models.Index(fields=['proforma', 'kind'], name='portal_prof_proform_3aba00_idx'),
        ),
        migrations.AddIndex(
            model_name='proformaline',
            index=models.Index(fields=['platform_id'], name='portal_prof_platfor_3ce2bb_idx'),
        ),
    ]
