# Generated by Django 5.2.12 on 2026-07-24

from django.db import migrations


class Migration(migrations.Migration):
    """Remove legacy Portal-owned billing tables from before the stateless API architecture."""

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="currency",
        ),
        migrations.RemoveField(
            model_name="proformainvoice",
            name="currency",
        ),
        migrations.RemoveField(
            model_name="invoiceline",
            name="invoice",
        ),
        migrations.RemoveField(
            model_name="proformaline",
            name="proforma",
        ),
        migrations.DeleteModel(
            name="Currency",
        ),
        migrations.DeleteModel(
            name="Invoice",
        ),
        migrations.DeleteModel(
            name="InvoiceLine",
        ),
        migrations.DeleteModel(
            name="ProformaInvoice",
        ),
        migrations.DeleteModel(
            name="ProformaLine",
        ),
    ]
