# Generated by Django 5.2.5 on 2025-09-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_add_performance_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_at',), 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ('created_at',), 'verbose_name': 'Order Item', 'verbose_name_plural': 'Order Items'},
        ),
        migrations.AlterModelOptions(
            name='orderstatushistory',
            options={'ordering': ('-created_at',), 'verbose_name': 'Order Status History', 'verbose_name_plural': 'Order Status Histories'},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], default='draft', help_text='Current order status', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Product configuration (domain, username, specs, etc.)'),
        ),
    ]
