# Generated by Django 5.0.14 on 2025-08-19 13:50

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Șters la"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nume")),
                (
                    "customer_type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual"),
                            ("company", "Company"),
                            ("pfa", "PFA/SRL"),
                            ("ngo", "NGO/Association"),
                        ],
                        default="individual",
                        max_length=20,
                        verbose_name="Tip client",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("suspended", "Suspended"),
                            ("prospect", "Prospect"),
                        ],
                        default="prospect",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Nume companie"
                    ),
                ),
                (
                    "primary_email",
                    models.EmailField(
                        default="contact@example.com",
                        max_length=254,
                        verbose_name="Email principal",
                    ),
                ),
                (
                    "primary_phone",
                    models.CharField(
                        default="+40712345678",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^(\\+40|0)[0-9]{9,10}$", "Număr telefon invalid"
                            )
                        ],
                        verbose_name="Telefon principal",
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Domeniu"
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="Website")),
                ("data_processing_consent", models.BooleanField(default=False)),
                ("marketing_consent", models.BooleanField(default=False)),
                ("gdpr_consent_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
                "db_table": "customers",
            },
        ),
        migrations.CreateModel(
            name="CustomerAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Șters la"
                    ),
                ),
                (
                    "address_type",
                    models.CharField(
                        choices=[
                            ("primary", "Adresa principală"),
                            ("billing", "Adresa facturare"),
                            ("delivery", "Adresa livrare"),
                            ("legal", "Sediul social"),
                        ],
                        max_length=20,
                        verbose_name="Tip adresă",
                    ),
                ),
                (
                    "address_line1",
                    models.CharField(max_length=200, verbose_name="Adresa 1"),
                ),
                (
                    "address_line2",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Adresa 2"
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="Oraș")),
                ("county", models.CharField(max_length=100, verbose_name="Județ")),
                (
                    "postal_code",
                    models.CharField(max_length=10, verbose_name="Cod poștal"),
                ),
                (
                    "country",
                    models.CharField(
                        default="România", max_length=100, verbose_name="Țara"
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(default=True, verbose_name="Adresa curentă"),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="Versiune"),
                ),
                (
                    "is_validated",
                    models.BooleanField(default=False, verbose_name="Validată"),
                ),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Customer Address",
                "verbose_name_plural": "Customer Addresses",
                "db_table": "customer_addresses",
            },
        ),
        migrations.CreateModel(
            name="CustomerBillingProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Șters la"
                    ),
                ),
                (
                    "payment_terms",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Termen plată (zile)"
                    ),
                ),
                (
                    "credit_limit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Limită credit (RON)",
                    ),
                ),
                (
                    "preferred_currency",
                    models.CharField(
                        choices=[("RON", "RON"), ("EUR", "EUR")],
                        default="RON",
                        max_length=3,
                        verbose_name="Monedă preferată",
                    ),
                ),
                (
                    "invoice_delivery_method",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("postal", "Poștă"),
                            ("both", "Email și poștă"),
                        ],
                        default="email",
                        max_length=20,
                        verbose_name="Mod livrare facturi",
                    ),
                ),
                ("auto_payment_enabled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Customer Billing Profile",
                "verbose_name_plural": "Customer Billing Profiles",
                "db_table": "customer_billing_profiles",
            },
        ),
        migrations.CreateModel(
            name="CustomerNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Șters la"
                    ),
                ),
                (
                    "note_type",
                    models.CharField(
                        choices=[
                            ("general", "Generală"),
                            ("call", "Apel telefonic"),
                            ("email", "Email"),
                            ("meeting", "Întâlnire"),
                            ("complaint", "Reclamație"),
                            ("compliment", "Compliment"),
                        ],
                        default="general",
                        max_length=20,
                        verbose_name="Tip notă",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titlu")),
                ("content", models.TextField(verbose_name="Conținut")),
                (
                    "is_important",
                    models.BooleanField(default=False, verbose_name="Important"),
                ),
                (
                    "is_private",
                    models.BooleanField(default=False, verbose_name="Privat"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Customer Note",
                "verbose_name_plural": "Customer Notes",
                "db_table": "customer_notes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerPaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Șters la"
                    ),
                ),
                (
                    "method_type",
                    models.CharField(
                        choices=[
                            ("stripe_card", "Card Stripe"),
                            ("bank_transfer", "Transfer bancar"),
                            ("cash", "Numerar"),
                            ("other", "Altele"),
                        ],
                        max_length=20,
                        verbose_name="Tip metodă",
                    ),
                ),
                ("stripe_customer_id", models.CharField(blank=True, max_length=100)),
                (
                    "stripe_payment_method_id",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "display_name",
                    models.CharField(max_length=100, verbose_name="Nume afișaj"),
                ),
                (
                    "last_four",
                    models.CharField(
                        blank=True, max_length=4, verbose_name="Ultimele 4 cifre"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="Implicit"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activ")),
                (
                    "bank_details",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Detalii bancare"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Customer Payment Method",
                "verbose_name_plural": "Customer Payment Methods",
                "db_table": "customer_payment_methods",
            },
        ),
        migrations.CreateModel(
            name="CustomerTaxProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Șters la"
                    ),
                ),
                (
                    "cui",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^RO\\d{2,10}$", "CUI invalid"
                            )
                        ],
                        verbose_name="CUI/CIF",
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Nr. registrul comerțului",
                    ),
                ),
                (
                    "is_vat_payer",
                    models.BooleanField(default=True, verbose_name="Plătitor TVA"),
                ),
                (
                    "vat_number",
                    models.CharField(blank=True, max_length=20, verbose_name="Nr. TVA"),
                ),
                (
                    "vat_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("19.00"),
                        max_digits=5,
                        verbose_name="Cota TVA (%)",
                    ),
                ),
                ("reverse_charge_eligible", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Customer Tax Profile",
                "verbose_name_plural": "Customer Tax Profiles",
                "db_table": "customer_tax_profiles",
            },
        ),
    ]
