# Generated by Django 5.2.5 on 2025-08-28 05:23

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customernote',
            options={'ordering': ('-created_at',), 'verbose_name': 'Customer Note', 'verbose_name_plural': 'Customer Notes'},
        ),
        migrations.AlterModelManagers(
            name='customer',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='customeraddress',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='customerbillingprofile',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='customernote',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='customerpaymentmethod',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='customertaxprofile',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
