# Generated by Django 5.2.5 on 2025-08-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_paymentretrypolicy_taxrule_vatvalidation_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paymentcollectionrun",
            options={
                "ordering": ("-started_at",),
                "verbose_name": "Payment Collection Run",
                "verbose_name_plural": "Payment Collection Runs",
            },
        ),
        migrations.AlterModelOptions(
            name="paymentretryattempt",
            options={
                "ordering": ("payment", "attempt_number"),
                "verbose_name": "Payment Retry Attempt",
                "verbose_name_plural": "Payment Retry Attempts",
            },
        ),
        migrations.AlterModelOptions(
            name="paymentretrypolicy",
            options={
                "ordering": ("name",),
                "verbose_name": "Payment Retry Policy",
                "verbose_name_plural": "Payment Retry Policies",
            },
        ),
        migrations.AlterModelOptions(
            name="taxrule",
            options={
                "ordering": ("country_code", "tax_type", "-valid_from"),
                "verbose_name": "Tax Rule",
                "verbose_name_plural": "Tax Rules",
            },
        ),
        migrations.AlterModelOptions(
            name="vatvalidation",
            options={
                "ordering": ("-validation_date",),
                "verbose_name": "VAT Validation",
                "verbose_name_plural": "VAT Validations",
            },
        ),
        migrations.AlterField(
            model_name="invoice",
            name="due_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
