# Generated by Django 5.2.5 on 2025-09-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_add_name_to_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformainvoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('expired', 'Expired')], default='draft', max_length=20),
        ),
    ]
