# Generated by Django 5.2.5 on 2025-09-01 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webhookdelivery',
            options={'ordering': ('-scheduled_at',), 'verbose_name': '📤 Webhook Delivery', 'verbose_name_plural': '📤 Webhook Deliveries'},
        ),
        migrations.AlterModelOptions(
            name='webhookevent',
            options={'ordering': ('-received_at',), 'verbose_name': '🔄 Webhook Event', 'verbose_name_plural': '🔄 Webhook Events'},
        ),
        migrations.RemoveField(
            model_name='webhookevent',
            name='signature',
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='signature_hash',
            field=models.CharField(blank=True, help_text='SHA-256 hash of webhook signature for verification tracking', max_length=64),
        ),
    ]
