# Generated by Django 5.2.5 on 2025-09-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_alter_webhookevent_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webhookevent',
            options={'ordering': ('-received_at',), 'verbose_name': '🔄 Webhook Event', 'verbose_name_plural': '🔄 Webhook Events'},
        ),
        migrations.AlterField(
            model_name='webhookevent',
            name='signature_hash',
            field=models.CharField(blank=True, default='', help_text='SHA-256 hash of webhook signature for verification tracking', max_length=64),
        ),
    ]
