# Generated by Django 5.2.17 on 2026-10-02 10:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Unique setting identifier (e.g., "billing.proforma_validity_days")', max_length=100, unique=True, verbose_name='Key')),
                ('category', models.CharField(default='system', help_text='Setting category for organization', max_length=50, verbose_name='Category')),
                ('name', models.CharField(help_text='Human-readable setting name', max_length=200, verbose_name='Name')),
                ('description', models.TextField(help_text='Detailed description of what this setting controls', verbose_name='Description')),
                ('data_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('boolean', 'Boolean'), ('decimal', 'Decimal'), ('list', 'List'), ('json', 'JSON')], default='string', help_text='Type of data this setting stores', max_length=20, verbose_name='Data Type')),
                ('value', models.JSONField(blank=True, help_text='Current setting value', verbose_name='Value')),
                ('default_value', models.JSONField(blank=True, help_text='Default value to use if setting is not configured', verbose_name='Default Value')),
                ('is_required', models.BooleanField(default=False, help_text='Whether this setting must have a value', verbose_name='Is Required')),
                ('is_sensitive', models.BooleanField(default=False, help_text='Whether this setting contains sensitive data', verbose_name='Is Sensitive')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this setting is currently active', verbose_name='Is Active')),
                ('requires_restart', models.BooleanField(default=False, help_text='Whether changing this setting requires application restart', verbose_name='Requires Restart')),
                ('help_text', models.TextField(blank=True, help_text='Additional help text for staff users', verbose_name='Help Text')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this setting was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this setting was last updated', verbose_name='Updated At')),
                ('revision', models.PositiveBigIntegerField(default=1, editable=False)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
                'db_table': 'setting_entries',
                'ordering': ['category', 'key'],
                'indexes': [models.Index(fields=['key'], name='setting_ent_key_0295de_idx'), models.Index(fields=['category'], name='setting_ent_categor_73cf0a_idx'), models.Index(fields=['updated_at'], name='setting_ent_updated_5c7d12_idx')],
            },
        ),
    ]
