# Generated by Django 5.2.5 on 2025-09-13 15:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SettingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Unique category identifier (e.g., "billing")', max_length=50, unique=True, verbose_name='Key')),
                ('name', models.CharField(help_text='Human-readable category name', max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Category description for staff', verbose_name='Description')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which to display this category', verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is currently active', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this category was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this category was last updated', verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Setting Category',
                'verbose_name_plural': 'Setting Categories',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['key'], name='settings_se_key_be39e1_idx'), models.Index(fields=['display_order'], name='settings_se_display_403bd9_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Unique setting identifier (e.g., "billing.proforma_validity_days")', max_length=100, unique=True, verbose_name='Key')),
                ('category', models.CharField(default='system', help_text='Setting category for organization', max_length=50, verbose_name='Category')),
                ('name', models.CharField(help_text='Human-readable setting name', max_length=200, verbose_name='Name')),
                ('description', models.TextField(help_text='Detailed description of what this setting controls', verbose_name='Description')),
                ('data_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('boolean', 'Boolean'), ('decimal', 'Decimal'), ('list', 'List'), ('json', 'JSON')], default='string', help_text='Type of data this setting stores', max_length=20, verbose_name='Data Type')),
                ('value', models.JSONField(help_text='Current setting value', verbose_name='Value')),
                ('default_value', models.JSONField(help_text='Default value to use if setting is not configured', verbose_name='Default Value')),
                ('is_required', models.BooleanField(default=False, help_text='Whether this setting must have a value', verbose_name='Is Required')),
                ('is_sensitive', models.BooleanField(default=False, help_text='Whether this setting contains sensitive data', verbose_name='Is Sensitive')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this setting is currently active', verbose_name='Is Active')),
                ('is_public', models.BooleanField(default=False, help_text='Whether this setting can be accessed publicly', verbose_name='Is Public')),
                ('requires_restart', models.BooleanField(default=False, help_text='Whether changing this setting requires application restart', verbose_name='Requires Restart')),
                ('validation_rules', models.JSONField(blank=True, default=dict, help_text='JSON object with validation rules (min, max, pattern, etc.)', verbose_name='Validation Rules')),
                ('help_text', models.TextField(blank=True, help_text='Additional help text for staff users', verbose_name='Help Text')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this setting was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this setting was last updated', verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
                'ordering': ['category', 'key'],
                'indexes': [models.Index(fields=['key'], name='settings_sy_key_d49ddf_idx'), models.Index(fields=['category'], name='settings_sy_categor_7c2f34_idx'), models.Index(fields=['updated_at'], name='settings_sy_updated_2d43a6_idx')],
            },
        ),
    ]
