# Generated by Django 5.2.5 on 2025-08-29 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this setting is currently active', verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Whether this setting can be accessed publicly', verbose_name='Is Public'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='requires_restart',
            field=models.BooleanField(default=False, help_text='Whether changing this setting requires application restart', verbose_name='Requires Restart'),
        ),
    ]
