# Generated by Django 5.2.5 on 2025-09-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_systemsetting_is_active_systemsetting_is_public_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='settingcategory',
            new_name='settings_se_key_be39e1_idx',
            old_name='system_sett_key_000f77_idx',
        ),
        migrations.RenameIndex(
            model_name='settingcategory',
            new_name='settings_se_display_403bd9_idx',
            old_name='system_sett_display_dd3ab5_idx',
        ),
        migrations.RenameIndex(
            model_name='systemsetting',
            new_name='settings_sy_key_d49ddf_idx',
            old_name='system_sett_key_05d472_idx',
        ),
        migrations.RenameIndex(
            model_name='systemsetting',
            new_name='settings_sy_categor_7c2f34_idx',
            old_name='system_sett_categor_a4d87b_idx',
        ),
        migrations.RenameIndex(
            model_name='systemsetting',
            new_name='settings_sy_updated_2d43a6_idx',
            old_name='system_sett_updated_24c311_idx',
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='category',
            field=models.CharField(default='system', help_text='Setting category for organization', max_length=50, verbose_name='Category'),
        ),
    ]
