# Generated by Django 5.2.12 on 2026-07-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_curate_catalog_rows'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SettingCategory',
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='validation_rules',
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='default_value',
            field=models.JSONField(blank=True, help_text='Default value to use if setting is not configured', verbose_name='Default Value'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='value',
            field=models.JSONField(blank=True, help_text='Current setting value', verbose_name='Value'),
        ),
    ]
