# Generated by Django 5.2.5 on 2025-09-02 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0003_encrypt_existing_registrar_credentials'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domain',
            options={'ordering': ('-created_at',), 'verbose_name': '🌍 Domain', 'verbose_name_plural': '🌍 Domains'},
        ),
        migrations.AlterModelOptions(
            name='domainorderitem',
            options={'ordering': ('-created_at',), 'verbose_name': '🛒 Domain Order Item', 'verbose_name_plural': '🛒 Domain Order Items'},
        ),
        migrations.AlterModelOptions(
            name='registrar',
            options={'ordering': ('name',), 'verbose_name': '🏢 Registrar', 'verbose_name_plural': '🏢 Registrars'},
        ),
        migrations.AlterModelOptions(
            name='tld',
            options={'ordering': ('extension',), 'verbose_name': '🌐 TLD', 'verbose_name_plural': '🌐 TLDs'},
        ),
        migrations.AlterModelOptions(
            name='tldregistrarassignment',
            options={'ordering': ('tld__extension', 'priority'), 'verbose_name': '🔗 TLD-Registrar Assignment', 'verbose_name_plural': '🔗 TLD-Registrar Assignments'},
        ),
    ]
