# Generated by Django 5.2.17 on 2026-10-02 10:28

import uuid
from decimal import Decimal

import django.core.validators
import django_fsm
from django.db import migrations, models

import apps.common.cnp_validator
import apps.common.cui_validator
import apps.common.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Șters la')),
                ('name', models.CharField(max_length=255, verbose_name='Nume')),
                ('customer_type', models.CharField(choices=[('individual', 'Individual'), ('company', 'Company'), ('pfa', 'PFA/SRL'), ('ngo', 'NGO/Association')], default='individual', max_length=20, verbose_name='Tip client')),
                ('status', django_fsm.FSMField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('prospect', 'Prospect')], db_index=True, default='prospect', max_length=20, protected=True, verbose_name='Status')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='Nume companie')),
                ('primary_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email principal')),
                ('primary_phone', models.CharField(blank=True, default='', max_length=20, validators=[django.core.validators.RegexValidator('^(\\+40|0)[0-9]{9,10}$', 'Număr telefon invalid')], verbose_name='Telefon principal')),
                ('industry', models.CharField(blank=True, max_length=100, verbose_name='Domeniu')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('data_processing_consent', models.BooleanField(default=False)),
                ('marketing_consent', models.BooleanField(default=False)),
                ('gdpr_consent_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Șters la')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Adresa principală')),
                ('is_billing', models.BooleanField(default=False, verbose_name='Adresa facturare')),
                ('label', models.CharField(blank=True, max_length=50, verbose_name='Etichetă')),
                ('address_line1', models.CharField(max_length=200, verbose_name='Adresa 1')),
                ('address_line2', models.CharField(blank=True, max_length=200, verbose_name='Adresa 2')),
                ('city', models.CharField(max_length=100, verbose_name='Oraș')),
                ('county', models.CharField(max_length=100, verbose_name='Județ')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Cod poștal')),
                ('country', models.CharField(default='România', max_length=100, verbose_name='Țara')),
                ('is_current', models.BooleanField(default=True, verbose_name='Adresa curentă')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Versiune')),
                ('is_validated', models.BooleanField(default=False, verbose_name='Validată')),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer Address',
                'verbose_name_plural': 'Customer Addresses',
                'db_table': 'customer_addresses',
            },
        ),
        migrations.CreateModel(
            name='CustomerBillingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Șters la')),
                ('payment_terms', models.PositiveIntegerField(default=30, verbose_name='Termen plată (zile)')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Limită credit (RON)')),
                ('preferred_currency', models.CharField(choices=[('RON', 'RON'), ('EUR', 'EUR'), ('USD', 'USD')], default='RON', max_length=3, verbose_name='Monedă preferată')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer Billing Profile',
                'verbose_name_plural': 'Customer Billing Profiles',
                'db_table': 'customer_billing_profiles',
            },
        ),
        migrations.CreateModel(
            name='CustomerNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Șters la')),
                ('note_type', models.CharField(choices=[('general', 'Generală'), ('call', 'Apel telefonic'), ('email', 'Email'), ('meeting', 'Întâlnire'), ('complaint', 'Reclamație'), ('compliment', 'Compliment')], default='general', max_length=20, verbose_name='Tip notă')),
                ('title', models.CharField(max_length=200, verbose_name='Titlu')),
                ('content', models.TextField(verbose_name='Conținut')),
                ('is_important', models.BooleanField(default=False, verbose_name='Important')),
                ('is_private', models.BooleanField(default=False, verbose_name='Privat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Customer Note',
                'verbose_name_plural': 'Customer Notes',
                'db_table': 'customer_notes',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CustomerPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Șters la')),
                ('method_type', models.CharField(choices=[('stripe_card', 'Card Stripe'), ('bank_transfer', 'Transfer bancar'), ('cash', 'Numerar'), ('other', 'Altele')], max_length=20, verbose_name='Tip metodă')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100)),
                ('stripe_payment_method_id', models.CharField(blank=True, max_length=100)),
                ('display_name', models.CharField(max_length=100, verbose_name='Nume afișaj')),
                ('last_four', models.CharField(blank=True, max_length=4, verbose_name='Ultimele 4 cifre')),
                ('is_default', models.BooleanField(default=False, verbose_name='Implicit')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activ')),
                ('encryption_context_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('bank_details', apps.common.fields.EncryptedJSONField(aad_context_field='encryption_context_id', blank=True, null=True, require_v2=True, verbose_name='Detalii bancare')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer Payment Method',
                'verbose_name_plural': 'Customer Payment Methods',
                'db_table': 'customer_payment_methods',
            },
        ),
        migrations.CreateModel(
            name='CustomerTaxProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Șters la')),
                ('cnp', models.CharField(blank=True, help_text='Cod Numeric Personal (13 cifre)', max_length=13, validators=[apps.common.cnp_validator.validate_cnp], verbose_name='CNP')),
                ('cui', models.CharField(blank=True, max_length=20, validators=[apps.common.cui_validator.validate_cui], verbose_name='CUI/CIF')),
                ('registration_number', models.CharField(blank=True, max_length=50, verbose_name='Nr. registrul comerțului')),
                ('is_vat_payer', models.BooleanField(default=True, verbose_name='Plătitor TVA')),
                ('vat_number', models.CharField(blank=True, max_length=20, verbose_name='Nr. TVA')),
                ('vat_rate', models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Optional customer-specific override; leave blank to use TaxService country rules', max_digits=5, null=True, verbose_name='Cota TVA (%)')),
                ('vat_rate_reason', models.CharField(blank=True, choices=[('diplomatic', 'Diplomatic exemption'), ('exempt_body', 'Exempt body'), ('other', 'Other exemption')], max_length=20, verbose_name='VAT exemption reason')),
                ('vies_consultation_reference', models.CharField(blank=True, max_length=255, verbose_name='VIES consultation reference')),
                ('reverse_charge_eligible', models.BooleanField(default=False)),
                ('vies_verified_at', models.DateTimeField(blank=True, help_text='Timestamp of last successful VIES verification', null=True, verbose_name='VIES verified at')),
                ('vies_verified_name', models.CharField(blank=True, help_text='Company name returned by VIES API', max_length=255, verbose_name='VIES company name')),
                ('vies_verification_status', models.CharField(choices=[('pending', 'Pending'), ('valid', 'VIES Verified'), ('invalid', 'VIES Invalid'), ('format_only', 'Format Valid (VIES unavailable)'), ('not_applicable', 'Not Applicable')], default='pending', max_length=25, verbose_name='VIES status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer Tax Profile',
                'verbose_name_plural': 'Customer Tax Profiles',
                'db_table': 'customer_tax_profiles',
            },
        ),
    ]
