# Generated by Django 5.2.5 on 2025-09-13 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='assigned_account_manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'staff_role__in': ['manager', 'support', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_customers', to=settings.AUTH_USER_MODEL, verbose_name='Manager cont'),
        ),
        migrations.AddField(
            model_name='customer',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Șters de'),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Șters de'),
        ),
        migrations.AddField(
            model_name='customerbillingprofile',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_profile', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='customerbillingprofile',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Șters de'),
        ),
        migrations.AddField(
            model_name='customernote',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creat de'),
        ),
        migrations.AddField(
            model_name='customernote',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='customernote',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Șters de'),
        ),
        migrations.AddField(
            model_name='customerpaymentmethod',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='customerpaymentmethod',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Șters de'),
        ),
        migrations.AddField(
            model_name='customertaxprofile',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax_profile', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='customertaxprofile',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Șters de'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['primary_email'], name='customers_primary_343f86_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['status'], name='customers_status_47bd31_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['customer_type'], name='customers_custome_3f7c53_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['created_at'], name='customers_created_c63477_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['deleted_at'], name='customers_deleted_508df4_idx'),
        ),
        migrations.AddIndex(
            model_name='customeraddress',
            index=models.Index(fields=['customer', 'address_type'], name='customer_ad_custome_7e9853_idx'),
        ),
        migrations.AddIndex(
            model_name='customeraddress',
            index=models.Index(fields=['customer', 'is_current'], name='customer_ad_custome_ae3164_idx'),
        ),
        migrations.AddIndex(
            model_name='customeraddress',
            index=models.Index(fields=['postal_code'], name='customer_ad_postal__f02291_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customeraddress',
            unique_together={('customer', 'address_type', 'is_current')},
        ),
        migrations.AddIndex(
            model_name='customernote',
            index=models.Index(fields=['customer', '-created_at'], name='customer_no_custome_f66812_idx'),
        ),
        migrations.AddIndex(
            model_name='customernote',
            index=models.Index(fields=['is_important'], name='customer_no_is_impo_6c8a78_idx'),
        ),
        migrations.AddIndex(
            model_name='customerpaymentmethod',
            index=models.Index(fields=['customer', 'is_default'], name='customer_pa_custome_da1a1d_idx'),
        ),
        migrations.AddIndex(
            model_name='customerpaymentmethod',
            index=models.Index(fields=['stripe_customer_id'], name='customer_pa_stripe__e3bab2_idx'),
        ),
        migrations.AddIndex(
            model_name='customertaxprofile',
            index=models.Index(fields=['cnp'], name='customer_ta_cnp_f1a5ad_idx'),
        ),
        migrations.AddIndex(
            model_name='customertaxprofile',
            index=models.Index(fields=['cui'], name='customer_ta_cui_df54f4_idx'),
        ),
        migrations.AddIndex(
            model_name='customertaxprofile',
            index=models.Index(fields=['vat_number'], name='customer_ta_vat_num_8e761c_idx'),
        ),
    ]
