# Generated by Django 5.2.5 on 2025-09-08

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0003_rename_payment_method_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="customertaxprofile",
            name="cnp",
            field=models.CharField(
                blank=True,
                max_length=13,
                validators=[django.core.validators.RegexValidator(r"^\d{13}$", "CNP invalid (trebuie 13 cifre)")],
                verbose_name="CNP",
                help_text="Cod Numeric Personal (13 cifre)",
            ),
        ),
        migrations.AddIndex(
            model_name="customertaxprofile",
            index=models.Index(fields=["cnp"], name="customer_tax_profile_cnp_idx"),
        ),
    ]

