# Generated by Django 5.2.11 on 2026-03-07 11:50

from django.db import migrations, models

import apps.common.cnp_validator


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_update_existing_vat_rates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customertaxprofile',
            name='cnp',
            field=models.CharField(blank=True, help_text='Cod Numeric Personal (13 cifre)', max_length=13, validators=[apps.common.cnp_validator.validate_cnp], verbose_name='CNP'),
        ),
    ]
