# Generated by Django 5.2.5 on 2025-09-08 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_add_cnp_to_customer_tax_profile'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customertaxprofile',
            new_name='customer_ta_cnp_f1a5ad_idx',
            old_name='customer_tax_profile_cnp_idx',
        ),
    ]
