# Generated by Django 5.2.11 on 2026-03-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_use_cnp_validator'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='meta',
            field=models.JSONField(blank=True, default=dict, verbose_name='Metadata'),
        ),
    ]
