# Generated by Django 5.2.11 on 2026-03-07 19:05

from django.conf import settings
from django.db import migrations, models

import apps.common.cui_validator


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0006_add_meta_jsonfield"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customer",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="customeraddress",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="customerbillingprofile",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="customernote",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="customerpaymentmethod",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="customertaxprofile",
            managers=[],
        ),
        migrations.AlterUniqueTogether(
            name="customeraddress",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="customertaxprofile",
            name="cui",
            field=models.CharField(
                blank=True,
                max_length=20,
                validators=[apps.common.cui_validator.validate_cui],
                verbose_name="CUI/CIF",
            ),
        ),
        # Partial unique constraint: SQLite supports CREATE UNIQUE INDEX ... WHERE
        # but not ALTER TABLE ... ADD CONSTRAINT. Use RunSQL for cross-DB compat.
        migrations.RunSQL(
            sql=(
                'CREATE UNIQUE INDEX IF NOT EXISTS "unique_current_address_per_type" '
                'ON "customer_addresses" ("customer_id", "address_type") '
                'WHERE "is_current" = true'
            ),
            reverse_sql='DROP INDEX IF EXISTS "unique_current_address_per_type"',
            state_operations=[
                migrations.AddConstraint(
                    model_name="customeraddress",
                    constraint=models.UniqueConstraint(
                        condition=models.Q(("is_current", True)),
                        fields=("customer", "address_type"),
                        name="unique_current_address_per_type",
                    ),
                ),
            ],
        ),
    ]
