# Generated by Django 5.2.11 on 2026-03-08 14:42

import django.core.validators
from django.conf import settings
from django.db import migrations, models

import apps.common.fields


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_fix_meta_check_not_valid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='primary_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email principal'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='primary_phone',
            field=models.CharField(blank=True, default='', max_length=20, validators=[django.core.validators.RegexValidator('^(\\+40|0)[0-9]{9,10}$', 'Număr telefon invalid')], verbose_name='Telefon principal'),
        ),
        migrations.AlterField(
            model_name='customerbillingprofile',
            name='preferred_currency',
            field=models.CharField(choices=[('RON', 'RON'), ('EUR', 'EUR'), ('USD', 'USD')], default='RON', max_length=3, verbose_name='Monedă preferată'),
        ),
        migrations.AlterField(
            model_name='customerpaymentmethod',
            name='bank_details',
            field=apps.common.fields.EncryptedJSONField(blank=True, null=True, verbose_name='Detalii bancare'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['status'], name='customers_status_active_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['customer_type'], name='customers_type_active_idx'),
        ),
        migrations.AddIndex(
            model_name='customeraddress',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['customer', 'address_type'], name='addr_cust_type_active_idx'),
        ),
        migrations.AlterConstraint(
            model_name='customeraddress',
            name='unique_current_address_per_type',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('customer', 'address_type'), name='unique_current_address_per_type', violation_error_message='A current address of this type already exists for this customer.'),
        ),
    ]
