# Generated by Django 5.2.11 on 2026-03-08 20:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_encrypt_bank_details_add_partial_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='customerpaymentmethod',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('customer',), name='unique_default_payment_per_cust', violation_error_message='Only one default payment method per customer is allowed.'),
        ),
    ]
