# Generated by Django 5.2.11 on 2026-03-09 13:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_add_unique_default_payment_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customeraddress',
            name='unique_current_address_per_type',
        ),
        migrations.RemoveConstraint(
            model_name='customerpaymentmethod',
            name='unique_default_payment_per_cust',
        ),
        migrations.AddConstraint(
            model_name='customeraddress',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_current', True)), fields=('customer', 'address_type'), name='unique_current_address_per_type', violation_error_message='A current address of this type already exists for this customer.'),
        ),
        migrations.AddConstraint(
            model_name='customerpaymentmethod',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_default', True)), fields=('customer',), name='unique_default_payment_per_cust', violation_error_message='Only one default payment method per customer is allowed.'),
        ),
    ]
