# Generated by Django 5.2.12 on 2026-03-10 23:00

import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_fix_soft_delete_unique_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=django_fsm.FSMField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('prospect', 'Prospect')], db_index=True, default='prospect', max_length=20, protected=True, verbose_name='Status'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['active', 'inactive', 'suspended', 'prospect'])), name='customer_valid_status'),
        ),
    ]
