# Generated by Django 5.2.12 on 2026-07-17 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0017_address_boolean_flags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerbillingprofile',
            name='auto_payment_enabled',
        ),
    ]
