# Generated by Django 5.2.12 on 2026-03-11 15:11

import uuid

import django.core.validators
import django.utils.timezone
from django.db import migrations, models

import apps.infrastructure.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CloudProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Provider Name')),
                ('provider_type', models.CharField(choices=[('hetzner', 'Hetzner Cloud'), ('digitalocean', 'DigitalOcean'), ('vultr', 'Vultr'), ('linode', 'Linode'), ('aws', 'Amazon Web Services'), ('gcp', 'Google Cloud Platform')], max_length=20, verbose_name='Provider Type')),
                ('code', models.CharField(help_text='3-letter code for hostname generation (e.g., het, dig, vul)', max_length=3, unique=True, verbose_name='Provider Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('credential_identifier', models.CharField(help_text='Identifier for API credentials in CredentialVault', max_length=100, verbose_name='Credential Identifier')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Provider-specific configuration', verbose_name='Configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cloud Provider',
                'verbose_name_plural': 'Cloud Providers',
                'db_table': 'infrastructure_cloud_providers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DriftCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(choices=[('cloud', 'Cloud Provider'), ('network', 'Network'), ('application', 'Application')], max_length=20, verbose_name='Check Type')),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20, verbose_name='Status')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('findings_count', models.PositiveIntegerField(default=0, verbose_name='Findings Count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Drift Check',
                'verbose_name_plural': 'Drift Checks',
                'db_table': 'infrastructure_drift_checks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DriftRemediationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('apply_desired', 'Apply Desired State'), ('accept_actual', 'Accept Actual State'), ('schedule', 'Schedule'), ('ignore', 'Ignore')], max_length=20, verbose_name='Action Type')),
                ('action_details', models.JSONField(default=dict, verbose_name='Action Details')),
                ('requires_approval', models.BooleanField(default=True, verbose_name='Requires Approval')),
                ('requires_restart', models.BooleanField(default=False, verbose_name='Requires Restart')),
                ('status', models.CharField(choices=[('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('rolled_back', 'Rolled Back'), ('rollback_failed', 'Rollback Failed')], default='pending_approval', max_length=20, verbose_name='Status')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('rejected_reason', models.TextField(blank=True, verbose_name='Rejected Reason')),
                ('scheduled_for', models.DateTimeField(blank=True, null=True, verbose_name='Scheduled For')),
                ('snapshot_id', models.CharField(blank=True, max_length=100, verbose_name='Snapshot ID')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Drift Remediation Request',
                'verbose_name_plural': 'Drift Remediation Requests',
                'db_table': 'infrastructure_drift_remediations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DriftReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('moderate', 'Moderate'), ('low', 'Low'), ('info', 'Info')], max_length=10, verbose_name='Severity')),
                ('category', models.CharField(choices=[('server_state', 'Server State'), ('network', 'Network'), ('firewall', 'Firewall'), ('application', 'Application'), ('capacity', 'Capacity')], max_length=20, verbose_name='Category')),
                ('field_name', models.CharField(max_length=100, verbose_name='Field Name')),
                ('expected_value', models.TextField(verbose_name='Expected Value')),
                ('actual_value', models.TextField(verbose_name='Actual Value')),
                ('auto_resolvable', models.BooleanField(default=False, verbose_name='Auto Resolvable')),
                ('resolved', models.BooleanField(default=False, verbose_name='Resolved')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolved At')),
                ('resolution_type', models.CharField(blank=True, choices=[('auto_sync', 'Auto Sync'), ('remediated', 'Remediated'), ('accepted', 'Accepted'), ('ignored', 'Ignored')], max_length=20, verbose_name='Resolution Type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Drift Report',
                'verbose_name_plural': 'Drift Reports',
                'db_table': 'infrastructure_drift_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DriftSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_snapshot_id', models.CharField(max_length=100, verbose_name='Provider Snapshot ID')),
                ('snapshot_type', models.CharField(choices=[('pre_remediation', 'Pre-Remediation'), ('scheduled', 'Scheduled'), ('manual', 'Manual')], max_length=20, verbose_name='Snapshot Type')),
                ('status', models.CharField(choices=[('creating', 'Creating'), ('available', 'Available'), ('restoring', 'Restoring'), ('deleted', 'Deleted'), ('failed', 'Failed')], default='creating', max_length=20, verbose_name='Status')),
                ('size_gb', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Size (GB)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires At')),
            ],
            options={
                'verbose_name': 'Drift Snapshot',
                'verbose_name_plural': 'Drift Snapshots',
                'db_table': 'infrastructure_drift_snapshots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NodeDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(choices=[('prd', 'Production'), ('stg', 'Staging'), ('dev', 'Development')], default='prd', max_length=3, verbose_name='Environment')),
                ('node_type', models.CharField(choices=[('sha', 'Shared Hosting'), ('vps', 'VPS Hosting'), ('ctr', 'Container'), ('ded', 'Dedicated'), ('app', 'Application Platform')], default='sha', max_length=3, verbose_name='Node Type')),
                ('hostname', models.CharField(help_text='Auto-generated 23-char hostname', max_length=23, unique=True, validators=[apps.infrastructure.models.validate_hostname_format], verbose_name='Hostname')),
                ('node_number', models.PositiveIntegerField(help_text='Sequential number (1-999)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)], verbose_name='Node Number')),
                ('display_name', models.CharField(blank=True, help_text='Optional friendly name', max_length=100, verbose_name='Display Name')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('provisioning_node', 'Provisioning Node'), ('configuring_dns', 'Configuring DNS'), ('installing_panel', 'Installing Panel'), ('configuring_backups', 'Configuring Backups'), ('validating', 'Validating'), ('registering', 'Registering Server'), ('completed', 'Completed'), ('stopped', 'Stopped'), ('failed', 'Failed'), ('destroying', 'Destroying'), ('destroyed', 'Destroyed')], default='pending', max_length=30, verbose_name='Status')),
                ('status_message', models.TextField(blank=True, verbose_name='Status Message')),
                ('last_successful_phase', models.CharField(blank=True, help_text='For retry logic', max_length=50, verbose_name='Last Successful Phase')),
                ('external_node_id', models.CharField(blank=True, help_text="Provider's server ID (e.g., Hetzner server ID)", max_length=100, verbose_name='External Node ID')),
                ('ipv4_address', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4', verbose_name='IPv4 Address')),
                ('ipv6_address', models.GenericIPAddressField(blank=True, null=True, protocol='IPv6', verbose_name='IPv6 Address')),
                ('ssh_key_credential_id', models.CharField(blank=True, max_length=100, verbose_name='SSH Key Credential ID')),
                ('dns_zone', models.CharField(blank=True, help_text='Zone used for this node', max_length=255, verbose_name='DNS Zone')),
                ('dns_record_ids', models.JSONField(blank=True, default=list, help_text='Created DNS record IDs', verbose_name='DNS Record IDs')),
                ('max_domains', models.PositiveIntegerField(default=50, help_text='Maximum domains for this deployment. Default based on server size.', verbose_name='Max Domains')),
                ('backup_enabled', models.BooleanField(default=True, verbose_name='Backup Enabled')),
                ('backup_storage', models.CharField(default='local', help_text="'local' or 's3'", max_length=20, verbose_name='Backup Storage')),
                ('total_cost_eur', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Cost (EUR)')),
                ('retry_count', models.PositiveIntegerField(default=0, help_text='Number of retry attempts for this deployment', verbose_name='Retry Count')),
                ('triggered_by_failover', models.BooleanField(default=False, verbose_name='Triggered by Failover')),
                ('correlation_id', models.UUIDField(default=uuid.uuid4, verbose_name='Correlation ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('destroyed_at', models.DateTimeField(blank=True, null=True, verbose_name='Destroyed At')),
            ],
            options={
                'verbose_name': 'Node Deployment',
                'verbose_name_plural': 'Node Deployments',
                'db_table': 'infrastructure_node_deployments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NodeDeploymentCostRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateTimeField(verbose_name='Period Start')),
                ('period_end', models.DateTimeField(verbose_name='Period End')),
                ('cost_eur', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Cost (EUR)')),
                ('compute_cost', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Compute Cost')),
                ('bandwidth_cost', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Bandwidth Cost')),
                ('storage_cost', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Storage Cost')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Node Deployment Cost Record',
                'verbose_name_plural': 'Node Deployment Cost Records',
                'db_table': 'infrastructure_node_deployment_costs',
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='NodeDeploymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=10, verbose_name='Level')),
                ('phase', models.CharField(help_text="'provision', 'ansible', 'dns', 'backup', etc.", max_length=50, verbose_name='Phase')),
                ('message', models.TextField(verbose_name='Message')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional structured data', verbose_name='Details')),
                ('duration_seconds', models.FloatField(blank=True, help_text='Phase duration', null=True, verbose_name='Duration (seconds)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Node Deployment Log',
                'verbose_name_plural': 'Node Deployment Logs',
                'db_table': 'infrastructure_node_deployment_logs',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='NodeRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name (e.g., "Falkenstein", "Helsinki")', max_length=100, verbose_name='Region Name')),
                ('provider_region_id', models.CharField(help_text='Provider\'s native ID (e.g., "fsn1", "us-east-1", "ewr")', max_length=50, verbose_name='Provider Region ID')),
                ('normalized_code', models.CharField(help_text='4-character normalized code for hostname (e.g., fsn1, nyc1, use1)', max_length=4, verbose_name='Normalized Code')),
                ('country_code', models.CharField(help_text='ISO 3166-1 alpha-2 country code (e.g., de, fi, us)', max_length=2, verbose_name='Country Code')),
                ('city', models.CharField(help_text='Datacenter city', max_length=100, verbose_name='City')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Node Region',
                'verbose_name_plural': 'Node Regions',
                'db_table': 'infrastructure_node_regions',
                'ordering': ['provider', 'country_code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NodeSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal name (e.g., "Small", "Medium", "Large")', max_length=100, verbose_name='Size Name')),
                ('display_name', models.CharField(help_text='UI display (e.g., "2 vCPU / 4GB RAM / 40GB")', max_length=100, verbose_name='Display Name')),
                ('provider_type_id', models.CharField(help_text='Provider\'s type ID (e.g., "cpx21", "cpx41")', max_length=50, verbose_name='Provider Type ID')),
                ('vcpus', models.PositiveIntegerField(verbose_name='vCPUs')),
                ('memory_gb', models.PositiveIntegerField(verbose_name='Memory (GB)')),
                ('disk_gb', models.PositiveIntegerField(verbose_name='Disk (GB)')),
                ('hourly_cost_eur', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Hourly Cost (EUR)')),
                ('monthly_cost_eur', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monthly Cost (EUR)')),
                ('max_domains', models.PositiveIntegerField(default=50, help_text='Estimated max domains for this size', verbose_name='Max Domains')),
                ('max_bandwidth_gb', models.PositiveIntegerField(default=1000, verbose_name='Max Bandwidth (GB)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort Order')),
            ],
            options={
                'verbose_name': 'Node Size',
                'verbose_name_plural': 'Node Sizes',
                'db_table': 'infrastructure_node_sizes',
                'ordering': ['provider', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='PanelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Panel Name')),
                ('panel_type', models.CharField(choices=[('virtualmin', 'Virtualmin GPL'), ('blesta', 'Blesta')], max_length=20, verbose_name='Panel Type')),
                ('version', models.CharField(blank=True, help_text='Pinned version (e.g., "7.10.0")', max_length=50, verbose_name='Version')),
                ('ansible_playbook', models.CharField(help_text='Playbook filename (e.g., "virtualmin.yml")', max_length=100, verbose_name='Ansible Playbook')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Panel Type',
                'verbose_name_plural': 'Panel Types',
                'db_table': 'infrastructure_panel_types',
                'ordering': ['name'],
            },
        ),
    ]
