# Generated by Django 5.2.12 on 2026-03-11 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infrastructure', '0001_initial'),
        ('provisioning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='driftremediationrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drift_requests_approved', to=settings.AUTH_USER_MODEL, verbose_name='Approved By'),
        ),
        migrations.AddField(
            model_name='driftremediationrequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drift_requests_created', to=settings.AUTH_USER_MODEL, verbose_name='Requested By'),
        ),
        migrations.AddField(
            model_name='driftreport',
            name='drift_check',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='infrastructure.driftcheck', verbose_name='Drift Check'),
        ),
        migrations.AddField(
            model_name='driftreport',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Resolved By'),
        ),
        migrations.AddField(
            model_name='driftremediationrequest',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remediation_requests', to='infrastructure.driftreport', verbose_name='Drift Report'),
        ),
        migrations.AddField(
            model_name='nodedeployment',
            name='initiated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_node_deployments', to=settings.AUTH_USER_MODEL, verbose_name='Initiated By'),
        ),
        migrations.AddField(
            model_name='nodedeployment',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deployments', to='infrastructure.cloudprovider', verbose_name='Provider'),
        ),
        migrations.AddField(
            model_name='nodedeployment',
            name='source_node',
            field=models.ForeignKey(blank=True, help_text='Original node this deployment is replacing (failover scenario)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_nodes', to='infrastructure.nodedeployment', verbose_name='Source Node'),
        ),
        migrations.AddField(
            model_name='nodedeployment',
            name='virtualmin_server',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='node_deployment', to='provisioning.virtualminserver', verbose_name='Virtualmin Server'),
        ),
        migrations.AddField(
            model_name='driftsnapshot',
            name='deployment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drift_snapshots', to='infrastructure.nodedeployment', verbose_name='Deployment'),
        ),
        migrations.AddField(
            model_name='driftreport',
            name='deployment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drift_reports', to='infrastructure.nodedeployment', verbose_name='Deployment'),
        ),
        migrations.AddField(
            model_name='driftremediationrequest',
            name='deployment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remediation_requests', to='infrastructure.nodedeployment', verbose_name='Deployment'),
        ),
        migrations.AddField(
            model_name='driftcheck',
            name='deployment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drift_checks', to='infrastructure.nodedeployment', verbose_name='Deployment'),
        ),
        migrations.AddField(
            model_name='nodedeploymentcostrecord',
            name='deployment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_records', to='infrastructure.nodedeployment', verbose_name='Deployment'),
        ),
        migrations.AddField(
            model_name='nodedeploymentlog',
            name='deployment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='infrastructure.nodedeployment', verbose_name='Deployment'),
        ),
        migrations.AddField(
            model_name='noderegion',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='infrastructure.cloudprovider', verbose_name='Provider'),
        ),
        migrations.AddField(
            model_name='nodedeployment',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deployments', to='infrastructure.noderegion', verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='nodesize',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='infrastructure.cloudprovider', verbose_name='Provider'),
        ),
        migrations.AddField(
            model_name='nodedeployment',
            name='node_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deployments', to='infrastructure.nodesize', verbose_name='Node Size'),
        ),
        migrations.AddField(
            model_name='nodedeployment',
            name='panel_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deployments', to='infrastructure.paneltype', verbose_name='Panel Type'),
        ),
        migrations.AddIndex(
            model_name='driftsnapshot',
            index=models.Index(fields=['deployment', 'status'], name='infrastruct_deploym_0d569c_idx'),
        ),
        migrations.AddIndex(
            model_name='driftsnapshot',
            index=models.Index(fields=['expires_at'], name='infrastruct_expires_bc6ff3_idx'),
        ),
        migrations.AddIndex(
            model_name='driftreport',
            index=models.Index(fields=['deployment', 'severity', '-created_at'], name='infrastruct_deploym_28d49f_idx'),
        ),
        migrations.AddIndex(
            model_name='driftreport',
            index=models.Index(fields=['resolved', 'severity'], name='infrastruct_resolve_cb541a_idx'),
        ),
        migrations.AddIndex(
            model_name='driftremediationrequest',
            index=models.Index(fields=['status', '-created_at'], name='infrastruct_status_0c8ee9_idx'),
        ),
        migrations.AddIndex(
            model_name='driftremediationrequest',
            index=models.Index(fields=['deployment', 'status'], name='infrastruct_deploym_909321_idx'),
        ),
        migrations.AddIndex(
            model_name='driftremediationrequest',
            index=models.Index(fields=['scheduled_for'], name='infrastruct_schedul_7a4485_idx'),
        ),
        migrations.AddIndex(
            model_name='driftcheck',
            index=models.Index(fields=['deployment', 'check_type', '-created_at'], name='infrastruct_deploym_48b578_idx'),
        ),
        migrations.AddIndex(
            model_name='driftcheck',
            index=models.Index(fields=['status'], name='infrastruct_status_464b8c_idx'),
        ),
        migrations.AddIndex(
            model_name='nodedeploymentcostrecord',
            index=models.Index(fields=['deployment', 'period_start'], name='infrastruct_deploym_47d622_idx'),
        ),
        migrations.AddIndex(
            model_name='nodedeploymentlog',
            index=models.Index(fields=['deployment', 'level'], name='infrastruct_deploym_aa2add_idx'),
        ),
        migrations.AddIndex(
            model_name='nodedeploymentlog',
            index=models.Index(fields=['deployment', 'phase'], name='infrastruct_deploym_b833de_idx'),
        ),
        migrations.AddIndex(
            model_name='noderegion',
            index=models.Index(fields=['provider', 'normalized_code'], name='infrastruct_provide_481813_idx'),
        ),
        migrations.AddIndex(
            model_name='noderegion',
            index=models.Index(fields=['country_code'], name='infrastruct_country_714d21_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='noderegion',
            unique_together={('provider', 'provider_region_id')},
        ),
        migrations.AlterUniqueTogether(
            name='nodesize',
            unique_together={('provider', 'provider_type_id')},
        ),
        migrations.AddIndex(
            model_name='nodedeployment',
            index=models.Index(fields=['status', 'created_at'], name='infrastruct_status_f9d1c4_idx'),
        ),
        migrations.AddIndex(
            model_name='nodedeployment',
            index=models.Index(fields=['environment', 'status'], name='infrastruct_environ_12f33a_idx'),
        ),
        migrations.AddIndex(
            model_name='nodedeployment',
            index=models.Index(fields=['node_type', 'status'], name='infrastruct_node_ty_3db5a4_idx'),
        ),
        migrations.AddIndex(
            model_name='nodedeployment',
            index=models.Index(fields=['provider', 'status'], name='infrastruct_provide_877041_idx'),
        ),
        migrations.AddIndex(
            model_name='nodedeployment',
            index=models.Index(fields=['environment', 'node_type', 'provider', 'region'], name='infrastruct_environ_04d845_idx'),
        ),
        migrations.AddIndex(
            model_name='nodedeployment',
            index=models.Index(fields=['initiated_by', 'created_at'], name='infrastruct_initiat_60a69e_idx'),
        ),
        migrations.AddIndex(
            model_name='nodedeployment',
            index=models.Index(fields=['triggered_by_failover', 'status'], name='infrastruct_trigger_690905_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='nodedeployment',
            unique_together={('environment', 'node_type', 'provider', 'region', 'node_number')},
        ),
    ]
