# Generated by Django 5.2.9 on 2025-12-27 08:34

import apps.infrastructure.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="nodedeployment",
            new_name="infrastruct_status_d531eb_idx",
            old_name="infra_nd_status_idx",
        ),
        migrations.RenameIndex(
            model_name="nodedeployment",
            new_name="infrastruct_environ_29f8a7_idx",
            old_name="infra_nd_env_status_idx",
        ),
        migrations.RenameIndex(
            model_name="nodedeployment",
            new_name="infrastruct_node_ty_48aee1_idx",
            old_name="infra_nd_type_status_idx",
        ),
        migrations.RenameIndex(
            model_name="nodedeployment",
            new_name="infrastruct_provide_de2f2d_idx",
            old_name="infra_nd_prov_status_idx",
        ),
        migrations.RenameIndex(
            model_name="nodedeployment",
            new_name="infrastruct_environ_07bfc1_idx",
            old_name="infra_nd_next_num_idx",
        ),
        migrations.RenameIndex(
            model_name="nodedeployment",
            new_name="infrastruct_initiat_df027b_idx",
            old_name="infra_nd_initiated_idx",
        ),
        migrations.RenameIndex(
            model_name="nodedeployment",
            new_name="infrastruct_trigger_599f2c_idx",
            old_name="infra_nd_failover_idx",
        ),
        migrations.RenameIndex(
            model_name="nodedeploymentcostrecord",
            new_name="infrastruct_deploym_ab7c36_idx",
            old_name="infra_ndcost_period_idx",
        ),
        migrations.RenameIndex(
            model_name="nodedeploymentlog",
            new_name="infrastruct_deploym_fd21b6_idx",
            old_name="infra_ndlog_level_idx",
        ),
        migrations.RenameIndex(
            model_name="nodedeploymentlog",
            new_name="infrastruct_deploym_a371ad_idx",
            old_name="infra_ndlog_phase_idx",
        ),
        migrations.RenameIndex(
            model_name="noderegion",
            new_name="infrastruct_provide_1d90a7_idx",
            old_name="infra_region_provider_idx",
        ),
        migrations.RenameIndex(
            model_name="noderegion",
            new_name="infrastruct_country_f676a9_idx",
            old_name="infra_region_country_idx",
        ),
        migrations.AddField(
            model_name="nodedeployment",
            name="retry_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of retry attempts for this deployment",
                verbose_name="Retry Count",
            ),
        ),
        migrations.AlterField(
            model_name="nodedeployment",
            name="hostname",
            field=models.CharField(
                help_text="Auto-generated 23-char hostname",
                max_length=23,
                unique=True,
                validators=[apps.infrastructure.models.validate_hostname_format],
                verbose_name="Hostname",
            ),
        ),
        migrations.AlterField(
            model_name="nodedeployment",
            name="node_number",
            field=models.PositiveIntegerField(
                help_text="Sequential number (1-999)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(999),
                ],
                verbose_name="Node Number",
            ),
        ),
        migrations.AlterField(
            model_name="nodedeployment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("provisioning_node", "Provisioning Node"),
                    ("configuring_dns", "Configuring DNS"),
                    ("installing_panel", "Installing Panel"),
                    ("configuring_backups", "Configuring Backups"),
                    ("validating", "Validating"),
                    ("registering", "Registering Server"),
                    ("completed", "Completed"),
                    ("stopped", "Stopped"),
                    ("failed", "Failed"),
                    ("destroying", "Destroying"),
                    ("destroyed", "Destroyed"),
                ],
                default="pending",
                max_length=30,
                verbose_name="Status",
            ),
        ),
    ]
