# Generated by Django 5.2.11 on 2026-03-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0002_rename_infra_nd_status_idx_infrastruct_status_d531eb_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodedeployment',
            name='terraform_state_backend',
        ),
        migrations.RemoveField(
            model_name='nodedeployment',
            name='terraform_state_path',
        ),
        migrations.AddField(
            model_name='nodedeployment',
            name='max_domains',
            field=models.PositiveIntegerField(default=50, help_text='Maximum domains for this deployment. Default based on server size.', verbose_name='Max Domains'),
        ),
    ]
