# Generated by Django 5.2.12 on 2026-07-18 19:50

from collections import defaultdict

from django.db import migrations, models
from django.utils import timezone

# Snapshots of service-layer vocabulary at migration time (migrations must not
# import application code).
_OPEN_STATUSES = ("pending_approval", "approved", "scheduled", "in_progress")
_STATUS_RANK = {"in_progress": 3, "scheduled": 2, "approved": 1, "pending_approval": 0}
_AUTO_FIXABLE_FIELDS = ("server_type", "server_status")


def _dedup_drift_state(apps, schema_editor):
    """
    One-time cleanup so the partial-unique constraints added in a follow-up
    migration can be created: collapse duplicate open reports/requests that the
    15-minute scanner has been minting unboundedly (#224 defect 4).
    """
    drift_report = apps.get_model("infrastructure", "DriftReport")
    remediation_request = apps.get_model("infrastructure", "DriftRemediationRequest")
    now = timezone.now()

    # 1. Stable network drift identity: escalation is expressed via severity,
    #    never by renaming the field (which would fork open rows).
    drift_report.objects.filter(resolved=False, field_name="network_unreachable_consecutive").update(
        field_name="network_unreachable", severity="critical"
    )

    # 2. At most one in_progress request per deployment (newest survives).
    by_deployment = defaultdict(list)
    for req in remediation_request.objects.filter(status="in_progress").order_by("-created_at"):
        by_deployment[req.deployment_id].append(req)
    for reqs in by_deployment.values():
        for loser in reqs[1:]:
            loser.status = "failed"
            loser.error_message = "Superseded by drift dedup migration"
            loser.completed_at = now
            loser.save(update_fields=["status", "error_message", "completed_at"])

    # 3. At most one open request per report (most-advanced survives).
    by_report = defaultdict(list)
    for req in remediation_request.objects.filter(status__in=_OPEN_STATUSES):
        by_report[req.report_id].append(req)
    for reqs in by_report.values():
        reqs.sort(key=lambda r: (_STATUS_RANK[r.status], r.created_at), reverse=True)
        for loser in reqs[1:]:
            loser.status = "superseded"
            loser.save(update_fields=["status"])

    # 4. At most one open report per (deployment, field): survivor is the report
    #    owning the most-advanced open request, else the newest report.
    def _open_rank(report_id: int) -> int:
        req = (
            remediation_request.objects.filter(report_id=report_id, status__in=_OPEN_STATUSES)
            .order_by("-created_at")
            .first()
        )
        return _STATUS_RANK[req.status] if req else -1

    groups = defaultdict(list)
    for rep in drift_report.objects.filter(resolved=False):
        groups[(rep.deployment_id, rep.field_name)].append(rep)
    for reps in groups.values():
        if len(reps) == 1:
            continue
        reps.sort(key=lambda r: (_open_rank(r.pk), r.created_at), reverse=True)
        for loser in reps[1:]:
            loser.resolved = True
            loser.resolved_at = now
            loser.resolution_type = "superseded"
            loser.save(update_fields=["resolved", "resolved_at", "resolution_type"])
            remediation_request.objects.filter(
                report_id=loser.pk, status__in=("pending_approval", "approved", "scheduled")
            ).update(status="superseded")

    # 5. Open requests for fields with no automated fix become manual work
    #    instead of no-op apply_desired executions.
    remediation_request.objects.filter(
        status__in=("pending_approval", "approved", "scheduled"), action_type="apply_desired"
    ).exclude(action_details__field_name__in=_AUTO_FIXABLE_FIELDS).update(action_type="manual_intervention")


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driftremediationrequest',
            name='execution_claimed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Execution Claimed At'),
        ),
        migrations.AddField(
            model_name='driftreport',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Seen At'),
        ),
        migrations.AddField(
            model_name='driftreport',
            name='occurrence_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Occurrence Count'),
        ),
        migrations.AlterField(
            model_name='driftremediationrequest',
            name='action_type',
            field=models.CharField(choices=[('apply_desired', 'Apply Desired State'), ('accept_actual', 'Accept Actual State'), ('manual_intervention', 'Manual Intervention'), ('schedule', 'Schedule'), ('ignore', 'Ignore')], max_length=20, verbose_name='Action Type'),
        ),
        migrations.AlterField(
            model_name='driftremediationrequest',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('rolled_back', 'Rolled Back'), ('rollback_failed', 'Rollback Failed'), ('superseded', 'Superseded')], default='pending_approval', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='driftreport',
            name='resolution_type',
            field=models.CharField(blank=True, choices=[('auto_sync', 'Auto Sync'), ('remediated', 'Remediated'), ('accepted', 'Accepted'), ('ignored', 'Ignored'), ('superseded', 'Superseded'), ('healed', 'Healed Externally')], max_length=20, verbose_name='Resolution Type'),
        ),
        migrations.RunPython(_dedup_drift_state, migrations.RunPython.noop),
    ]
