# Generated by Django 5.2.12 on 2026-07-18 20:22

import importlib

from django.conf import settings
from django.db import migrations, models


def _re_dedup_before_constraints(apps, schema_editor):
    """
    Re-run 0003's dedup immediately before the constraints land: cheap
    insurance against duplicates minted between the two migrations by any
    writer still running old scanner code.
    """
    dedup_module = importlib.import_module(
        "apps.infrastructure.migrations.0003_driftremediationrequest_execution_claimed_at_and_more"
    )
    dedup_module._dedup_drift_state(apps, schema_editor)


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0003_driftremediationrequest_execution_claimed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(_re_dedup_before_constraints, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='driftremediationrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('pending_approval', 'approved', 'scheduled', 'in_progress'))), fields=('report',), name='uniq_open_request_per_report'),
        ),
        migrations.AddConstraint(
            model_name='driftremediationrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'in_progress')), fields=('deployment',), name='uniq_in_progress_remediation_per_deployment'),
        ),
        migrations.AddConstraint(
            model_name='driftreport',
            constraint=models.UniqueConstraint(condition=models.Q(('resolved', False)), fields=('deployment', 'field_name'), name='uniq_open_drift_report_per_field'),
        ),
    ]
