# Generated by Django 5.2.11 on 2026-03-03 13:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0003_remove_terraform_fields_add_max_domains"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="nodedeploymentlog",
            name="phase",
            field=models.CharField(
                help_text="'provision', 'ansible', 'dns', 'backup', etc.",
                max_length=50,
                verbose_name="Phase",
            ),
        ),
        migrations.CreateModel(
            name="DriftCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "check_type",
                    models.CharField(
                        choices=[
                            ("cloud", "Cloud Provider"),
                            ("network", "Network"),
                            ("application", "Application"),
                        ],
                        max_length=20,
                        verbose_name="Check Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="Started At"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completed At"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Error Message"),
                ),
                (
                    "findings_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Findings Count"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "deployment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drift_checks",
                        to="infrastructure.nodedeployment",
                        verbose_name="Deployment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Drift Check",
                "verbose_name_plural": "Drift Checks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DriftReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("moderate", "Moderate"),
                            ("low", "Low"),
                            ("info", "Info"),
                        ],
                        max_length=10,
                        verbose_name="Severity",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("server_state", "Server State"),
                            ("network", "Network"),
                            ("firewall", "Firewall"),
                            ("application", "Application"),
                            ("capacity", "Capacity"),
                        ],
                        max_length=20,
                        verbose_name="Category",
                    ),
                ),
                (
                    "field_name",
                    models.CharField(max_length=100, verbose_name="Field Name"),
                ),
                ("expected_value", models.TextField(verbose_name="Expected Value")),
                ("actual_value", models.TextField(verbose_name="Actual Value")),
                (
                    "auto_resolvable",
                    models.BooleanField(default=False, verbose_name="Auto Resolvable"),
                ),
                (
                    "resolved",
                    models.BooleanField(default=False, verbose_name="Resolved"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Resolved At"
                    ),
                ),
                (
                    "resolution_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("auto_sync", "Auto Sync"),
                            ("remediated", "Remediated"),
                            ("accepted", "Accepted"),
                            ("ignored", "Ignored"),
                        ],
                        max_length=20,
                        verbose_name="Resolution Type",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "deployment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drift_reports",
                        to="infrastructure.nodedeployment",
                        verbose_name="Deployment",
                    ),
                ),
                (
                    "drift_check",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="infrastructure.driftcheck",
                        verbose_name="Drift Check",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Resolved By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Drift Report",
                "verbose_name_plural": "Drift Reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DriftRemediationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("apply_desired", "Apply Desired State"),
                            ("accept_actual", "Accept Actual State"),
                            ("schedule", "Schedule"),
                            ("ignore", "Ignore"),
                        ],
                        max_length=20,
                        verbose_name="Action Type",
                    ),
                ),
                (
                    "action_details",
                    models.JSONField(default=dict, verbose_name="Action Details"),
                ),
                (
                    "requires_approval",
                    models.BooleanField(default=True, verbose_name="Requires Approval"),
                ),
                (
                    "requires_restart",
                    models.BooleanField(default=False, verbose_name="Requires Restart"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_approval", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("rolled_back", "Rolled Back"),
                        ],
                        default="pending_approval",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Approved At"
                    ),
                ),
                (
                    "rejected_reason",
                    models.TextField(blank=True, verbose_name="Rejected Reason"),
                ),
                (
                    "scheduled_for",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Scheduled For"
                    ),
                ),
                (
                    "snapshot_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Snapshot ID"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Started At"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completed At"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Error Message"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="drift_requests_approved",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved By",
                    ),
                ),
                (
                    "deployment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remediation_requests",
                        to="infrastructure.nodedeployment",
                        verbose_name="Deployment",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="drift_requests_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Requested By",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remediation_requests",
                        to="infrastructure.driftreport",
                        verbose_name="Drift Report",
                    ),
                ),
            ],
            options={
                "verbose_name": "Drift Remediation Request",
                "verbose_name_plural": "Drift Remediation Requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DriftSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider_snapshot_id",
                    models.CharField(
                        max_length=100, verbose_name="Provider Snapshot ID"
                    ),
                ),
                (
                    "snapshot_type",
                    models.CharField(
                        choices=[
                            ("pre_remediation", "Pre-Remediation"),
                            ("scheduled", "Scheduled"),
                            ("manual", "Manual"),
                        ],
                        max_length=20,
                        verbose_name="Snapshot Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("creating", "Creating"),
                            ("available", "Available"),
                            ("restoring", "Restoring"),
                            ("deleted", "Deleted"),
                            ("failed", "Failed"),
                        ],
                        default="creating",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "size_gb",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Size (GB)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Expires At"
                    ),
                ),
                (
                    "deployment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drift_snapshots",
                        to="infrastructure.nodedeployment",
                        verbose_name="Deployment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Drift Snapshot",
                "verbose_name_plural": "Drift Snapshots",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="driftcheck",
            index=models.Index(
                fields=["deployment", "check_type", "-created_at"],
                name="infrastruct_deploym_7f8e1a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="driftcheck",
            index=models.Index(fields=["status"], name="infrastruct_status_1ac6b3_idx"),
        ),
        migrations.AddIndex(
            model_name="driftreport",
            index=models.Index(
                fields=["deployment", "severity", "-created_at"],
                name="infrastruct_deploym_fe6860_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="driftreport",
            index=models.Index(
                fields=["resolved", "severity"], name="infrastruct_resolve_c4158a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="driftremediationrequest",
            index=models.Index(
                fields=["status", "-created_at"], name="infrastruct_status_a0b559_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="driftremediationrequest",
            index=models.Index(
                fields=["deployment", "status"], name="infrastruct_deploym_1dbbf5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="driftremediationrequest",
            index=models.Index(
                fields=["scheduled_for"], name="infrastruct_schedul_463194_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="driftsnapshot",
            index=models.Index(
                fields=["deployment", "status"], name="infrastruct_deploym_5c4f4a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="driftsnapshot",
            index=models.Index(
                fields=["expires_at"], name="infrastruct_expires_35dbec_idx"
            ),
        ),
    ]
