# Generated by Django 5.2.11 on 2026-03-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0004_drift_detection_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driftremediationrequest',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('rolled_back', 'Rolled Back'), ('rollback_failed', 'Rollback Failed')], default='pending_approval', max_length=20, verbose_name='Status'),
        ),
    ]
