# Generated by Django 5.2.12 on 2026-07-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infrastructure", "0004_driftremediationrequest_uniq_open_request_per_report_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="driftremediationrequest",
            name="restart_approved",
            field=models.BooleanField(default=False, verbose_name="Restart Approved"),
        ),
        migrations.AlterField(
            model_name="driftsnapshot",
            name="status",
            field=models.CharField(
                choices=[
                    ("creating", "Creating"),
                    ("available", "Available"),
                    ("restoring", "Restoring"),
                    ("deleted", "Deleted"),
                    ("failed", "Failed"),
                    ("cleanup_failed", "Cleanup Failed"),
                ],
                default="creating",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
