# Generated by Django 5.2.5 on 2025-09-13 15:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('security_incident', 'Security Incident'), ('compliance_violation', 'Compliance Violation'), ('data_integrity', 'Data Integrity Issue'), ('suspicious_activity', 'Suspicious Activity'), ('performance_anomaly', 'Performance Anomaly'), ('retention_violation', 'Retention Policy Violation')], db_index=True, max_length=30)),
                ('severity', models.CharField(choices=[('info', 'Informational'), ('warning', 'Warning'), ('high', 'High Priority'), ('critical', 'Critical')], db_index=True, max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('investigating', 'Under Investigation'), ('resolved', 'Resolved'), ('false_positive', 'False Positive')], db_index=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('resolution_notes', models.TextField(blank=True)),
                ('remediation_actions', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'audit_alert',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('actor_type', models.CharField(default='user', max_length=20)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('access', 'Access'), ('export', 'Export'), ('import', 'Import'), ('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('login_failed_password', 'Login Failed - Invalid Password'), ('login_failed_user_not_found', 'Login Failed - User Not Found'), ('login_failed_account_locked', 'Login Failed - Account Locked'), ('login_failed_2fa', 'Login Failed - 2FA Verification'), ('logout_manual', 'Manual Logout'), ('logout_session_expired', 'Session Expired Logout'), ('logout_concurrent_session', 'Concurrent Session Logout'), ('logout_security_event', 'Security Event Logout'), ('account_locked', 'Account Locked'), ('account_unlocked', 'Account Unlocked'), ('session_rotation', 'Session Rotation'), ('session_terminated', 'Session Terminated'), ('password_changed', 'Password Changed'), ('password_reset_requested', 'Password Reset Requested'), ('password_reset_completed', 'Password Reset Completed'), ('password_reset_failed', 'Password Reset Failed'), ('password_strength_weak', 'Weak Password Attempted'), ('password_compromised', 'Compromised Password Detected'), ('password_expired', 'Password Expired'), ('password_policy_violation', 'Password Policy Violation'), ('2fa_enabled', '2FA Enabled'), ('2fa_disabled', '2FA Disabled'), ('2fa_admin_reset', '2FA Admin Reset'), ('2fa_backup_codes_generated', '2FA Backup Codes Generated'), ('2fa_backup_codes_viewed', '2FA Backup Codes Viewed'), ('2fa_backup_code_used', '2FA Backup Code Used'), ('2fa_secret_regenerated', '2FA Secret Regenerated'), ('2fa_verification_success', '2FA Verification Success'), ('2fa_verification_failed', '2FA Verification Failed'), ('2fa_setup_started', '2FA Setup Started'), ('2fa_setup_completed', '2FA Setup Completed'), ('2fa_recovery_used', '2FA Recovery Code Used'), ('2fa_device_registered', '2FA Device Registered'), ('2fa_device_removed', '2FA Device Removed'), ('profile_updated', 'Profile Updated'), ('profile_picture_changed', 'Profile Picture Changed'), ('email_changed', 'Email Address Changed'), ('email_verification_requested', 'Email Verification Requested'), ('email_verification_completed', 'Email Verification Completed'), ('phone_updated', 'Phone Number Updated'), ('phone_verification_requested', 'Phone Verification Requested'), ('phone_verification_completed', 'Phone Verification Completed'), ('name_changed', 'Name Changed'), ('language_preference_changed', 'Language Preference Changed'), ('timezone_changed', 'Timezone Changed'), ('emergency_contact_updated', 'Emergency Contact Updated'), ('privacy_settings_changed', 'Privacy Settings Changed'), ('marketing_consent_granted', 'Marketing Consent Granted'), ('marketing_consent_withdrawn', 'Marketing Consent Withdrawn'), ('gdpr_consent_granted', 'GDPR Consent Granted'), ('gdpr_consent_withdrawn', 'GDPR Consent Withdrawn'), ('data_processing_consent_changed', 'Data Processing Consent Changed'), ('cookie_consent_updated', 'Cookie Consent Updated'), ('privacy_policy_accepted', 'Privacy Policy Accepted'), ('terms_of_service_accepted', 'Terms of Service Accepted'), ('notification_settings_changed', 'Notification Settings Changed'), ('email_notifications_toggled', 'Email Notifications Toggled'), ('sms_notifications_toggled', 'SMS Notifications Toggled'), ('push_notifications_toggled', 'Push Notifications Toggled'), ('notification_frequency_changed', 'Notification Frequency Changed'), ('role_assigned', 'Role Assigned'), ('role_removed', 'Role Removed'), ('permission_granted', 'Permission Granted'), ('permission_revoked', 'Permission Revoked'), ('access_denied', 'Access Denied'), ('privilege_escalation_attempt', 'Privilege Escalation Attempt'), ('staff_role_changed', 'Staff Role Changed'), ('customer_role_changed', 'Customer Role Changed'), ('customer_membership_created', 'Customer Membership Created'), ('customer_membership_updated', 'Customer Membership Updated'), ('customer_membership_deleted', 'Customer Membership Deleted'), ('primary_customer_changed', 'Primary Customer Changed'), ('customer_access_granted', 'Customer Access Granted'), ('customer_access_revoked', 'Customer Access Revoked'), ('customer_context_switched', 'Customer Context Switched'), ('api_key_generated', 'API Key Generated'), ('api_key_regenerated', 'API Key Regenerated'), ('api_key_revoked', 'API Key Revoked'), ('api_key_used', 'API Key Used'), ('api_access_denied', 'API Access Denied'), ('webhook_configured', 'Webhook Configured'), ('webhook_updated', 'Webhook Updated'), ('webhook_removed', 'Webhook Removed'), ('security_incident_detected', 'Security Incident Detected'), ('suspicious_activity', 'Suspicious Activity'), ('brute_force_attempt', 'Brute Force Attempt'), ('ip_blocked', 'IP Address Blocked'), ('ip_unblocked', 'IP Address Unblocked'), ('rate_limit_exceeded', 'Rate Limit Exceeded'), ('malicious_request', 'Malicious Request Detected'), ('security_scan_detected', 'Security Scan Detected'), ('data_export_requested', 'Data Export Requested'), ('data_export_completed', 'Data Export Completed'), ('data_export_downloaded', 'Data Export Downloaded'), ('data_deletion_requested', 'Data Deletion Requested'), ('data_deletion_completed', 'Data Deletion Completed'), ('data_anonymization_completed', 'Data Anonymization Completed'), ('data_breach_detected', 'Data Breach Detected'), ('data_breach_contained', 'Data Breach Contained'), ('data_breach_reported', 'Data Breach Reported'), ('invoice_accessed', 'Invoice Accessed'), ('invoice_downloaded', 'Invoice Downloaded'), ('payment_method_added', 'Payment Method Added'), ('payment_method_updated', 'Payment Method Updated'), ('payment_method_removed', 'Payment Method Removed'), ('billing_address_updated', 'Billing Address Updated'), ('tax_information_updated', 'Tax Information Updated'), ('order_placed', 'Order Placed'), ('order_cancelled', 'Order Cancelled'), ('service_activated', 'Service Activated'), ('service_suspended', 'Service Suspended'), ('support_ticket_created', 'Support Ticket Created'), ('support_ticket_updated', 'Support Ticket Updated'), ('support_ticket_closed', 'Support Ticket Closed'), ('proforma_created', 'Proforma Created'), ('proforma_converted', 'Proforma Converted to Invoice'), ('proforma_expired', 'Proforma Expired'), ('invoice_created', 'Invoice Created'), ('invoice_issued', 'Invoice Issued'), ('invoice_sent', 'Invoice Sent'), ('invoice_paid', 'Invoice Paid'), ('invoice_partially_paid', 'Invoice Partially Paid'), ('invoice_overdue', 'Invoice Overdue'), ('invoice_voided', 'Invoice Voided'), ('invoice_refunded', 'Invoice Refunded'), ('invoice_status_changed', 'Invoice Status Changed'), ('invoice_number_generated', 'Invoice Number Generated'), ('invoice_pdf_generated', 'Invoice PDF Generated'), ('invoice_xml_generated', 'Invoice XML Generated'), ('efactura_submitted', 'e-Factura Submitted'), ('efactura_accepted', 'e-Factura Accepted'), ('efactura_rejected', 'e-Factura Rejected'), ('vat_calculation_applied', 'VAT Calculation Applied'), ('tax_rule_applied', 'Tax Rule Applied'), ('currency_conversion_applied', 'Currency Conversion Applied'), ('payment_initiated', 'Payment Initiated'), ('payment_processing', 'Payment Processing'), ('payment_succeeded', 'Payment Succeeded'), ('payment_failed', 'Payment Failed'), ('payment_refunded', 'Payment Refunded'), ('payment_partially_refunded', 'Payment Partially Refunded'), ('payment_retry_scheduled', 'Payment Retry Scheduled'), ('payment_retry_attempted', 'Payment Retry Attempted'), ('payment_retry_succeeded', 'Payment Retry Succeeded'), ('payment_retry_failed', 'Payment Retry Failed'), ('payment_retry_exhausted', 'Payment Retry Exhausted'), ('payment_method_changed', 'Payment Method Changed'), ('payment_gateway_error', 'Payment Gateway Error'), ('payment_fraud_detected', 'Payment Fraud Detected'), ('payment_chargeback_received', 'Payment Chargeback Received'), ('dunning_email_sent', 'Dunning Email Sent'), ('collection_run_started', 'Collection Run Started'), ('collection_run_completed', 'Collection Run Completed'), ('credit_added', 'Credit Added'), ('credit_used', 'Credit Used'), ('credit_adjusted', 'Credit Adjusted'), ('credit_expired', 'Credit Expired'), ('balance_low_warning', 'Balance Low Warning'), ('balance_insufficient', 'Balance Insufficient'), ('credit_limit_changed', 'Credit Limit Changed'), ('credit_hold_applied', 'Credit Hold Applied'), ('credit_hold_released', 'Credit Hold Released'), ('order_created', 'Order Created'), ('order_updated', 'Order Updated'), ('order_status_changed', 'Order Status Changed'), ('order_item_added', 'Order Item Added'), ('order_item_removed', 'Order Item Removed'), ('order_item_updated', 'Order Item Updated'), ('order_quantity_changed', 'Order Quantity Changed'), ('order_pricing_updated', 'Order Pricing Updated'), ('order_submitted', 'Order Submitted'), ('order_confirmed', 'Order Confirmed'), ('order_processing', 'Order Processing'), ('order_completed', 'Order Completed'), ('order_cancelled_customer', 'Order Cancelled by Customer'), ('order_cancelled_admin', 'Order Cancelled by Admin'), ('order_failed', 'Order Failed'), ('order_refund_requested', 'Order Refund Requested'), ('order_refund_approved', 'Order Refund Approved'), ('order_refund_processed', 'Order Refund Processed'), ('order_discount_applied', 'Order Discount Applied'), ('order_discount_removed', 'Order Discount Removed'), ('order_tax_calculated', 'Order Tax Calculated'), ('order_shipping_updated', 'Order Shipping Updated'), ('order_notes_updated', 'Order Notes Updated'), ('provisioning_started', 'Provisioning Started'), ('provisioning_in_progress', 'Provisioning In Progress'), ('provisioning_completed', 'Provisioning Completed'), ('provisioning_failed', 'Provisioning Failed'), ('provisioning_retried', 'Provisioning Retried'), ('service_configuration_updated', 'Service Configuration Updated'), ('domain_associated', 'Domain Associated'), ('domain_dissociated', 'Domain Dissociated'), ('service_credentials_generated', 'Service Credentials Generated'), ('service_access_granted', 'Service Access Granted'), ('service_access_revoked', 'Service Access Revoked'), ('system_maintenance_started', 'System Maintenance Started'), ('system_maintenance_completed', 'System Maintenance Completed'), ('backup_created', 'Backup Created'), ('backup_restored', 'Backup Restored'), ('configuration_changed', 'Configuration Changed'), ('user_impersonation_started', 'User Impersonation Started'), ('user_impersonation_ended', 'User Impersonation Ended'), ('bulk_operation_started', 'Bulk Operation Started'), ('bulk_operation_completed', 'Bulk Operation Completed')], db_index=True, max_length=50)),
                ('category', models.CharField(choices=[('authentication', 'Authentication'), ('authorization', 'Authorization'), ('account_management', 'Account Management'), ('data_protection', 'Data Protection'), ('security_event', 'Security Event'), ('business_operation', 'Business Operation'), ('system_admin', 'System Administration'), ('compliance', 'Compliance'), ('privacy', 'Privacy'), ('integration', 'Integration')], db_index=True, default='business_operation', max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='low', max_length=10)),
                ('is_sensitive', models.BooleanField(db_index=True, default=False)),
                ('requires_review', models.BooleanField(db_index=True, default=False)),
                ('object_id', models.CharField(db_index=True, max_length=36)),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=36)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'audit_event',
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='AuditIntegrityCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_type', models.CharField(db_index=True, max_length=50)),
                ('checked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('period_start', models.DateTimeField(db_index=True)),
                ('period_end', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('warning', 'Warning'), ('compromised', 'Compromised')], default='healthy', max_length=20)),
                ('records_checked', models.PositiveIntegerField(default=0)),
                ('issues_found', models.PositiveIntegerField(default=0)),
                ('findings', models.JSONField(blank=True, default=list)),
                ('hash_chain', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'audit_integrity_check',
                'ordering': ('-checked_at',),
            },
        ),
        migrations.CreateModel(
            name='AuditRetentionPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('authentication', 'Authentication'), ('authorization', 'Authorization'), ('account_management', 'Account Management'), ('data_protection', 'Data Protection'), ('security_event', 'Security Event'), ('business_operation', 'Business Operation'), ('system_admin', 'System Administration'), ('compliance', 'Compliance'), ('privacy', 'Privacy'), ('integration', 'Integration')], max_length=30)),
                ('severity', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('retention_days', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('archive', 'Archive to Cold Storage'), ('delete', 'Permanent Deletion'), ('anonymize', 'Anonymize Sensitive Data')], default='archive', max_length=20)),
                ('legal_basis', models.CharField(blank=True, max_length=200)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'audit_retention_policy',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='AuditSearchQuery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('query_params', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('is_shared', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'audit_search_query',
                'ordering': ('-last_used_at', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ComplianceLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('compliance_type', models.CharField(choices=[('gdpr_consent', 'GDPR Consent'), ('gdpr_deletion', 'GDPR Data Deletion'), ('vat_validation', 'VAT Number Validation'), ('efactura_submission', 'e-Factura Submission'), ('data_retention', 'Data Retention Policy'), ('security_incident', 'Security Incident'), ('audit_integrity', 'Audit Data Integrity')], max_length=30)),
                ('reference_id', models.CharField(db_index=True, max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'audit_compliance_log',
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='DataExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('export_type', models.CharField(max_length=50)),
                ('scope', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('file_path', models.CharField(blank=True, default='', max_length=255)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('record_count', models.PositiveIntegerField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'audit_data_export',
                'ordering': ('-requested_at',),
            },
        ),
    ]
