# Generated by Django 5.2.5 on 2025-09-13 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditalert',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_audit_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditalert',
            name='affected_users',
            field=models.ManyToManyField(blank=True, related_name='audit_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditalert',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_audit_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditalert',
            name='related_events',
            field=models.ManyToManyField(blank=True, to='audit.auditevent'),
        ),
        migrations.AddIndex(
            model_name='auditintegritycheck',
            index=models.Index(fields=['check_type', '-checked_at'], name='audit_integ_check_t_4b1da6_idx'),
        ),
        migrations.AddIndex(
            model_name='auditintegritycheck',
            index=models.Index(fields=['status', '-checked_at'], name='audit_integ_status_e2041d_idx'),
        ),
        migrations.AddIndex(
            model_name='auditintegritycheck',
            index=models.Index(fields=['period_start', 'period_end'], name='audit_integ_period__bf3b01_idx'),
        ),
        migrations.AddField(
            model_name='auditretentionpolicy',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditsearchquery',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditsearchquery',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_audit_queries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compliancelog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dataexport',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['user', '-timestamp'], name='audit_event_user_id_a974a6_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['content_type', 'object_id', '-timestamp'], name='audit_event_content_919dd1_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['action', '-timestamp'], name='audit_event_action_1b99fa_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['request_id'], name='audit_event_request_0a5a80_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['category', '-timestamp'], name='idx_audit_category_time'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['severity', '-timestamp'], name='idx_audit_severity_time'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['is_sensitive', '-timestamp'], name='idx_audit_sensitive_time'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['requires_review', '-timestamp'], name='idx_audit_review_time'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['category', 'severity', '-timestamp'], name='idx_audit_cat_sev_time'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['user', 'category', '-timestamp'], name='idx_audit_user_cat_time'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['ip_address', 'severity', '-timestamp'], name='idx_audit_ip_sev_time'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['user', 'action', '-timestamp'], name='idx_audit_user_action_time'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['ip_address', 'action', '-timestamp'], name='idx_audit_ip_action_time'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['session_key', '-timestamp'], name='idx_audit_session_time'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['actor_type', 'action', '-timestamp'], name='idx_audit_actor_action_time'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['user', 'category', 'is_sensitive', '-timestamp'], name='idx_audit_compliance'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['timestamp', 'category'], name='idx_audit_time_cat'),
        ),
        migrations.AddIndex(
            model_name='auditalert',
            index=models.Index(fields=['alert_type', '-created_at'], name='audit_alert_alert_t_abdf52_idx'),
        ),
        migrations.AddIndex(
            model_name='auditalert',
            index=models.Index(fields=['severity', 'status', '-created_at'], name='audit_alert_severit_8723ab_idx'),
        ),
        migrations.AddIndex(
            model_name='auditalert',
            index=models.Index(fields=['assigned_to', 'status'], name='audit_alert_assigne_d9d5f5_idx'),
        ),
        migrations.AddIndex(
            model_name='auditalert',
            index=models.Index(fields=['status', '-created_at'], name='audit_alert_status_10822e_idx'),
        ),
        migrations.AddIndex(
            model_name='auditretentionpolicy',
            index=models.Index(fields=['category', 'severity'], name='audit_reten_categor_37b735_idx'),
        ),
        migrations.AddIndex(
            model_name='auditretentionpolicy',
            index=models.Index(fields=['is_active', 'retention_days'], name='audit_reten_is_acti_10a899_idx'),
        ),
        migrations.AddIndex(
            model_name='auditsearchquery',
            index=models.Index(fields=['created_by', '-created_at'], name='audit_searc_created_b18584_idx'),
        ),
        migrations.AddIndex(
            model_name='auditsearchquery',
            index=models.Index(fields=['is_shared', '-usage_count'], name='audit_searc_is_shar_063c71_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancelog',
            index=models.Index(fields=['compliance_type', '-timestamp'], name='audit_compl_complia_fdc50e_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancelog',
            index=models.Index(fields=['reference_id'], name='audit_compl_referen_86808f_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancelog',
            index=models.Index(fields=['status', '-timestamp'], name='audit_compl_status_5cc267_idx'),
        ),
    ]
