# Generated by Django 5.2.12 on 2026-03-11 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def apply_postgres_event_storage_indexes(apps, schema_editor) -> None:  # type: ignore[no-untyped-def]
    if schema_editor.connection.vendor != "postgresql":
        return

    statements = (
        """
        CREATE INDEX IF NOT EXISTS audit_events_dashboard_cover_idx
        ON audit_events (timestamp DESC)
        INCLUDE (user_id, action, category, severity, actor_type, content_type_id, object_id, request_id, is_sensitive, requires_review);
        """,
        """
        CREATE INDEX IF NOT EXISTS audit_events_timestamp_brin
        ON audit_events USING BRIN (timestamp) WITH (pages_per_range = 32);
        """,
    )
    with schema_editor.connection.cursor() as cursor:
        for statement in statements:
            cursor.execute(statement)


def reverse_postgres_event_storage_indexes(apps, schema_editor) -> None:  # type: ignore[no-untyped-def]
    if schema_editor.connection.vendor != "postgresql":
        return

    statements = (
        "DROP INDEX IF EXISTS audit_events_timestamp_brin;",
        "DROP INDEX IF EXISTS audit_events_dashboard_cover_idx;",
    )
    with schema_editor.connection.cursor() as cursor:
        for statement in statements:
            cursor.execute(statement)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditalert',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_audit_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditalert',
            name='affected_users',
            field=models.ManyToManyField(blank=True, related_name='audit_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditalert',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_audit_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditalert',
            name='related_events',
            field=models.ManyToManyField(blank=True, to='audit.auditevent'),
        ),
        migrations.AddIndex(
            model_name='auditintegritycheck',
            index=models.Index(fields=['check_type', '-checked_at'], name='audit_integ_check_t_54079c_idx'),
        ),
        migrations.AddIndex(
            model_name='auditintegritycheck',
            index=models.Index(fields=['status', '-checked_at'], name='audit_integ_status_7654d9_idx'),
        ),
        migrations.AddIndex(
            model_name='auditintegritycheck',
            index=models.Index(fields=['period_start', 'period_end'], name='audit_integ_period__d2d9e7_idx'),
        ),
        migrations.AddField(
            model_name='auditretentionpolicy',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditsearchquery',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditsearchquery',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_audit_queries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compliancelog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compliancereportrecord',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cookieconsent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cookie_consents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dataexport',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='siemexportlog',
            index=models.Index(fields=['status', '-started_at'], name='audit_siem__status_140df6_idx'),
        ),
        migrations.AddIndex(
            model_name='siemexportlog',
            index=models.Index(fields=['export_format', '-started_at'], name='audit_siem__export__9aa5e1_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['user', '-timestamp'], name='audit_event_user_id_36e2e1_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['content_type', 'object_id', '-timestamp'], name='audit_event_content_db7981_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['action', '-timestamp'], name='audit_event_action_39022f_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['request_id'], name='audit_event_request_3a79d3_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['category', '-timestamp'], name='idx_audit_category_time'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['severity', '-timestamp'], name='idx_audit_severity_time'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['is_sensitive', '-timestamp'], name='idx_audit_sensitive_time'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['requires_review', '-timestamp'], name='idx_audit_review_time'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['category', 'severity', '-timestamp'], name='idx_audit_cat_sev_time'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['user', 'category', '-timestamp'], name='idx_audit_user_cat_time'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['ip_address', 'severity', '-timestamp'], name='idx_audit_ip_sev_time'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['user', 'action', '-timestamp'], name='idx_audit_user_action_time'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['ip_address', 'action', '-timestamp'], name='idx_audit_ip_action_time'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['session_key', '-timestamp'], name='idx_audit_session_time'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['actor_type', 'action', '-timestamp'], name='idx_audit_actor_action_time'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['user', 'category', 'is_sensitive', '-timestamp'], name='idx_audit_compliance'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['timestamp', 'category'], name='idx_audit_time_cat'),
        ),
        migrations.AddIndex(
            model_name='auditalert',
            index=models.Index(fields=['alert_type', '-created_at'], name='audit_alert_alert_t_8f3c36_idx'),
        ),
        migrations.AddIndex(
            model_name='auditalert',
            index=models.Index(fields=['severity', 'status', '-created_at'], name='audit_alert_severit_888f8c_idx'),
        ),
        migrations.AddIndex(
            model_name='auditalert',
            index=models.Index(fields=['assigned_to', 'status'], name='audit_alert_assigne_0d0516_idx'),
        ),
        migrations.AddIndex(
            model_name='auditalert',
            index=models.Index(fields=['status', '-created_at'], name='audit_alert_status_f3092a_idx'),
        ),
        migrations.AddIndex(
            model_name='auditretentionpolicy',
            index=models.Index(fields=['category', 'severity'], name='audit_reten_categor_63cf79_idx'),
        ),
        migrations.AddIndex(
            model_name='auditretentionpolicy',
            index=models.Index(fields=['is_active', 'retention_days'], name='audit_reten_is_acti_964603_idx'),
        ),
        migrations.AddIndex(
            model_name='auditsearchquery',
            index=models.Index(fields=['created_by', '-created_at'], name='audit_searc_created_cb81ca_idx'),
        ),
        migrations.AddIndex(
            model_name='auditsearchquery',
            index=models.Index(fields=['is_shared', '-usage_count'], name='audit_searc_is_shar_bf7965_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancelog',
            index=models.Index(fields=['compliance_type', '-timestamp'], name='audit_compl_complia_4b837d_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancelog',
            index=models.Index(fields=['reference_id'], name='audit_compl_referen_3e5493_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancelog',
            index=models.Index(fields=['status', '-timestamp'], name='audit_compl_status_667a69_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancereportrecord',
            index=models.Index(fields=['report_type', '-generated_at'], name='audit_compl_report__fdad80_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancereportrecord',
            index=models.Index(fields=['framework', '-generated_at'], name='audit_compl_framewo_af76fc_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancereportrecord',
            index=models.Index(fields=['overall_status', '-generated_at'], name='audit_compl_overall_39dd2a_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancereportrecord',
            index=models.Index(fields=['period_start', 'period_end'], name='audit_compl_period__5b67fe_idx'),
        ),
        migrations.AddIndex(
            model_name='cookieconsent',
            index=models.Index(fields=['user', '-updated_at'], name='audit_cooki_user_id_6ccc67_idx'),
        ),
        migrations.AddIndex(
            model_name='cookieconsent',
            index=models.Index(fields=['cookie_id', '-updated_at'], name='audit_cooki_cookie__7cbe54_idx'),
        ),
        migrations.AddIndex(
            model_name='cookieconsent',
            index=models.Index(fields=['status', '-created_at'], name='audit_cooki_status_4c83b6_idx'),
        ),
        migrations.RunPython(apply_postgres_event_storage_indexes, reverse_postgres_event_storage_indexes),
    ]
