# Generated by Django 5.2.12 on 2026-07-22 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SIEMExportLog',
        ),
        migrations.DeleteModel(
            name='SIEMHashChainState',
        ),
    ]
