# Generated by Django 5.2.12 on 2026-07-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0003_delete_siemexportlog_delete_siemhashchainstate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditintegritycheck",
            name="status",
            field=models.CharField(
                choices=[
                    ("healthy", "Healthy"),
                    ("warning", "Warning"),
                    ("compromised", "Compromised"),
                    ("error", "Error"),
                ],
                default="healthy",
                max_length=20,
            ),
        ),
    ]
