# Generated by Django 5.2.5 on 2025-08-26 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0004_alter_dataexport_file_path"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auditevent",
            options={"ordering": ("-timestamp",)},
        ),
        migrations.AlterModelOptions(
            name="compliancelog",
            options={"ordering": ("-timestamp",)},
        ),
        migrations.AlterModelOptions(
            name="dataexport",
            options={"ordering": ("-requested_at",)},
        ),
    ]
