# Generated by Django 5.2.5 on 2025-08-28 06:06

from django.db import migrations, models


def convert_object_ids_to_string(apps, schema_editor):
    """
    Convert existing integer object_id values to string format.
    This is safe as CharField will store integers as strings.
    """
    AuditEvent = apps.get_model('audit', 'AuditEvent')
    
    # PostgreSQL and SQLite handle this conversion automatically
    # when we change the field type, but we can be explicit
    # about the data transformation if needed
    
    # No explicit data conversion needed since:
    # 1. Existing integer PKs will be stored as "123" strings
    # 2. New UUID PKs will be stored as "550e8400-e29b-41d4-a716-446655440000" strings
    # 3. Django's GenericForeignKey handles the conversion automatically
    
    pass  # Django's field type change handles this automatically


def reverse_convert_object_ids_to_integer(apps, schema_editor):
    """
    Reverse migration: Convert string object_id back to integer.
    This is more complex as we need to validate that all values are numeric.
    """
    AuditEvent = apps.get_model('audit', 'AuditEvent')
    
    # Check if any audit events have non-numeric object_ids (UUIDs)
    non_numeric_count = AuditEvent.objects.exclude(
        object_id__regex=r'^\d+$'
    ).count()
    
    if non_numeric_count > 0:
        raise ValueError(
            f"Cannot reverse migration: Found {non_numeric_count} audit events "
            f"with non-numeric object_ids (likely UUIDs). "
            f"This migration cannot be safely reversed."
        )


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0005_fix_dataexport_file_path_nullable"),
    ]

    operations = [
        # Step 1: Run data conversion (though it's mostly automatic)
        migrations.RunPython(
            convert_object_ids_to_string,
            reverse_convert_object_ids_to_integer
        ),
        
        # Step 2: Change the field type from PositiveIntegerField to CharField
        migrations.AlterField(
            model_name='auditevent',
            name='object_id',
            field=models.CharField(db_index=True, max_length=36),
        ),
    ]
