# Generated by Django 5.2.12 on 2026-07-22 19:58

import uuid

from django.conf import settings
from django.db import migrations, models


def _normalize_retention_policies(apps, schema_editor):
    """Bring pre-existing rows into constraint-satisfying shape.

    - archive action (removed placeholder) -> anonymize (never silently deletes)
    - mandatory but inactive -> reactivate (a legal rule cannot be off)
    - multiple active policies per (category, severity) -> keep newest, deactivate rest
    """
    policy_model = apps.get_model("audit", "AuditRetentionPolicy")
    policy_model.objects.filter(action="archive").update(action="anonymize")
    policy_model.objects.filter(is_mandatory=True, is_active=False).update(is_active=True)

    seen_scopes = set()
    for policy in policy_model.objects.filter(is_active=True).order_by("-created_at"):
        scope = (policy.category, policy.severity)
        if scope in seen_scopes:
            policy.is_active = False
            policy.is_mandatory = False
            policy.save(update_fields=["is_active", "is_mandatory"])
        else:
            seen_scopes.add(scope)


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0005_alter_auditevent_content_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(_normalize_retention_policies, migrations.RunPython.noop),
        migrations.CreateModel(
            name="FileIntegrityBaseline",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("path", models.CharField(max_length=500, unique=True)),
                ("sha256", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "audit_file_integrity_baselines",
                "ordering": ("path",),
            },
        ),
        migrations.AlterField(
            model_name="auditretentionpolicy",
            name="action",
            field=models.CharField(
                choices=[("delete", "Permanent Deletion"), ("anonymize", "Anonymize Sensitive Data")],
                default="anonymize",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="auditretentionpolicy",
            constraint=models.CheckConstraint(
                condition=models.Q(("is_mandatory", False), ("is_active", True), _connector="OR"),
                name="audit_retention_mandatory_implies_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="auditretentionpolicy",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("category", "severity"),
                name="audit_retention_one_active_per_scope",
            ),
        ),
    ]
