# Generated by Django 5.2.12 on 2026-07-29 12:31

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0008_alter_auditevent_action"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEventReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Reviewed At"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "audit_event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review",
                        to="audit.auditevent",
                        verbose_name="Audit Event",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_event_reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reviewed By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Event Review",
                "verbose_name_plural": "Audit Event Reviews",
                "db_table": "audit_event_reviews",
                "ordering": ("-reviewed_at",),
                "indexes": [
                    models.Index(
                        fields=["reviewed_by", "-reviewed_at"],
                        name="audit_event_reviewe_d744bb_idx",
                    )
                ],
            },
        ),
    ]
