# Generated by Django 5.2.12 on 2026-07-26 19:39

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0009_auditeventreview"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditChainHead",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("last_sequence", models.BigIntegerField(default=0)),
                (
                    "last_chain_mac",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "backfill_complete",
                    models.BooleanField(
                        default=False,
                        help_text="Live appends stay gated until the historical backfill has run.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "audit_chain_head",
            },
        ),
        migrations.CreateModel(
            name="AuditChainLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sequence", models.BigIntegerField(db_index=True, unique=True)),
                ("event_id_str", models.CharField(db_index=True, max_length=36)),
                ("event_timestamp", models.DateTimeField()),
                ("event_action", models.CharField(max_length=50)),
                ("event_content_type_id", models.IntegerField(blank=True, null=True)),
                (
                    "event_object_id",
                    models.CharField(blank=True, default="", max_length=36),
                ),
                (
                    "event_v2_mac",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("chain_mac", models.CharField(max_length=64)),
                (
                    "prev_chain_mac",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("key_id", models.CharField(max_length=8)),
                ("is_tombstone", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chain_links",
                        to="audit.auditevent",
                    ),
                ),
            ],
            options={
                "db_table": "audit_chain_links",
                "ordering": ("sequence",),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_tombstone", False)),
                        fields=("event",),
                        name="audit_chain_one_link_per_event",
                    )
                ],
            },
        ),
    ]
