# Generated by Django 5.2.9 on 2025-12-27 20:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SIEMHashChainState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sequence_number", models.BigIntegerField(db_index=True, default=0)),
                ("last_hash", models.CharField(blank=True, max_length=128)),
                ("last_event_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("hash_algorithm", models.CharField(default="sha256", max_length=20)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "audit_siem_hash_chain_state",
                "ordering": ("-updated_at",),
            },
        ),
        migrations.CreateModel(
            name="SIEMExportLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "export_format",
                    models.CharField(
                        choices=[
                            ("cef", "CEF (ArcSight/Splunk)"),
                            ("leef", "LEEF (IBM QRadar)"),
                            ("json", "JSON (ELK/Graylog)"),
                            ("syslog", "Syslog (RFC 5424)"),
                            ("ocsf", "OCSF"),
                        ],
                        max_length=10,
                    ),
                ),
                ("destination", models.CharField(max_length=255)),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("events_exported", models.PositiveIntegerField(default=0)),
                ("events_failed", models.PositiveIntegerField(default=0)),
                ("bytes_transferred", models.BigIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "audit_siem_export_log",
                "ordering": ("-started_at",),
                "indexes": [
                    models.Index(
                        fields=["status", "-started_at"],
                        name="audit_siem__status_2cdb74_idx",
                    ),
                    models.Index(
                        fields=["export_format", "-started_at"],
                        name="audit_siem__export__efd8b5_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ComplianceReportRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("security_summary", "Security Summary"),
                            ("access_review", "Access Review"),
                            ("authentication_audit", "Authentication Audit"),
                            ("data_access_audit", "Data Access Audit"),
                            ("compliance_violations", "Compliance Violations"),
                            ("gdpr_compliance", "GDPR Compliance"),
                            (
                                "romanian_fiscal_compliance",
                                "Romanian Fiscal Compliance",
                            ),
                            ("log_integrity", "Log Integrity"),
                            ("retention_compliance", "Retention Compliance"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "framework",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("iso27001", "ISO 27001"),
                            ("soc2", "SOC 2"),
                            ("gdpr", "GDPR"),
                            ("romanian_fiscal", "Romanian Fiscal"),
                            ("e_factura", "e-Factura"),
                            ("nist", "NIST"),
                            ("pci_dss", "PCI DSS"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                (
                    "generated_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    "overall_status",
                    models.CharField(
                        choices=[
                            ("compliant", "Compliant"),
                            ("partial", "Partial Compliance"),
                            ("non_compliant", "Non-Compliant"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "compliance_score",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("total_events", models.PositiveIntegerField(default=0)),
                ("total_violations", models.PositiveIntegerField(default=0)),
                ("critical_findings", models.PositiveIntegerField(default=0)),
                ("file_path", models.CharField(blank=True, max_length=500)),
                ("file_format", models.CharField(default="json", max_length=10)),
                ("sections_summary", models.JSONField(blank=True, default=list)),
                ("violations_summary", models.JSONField(blank=True, default=list)),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_compliance_report",
                "ordering": ("-generated_at",),
                "indexes": [
                    models.Index(
                        fields=["report_type", "-generated_at"],
                        name="audit_compl_report__5a7616_idx",
                    ),
                    models.Index(
                        fields=["framework", "-generated_at"],
                        name="audit_compl_framewo_7c3957_idx",
                    ),
                    models.Index(
                        fields=["overall_status", "-generated_at"],
                        name="audit_compl_overall_ad8151_idx",
                    ),
                    models.Index(
                        fields=["period_start", "period_end"],
                        name="audit_compl_period__f62e18_idx",
                    ),
                ],
            },
        ),
    ]
