# Generated by Django 5.2.12 on 2026-07-26 20:26

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0010_auditchainhead_auditchainlink"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditChainAnchor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sequence", models.BigIntegerField(db_index=True)),
                ("head_chain_mac", models.CharField(max_length=64)),
                ("link_count", models.BigIntegerField()),
                ("anchor_mac", models.CharField(max_length=64)),
                ("key_id", models.CharField(max_length=8)),
                ("sink", models.CharField(max_length=32)),
                ("anchored_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "audit_chain_anchors",
                "ordering": ("-sequence",),
            },
        ),
    ]
