# Generated by Django 5.2.12 on 2026-07-26 20:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0011_auditchainanchor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditevent",
            name="timestamp",
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
