"""Romanian city-to-county mapping for automatic county detection."""

# Maps lowercase city names to their county (judet).
# Includes all 41 county seats, Bucharest sectors, and common anglicized variants.
CITY_TO_COUNTY: dict[str, str] = {
    # County seats (alphabetical by county)
    "alba iulia": "Alba",
    "arad": "Arad",
    "pitesti": "Argeș",
    "pitești": "Argeș",
    "curtea de arges": "Argeș",
    "curtea de argeș": "Argeș",
    "bacau": "Bacău",
    "bacău": "Bacău",
    "oradea": "Bihor",
    "bistrita": "Bistrița-Năsăud",
    "bistrița": "Bistrița-Năsăud",
    "bistrita-nasaud": "Bistrița-Năsăud",
    "bistrița-năsăud": "Bistrița-Năsăud",
    "botosani": "Botoșani",
    "botoșani": "Botoșani",
    "brasov": "Brașov",
    "brașov": "Brașov",
    "braila": "Brăila",
    "brăila": "Brăila",
    "bucuresti": "București",
    "bucurești": "București",
    "bucharest": "București",
    "sector 1": "București",
    "sector 2": "București",
    "sector 3": "București",
    "sector 4": "București",
    "sector 5": "București",
    "sector 6": "București",
    "buzau": "Buzău",
    "buzău": "Buzău",
    "resita": "Caraș-Severin",
    "reșița": "Caraș-Severin",
    "calarasi": "Călărași",
    "călărași": "Călărași",
    "cluj-napoca": "Cluj",
    "cluj napoca": "Cluj",
    "cluj": "Cluj",
    "constanta": "Constanța",
    "constanța": "Constanța",
    "sfantu gheorghe": "Covasna",
    "sfântu gheorghe": "Covasna",
    "targoviste": "Dâmbovița",
    "târgoviște": "Dâmbovița",
    "târgovişte": "Dâmbovița",
    "craiova": "Dolj",
    "galati": "Galați",
    "galați": "Galați",
    "giurgiu": "Giurgiu",
    "targu jiu": "Gorj",
    "târgu jiu": "Gorj",
    "miercurea ciuc": "Harghita",
    "deva": "Hunedoara",
    "hunedoara": "Hunedoara",
    "slobozia": "Ialomița",
    "iasi": "Iași",
    "iași": "Iași",
    "baia mare": "Maramureș",
    "maramures": "Maramureș",
    "maramureș": "Maramureș",
    "drobeta-turnu severin": "Mehedinți",
    "drobeta turnu severin": "Mehedinți",
    "targu mures": "Mureș",
    "târgu mureș": "Mureș",
    "târgu mures": "Mureș",
    "piatra neamt": "Neamț",
    "piatra neamț": "Neamț",
    "slatina": "Olt",
    "ploiesti": "Prahova",
    "ploiești": "Prahova",
    "satu mare": "Satu Mare",
    "zalau": "Sălaj",
    "zalău": "Sălaj",
    "sibiu": "Sibiu",
    "suceava": "Suceava",
    "alexandria": "Teleorman",
    "timisoara": "Timiș",
    "timișoara": "Timiș",
    "tulcea": "Tulcea",
    "ramnicu valcea": "Vâlcea",
    "râmnicu vâlcea": "Vâlcea",
    "vaslui": "Vaslui",
    "focsani": "Vrancea",
    "focșani": "Vrancea",
    # Additional major cities
    "ilfov": "Ilfov",
    "voluntari": "Ilfov",
    "popesti-leordeni": "Ilfov",
    "bragadiru": "Ilfov",
    "medias": "Sibiu",
    "mediaș": "Sibiu",
    "campina": "Prahova",
    "câmpina": "Prahova",
    "dej": "Cluj",
    "turda": "Cluj",
    "lugoj": "Timiș",
    "petrosani": "Hunedoara",
    "petroșani": "Hunedoara",
    "mangalia": "Constanța",
    "medgidia": "Constanța",
}


def detect_county(city: str) -> str:
    """Detect Romanian county from city name.

    Returns the county name if found, empty string otherwise.
    Handles diacritics and case-insensitive matching.
    """
    if not city:
        return ""
    return CITY_TO_COUNTY.get(city.strip().lower(), "")
