#!/bin/bash
# =============================================================================
# PRAHO - Portal host env file
# =============================================================================
# Writes the env file a separate portal host needs (deploy.sh portal-only) from the full operator
# file, on the machine that holds it. It keeps only the variables the portal-only compose file uses,
# so the platform's database password, encryption keys, payment and mail credentials and its Django
# secret key never reach the portal host.
#
# Usage:
#   ./portal-env.sh [--env prod|staging | --env-file PATH] [--output PATH] [--force]
#
# The output (default: the env file's path plus .portal, e.g. .env.prod.portal) is mode 600. Copy it
# to the portal host as .env.prod (or .env.staging), for example with scp -p.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEPLOY_DIR="$(dirname "$SCRIPT_DIR")"
PROJECT_ROOT="$(dirname "$DEPLOY_DIR")"
# shellcheck source=SCRIPTDIR/lib/compose.sh
source "${SCRIPT_DIR}/lib/compose.sh"

usage() {
    echo "PRAHO portal host env file"
    echo ""
    echo "Usage: $0 [--env prod|staging | --env-file PATH] [--output PATH] [--force]"
    echo ""
    echo "Reads the full env file (.env.prod by default) and writes only what the portal stack"
    echo "uses, plus the portal's own PORTAL_DJANGO_SECRET_KEY, to PATH (default: <env file>.portal)."
    echo "  --force    Replace an existing output file"
    exit "${1:-1}"
}

warn() { echo -e "\033[1;33m[WARN]\033[0m $1" >&2; }

for arg in "$@"; do
    case "$arg" in
        --help | -h) usage 0 ;;
    esac
done

praho_parse_env_args "$@"
OUTPUT=""
FORCE=false
set -- ${PRAHO_ARGS[@]+"${PRAHO_ARGS[@]}"}
while [ $# -gt 0 ]; do
    case "$1" in
        --output)
            [ $# -ge 2 ] || praho_die "--output needs a path"
            OUTPUT="$2"
            shift 2
            ;;
        --force)
            FORCE=true
            shift
            ;;
        *) praho_die "Unknown option: $1" ;;
    esac
done

praho_load_env

# The portal signs its sessions and price seals with this key; the platform derives its MFA, audit and
# unsubscribe keys from DJANGO_SECRET_KEY, so the two must differ.
portal_key="$(praho_env_value PORTAL_DJANGO_SECRET_KEY)"
[ -n "$portal_key" ] || praho_die "PORTAL_DJANGO_SECRET_KEY is empty in ${PRAHO_ENV_FILE}. Generate one: openssl rand -base64 50"
if [ "$portal_key" = "$(praho_env_value DJANGO_SECRET_KEY)" ]; then
    praho_die "PORTAL_DJANGO_SECRET_KEY equals DJANGO_SECRET_KEY in ${PRAHO_ENV_FILE}: the portal needs its own key."
fi

OUTPUT="${OUTPUT:-${PRAHO_ENV_FILE}.portal}"
out_dir="$(cd "$(dirname "$OUTPUT")" 2>/dev/null && pwd -P)" || praho_die "No such directory: $(dirname "$OUTPUT")"
OUTPUT="${out_dir}/$(basename "$OUTPUT")"
if [ "$OUTPUT" = "$PRAHO_ENV_FILE" ] || [ "$OUTPUT" -ef "$PRAHO_ENV_FILE" ]; then
    praho_die "Refusing to write the portal file over its source, ${PRAHO_ENV_FILE}."
fi
if [ -e "$OUTPUT" ] && [ "$FORCE" != true ]; then
    praho_die "${OUTPUT} exists. Pass --force to replace it."
fi

# Written beside the target with no access for others, checked, then moved into place.
umask 077
tmp="$(mktemp "${OUTPUT}.XXXXXX")"
trap 'rm -f "$tmp"' EXIT
{
    echo "# Generated by deploy/scripts/portal-env.sh from $(basename "$PRAHO_ENV_FILE"). It holds only what"
    echo "# the portal stack uses; regenerate it rather than editing it."
    echo "DJANGO_SETTINGS_MODULE=${PRAHO_SETTINGS_MODULE}"
} > "$tmp"
# Each allowed key's last declaration, copied as written so its quoting means the same. The lines of a
# quoted value that spans lines belong to that value, as Compose reads them, never to a declaration. An
# allowed key the copy cannot carry as written (export, indentation, a value spanning lines) is reported
# rather than dropped.
unsupported="$(awk -v allowed=" $(praho_portal_allowlist | tr '\n' ' ') " -v out="$tmp" '
    function closes(rest, quote,    i, c) {
        for (i = 1; i <= length(rest); i++) {
            c = substr(rest, i, 1)
            if (quote == "\"" && c == "\\") { i++; continue }
            if (c == quote) return 1
        }
        return 0
    }
    function opens(value,    quote) {
        quote = substr(value, 1, 1)
        if ((quote == "\"" || quote == "\047") && !closes(substr(value, 2), quote)) return quote
        return ""
    }
    inside != "" { if (closes($0, inside)) inside = ""; next }
    /^[[:space:]]*$/ || /^[[:space:]]*#/ { next }
    {
        line = $0
        plain = match(line, /^[A-Za-z_][A-Za-z0-9_]*=/)
        if (!plain) {
            sub(/^[[:space:]]+/, "", line)
            sub(/^export[[:space:]]+/, "", line)
            if (!match(line, /^[A-Za-z_][A-Za-z0-9_]*=/)) next
        }
        key = substr(line, 1, RLENGTH - 1)
        inside = opens(substr(line, RLENGTH + 1))
        if (key == "DJANGO_SETTINGS_MODULE" || !index(allowed, " " key " ")) next
        if (!plain || inside != "") { print key; next }
        if (!(key in last)) order[++count] = key
        last[key] = $0
    }
    END { for (i = 1; i <= count; i++) print last[order[i]] >> out }' "$PRAHO_ENV_FILE" | sort -u | tr '\n' ' ' | sed 's/ $//')"
if [ -n "$unsupported" ]; then
    praho_die "In ${PRAHO_ENV_FILE}, ${unsupported} cannot be copied as written: give each one plain KEY=value line (no export, no indentation, no value spanning lines)."
fi
problems="$(praho_portal_env_offenders "$tmp")"
if [ -n "$problems" ]; then
    praho_die "Could not write a clean portal file (${problems} of the output)."
fi
# Compose expands $ in unquoted and double-quoted values. A reference such as ${HMAC_SECRET} points at a
# variable this file does not carry, so it would be empty on the portal host (and a portal key written
# as ${DJANGO_SECRET_KEY} would be the platform's after all).
references="$(awk 'match($0, /^[A-Za-z_][A-Za-z0-9_]*=/) {
        value = substr($0, RLENGTH + 1)
        if (substr(value, 1, 1) != "\047" && index(value, "$")) print substr($0, 1, RLENGTH - 1)
    }' "$tmp" | tr '\n' ' ' | sed 's/ $//')"
if [ -n "$references" ]; then
    praho_die "In ${PRAHO_ENV_FILE}, ${references} refer to other variables, which the portal file does not carry. Write the literal values (single-quote a value that contains a \$)."
fi
# The stack's required variables (${NAME:?...}) must be set, or Compose refuses to start on the portal host.
missing=""
while read -r name; do
    if [ -z "$(PRAHO_ENV_FILE="$tmp" praho_env_value "$name")" ]; then
        missing="${missing} ${name}"
    fi
done < <(praho_portal_required)
if [ -n "$missing" ]; then
    praho_die "${PRAHO_ENV_FILE} leaves${missing} empty; the portal stack requires them."
fi
chmod 600 "$tmp"
mv -f "$tmp" "$OUTPUT"
trap - EXIT

# Native defaults that would be wrong on a separate host.
api_url="$(praho_env_value PLATFORM_API_BASE_URL)"
case "$api_url" in
    "") warn "PLATFORM_API_BASE_URL is empty: set it to the platform's public URL, e.g. https://platform.example.com/api" ;;
    *://localhost* | *://127.0.0.1* | *://platform:* | *://platform/*)
        warn "PLATFORM_API_BASE_URL is ${api_url}: on a separate host it must be the platform's public URL." ;;
esac
if [ "$(praho_env_value PLATFORM_API_ALLOW_INSECURE_HTTP | tr '[:upper:]' '[:lower:]')" = true ]; then
    warn "PLATFORM_API_ALLOW_INSECURE_HTTP is true: a separate portal host should reach the platform over HTTPS."
fi

case "$PRAHO_SETTINGS_MODULE" in
    config.settings.staging) target=".env.staging" ;;
    *) target=".env.prod" ;;
esac
echo "Wrote ${OUTPUT} (mode 600) with: $(grep -oE '^[A-Za-z_][A-Za-z0-9_]*=' "$OUTPUT" | tr -d '=' | tr '\n' ' ')"
echo "Copy it to the portal host as ${target} (for example with scp -p), then run deploy.sh portal-only there."
