# Generated by Django 5.2.12 on 2026-03-11 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provisioning', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualminaccount',
            name='customer_membership',
            field=models.ForeignKey(blank=True, help_text='Links hosting account to customer membership for access control', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='virtualmin_accounts', to='users.customermembership', verbose_name='Customer Membership'),
        ),
        migrations.AddField(
            model_name='virtualminaccount',
            name='service',
            field=models.OneToOneField(help_text='One-to-one relationship ensures each service has at most one VirtualMin account. This enforces current business logic at database level.', on_delete=django.db.models.deletion.CASCADE, related_name='virtualmin_account', to='provisioning.service', verbose_name='PRAHO Service'),
        ),
        migrations.AddField(
            model_name='virtualminprovisioningjob',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provisioning_jobs', to='provisioning.virtualminaccount'),
        ),
        migrations.AddField(
            model_name='virtualminprovisioningjob',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provisioning_jobs', to='provisioning.virtualminserver'),
        ),
        migrations.AddField(
            model_name='virtualmindriftrecord',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provisioning.virtualminserver'),
        ),
        migrations.AddField(
            model_name='virtualminaccount',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='provisioning.virtualminserver', verbose_name='Virtualmin Server'),
        ),
        migrations.AddIndex(
            model_name='provisioningtask',
            index=models.Index(fields=['status', 'created_at'], name='provisionin_status_17c83b_idx'),
        ),
        migrations.AddIndex(
            model_name='provisioningtask',
            index=models.Index(fields=['service', 'task_type'], name='provisionin_service_559405_idx'),
        ),
        migrations.AddIndex(
            model_name='provisioningtask',
            index=models.Index(fields=['next_retry_at'], name='provisionin_next_re_f32b56_idx'),
        ),
        migrations.AddIndex(
            model_name='provisioningtask',
            index=models.Index(fields=['status', 'next_retry_at'], name='provisionin_status_d0b470_idx'),
        ),
        migrations.AddIndex(
            model_name='provisioningtask',
            index=models.Index(fields=['task_type', 'status', '-created_at'], name='provisionin_task_ty_d071c9_idx'),
        ),
        migrations.AddIndex(
            model_name='servicedomain',
            index=models.Index(fields=['service', 'domain_type'], name='service_domain_type_idx'),
        ),
        migrations.AddIndex(
            model_name='servicedomain',
            index=models.Index(fields=['domain', 'is_active'], name='service_domain_active_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='servicedomain',
            unique_together={('service', 'domain', 'subdomain')},
        ),
        migrations.AddIndex(
            model_name='servicegroup',
            index=models.Index(fields=['customer', 'status'], name='service_group_customer_idx'),
        ),
        migrations.AddIndex(
            model_name='servicegroup',
            index=models.Index(fields=['group_type', 'status'], name='service_group_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='servicegroup',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['active', 'suspended', 'cancelled', 'pending'])), name='service_group_valid_status'),
        ),
        migrations.AddIndex(
            model_name='servicegroupmember',
            index=models.Index(fields=['group', 'provision_order'], name='service_member_order_idx'),
        ),
        migrations.AddIndex(
            model_name='servicegroupmember',
            index=models.Index(fields=['service', 'is_active'], name='service_member_active_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='servicegroupmember',
            unique_together={('group', 'service')},
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['customer', 'status'], name='provisionin_custome_03754e_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['server', 'status'], name='provisionin_server__9e1d59_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['status', 'expires_at'], name='provisionin_status_962ab0_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['domain'], name='provisionin_domain_e43ef3_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['username'], name='provisionin_usernam_3fe753_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['auto_renew', 'expires_at', 'status'], name='provisionin_auto_re_f9e4d3_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['service_plan', 'status'], name='provisionin_service_e6c085_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['billing_cycle', 'status', '-created_at'], name='provisionin_billing_b178eb_idx'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'provisioning', 'active', 'suspended', 'failed', 'terminated', 'expired'])), name='service_status_valid_values'),
        ),
        migrations.AddIndex(
            model_name='servicerelationship',
            index=models.Index(fields=['parent_service', 'relationship_type'], name='service_rel_parent_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerelationship',
            index=models.Index(fields=['child_service', 'is_required'], name='service_rel_child_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='servicerelationship',
            unique_together={('parent_service', 'child_service')},
        ),
        migrations.AddIndex(
            model_name='virtualminprovisioningjob',
            index=models.Index(fields=['status'], name='provisionin_status_21b637_idx'),
        ),
        migrations.AddIndex(
            model_name='virtualminprovisioningjob',
            index=models.Index(fields=['operation'], name='provisionin_operati_573ccc_idx'),
        ),
        migrations.AddIndex(
            model_name='virtualminprovisioningjob',
            index=models.Index(fields=['server', 'status'], name='provisionin_server__f15069_idx'),
        ),
        migrations.AddIndex(
            model_name='virtualminprovisioningjob',
            index=models.Index(fields=['correlation_id'], name='provisionin_correla_ef5a94_idx'),
        ),
        migrations.AddIndex(
            model_name='virtualminprovisioningjob',
            index=models.Index(fields=['task_id'], name='provisionin_task_id_5de114_idx'),
        ),
        migrations.AddIndex(
            model_name='virtualmindriftrecord',
            index=models.Index(fields=['domain'], name='provisionin_domain_06c6bf_idx'),
        ),
        migrations.AddIndex(
            model_name='virtualmindriftrecord',
            index=models.Index(fields=['drift_type'], name='provisionin_drift_t_32db29_idx'),
        ),
        migrations.AddIndex(
            model_name='virtualmindriftrecord',
            index=models.Index(fields=['resolution_status'], name='provisionin_resolut_ecc760_idx'),
        ),
        migrations.AddIndex(
            model_name='virtualmindriftrecord',
            index=models.Index(fields=['server', 'resolution_status'], name='provisionin_server__b94e49_idx'),
        ),
        migrations.AddIndex(
            model_name='virtualminaccount',
            index=models.Index(fields=['domain'], name='provisionin_domain_df3633_idx'),
        ),
        migrations.AddIndex(
            model_name='virtualminaccount',
            index=models.Index(fields=['status'], name='provisionin_status_3bfefc_idx'),
        ),
        migrations.AddIndex(
            model_name='virtualminaccount',
            index=models.Index(fields=['server', 'status'], name='provisionin_server__a541f6_idx'),
        ),
    ]
