# Generated by Django 5.2.17 on 2026-10-02 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0002_initial'),
        ('customers', '0002_initial'),
        ('domains', '0003_initial'),
        ('provisioning', '0001_initial'),
        ('tickets', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='nodedrain',
            name='initiated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='server',
            index=models.Index(fields=['status', 'server_type'], name='provisionin_status_f282fb_idx'),
        ),
        migrations.AddIndex(
            model_name='server',
            index=models.Index(fields=['location'], name='provisionin_locatio_a5de11_idx'),
        ),
        migrations.AddIndex(
            model_name='server',
            index=models.Index(fields=['primary_ip'], name='provisionin_primary_4a3581_idx'),
        ),
        migrations.AddField(
            model_name='service',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.currency', verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='service',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='customers.customer', verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='service',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='provisioning.server', verbose_name='Server'),
        ),
        migrations.AddField(
            model_name='provisioningtask',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provisioning_tasks', to='provisioning.service', verbose_name='Service'),
        ),
        migrations.AddField(
            model_name='servicedomain',
            name='domain',
            field=models.ForeignKey(help_text='Domain assigned to service', on_delete=django.db.models.deletion.CASCADE, related_name='services', to='domains.domain'),
        ),
        migrations.AddField(
            model_name='servicedomain',
            name='service',
            field=models.ForeignKey(help_text='Hosting service for this domain', on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='provisioning.service'),
        ),
        migrations.AddField(
            model_name='servicegroup',
            name='customer',
            field=models.ForeignKey(help_text='Customer owning this service group', on_delete=django.db.models.deletion.CASCADE, related_name='service_groups', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='servicegroupmember',
            name='group',
            field=models.ForeignKey(help_text='Service group', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='provisioning.servicegroup'),
        ),
        migrations.AddField(
            model_name='servicegroupmember',
            name='service',
            field=models.ForeignKey(help_text='Service in group', on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='provisioning.service'),
        ),
        migrations.AddIndex(
            model_name='serviceplan',
            index=models.Index(fields=['plan_type', 'is_active'], name='provisionin_plan_ty_15481c_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceplan',
            index=models.Index(fields=['is_public', 'is_active'], name='provisionin_is_publ_eadfc0_idx'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='provisioning.serviceplan', verbose_name='Service Plan'),
        ),
        migrations.AddField(
            model_name='serviceplanprice',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.currency'),
        ),
        migrations.AddField(
            model_name='serviceplanprice',
            name='service_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_prices', to='provisioning.serviceplan'),
        ),
        migrations.AddField(
            model_name='servicerelationship',
            name='child_service',
            field=models.ForeignKey(help_text='Related service (e.g., domain, SSL, backup)', on_delete=django.db.models.deletion.CASCADE, related_name='parent_relationships', to='provisioning.service'),
        ),
        migrations.AddField(
            model_name='servicerelationship',
            name='parent_service',
            field=models.ForeignKey(help_text='Primary service (e.g., VPS hosting)', on_delete=django.db.models.deletion.CASCADE, related_name='child_relationships', to='provisioning.service'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_service_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='customer',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='customers.customer'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='requested_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_service_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='service',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='provisioning.service'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='ticket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_request', to='tickets.ticket'),
        ),
        migrations.AddField(
            model_name='virtualminaccount',
            name='customer_membership',
            field=models.ForeignKey(blank=True, help_text='Links hosting account to customer membership for access control', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='virtualmin_accounts', to='users.customermembership', verbose_name='Customer Membership'),
        ),
        migrations.AddField(
            model_name='virtualminaccount',
            name='service',
            field=models.OneToOneField(help_text='One-to-one relationship ensures each service has at most one VirtualMin account. This enforces current business logic at database level.', on_delete=django.db.models.deletion.CASCADE, related_name='virtualmin_account', to='provisioning.service', verbose_name='PRAHO Service'),
        ),
        migrations.AddField(
            model_name='virtualminmigration',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='migrations', to='provisioning.virtualminaccount'),
        ),
        migrations.AddField(
            model_name='virtualminmigration',
            name='initiated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nodedrain',
            name='current_migration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='provisioning.virtualminmigration'),
        ),
        migrations.AddField(
            model_name='virtualminprovisioningjob',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provisioning_jobs', to='provisioning.virtualminaccount'),
        ),
        migrations.AddField(
            model_name='virtualminprovisioningjob',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provisioning_jobs', to='provisioning.virtualminserver'),
        ),
        migrations.AddField(
            model_name='virtualminmigration',
            name='source_server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='migrations_out', to='provisioning.virtualminserver'),
        ),
        migrations.AddField(
            model_name='virtualminmigration',
            name='target_server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='migrations_in', to='provisioning.virtualminserver'),
        ),
        migrations.AddField(
            model_name='virtualmindriftrecord',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provisioning.virtualminserver'),
        ),
        migrations.AddField(
            model_name='virtualminaccount',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='provisioning.virtualminserver', verbose_name='Virtualmin Server'),
        ),
        migrations.AddField(
            model_name='nodedrain',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drains', to='provisioning.virtualminserver'),
        ),
        migrations.AddIndex(
            model_name='provisioningtask',
            index=models.Index(fields=['status', 'created_at'], name='provisionin_status_17c83b_idx'),
        ),
        migrations.AddIndex(
            model_name='provisioningtask',
            index=models.Index(fields=['service', 'task_type'], name='provisionin_service_559405_idx'),
        ),
        migrations.AddIndex(
            model_name='provisioningtask',
            index=models.Index(fields=['next_retry_at'], name='provisionin_next_re_f32b56_idx'),
        ),
        migrations.AddIndex(
            model_name='provisioningtask',
            index=models.Index(fields=['status', 'next_retry_at'], name='provisionin_status_d0b470_idx'),
        ),
        migrations.AddIndex(
            model_name='provisioningtask',
            index=models.Index(fields=['task_type', 'status', '-created_at'], name='provisionin_task_ty_d071c9_idx'),
        ),
        migrations.AddIndex(
            model_name='servicedomain',
            index=models.Index(fields=['service', 'domain_type'], name='service_domain_type_idx'),
        ),
        migrations.AddIndex(
            model_name='servicedomain',
            index=models.Index(fields=['domain', 'is_active'], name='service_domain_active_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='servicedomain',
            unique_together={('service', 'domain', 'subdomain')},
        ),
        migrations.AddIndex(
            model_name='servicegroup',
            index=models.Index(fields=['customer', 'status'], name='service_group_customer_idx'),
        ),
        migrations.AddIndex(
            model_name='servicegroup',
            index=models.Index(fields=['group_type', 'status'], name='service_group_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='servicegroup',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['active', 'suspended', 'cancelled', 'pending'])), name='service_group_valid_status'),
        ),
        migrations.AddIndex(
            model_name='servicegroupmember',
            index=models.Index(fields=['group', 'provision_order'], name='service_member_order_idx'),
        ),
        migrations.AddIndex(
            model_name='servicegroupmember',
            index=models.Index(fields=['service', 'is_active'], name='service_member_active_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='servicegroupmember',
            unique_together={('group', 'service')},
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['customer', 'status'], name='provisionin_custome_03754e_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['server', 'status'], name='provisionin_server__9e1d59_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['status', 'expires_at'], name='provisionin_status_962ab0_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['domain'], name='provisionin_domain_e43ef3_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['username'], name='provisionin_usernam_3fe753_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['auto_renew', 'expires_at', 'status'], name='provisionin_auto_re_f9e4d3_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['service_plan', 'status'], name='provisionin_service_e6c085_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['billing_cycle', 'status', '-created_at'], name='provisionin_billing_b178eb_idx'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'provisioning', 'active', 'suspended', 'failed', 'terminated', 'expired'])), name='service_status_valid_values'),
        ),
        migrations.AddConstraint(
            model_name='serviceplanprice',
            constraint=models.UniqueConstraint(fields=('service_plan', 'currency'), name='service_plan_currency_price'),
        ),
        migrations.AddIndex(
            model_name='servicerelationship',
            index=models.Index(fields=['parent_service', 'relationship_type'], name='service_rel_parent_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerelationship',
            index=models.Index(fields=['child_service', 'is_required'], name='service_rel_child_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='servicerelationship',
            unique_together={('parent_service', 'child_service')},
        ),
        migrations.AddConstraint(
            model_name='servicerequest',
            constraint=models.UniqueConstraint(fields=('customer', 'requested_by', 'submission_id'), name='unique_customer_service_submission'),
        ),
        migrations.AddConstraint(
            model_name='servicerequest',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'approved', 'rejected', 'completed'])), name='service_request_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='servicerequest',
            constraint=models.CheckConstraint(condition=models.Q(('action__in', ['upgrade_request', 'downgrade_request', 'suspend_request', 'cancel_request'])), name='service_request_valid_action'),
        ),
        migrations.AddIndex(
            model_name='virtualminprovisioningjob',
            index=models.Index(fields=['status'], name='provisionin_status_21b637_idx'),
        ),
        migrations.AddIndex(
            model_name='virtualminprovisioningjob',
            index=models.Index(fields=['operation'], name='provisionin_operati_573ccc_idx'),
        ),
        migrations.AddIndex(
            model_name='virtualminprovisioningjob',
            index=models.Index(fields=['server', 'status'], name='provisionin_server__f15069_idx'),
        ),
        migrations.AddIndex(
            model_name='virtualminprovisioningjob',
            index=models.Index(fields=['correlation_id'], name='provisionin_correla_ef5a94_idx'),
        ),
        migrations.AddIndex(
            model_name='virtualminprovisioningjob',
            index=models.Index(fields=['task_id'], name='provisionin_task_id_5de114_idx'),
        ),
        migrations.AddConstraint(
            model_name='virtualminmigration',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('completed', 'failed', 'rolled_back')), _negated=True), fields=('account',), name='unique_active_virtualmin_migration'),
        ),
        migrations.AddIndex(
            model_name='virtualmindriftrecord',
            index=models.Index(fields=['domain'], name='provisionin_domain_06c6bf_idx'),
        ),
        migrations.AddIndex(
            model_name='virtualmindriftrecord',
            index=models.Index(fields=['drift_type'], name='provisionin_drift_t_32db29_idx'),
        ),
        migrations.AddIndex(
            model_name='virtualmindriftrecord',
            index=models.Index(fields=['resolution_status'], name='provisionin_resolut_ecc760_idx'),
        ),
        migrations.AddIndex(
            model_name='virtualmindriftrecord',
            index=models.Index(fields=['server', 'resolution_status'], name='provisionin_server__b94e49_idx'),
        ),
        migrations.AddIndex(
            model_name='virtualminaccount',
            index=models.Index(fields=['domain'], name='provisionin_domain_df3633_idx'),
        ),
        migrations.AddIndex(
            model_name='virtualminaccount',
            index=models.Index(fields=['status'], name='provisionin_status_3bfefc_idx'),
        ),
        migrations.AddIndex(
            model_name='virtualminaccount',
            index=models.Index(fields=['server', 'status'], name='provisionin_server__a541f6_idx'),
        ),
        migrations.AddConstraint(
            model_name='nodedrain',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('completed', 'cancelled', 'failed')), _negated=True), fields=('server',), name='unique_active_node_drain'),
        ),
    ]
