# Generated by Django 5.2.5 on 2025-09-13 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provisioning', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualminaccount',
            name='customer_membership',
            field=models.ForeignKey(blank=True, help_text='Links hosting account to customer membership for access control', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='virtualmin_accounts', to='users.customermembership', verbose_name='Customer Membership'),
        ),
        migrations.AddField(
            model_name='virtualminaccount',
            name='service',
            field=models.OneToOneField(help_text='One-to-one relationship ensures each service has at most one VirtualMin account. This enforces current business logic at database level.', on_delete=django.db.models.deletion.CASCADE, related_name='virtualmin_account', to='provisioning.service', verbose_name='PRAHO Service'),
        ),
        migrations.AddField(
            model_name='virtualminprovisioningjob',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provisioning_jobs', to='provisioning.virtualminaccount'),
        ),
        migrations.AddField(
            model_name='virtualminprovisioningjob',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provisioning_jobs', to='provisioning.virtualminserver'),
        ),
        migrations.AddField(
            model_name='virtualmindriftrecord',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provisioning.virtualminserver'),
        ),
        migrations.AddField(
            model_name='virtualminaccount',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='provisioning.virtualminserver', verbose_name='Virtualmin Server'),
        ),
        migrations.AddIndex(
            model_name='provisioningtask',
            index=models.Index(fields=['status', 'created_at'], name='provisionin_status_17c83b_idx'),
        ),
        migrations.AddIndex(
            model_name='provisioningtask',
            index=models.Index(fields=['service', 'task_type'], name='provisionin_service_559405_idx'),
        ),
        migrations.AddIndex(
            model_name='provisioningtask',
            index=models.Index(fields=['next_retry_at'], name='provisionin_next_re_f32b56_idx'),
        ),
        migrations.AddIndex(
            model_name='provisioningtask',
            index=models.Index(fields=['status', 'next_retry_at'], name='provisionin_status_d0b470_idx'),
        ),
        migrations.AddIndex(
            model_name='provisioningtask',
            index=models.Index(fields=['task_type', 'status', '-created_at'], name='provisionin_task_ty_d071c9_idx'),
        ),
        migrations.AddIndex(
            model_name='servicedomain',
            index=models.Index(fields=['service', 'domain_type'], name='service_domain_type_idx'),
        ),
        migrations.AddIndex(
            model_name='servicedomain',
            index=models.Index(fields=['domain', 'is_active'], name='service_domain_active_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='servicedomain',
            unique_together={('service', 'domain', 'subdomain')},
        ),
        migrations.AddIndex(
            model_name='servicegroup',
            index=models.Index(fields=['customer', 'status'], name='service_group_customer_idx'),
        ),
        migrations.AddIndex(
            model_name='servicegroup',
            index=models.Index(fields=['group_type', 'status'], name='service_group_type_idx'),
        ),
        migrations.AddIndex(
            model_name='servicegroupmember',
            index=models.Index(fields=['group', 'provision_order'], name='service_member_order_idx'),
        ),
        migrations.AddIndex(
            model_name='servicegroupmember',
            index=models.Index(fields=['service', 'is_active'], name='service_member_active_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='servicegroupmember',
            unique_together={('group', 'service')},
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['customer', 'status'], name='services_custome_308303_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['server', 'status'], name='services_server__32da6c_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['status', 'expires_at'], name='services_status_3758f7_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['domain'], name='services_domain_4dd8b5_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['username'], name='services_usernam_a5a1a7_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['auto_renew', 'expires_at', 'status'], name='services_auto_re_149d05_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['service_plan', 'status'], name='services_service_b8062d_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['billing_cycle', 'status', '-created_at'], name='services_billing_0f2ec3_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerelationship',
            index=models.Index(fields=['parent_service', 'relationship_type'], name='service_rel_parent_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerelationship',
            index=models.Index(fields=['child_service', 'is_required'], name='service_rel_child_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='servicerelationship',
            unique_together={('parent_service', 'child_service')},
        ),
        migrations.AddIndex(
            model_name='virtualminprovisioningjob',
            index=models.Index(fields=['status'], name='virtualmin__status_0a5a7e_idx'),
        ),
        migrations.AddIndex(
            model_name='virtualminprovisioningjob',
            index=models.Index(fields=['operation'], name='virtualmin__operati_3113db_idx'),
        ),
        migrations.AddIndex(
            model_name='virtualminprovisioningjob',
            index=models.Index(fields=['server', 'status'], name='virtualmin__server__662f76_idx'),
        ),
        migrations.AddIndex(
            model_name='virtualminprovisioningjob',
            index=models.Index(fields=['correlation_id'], name='virtualmin__correla_f4fed1_idx'),
        ),
        migrations.AddIndex(
            model_name='virtualminprovisioningjob',
            index=models.Index(fields=['task_id'], name='virtualmin__task_id_a5be6a_idx'),
        ),
        migrations.AddIndex(
            model_name='virtualmindriftrecord',
            index=models.Index(fields=['domain'], name='virtualmin__domain_3a8233_idx'),
        ),
        migrations.AddIndex(
            model_name='virtualmindriftrecord',
            index=models.Index(fields=['drift_type'], name='virtualmin__drift_t_9d7201_idx'),
        ),
        migrations.AddIndex(
            model_name='virtualmindriftrecord',
            index=models.Index(fields=['resolution_status'], name='virtualmin__resolut_651319_idx'),
        ),
        migrations.AddIndex(
            model_name='virtualmindriftrecord',
            index=models.Index(fields=['server', 'resolution_status'], name='virtualmin__server__590da3_idx'),
        ),
        migrations.AddIndex(
            model_name='virtualminaccount',
            index=models.Index(fields=['domain'], name='virtualmin__domain_5fbde3_idx'),
        ),
        migrations.AddIndex(
            model_name='virtualminaccount',
            index=models.Index(fields=['status'], name='virtualmin__status_300042_idx'),
        ),
        migrations.AddIndex(
            model_name='virtualminaccount',
            index=models.Index(fields=['server', 'status'], name='virtualmin__server__264233_idx'),
        ),
    ]
