# Generated by Django 5.2.5 on 2025-09-19 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provisioning', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('provisioning', 'Provisioning'), ('active', 'Active'), ('suspended', 'Suspended'), ('failed', 'Provisioning Failed'), ('terminated', 'Terminated'), ('expired', 'Expired')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
