# Generated by Django 5.2.12 on 2026-07-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provisioning', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualminprovisioningjob',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='virtualminserver',
            name='consecutive_health_failures',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='virtualminserver',
            name='failed_by_health_check',
            field=models.BooleanField(default=False),
        ),
    ]
