# Generated by Django 5.2.5 on 2025-09-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provisioning', '0003_add_failed_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='provisioning_task_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Provisioning Task ID'),
        ),
    ]
