# Generated by Django 5.2.12 on 2026-09-07 23:59

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provisioning', '0003_virtualminprovisioningjob_claimed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualminprovisioningjob',
            name='operation',
            field=models.CharField(choices=[('create_domain', 'Create Domain'), ('delete_domain', 'Delete Domain'), ('modify_domain', 'Modify Domain'), ('suspend_domain', 'Suspend Domain'), ('unsuspend_domain', 'Unsuspend Domain'), ('create_user', 'Create User'), ('delete_user', 'Delete User'), ('create_database', 'Create Database'), ('delete_database', 'Delete Database'), ('install_ssl', 'Install SSL Certificate'), ('backup_domain', 'Backup Domain'), ('restore_domain', 'Restore Domain'), ('migrate_domain', 'Migrate Domain')], max_length=30),
        ),
        migrations.CreateModel(
            name='VirtualminMigration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('quiescing', 'Quiescing'), ('backing_up', 'Backing Up'), ('fetching', 'Fetching'), ('pushing', 'Pushing'), ('restoring', 'Restoring'), ('verifying', 'Verifying'), ('activating', 'Activating'), ('repointing', 'Repointing'), ('completed', 'Completed'), ('failed', 'Failed'), ('needs_review', 'Needs Review'), ('rolled_back', 'Rolled Back')], default='pending', max_length=20)),
                ('reason', models.CharField(choices=[('manual', 'Manual'), ('drain', 'Drain')], default='manual', max_length=10)),
                ('error_detail', models.TextField(blank=True)),
                ('lease_token', models.UUIDField(blank=True, null=True)),
                ('worker_lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('archive_name', models.CharField(editable=False, max_length=255)),
                ('archive_sha256', models.CharField(blank=True, max_length=64)),
                ('source_disabled_at', models.DateTimeField(blank=True, null=True)),
                ('restore_issued', models.BooleanField(default=False)),
                ('routing_note_shown', models.BooleanField(default=False)),
                ('pre_migration_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='migrations', to='provisioning.virtualminaccount')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source_server', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='migrations_out', to='provisioning.virtualminserver')),
                ('target_server', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='migrations_in', to='provisioning.virtualminserver')),
            ],
            options={
                'verbose_name': 'Virtualmin Migration',
                'verbose_name_plural': 'Virtualmin Migrations',
                'db_table': 'provisioning_virtualmin_migrations',
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ('completed', 'failed', 'rolled_back')), _negated=True), fields=('account',), name='unique_active_virtualmin_migration')],
            },
        ),
    ]
