# Generated by Django 5.2.12 on 2026-09-08 01:41

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provisioning', '0004_alter_virtualminprovisioningjob_operation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualminserver',
            name='is_draining',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='NodeDrain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('paused_needs_review', 'Paused: needs review'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=24)),
                ('reason', models.CharField(choices=[('manual', 'Manual'), ('auto_health', 'Automatic health trigger')], default='manual', max_length=12)),
                ('accounts_total', models.PositiveIntegerField(default=0)),
                ('accounts_migrated', models.PositiveIntegerField(default=0)),
                ('accounts_skipped', models.PositiveIntegerField(default=0)),
                ('error_detail', models.TextField(blank=True)),
                ('routing_confirmed', models.BooleanField(default=False)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('task_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('worker_started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_migration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='provisioning.virtualminmigration')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drains', to='provisioning.virtualminserver')),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ('completed', 'cancelled', 'failed')), _negated=True), fields=('server',), name='unique_active_node_drain')],
            },
        ),
    ]
