# Generated by Django 5.2.12 on 2026-09-08 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provisioning', '0005_virtualminserver_is_draining_nodedrain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualminserver',
            name='weight',
            field=models.PositiveIntegerField(default=100, help_text='Server placement weight (higher = strictly preferred; ties broken by current load)'),
        ),
    ]
