# Generated by Django 5.2.12 on 2026-09-08 10:47

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provisioning', '0006_alter_virtualminserver_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpoolReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('archive_name', models.CharField(max_length=120, unique=True)),
                ('expected_bytes', models.BigIntegerField()),
                ('owner', models.CharField(max_length=120)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpoolRoot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('singleton', models.BooleanField(default=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='virtualminprovisioningjob',
            name='execution_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='virtualminprovisioningjob',
            name='execution_token',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='virtualminprovisioningjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('attention', 'Needs Attention')], default='pending', max_length=20),
        ),
    ]
