# Generated by Django 5.2.5 on 2025-09-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provisioning', '0007_rename_celery_task_id_to_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualminaccount',
            name='domains',
            field=models.JSONField(default=list, help_text='All domains managed by this Virtualmin account'),
        ),
        migrations.AlterField(
            model_name='virtualminaccount',
            name='domain',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Primary Domain'),
        ),
        migrations.AlterField(
            model_name='virtualminaccount',
            name='virtualmin_username',
            field=models.CharField(db_index=True, help_text='Unique Virtualmin virtual server username', max_length=32, unique=True, verbose_name='Virtualmin Username'),
        ),
    ]
