# Generated by Django 5.2.12 on 2026-09-28 06:37

import uuid

import django.db.models.deletion
import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0021_repair_address_billing_flags'),
        ('provisioning', '0007_spoolreservation_spoolroot_and_more'),
        ('tickets', '0004_alter_ticket_assigned_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submission_id', models.UUIDField(editable=False)),
                ('action', models.CharField(choices=[('upgrade_request', 'Upgrade request'), ('downgrade_request', 'Downgrade request'), ('suspend_request', 'Suspension request'), ('cancel_request', 'Cancellation request')], editable=False, max_length=24)),
                ('reason', models.TextField(blank=True, editable=False, max_length=4000)),
                ('status', django_fsm.FSMField(choices=[('pending', 'Pending review'), ('approved', 'Approved; awaiting manual completion'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=16, protected=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_service_requests', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='customers.customer')),
                ('requested_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_service_requests', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='provisioning.service')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_request', to='tickets.ticket')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('customer', 'requested_by', 'submission_id'), name='unique_customer_service_submission'), models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'approved', 'rejected', 'completed'])), name='service_request_valid_status'), models.CheckConstraint(condition=models.Q(('action__in', ['upgrade_request', 'downgrade_request', 'suspend_request', 'cancel_request'])), name='service_request_valid_action')],
            },
            bases=(django_fsm.ConcurrentTransitionMixin, models.Model),
        ),
    ]
