# Generated by Django 5.2.17 on 2026-09-28 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provisioning', '0008_servicerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='last_decision_from_status',
            field=models.CharField(blank=True, editable=False, max_length=16),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='last_decision_note',
            field=models.TextField(blank=True, editable=False, max_length=4000),
        ),
    ]
