# Generated by Django 5.2.17 on 2026-09-29 07:51

import uuid

import django.db.models.deletion
from django.db import migrations, models


def preserve_ron_prices(apps, schema_editor):
    plan_model = apps.get_model("provisioning", "ServicePlan")
    price_model = apps.get_model("provisioning", "ServicePlanPrice")
    alias = schema_editor.connection.alias
    for plan in plan_model.objects.using(alias).iterator():
        price_model.objects.using(alias).get_or_create(
            service_plan_id=plan.pk, currency_id="RON",
            defaults={
                "monthly_price_cents": int(plan.price_monthly * 100),
                "quarterly_price_cents": int(plan.price_quarterly * 100) if plan.price_quarterly is not None else None,
                "annual_price_cents": int(plan.price_annual * 100) if plan.price_annual is not None else None,
                "setup_cents": int(plan.setup_fee * 100),
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0060_currency_bound_balances'),
        ('provisioning', '0009_servicerequest_last_decision_from_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePlanPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monthly_price_cents', models.PositiveBigIntegerField()),
                ('quarterly_price_cents', models.PositiveBigIntegerField(blank=True, null=True)),
                ('semiannual_price_cents', models.PositiveBigIntegerField(blank=True, null=True)),
                ('annual_price_cents', models.PositiveBigIntegerField(blank=True, null=True)),
                ('setup_cents', models.PositiveBigIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.currency')),
                ('service_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_prices', to='provisioning.serviceplan')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('service_plan', 'currency'), name='service_plan_currency_price')],
            },
        ),
        # Prices are historical evidence and survive a rollback of application code.
        migrations.RunPython(preserve_ron_prices, migrations.RunPython.noop),
    ]
