# Generated by Django 5.2.5 on 2025-09-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provisioning', '0010_alter_provisioningtask_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualminaccount',
            name='bandwidth_quota_mb',
            field=models.IntegerField(blank=True, help_text='Use -1 for unlimited bandwidth', null=True, verbose_name='Bandwidth Quota (MB)'),
        ),
    ]
