# Generated by Django 5.2.5 on 2025-09-08 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provisioning', '0012_add_virtualmin_domain_uniqueness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualminaccount',
            name='service',
            field=models.OneToOneField(help_text='One-to-one relationship ensures each service has at most one VirtualMin account. This enforces current business logic at database level.', on_delete=django.db.models.deletion.CASCADE, related_name='virtualmin_account', to='provisioning.service', verbose_name='PRAHO Service'),
        ),
    ]
