# Generated by Django 5.2.9 on 2025-12-25 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("provisioning", "0013_add_rollback_tracking_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="virtualminaccount",
            name="service",
            field=models.OneToOneField(
                help_text="One-to-one relationship ensures each service has at most one VirtualMin account. This enforces current business logic at database level.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="virtualmin_account",
                to="provisioning.service",
                verbose_name="PRAHO Service",
            ),
        ),
    ]
