# Generated by Django 5.2.11 on 2026-02-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provisioning', '0014_usage_based_billing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualminprovisioningjob',
            name='rollback_status',
            field=models.CharField(blank=True, choices=[('', 'Not Applicable'), ('success', 'Rollback Successful'), ('partial', 'Rollback Partially Successful'), ('failed', 'Rollback Failed')], help_text='Status of rollback operation if executed', max_length=20, verbose_name='Rollback Status'),
        ),
    ]
