# Generated by Django 5.2.11 on 2026-03-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provisioning', '0017_encrypt_server_management_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='_api_password_encrypted',
            field=models.TextField(blank=True, default='', verbose_name='AES-256-GCM Encrypted API Password'),
        ),
        migrations.AddField(
            model_name='server',
            name='api_username',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Virtualmin API Username'),
        ),
        migrations.AlterField(
            model_name='server',
            name='management_api_key',
            field=models.TextField(blank=True, default='', verbose_name='AES-256-GCM Encrypted API Key'),
        ),
        migrations.AlterField(
            model_name='server',
            name='management_api_secret',
            field=models.TextField(blank=True, default='', verbose_name='AES-256-GCM Encrypted API Secret'),
        ),
    ]
