# Generated by Django 5.2.11 on 2026-03-09 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provisioning', '0019_service_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price'),
        ),
    ]
