# Generated by Django 5.2.11 on 2026-03-10 18:07

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provisioning', '0020_alter_service_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='terminated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Terminated At'),
        ),
        migrations.AlterField(
            model_name='service',
            name='status',
            field=django_fsm.FSMField(choices=[('pending', 'Pending'), ('provisioning', 'Provisioning'), ('active', 'Active'), ('suspended', 'Suspended'), ('failed', 'Provisioning Failed'), ('terminated', 'Terminated'), ('expired', 'Expired')], default='pending', max_length=20, protected=True, verbose_name='Status'),
        ),
    ]
