# Generated by Django 5.2.11 on 2026-03-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('billing', '0022_invoice_invoice_subtotal_non_negative_and_more'),
        ('customers', '0012_fix_soft_delete_unique_constraints'),
        ('provisioning', '0021_service_terminated_at_alter_service_status'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'provisioning', 'active', 'suspended', 'failed', 'terminated', 'expired'])), name='service_status_valid_values'),
        ),
    ]
