# Generated by Django 5.2.12 on 2026-03-10 23:00

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_alter_customer_status_customer_customer_valid_status'),
        ('provisioning', '0022_service_service_status_valid_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicegroup',
            name='status',
            field=django_fsm.FSMField(choices=[('active', '🟢 Active'), ('suspended', '🟡 Suspended'), ('cancelled', '🔴 Cancelled'), ('pending', '⏳ Pending Setup')], db_index=True, default='pending', max_length=20, protected=True),
        ),
        migrations.AddConstraint(
            model_name='servicegroup',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['active', 'suspended', 'cancelled', 'pending'])), name='service_group_valid_status'),
        ),
    ]
