"""Repairing a document's type left the wrong builder's bytes in place.

`_repair_stale_document_type` corrects a credit note whose `EFacturaDocument` still claims to
be an invoice, and saved only `document_type`. But the stored XML was produced while the row
said INVOICE, so `UBLInvoiceBuilder` wrote it: a 380 with negative amounts and no reference to
the document being reversed. Fixing the label and keeping the bytes leaves the row internally
inconsistent in the one way that matters, because submission re-validates and files what is
stored, not what the label now says.

Blanking `xml_content` is enough to fix it. `submit` regenerates whenever the field is empty,
and `_generate_xml` chooses the builder with `builder_for(invoice)`, which keys on the
INVOICE's `document_kind` rather than on the document's type - so the regenerated bytes come
from `UBLCreditNoteBuilder` regardless of what the stale label said.

It is also permitted, which is not obvious: `EFacturaDocument.save` refuses an XML change when
a claim is held OR the stored status is one ANAF may have seen. The repair is already bounded
by `repairable_statuses()` - `{draft, queued, error}` - none of which is in the frozen set, and
`efactura_claim_state_consistent` guarantees at the database level that anything other than
`uploading` holds no claim. So neither arm of the guard can fire on this path.

Migration `0056` performs the same repair for rows that existed before it, and left their bytes
behind too, so `0058` blanks them.
"""

from __future__ import annotations

import uuid
from decimal import Decimal

from django.db import connection
from django.db.migrations.executor import MigrationExecutor
from django.test import TestCase, TransactionTestCase
from django.utils import timezone

from apps.billing.efactura.models import EFacturaDocument, EFacturaDocumentType, EFacturaStatus
from apps.billing.efactura.service import EFacturaService
from apps.billing.invoice_models import (
    DOCUMENT_KIND_CREDIT_NOTE,
    ISSUER_BUILTIN,
    Currency,
    Invoice,
)
from tests.factories.billing_factories import CustomerFactory, InvoiceLineFactory
from tests.helpers.migrations import restore_to_leaf

MIGRATE_FROM = ("billing", "0057_backfill_provider_submission_budget")
MIGRATION_UNDER_TEST = ("billing", "0058_clear_credit_note_xml_built_by_the_wrong_builder")

# Recognisably an ordinary invoice: the root element is what the wrong builder emits.
WRONG_BUILDER_XML = '<?xml version="1.0"?><Invoice><ID>CN-000960</ID></Invoice>'


class StaleCreditNoteXmlRuntimeTests(TestCase):
    def setUp(self) -> None:
        self.customer = CustomerFactory()
        self.currency = Currency.objects.get_or_create(code="RON", defaults={"symbol": "L", "decimals": 2})[0]
        self._seq = 0

    def _invoice(self) -> Invoice:
        self._seq += 1
        invoice = Invoice.objects.create(
            customer=self.customer,
            currency=self.currency,
            number=f"FCT-0006{self._seq:02d}",
            status="draft",
            subtotal_cents=10000,
            tax_cents=2100,
            total_cents=12100,
            bill_to_name="Test Company SRL",
            bill_to_country="RO",
            issuer_provider=ISSUER_BUILTIN,
        )
        InvoiceLineFactory(
            invoice=invoice,
            description="Hosting",
            quantity=Decimal("1"),
            unit_price_cents=10000,
            tax_rate=Decimal("0.2100"),
            tax_cents=2100,
            line_total_cents=12100,
        )
        return invoice

    def _credit_note(self) -> Invoice:
        self._seq += 1
        return Invoice.objects.create(
            customer=self.customer,
            currency=self.currency,
            number=f"CN-0006{self._seq:02d}",
            status="draft",
            document_kind=DOCUMENT_KIND_CREDIT_NOTE,
            reverses_invoice=self._invoice(),
            subtotal_cents=-10000,
            tax_cents=-2100,
            total_cents=-12100,
            bill_to_name="Test Company SRL",
            bill_to_country="RO",
            issuer_provider=ISSUER_BUILTIN,
        )

    def _stale_document_with_xml(self, invoice: Invoice, status: str) -> EFacturaDocument:
        document = EFacturaDocument.objects.create(
            invoice=invoice,
            document_type=EFacturaDocumentType.INVOICE.value,
            environment="test",
            xml_content=WRONG_BUILDER_XML,
            xml_generated_at=timezone.now(),
        )
        fields: dict[str, object] = {"status": status}
        if status == EFacturaStatus.UPLOADING.value:
            fields |= {
                "submission_claim_token": uuid.uuid4(),
                "submission_claimed_at": timezone.now(),
                "submission_claim_expires_at": timezone.now() + timezone.timedelta(minutes=10),
            }
        EFacturaDocument.objects.filter(pk=document.pk).update(**fields)
        return EFacturaDocument.objects.get(pk=document.pk)

    def test_the_repair_discards_the_wrong_builders_bytes(self) -> None:
        for status in (EFacturaStatus.DRAFT.value, EFacturaStatus.QUEUED.value, EFacturaStatus.ERROR.value):
            with self.subTest(status=status):
                credit_note = self._credit_note()
                stale = self._stale_document_with_xml(credit_note, status)

                EFacturaService()._get_or_create_document(credit_note)

                stored = EFacturaDocument.objects.get(pk=stale.pk)
                self.assertEqual(stored.document_type, EFacturaDocumentType.CREDIT_NOTE.value)
                self.assertEqual(stored.xml_content, "")
                self.assertEqual(stored.xml_hash, "", "a blanked document must not keep a hash of the old bytes")
                self.assertIsNone(stored.xml_generated_at)

    def test_a_document_anaf_may_have_seen_keeps_its_bytes(self) -> None:
        """The stored XML is the evidence of what was filed; it outranks the label."""
        for status in (
            EFacturaStatus.SUBMITTED.value,
            EFacturaStatus.ACCEPTED.value,
            EFacturaStatus.UPLOADING.value,
        ):
            with self.subTest(status=status):
                credit_note = self._credit_note()
                stale = self._stale_document_with_xml(credit_note, status)

                EFacturaService()._get_or_create_document(credit_note)

                self.assertEqual(EFacturaDocument.objects.get(pk=stale.pk).xml_content, WRONG_BUILDER_XML)

    def test_a_correctly_typed_document_keeps_its_bytes(self) -> None:
        """Nothing is stale here, so regenerating would be churn with a cost."""
        credit_note = self._credit_note()
        document = EFacturaDocument.objects.create(
            invoice=credit_note,
            document_type=EFacturaDocumentType.CREDIT_NOTE.value,
            environment="test",
            xml_content=WRONG_BUILDER_XML,
            xml_generated_at=timezone.now(),
        )

        EFacturaService()._get_or_create_document(credit_note)

        self.assertEqual(EFacturaDocument.objects.get(pk=document.pk).xml_content, WRONG_BUILDER_XML)


class StaleCreditNoteXmlMigrationTest(TransactionTestCase):
    """0056 already repaired the label on rows that existed before it, and kept the bytes."""

    def tearDown(self) -> None:
        restore_to_leaf("billing")
        super().tearDown()

    def _seed(self, *, status: str, document_kind: str, document_type: str) -> object:
        executor = MigrationExecutor(connection)
        executor.migrate([MIGRATE_FROM])
        old = executor.loader.project_state([MIGRATE_FROM]).apps

        customer_model = old.get_model("customers", "Customer")
        currency_model = old.get_model("billing", "Currency")
        invoice_model = old.get_model("billing", "Invoice")
        document_model = old.get_model("billing", "EFacturaDocument")

        customer = customer_model.objects.create(
            name="Test Co", customer_type="company", company_name="Test Co", status="active"
        )
        currency, _ = currency_model.objects.get_or_create(
            code="RON", defaults={"symbol": "L", "decimals": 2, "name": "Romanian Leu"}
        )
        sign = -1 if document_kind == "credit_note" else 1
        original = invoice_model.objects.create(
            customer=customer,
            currency=currency,
            number="FCT-000960",
            status="issued",
            subtotal_cents=10000,
            tax_cents=2100,
            total_cents=12100,
            bill_to_name="Test Co",
            bill_to_country="RO",
        )
        subject = invoice_model.objects.create(
            customer=customer,
            currency=currency,
            number="CN-000960",
            status="issued",
            document_kind=document_kind,
            reverses_invoice=original if document_kind == "credit_note" else None,
            subtotal_cents=10000 * sign,
            tax_cents=2100 * sign,
            total_cents=12100 * sign,
            bill_to_name="Test Co",
            bill_to_country="RO",
        )
        document = document_model.objects.create(
            invoice=subject,
            document_type=document_type,
            status=status,
            environment="test",
            xml_content=WRONG_BUILDER_XML,
            xml_hash="a" * 64,
            xml_generated_at=timezone.now(),
        )
        return document.pk

    def _document_after_migration(self, pk: object) -> object:
        MigrationExecutor(connection).migrate([MIGRATION_UNDER_TEST])
        new = MigrationExecutor(connection).loader.project_state([MIGRATION_UNDER_TEST]).apps
        return new.get_model("billing", "EFacturaDocument").objects.get(pk=pk)

    def test_an_unsent_credit_note_document_loses_its_bytes(self) -> None:
        pk = self._seed(status="draft", document_kind="credit_note", document_type="credit_note")

        document = self._document_after_migration(pk)

        self.assertEqual(document.xml_content, "")
        self.assertEqual(document.xml_hash, "")
        self.assertIsNone(document.xml_generated_at)

    def test_a_sent_credit_note_document_keeps_its_bytes(self) -> None:
        pk = self._seed(status="accepted", document_kind="credit_note", document_type="credit_note")

        self.assertEqual(self._document_after_migration(pk).xml_content, WRONG_BUILDER_XML)

    def test_an_ordinary_invoices_document_keeps_its_bytes(self) -> None:
        """Only the credit-note builder was ever in question."""
        pk = self._seed(status="draft", document_kind="invoice", document_type="invoice")

        self.assertEqual(self._document_after_migration(pk).xml_content, WRONG_BUILDER_XML)
