# Generated by Django 5.2.5 on 2025-09-14 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('provisioning', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='default_service_plan',
            field=models.ForeignKey(blank=True, help_text='Default service plan to use when creating services from orders', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='provisioning.serviceplan'),
        ),
    ]
