# Generated by Django 5.2.12 on 2026-03-11 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('products', '0001_initial'),
        ('provisioning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='default_service_plan',
            field=models.ForeignKey(blank=True, help_text='Default service plan to use when creating services from orders', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='provisioning.serviceplan'),
        ),
        migrations.AddField(
            model_name='productbundleitem',
            name='bundle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.productbundle'),
        ),
        migrations.AddField(
            model_name='productbundleitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_items', to='products.product'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='currency',
            field=models.ForeignKey(help_text='Currency for this price', on_delete=django.db.models.deletion.PROTECT, to='billing.currency'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='products.product'),
        ),
        migrations.AddField(
            model_name='productrelationship',
            name='source_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_from', to='products.product'),
        ),
        migrations.AddField(
            model_name='productrelationship',
            name='target_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_to', to='products.product'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='products_slug_5e91f2_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_type', 'is_active'], name='products_product_6ea65b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'is_public'], name='products_is_acti_2245a6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sort_order'], name='products_sort_or_6c1e3d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productbundleitem',
            unique_together={('bundle', 'product')},
        ),
        migrations.AddIndex(
            model_name='productprice',
            index=models.Index(fields=['currency'], name='product_pri_currenc_ee75d2_idx'),
        ),
        migrations.AddIndex(
            model_name='productprice',
            index=models.Index(fields=['is_active'], name='product_pri_is_acti_33e3d0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productprice',
            unique_together={('product', 'currency')},
        ),
        migrations.AddIndex(
            model_name='productrelationship',
            index=models.Index(fields=['source_product', 'relationship_type'], name='product_rel_source__a85181_idx'),
        ),
        migrations.AddIndex(
            model_name='productrelationship',
            index=models.Index(fields=['target_product', 'relationship_type'], name='product_rel_target__ad4bcb_idx'),
        ),
        migrations.AddIndex(
            model_name='productrelationship',
            index=models.Index(fields=['is_active'], name='product_rel_is_acti_b28a02_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productrelationship',
            unique_together={('source_product', 'target_product', 'relationship_type')},
        ),
    ]
