# Generated by Django 5.2.17 on 2026-09-29 08:27

from django.db import migrations, models

import apps.products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprice',
            name='custom_period_prices',
            field=models.JSONField(blank=True, default=dict, validators=[apps.products.models.validate_custom_period_prices]),
        ),
        migrations.AddField(
            model_name='productprice',
            name='quarterly_price_cents',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
