# Generated by Django 5.0.14 on 2025-08-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user__two_factor_secret_webauthncredential"),
    ]

    operations = [
        # ===============================================================================
        # STEP 1: RENAME TABLE TO CONSISTENT TFA (TWO-FACTOR AUTH) NAMING
        # ===============================================================================
        migrations.RunSQL(
            sql="ALTER TABLE webauthn_credentials RENAME TO tfa_webauthn_credentials;",
            reverse_sql="ALTER TABLE tfa_webauthn_credentials RENAME TO webauthn_credentials;",
        ),
        
        # ===============================================================================
        # STEP 2: DROP OLD INDEXES WITH INCONSISTENT NAMES
        # ===============================================================================
        migrations.RunSQL(
            sql=[
                "DROP INDEX IF EXISTS webauthn_cr_user_id_e94f82_idx;",
                "DROP INDEX IF EXISTS webauthn_cr_credent_3c0f86_idx;",
                "DROP INDEX IF EXISTS webauthn_cr_is_acti_6e7494_idx;",
            ],
            reverse_sql=[
                "CREATE INDEX webauthn_cr_user_id_e94f82_idx ON tfa_webauthn_credentials (user_id, created_at DESC);",
                "CREATE INDEX webauthn_cr_credent_3c0f86_idx ON tfa_webauthn_credentials (credential_id);",
                "CREATE INDEX webauthn_cr_is_acti_6e7494_idx ON tfa_webauthn_credentials (is_active, last_used DESC);",
            ]
        ),
        
        # ===============================================================================
        # STEP 3: CREATE NEW INDEXES WITH CONSISTENT TFA NAMING
        # ===============================================================================
        migrations.RunSQL(
            sql=[
                # Core WebAuthn indexes with consistent naming (idx_tfa_*)
                "CREATE INDEX idx_tfa_webauthn_user_created ON tfa_webauthn_credentials (user_id, created_at DESC);",
                "CREATE INDEX idx_tfa_webauthn_credential_id ON tfa_webauthn_credentials (credential_id);",
                "CREATE INDEX idx_tfa_webauthn_active_used ON tfa_webauthn_credentials (is_active, last_used DESC);",
                
                # Additional performance indexes for 2FA queries
                "CREATE INDEX idx_tfa_webauthn_user_lookup ON tfa_webauthn_credentials (user_id);",
                "CREATE INDEX idx_tfa_webauthn_aaguid ON tfa_webauthn_credentials (aaguid);",
                "CREATE INDEX idx_tfa_webauthn_type ON tfa_webauthn_credentials (credential_type);",
                "CREATE INDEX idx_tfa_webauthn_active ON tfa_webauthn_credentials (is_active);",
                
                # User table indexes for 2FA filtering (idx_users_2fa_*)
                "CREATE INDEX idx_users_2fa_enabled ON users (two_factor_enabled);",
                "CREATE INDEX idx_users_2fa_enabled_staff ON users (two_factor_enabled, is_staff);",
            ],
            reverse_sql=[
                "DROP INDEX IF EXISTS idx_tfa_webauthn_user_created;",
                "DROP INDEX IF EXISTS idx_tfa_webauthn_credential_id;",
                "DROP INDEX IF EXISTS idx_tfa_webauthn_active_used;",
                "DROP INDEX IF EXISTS idx_tfa_webauthn_user_lookup;",
                "DROP INDEX IF EXISTS idx_tfa_webauthn_aaguid;",
                "DROP INDEX IF EXISTS idx_tfa_webauthn_type;",
                "DROP INDEX IF EXISTS idx_tfa_webauthn_active;",
                "DROP INDEX IF EXISTS idx_users_2fa_enabled;",
                "DROP INDEX IF EXISTS idx_users_2fa_enabled_staff;",
            ]
        ),
        
        # ===============================================================================
        # STEP 4: UPDATE MODEL META TO REFLECT NEW TABLE NAME
        # ===============================================================================
        migrations.AlterModelTable(
            name='webauthncredential',
            table='tfa_webauthn_credentials',
        ),
    ]
