# Generated by Django 5.2.5 on 2025-08-31 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_rename_payment_method_field'),
        ('users', '0006_webauthn_credential_enhancements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='customers',
            field=models.ManyToManyField(blank=True, related_name='members', through='users.CustomerMembership', through_fields=('user', 'customer'), to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='user',
            name='staff_role',
            field=models.CharField(blank=True, choices=[('admin', 'System Administrator'), ('support', 'Support Agent'), ('billing', 'Billing Staff'), ('manager', 'Manager')], default='', help_text='Staff role for internal staff. Leave empty for customer users.', max_length=20),
        ),
        migrations.CreateModel(
            name='BackupCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashed_code', models.CharField(help_text='Argon2-hashed backup code for secure storage', max_length=128)),
                ('is_used', models.BooleanField(default=False, help_text='Whether this backup code has been used')),
                ('used_at', models.DateTimeField(blank=True, help_text='Timestamp when this backup code was used', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this backup code was generated')),
                ('created_from_ip', models.GenericIPAddressField(blank=True, help_text='Client IP where backup code was generated', null=True)),
                ('used_from_ip', models.GenericIPAddressField(blank=True, help_text='Client IP where backup code was used', null=True)),
                ('generation_context', models.CharField(blank=True, default='user_requested', help_text="Context for backup code generation (e.g., 'mfa_setup', 'regeneration')", max_length=100)),
                ('user', models.ForeignKey(help_text='User who owns this backup code', on_delete=django.db.models.deletion.CASCADE, related_name='backup_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Backup Code',
                'verbose_name_plural': 'Backup Codes',
                'db_table': 'users_backupcode',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_used'], name='backup_code_user_unused'), models.Index(fields=['created_at'], name='backup_code_created'), models.Index(fields=['used_at'], name='backup_code_used')],
            },
        ),
    ]
