# Generated by Django 5.2.5 on 2025-08-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_convert_object_id_to_string'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportcategory',
            options={'ordering': ('sort_order', 'name'), 'verbose_name': 'Support Category', 'verbose_name_plural': 'Support Categories'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ('-created_at',), 'verbose_name': 'Support Ticket', 'verbose_name_plural': 'Support Tickets'},
        ),
        migrations.AlterModelOptions(
            name='ticketattachment',
            options={'ordering': ('uploaded_at',), 'verbose_name': 'Ticket Attachment', 'verbose_name_plural': 'Ticket Attachments'},
        ),
        migrations.AlterModelOptions(
            name='ticketcomment',
            options={'ordering': ('created_at',), 'verbose_name': 'Ticket Comment', 'verbose_name_plural': 'Ticket Comments'},
        ),
        migrations.AlterModelOptions(
            name='ticketworklog',
            options={'ordering': ('-work_date',), 'verbose_name': 'Ticket Worklog', 'verbose_name_plural': 'Ticket Worklogs'},
        ),
        migrations.AlterField(
            model_name='ticket',
            name='object_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=36),
        ),
    ]
