# Generated by Django 5.2.5 on 2025-09-13 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='credentialaccesslog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='encryptedcredential',
            index=models.Index(fields=['service_type', 'service_identifier'], name='credential__service_df0d81_idx'),
        ),
        migrations.AddIndex(
            model_name='encryptedcredential',
            index=models.Index(fields=['expires_at'], name='credential__expires_4df01a_idx'),
        ),
        migrations.AddIndex(
            model_name='encryptedcredential',
            index=models.Index(fields=['last_accessed'], name='credential__last_ac_df2945_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='encryptedcredential',
            unique_together={('service_type', 'service_identifier')},
        ),
        migrations.AddField(
            model_name='credentialaccesslog',
            name='credential',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='common.encryptedcredential'),
        ),
        migrations.AddIndex(
            model_name='credentialaccesslog',
            index=models.Index(fields=['credential', 'accessed_at'], name='credential__credent_be52de_idx'),
        ),
        migrations.AddIndex(
            model_name='credentialaccesslog',
            index=models.Index(fields=['user', 'accessed_at'], name='credential__user_id_27d6bb_idx'),
        ),
        migrations.AddIndex(
            model_name='credentialaccesslog',
            index=models.Index(fields=['accessed_at'], name='credential__accesse_5b99f0_idx'),
        ),
    ]
