# Generated by Django 5.2.12 on 2026-03-11 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='credentialaccesslog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='encryptedcredential',
            index=models.Index(fields=['service_type', 'service_identifier'], name='common_cred_service_ca3d88_idx'),
        ),
        migrations.AddIndex(
            model_name='encryptedcredential',
            index=models.Index(fields=['expires_at'], name='common_cred_expires_cf5dd6_idx'),
        ),
        migrations.AddIndex(
            model_name='encryptedcredential',
            index=models.Index(fields=['last_accessed'], name='common_cred_last_ac_9aa258_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='encryptedcredential',
            unique_together={('service_type', 'service_identifier')},
        ),
        migrations.AddField(
            model_name='credentialaccesslog',
            name='credential',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='common.encryptedcredential'),
        ),
        migrations.AddIndex(
            model_name='credentialaccesslog',
            index=models.Index(fields=['credential', 'accessed_at'], name='common_cred_credent_fd1a01_idx'),
        ),
        migrations.AddIndex(
            model_name='credentialaccesslog',
            index=models.Index(fields=['user', 'accessed_at'], name='common_cred_user_id_e4c22e_idx'),
        ),
        migrations.AddIndex(
            model_name='credentialaccesslog',
            index=models.Index(fields=['accessed_at'], name='common_cred_accesse_f5e208_idx'),
        ),
    ]
