# Generated by Django 5.2.11 on 2026-03-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptedcredential',
            name='service_type',
            field=models.CharField(choices=[('virtualmin', 'Virtualmin API'), ('stripe', 'Stripe Payment Gateway'), ('dns_cloudflare', 'Cloudflare DNS'), ('dns_route53', 'AWS Route53 DNS'), ('ssh', 'SSH Access'), ('ssl_certificate', 'SSL Certificate'), ('backup_storage', 'Backup Storage'), ('monitoring', 'Monitoring Service'), ('email_smtp', 'SMTP Email Service'), ('domain_registrar', 'Domain Registrar'), ('cloud_provider', 'Cloud Provider API')], max_length=50),
        ),
    ]
