# Generated by Django 5.2.12 on 2026-03-11 15:11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


def apply_postgres_event_storage_indexes(apps, schema_editor) -> None:  # type: ignore[no-untyped-def]
    if schema_editor.connection.vendor != "postgresql":
        return

    statements = (
        """
        CREATE INDEX IF NOT EXISTS integration_webhook_events_recent_cover_idx
        ON integration_webhook_events (received_at DESC)
        INCLUDE (source, event_type, status, processed_at, retry_count, next_retry_at);
        """,
        """
        CREATE INDEX IF NOT EXISTS integration_webhook_events_efactura_lookup_idx
        ON integration_webhook_events (source, event_id varchar_pattern_ops, received_at DESC)
        INCLUDE (status, processed_at, error_message);
        """,
        """
        CREATE INDEX IF NOT EXISTS integration_webhook_events_received_at_brin
        ON integration_webhook_events USING BRIN (received_at) WITH (pages_per_range = 32);
        """,
    )
    with schema_editor.connection.cursor() as cursor:
        for statement in statements:
            cursor.execute(statement)


def reverse_postgres_event_storage_indexes(apps, schema_editor) -> None:  # type: ignore[no-untyped-def]
    if schema_editor.connection.vendor != "postgresql":
        return

    statements = (
        "DROP INDEX IF EXISTS integration_webhook_events_received_at_brin;",
        "DROP INDEX IF EXISTS integration_webhook_events_efactura_lookup_idx;",
        "DROP INDEX IF EXISTS integration_webhook_events_recent_cover_idx;",
    )
    with schema_editor.connection.cursor() as cursor:
        for statement in statements:
            cursor.execute(statement)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('stripe', '💳 Stripe'), ('paypal', '🟡 PayPal'), ('virtualmin', '🖥️ Virtualmin'), ('cpanel', '🌐 cPanel'), ('registrar_namecheap', '🏷️ Namecheap'), ('registrar_godaddy', '🏷️ GoDaddy'), ('bank_bt', '🏦 Banca Transilvania'), ('bank_bcr', '🏦 BCR'), ('efactura', '🇷🇴 e-Factura'), ('other', '🔌 Other')], help_text='External service that sent the webhook', max_length=50)),
                ('event_id', models.CharField(help_text='Unique event ID from the external service', max_length=255)),
                ('event_type', models.CharField(help_text="Type of event (e.g., 'payment.succeeded', 'domain.created')", max_length=100)),
                ('status', models.CharField(choices=[('pending', '⏳ Pending'), ('processed', '✅ Processed'), ('failed', '❌ Failed'), ('skipped', '⏭️ Skipped')], default='pending', max_length=20)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When webhook was received by our system')),
                ('processed_at', models.DateTimeField(blank=True, help_text='When webhook processing completed', null=True)),
                ('payload', models.JSONField(help_text='Complete webhook payload from external service')),
                ('signature_hash', models.CharField(blank=True, default='', help_text='SHA-256 hash of webhook signature for verification tracking', max_length=64)),
                ('error_message', models.TextField(blank=True, help_text='Error details if processing failed')),
                ('retry_count', models.PositiveIntegerField(default=0, help_text='Number of processing attempts', validators=[django.core.validators.MinValueValidator(0)])),
                ('next_retry_at', models.DateTimeField(blank=True, help_text='When to retry processing (for failed webhooks)', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address webhook was received from', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent of webhook sender')),
                ('headers', models.JSONField(blank=True, default=dict, help_text='HTTP headers from webhook request')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '🔄 Webhook Event',
                'verbose_name_plural': '🔄 Webhook Events',
                'db_table': 'integration_webhook_events',
                'ordering': ('-received_at',),
                'indexes': [models.Index(condition=models.Q(('status', 'pending')), fields=['status', 'received_at'], name='webhook_pending_idx'), models.Index(condition=models.Q(('next_retry_at__isnull', False), ('status', 'failed')), fields=['status', 'next_retry_at'], name='webhook_retry_idx'), models.Index(fields=['source', 'event_type', 'received_at'], name='webhook_source_type_idx')],
                'unique_together': {('source', 'event_id')},
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('endpoint_url', models.URLField(help_text="Customer's webhook endpoint URL")),
                ('event_type', models.CharField(help_text='Type of event being delivered', max_length=100)),
                ('payload', models.JSONField(help_text='Webhook payload sent to customer')),
                ('status', models.CharField(choices=[('pending', '⏳ Pending'), ('delivered', '✅ Delivered'), ('failed', '❌ Failed'), ('disabled', '🚫 Disabled')], default='pending', max_length=20)),
                ('http_status', models.PositiveIntegerField(blank=True, help_text='HTTP response status from customer endpoint', null=True)),
                ('response_body', models.TextField(blank=True, help_text='Response body from customer endpoint')),
                ('scheduled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_deliveries', to='customers.customer')),
            ],
            options={
                'verbose_name': '📤 Webhook Delivery',
                'verbose_name_plural': '📤 Webhook Deliveries',
                'db_table': 'integration_webhook_deliveries',
                'ordering': ('-scheduled_at',),
                'indexes': [models.Index(fields=['status', 'scheduled_at'], name='delivery_pending_idx'), models.Index(fields=['customer', 'event_type', 'scheduled_at'], name='delivery_customer_idx')],
            },
        ),
        migrations.RunPython(apply_postgres_event_storage_indexes, reverse_postgres_event_storage_indexes),
    ]
