# Generated by Django 5.2.5 on 2025-09-01 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_alter_webhookdelivery_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webhookevent',
            options={'ordering': ('-received_at',), 'permissions': [('view_webhook_stats', 'Can view webhook statistics'), ('retry_webhook', 'Can retry failed webhooks')], 'verbose_name': '🔄 Webhook Event', 'verbose_name_plural': '🔄 Webhook Events'},
        ),
    ]
