"""
Settings catalog — the single source of truth for runtime settings (ADR-0042).

Every runtime setting the platform exposes is declared here: key, type, default,
UI placement (zone → group → section), input kind, sensitivity, criticality, and
validation rules. The database stores current values; this catalog owns identity
and metadata. A consumer-contract test enforces that every key declared here is
read somewhere in production code — decoy settings cannot exist.

The e-Factura entries mirror apps.billing.efactura.settings.EFACTURA_DEFAULTS
(kept as literals to avoid a settings → billing import cycle); a test asserts
the two stay identical.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any

from django.utils.translation import gettext_lazy as _

if TYPE_CHECKING:
    from django.utils.functional import _StrPromise

    LazyLabel = str | _StrPromise
else:
    LazyLabel = str

# Zones: the three UI surfaces
ZONE_BUSINESS = "business"
ZONE_INTEGRATIONS = "integrations"
ZONE_PLATFORM = "platform"


@dataclass(frozen=True)
class GroupDef:
    """A navigable settings group (one page in the UI)"""

    slug: str
    zone: str
    label: LazyLabel
    description: LazyLabel = ""
    section_order: tuple[str, ...] = ()


@dataclass(frozen=True)
class SettingDef:
    """Declaration of one runtime setting"""

    key: str
    data_type: str  # string | integer | boolean | decimal | list | json
    default: Any
    group: str
    section: LazyLabel
    label: LazyLabel
    help_text: LazyLabel = ""
    unit: str = ""
    input_kind: str = "text"  # text | number | toggle | select | chips | json | secret
    sensitive: bool = False
    critical: bool = False
    requires_restart: bool = False
    advanced: bool = False
    validation: dict[str, Any] | None = field(default=None, hash=False)


GROUPS: tuple[GroupDef, ...] = (
    GroupDef(
        "company",
        ZONE_BUSINESS,
        _("Company & Identity"),
        _("Legal identity and contact addresses used on documents and emails"),
    ),
    GroupDef(
        "billing",
        ZONE_BUSINESS,
        _("Billing & Invoicing"),
        _("Payment terms, proforma validity, collections, and e-Factura policy"),
        section_order=("Invoicing", "Payments", "Collections", "e-Factura"),
    ),
    GroupDef(
        "orders", ZONE_BUSINESS, _("Orders & Checkout"), _("Payment timeouts, price-override caps, and review policy")
    ),
    GroupDef("domains", ZONE_BUSINESS, _("Domains"), _("Expiry notices and domain add-on pricing")),
    GroupDef("customers", ZONE_BUSINESS, _("Customers & Credit"), _("Credit scoring and engagement weighting")),
    GroupDef("support", ZONE_BUSINESS, _("Support"), _("Ticket attachment policy")),
    GroupDef("security", ZONE_BUSINESS, _("Security & Access"), _("Session timeouts and access policy")),
    GroupDef("stripe", ZONE_INTEGRATIONS, _("Stripe"), _("Payment gateway credentials and state")),
    GroupDef(
        "virtualmin",
        ZONE_INTEGRATIONS,
        _("Virtualmin"),
        _("Control-panel connection and provisioning defaults"),
        section_order=("Connection", "Rate limits", "Quotas", "Hosted services", "Backups"),
    ),
    GroupDef(
        "efactura",
        ZONE_INTEGRATIONS,
        "e-Factura (ANAF)",
        "Romanian e-invoicing: OAuth, company profile, submission policy",
    ),
    GroupDef(
        "node-deployment", ZONE_INTEGRATIONS, _("Node Deployment"), _("Terraform, DNS, and node backup configuration")
    ),
    GroupDef("backup", ZONE_INTEGRATIONS, _("Backup Storage"), _("S3 storage for Virtualmin backups")),
    GroupDef("platform", ZONE_PLATFORM, _("Maintenance & Availability"), _("Platform-wide availability controls")),
    GroupDef(
        "advanced",
        ZONE_PLATFORM,
        "Advanced Tuning",
        "Engineering tuning constants — defaults are appropriate for most deployments",
    ),
)

GROUPS_BY_SLUG: dict[str, GroupDef] = {g.slug: g for g in GROUPS}


CATALOG: tuple[SettingDef, ...] = (
    SettingDef(
        key="audit.compliant_score_threshold",
        data_type="integer",
        default=90,
        group="advanced",
        section=_("Audit"),
        label=_("Compliant score threshold"),
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="audit.high_complexity_filter_threshold",
        data_type="integer",
        default=5,
        group="advanced",
        section=_("Audit"),
        label=_("High complexity filter threshold"),
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="audit.max_files_displayed",
        data_type="integer",
        default=5,
        group="advanced",
        section=_("Audit"),
        label=_("Max files displayed"),
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="audit.max_violations_displayed",
        data_type="integer",
        default=10,
        group="advanced",
        section=_("Audit"),
        label=_("Max violations displayed"),
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="audit.notify_on_critical_alerts",
        data_type="boolean",
        default=True,
        group="advanced",
        section=_("Audit"),
        label=_("Notify on critical alerts"),
        input_kind="toggle",
        advanced=True,
    ),
    SettingDef(
        key="audit.notify_on_file_integrity_alerts",
        data_type="boolean",
        default=True,
        group="advanced",
        section=_("Audit"),
        label=_("Notify on file integrity alerts"),
        input_kind="toggle",
        advanced=True,
    ),
    SettingDef(
        key="audit.partial_score_threshold",
        data_type="integer",
        default=70,
        group="advanced",
        section=_("Audit"),
        label=_("Partial score threshold"),
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="audit.webhook_healthy_response_threshold",
        data_type="integer",
        default=300,
        group="advanced",
        section=_("Audit"),
        label=_("Webhook healthy response threshold"),
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="audit.webhook_max_retry_threshold",
        data_type="integer",
        default=5,
        group="advanced",
        section=_("Audit"),
        label=_("Webhook max retry threshold"),
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="audit.webhook_suspicious_retry_threshold",
        data_type="integer",
        default=3,
        group="advanced",
        section=_("Audit"),
        label=_("Webhook suspicious retry threshold"),
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="backup.aws_access_key_id",
        data_type="string",
        default="",
        group="backup",
        section=_("S3 storage"),
        label=_("AWS access key ID"),
    ),
    SettingDef(
        key="backup.aws_region",
        data_type="string",
        default="eu-west-1",
        group="backup",
        section=_("S3 storage"),
        label=_("AWS region"),
    ),
    SettingDef(
        key="backup.aws_secret_access_key",
        data_type="string",
        default="",
        group="backup",
        section=_("S3 storage"),
        label=_("AWS secret access key"),
        input_kind="secret",
        sensitive=True,
    ),
    SettingDef(
        key="backup.s3_bucket_name",
        data_type="string",
        default="",
        group="backup",
        section=_("S3 storage"),
        label=_("S3 bucket name"),
    ),
    SettingDef(
        key="billing.alert_cooldown_hours",
        data_type="integer",
        default=24,
        group="advanced",
        section=_("Billing"),
        label=_("Alert cooldown"),
        help_text=_("Prevents alert flooding for the same issue."),
        unit="hours",
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="billing.credit_consecutive_bonus_12",
        data_type="integer",
        default=20,
        group="advanced",
        section=_("Billing"),
        label=_("Credit bonus after 12 consecutive on-time payments"),
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="billing.credit_consecutive_bonus_6",
        data_type="integer",
        default=10,
        group="advanced",
        section=_("Billing"),
        label=_("Credit bonus after 6 consecutive on-time payments"),
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="billing.efactura_api_max_retries",
        data_type="integer",
        default=3,
        group="advanced",
        section=_("Billing"),
        label=_("e-Factura api max retries"),
        help_text=_("Maximum API retry attempts for e-Factura calls"),
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="billing.efactura_api_timeout_seconds",
        data_type="integer",
        default=30,
        group="advanced",
        section=_("Billing"),
        label=_("e-Factura api timeout"),
        help_text=_("Increase if ANAF servers are slow."),
        unit="seconds",
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="billing.efactura_batch_size",
        data_type="integer",
        default=100,
        group="advanced",
        section=_("Billing"),
        label=_("e-Factura batch size"),
        help_text=_("Larger batches are faster but use more memory."),
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="billing.efactura_deadline_warning_hours",
        data_type="integer",
        default=24,
        group="billing",
        section=_("e-Factura"),
        label=_("e-Factura deadline warning"),
        help_text=_("Alert staff this many hours before deadline."),
        unit="hours",
        input_kind="number",
        validation={"min": 0},
    ),
    SettingDef(
        key="billing.efactura_submission_deadline_days",
        data_type="integer",
        default=5,
        group="billing",
        section=_("e-Factura"),
        label=_("Submission deadline"),
        help_text=_("Romanian law requires submission within 5 days."),
        unit="days",
        input_kind="number",
        validation={"min": 0},
    ),
    SettingDef(
        key="billing.event_grace_period_hours",
        data_type="integer",
        default=24,
        group="advanced",
        section=_("Billing"),
        label=_("Event grace period"),
        help_text=_("Prevents duplicate billing event processing."),
        unit="hours",
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="billing.extended_payment_terms_threshold",
        data_type="integer",
        default=60,
        group="advanced",
        section=_("Billing"),
        label=_("Extended payment terms threshold"),
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="billing.future_event_drift_minutes",
        data_type="integer",
        default=5,
        group="advanced",
        section=_("Billing"),
        label=_("Future event drift"),
        help_text=_("Allowed clock drift for future event detection"),
        unit="minutes",
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="billing.invoice_generation_lead_days",
        data_type="integer",
        default=14,
        group="billing",
        section=_("Invoicing"),
        label=_("Renewal billing notice lead time"),
        help_text=_(
            "Generate renewal proformas this many days before the paid-through date. "
            "The global range is 7-30 days so automatic collection never precedes the billing notice "
            "and advance billing stays bounded for monthly services."
        ),
        unit="days",
        input_kind="number",
        validation={"min": 7, "max": 30},
    ),
    SettingDef(
        key="billing.invoice_payment_terms_days",
        data_type="integer",
        default=14,
        group="billing",
        section=_("Invoicing"),
        label=_("Invoice payment terms"),
        help_text=_("Default number of days until invoice payment is due"),
        unit="days",
        input_kind="number",
        validation={"min": 0},
    ),
    SettingDef(
        key="billing.large_credit_limit_threshold",
        data_type="integer",
        default=10000,
        group="advanced",
        section=_("Billing"),
        label=_("Large credit limit threshold"),
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="billing.max_payment_amount_cents",
        data_type="integer",
        default=100000000,
        group="billing",
        section=_("Payments"),
        label=_("Max payment amount"),
        help_text=_("Safety limit to prevent erroneous large payments."),
        unit="cents",
        input_kind="number",
        validation={"min": 0},
    ),
    SettingDef(
        key="billing.max_payment_retries",
        data_type="integer",
        default=5,
        group="advanced",
        section=_("Billing"),
        label=_("Max payment retries"),
        help_text=_("Retry ceiling for the subscription payment retry loop."),
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="billing.max_payment_retry_attempts",
        data_type="integer",
        default=5,
        group="advanced",
        section=_("Billing"),
        label=_("Max payment retry attempts"),
        help_text=_("Attempt cap recorded on subscription payment state."),
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="billing.metering_task_timeout",
        data_type="integer",
        default=300,
        group="advanced",
        section=_("Billing"),
        label=_("Metering task timeout"),
        unit="seconds",
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="billing.proforma_validity_days",
        data_type="integer",
        default=30,
        group="billing",
        section=_("Invoicing"),
        label=_("Proforma validity"),
        help_text=_("Number of days a proforma invoice remains valid"),
        unit="days",
        input_kind="number",
        validation={"min": 0},
    ),
    SettingDef(
        key="billing.recurring_auto_collection_enabled",
        data_type="boolean",
        default=False,
        group="billing",
        section=_("Collections"),
        label=_("Recurring auto collection enabled"),
        input_kind="toggle",
        critical=True,
    ),
    SettingDef(
        key="billing.subscription_grace_period_days",
        data_type="integer",
        default=7,
        group="billing",
        section=_("Collections"),
        label=_("Subscription grace period"),
        help_text=_("Days a customer can use service after payment failure."),
        unit="days",
        input_kind="number",
        validation={"min": 0},
    ),
    SettingDef(
        key="billing.task_max_retries",
        data_type="integer",
        default=3,
        group="advanced",
        section=_("Billing"),
        label=_("Task max retries"),
        help_text=_("Maximum retries for billing background tasks"),
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="billing.task_retry_delay_seconds",
        data_type="integer",
        default=300,
        group="advanced",
        section=_("Billing"),
        label=_("Task retry delay"),
        help_text=_("Delay before retrying a failed billing task."),
        unit="seconds",
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="common.cache_timeout_long",
        data_type="integer",
        default=3600,
        group="advanced",
        section=_("Common"),
        label=_("Cache timeout long"),
        unit="seconds",
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="common.cache_timeout_medium",
        data_type="integer",
        default=300,
        group="advanced",
        section=_("Common"),
        label=_("Cache timeout medium"),
        unit="seconds",
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="common.cache_timeout_short",
        data_type="integer",
        default=60,
        group="advanced",
        section=_("Common"),
        label=_("Cache timeout short"),
        unit="seconds",
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="common.cache_timeout_very_long",
        data_type="integer",
        default=86400,
        group="advanced",
        section=_("Common"),
        label=_("Cache timeout very long"),
        unit="seconds",
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="common.default_orphans",
        data_type="integer",
        default=3,
        group="advanced",
        section=_("Common"),
        label=_("Default orphans"),
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="common.max_header_json_length",
        data_type="integer",
        default=1000,
        group="advanced",
        section=_("Common"),
        label=_("Max header json length"),
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="common.max_summarized_args",
        data_type="integer",
        default=3,
        group="advanced",
        section=_("Common"),
        label=_("Max summarized args"),
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="common.proximity_line_threshold",
        data_type="integer",
        default=5,
        group="advanced",
        section=_("Common"),
        label=_("Proximity line threshold"),
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="common.query_warning_threshold",
        data_type="integer",
        default=10,
        group="advanced",
        section=_("Common"),
        label=_("Query warning threshold"),
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="common.sql_display_limit",
        data_type="integer",
        default=200,
        group="advanced",
        section=_("Common"),
        label=_("SQL display limit"),
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="common.value_summary_limit",
        data_type="integer",
        default=50,
        group="advanced",
        section=_("Common"),
        label=_("Value summary limit"),
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="company.address",
        data_type="string",
        default="",
        group="company",
        section=_("Identity"),
        label=_("Address"),
        help_text=_("Registered office address for legal documents"),
    ),
    SettingDef(
        key="company.email_contact",
        data_type="string",
        default="contact@pragmatichost.com",
        group="company",
        section=_("Email addresses"),
        label=_("Contact email"),
        help_text=_("Public-facing contact shown on website footer."),
    ),
    SettingDef(
        key="company.email_dpo",
        data_type="string",
        default="dpo@pragmatichost.com",
        group="company",
        section=_("Email addresses"),
        label=_("DPO email"),
        help_text=_("Data Protection Officer contact for GDPR compliance."),
    ),
    SettingDef(
        key="company.email_noreply",
        data_type="string",
        default="noreply@pragmatichost.com",
        group="company",
        section=_("Email addresses"),
        label=_("No-reply email"),
        help_text=_("Sender address for automated system emails."),
    ),
    SettingDef(
        key="company.email_privacy",
        data_type="string",
        default="privacy@pragmatichost.com",
        group="company",
        section=_("Email addresses"),
        label=_("Privacy email"),
        help_text=_("Shown on privacy policy page for GDPR inquiries."),
    ),
    SettingDef(
        key="company.email_support",
        data_type="string",
        default="support@pragmatichost.com",
        group="company",
        section=_("Email addresses"),
        label=_("Support email"),
        help_text=_("Used in support-related email templates."),
    ),
    SettingDef(
        key="company.legal_name",
        data_type="string",
        default="PragmaticHost SRL",
        group="company",
        section=_("Identity"),
        label=_("Legal name"),
        help_text=_("Appears on invoices, contracts, and legal pages."),
    ),
    SettingDef(
        key="company.phone",
        data_type="string",
        default="",
        group="company",
        section=_("Identity"),
        label=_("Phone"),
        help_text=_("Company phone number for customer support"),
    ),
    SettingDef(
        key="company.registration_number",
        data_type="string",
        default="",
        group="company",
        section=_("Identity"),
        label=_("Registration number"),
        help_text=_("Company registration number (CUI/J-number)"),
    ),
    SettingDef(
        key="customers.base_credit_score",
        data_type="integer",
        default=750,
        group="customers",
        section=_("Credit scoring"),
        label=_("Base credit score"),
        input_kind="number",
        validation={"min": 0},
    ),
    SettingDef(
        key="customers.credit_adjustments",
        data_type="json",
        default={
            "positive_payment": 15,
            "early_payment": 25,
            "failed_payment": -50,
            "late_payment": -30,
            "chargeback": -100,
            "refund_issued": -10,
            "account_age_bonus": 5,
            "order_completed": 5,
        },
        group="customers",
        section=_("Credit scoring"),
        label=_("Credit adjustments"),
        help_text=_("Integer score points applied for each credit event."),
        input_kind="json",
        validation={"mapping_value_type": "integer"},
    ),
    SettingDef(
        key="customers.engagement_activity_weight",
        data_type="integer",
        default=30,
        group="customers",
        section=_("Engagement scoring"),
        label=_("Engagement activity weight"),
        input_kind="number",
        validation={"min": 0, "max": 100},
    ),
    SettingDef(
        key="customers.engagement_order_weight",
        data_type="integer",
        default=40,
        group="customers",
        section=_("Engagement scoring"),
        label=_("Engagement order weight"),
        input_kind="number",
        validation={"min": 0, "max": 100},
    ),
    SettingDef(
        key="customers.engagement_recency_weight",
        data_type="integer",
        default=30,
        group="customers",
        section=_("Engagement scoring"),
        label=_("Engagement recency weight"),
        input_kind="number",
        validation={"min": 0, "max": 100},
    ),
    SettingDef(
        key="customers.orders_high_threshold",
        data_type="integer",
        default=10,
        group="advanced",
        section=_("Customers"),
        label=_("Orders high threshold"),
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="customers.orders_low_threshold",
        data_type="integer",
        default=2,
        group="advanced",
        section=_("Customers"),
        label=_("Orders low threshold"),
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="customers.orders_medium_threshold",
        data_type="integer",
        default=5,
        group="advanced",
        section=_("Customers"),
        label=_("Orders medium threshold"),
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="customers.payment_rate_excellent",
        data_type="integer",
        default=95,
        group="advanced",
        section=_("Customers"),
        label=_("Payment rate excellent"),
        input_kind="number",
        advanced=True,
        validation={"min": 0, "max": 100},
    ),
    SettingDef(
        key="customers.payment_rate_fair",
        data_type="integer",
        default=60,
        group="advanced",
        section=_("Customers"),
        label=_("Payment rate fair"),
        input_kind="number",
        advanced=True,
        validation={"min": 0, "max": 100},
    ),
    SettingDef(
        key="customers.payment_rate_good",
        data_type="integer",
        default=80,
        group="advanced",
        section=_("Customers"),
        label=_("Payment rate good"),
        input_kind="number",
        advanced=True,
        validation={"min": 0, "max": 100},
    ),
    SettingDef(
        key="customers.services_high_threshold",
        data_type="integer",
        default=3,
        group="advanced",
        section=_("Customers"),
        label=_("Services high threshold"),
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="customers.services_medium_threshold",
        data_type="integer",
        default=2,
        group="advanced",
        section=_("Customers"),
        label=_("Services medium threshold"),
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="customers.task_soft_time_limit",
        data_type="integer",
        default=300,
        group="advanced",
        section=_("Customers"),
        label=_("Task soft time limit"),
        unit="seconds",
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="customers.task_time_limit",
        data_type="integer",
        default=600,
        group="advanced",
        section=_("Customers"),
        label=_("Task time limit"),
        unit="seconds",
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="domains.expiry_critical_days",
        data_type="integer",
        default=7,
        group="domains",
        section=_("Expiry notices"),
        label=_("Expiry critical"),
        help_text=_("Triggers urgent renewal notifications."),
        unit="days",
        input_kind="number",
        validation={"min": 0},
    ),
    SettingDef(
        key="domains.expiry_warning_days",
        data_type="integer",
        default=30,
        group="domains",
        section=_("Expiry notices"),
        label=_("Expiry warning"),
        help_text=_("Triggers standard renewal reminder emails."),
        unit="days",
        input_kind="number",
        validation={"min": 0},
    ),
    SettingDef(
        key="domains.whois_privacy_price_cents",
        data_type="integer",
        default=500,
        group="domains",
        section=_("Pricing"),
        label=_("Whois privacy price"),
        help_text=_("Annual fee for WHOIS privacy protection service."),
        unit="cents",
        input_kind="number",
        validation={"min": 0},
    ),
    SettingDef(
        key="efactura.company.bank_account",
        data_type="string",
        default="",
        group="efactura",
        section=_("Company profile"),
        label=_("Bank account"),
    ),
    SettingDef(
        key="efactura.company.bank_name",
        data_type="string",
        default="",
        group="efactura",
        section=_("Company profile"),
        label=_("Bank name"),
    ),
    SettingDef(
        key="efactura.company.city",
        data_type="string",
        default="",
        group="efactura",
        section=_("Company profile"),
        label=_("City"),
    ),
    SettingDef(
        key="efactura.company.country_code",
        data_type="string",
        default="RO",
        group="efactura",
        section=_("Company profile"),
        label=_("Country code"),
    ),
    SettingDef(
        key="efactura.company.cui",
        data_type="string",
        default="",
        group="efactura",
        section=_("Company profile"),
        label=_("Company CUI"),
    ),
    SettingDef(
        key="efactura.company.email",
        data_type="string",
        default="",
        group="efactura",
        section=_("Company profile"),
        label=_("Email"),
    ),
    SettingDef(
        key="efactura.company.name",
        data_type="string",
        default="",
        group="efactura",
        section=_("Company profile"),
        label=_("Name"),
    ),
    SettingDef(
        key="efactura.company.phone",
        data_type="string",
        default="",
        group="efactura",
        section=_("Company profile"),
        label=_("Phone"),
    ),
    SettingDef(
        key="efactura.company.postal_code",
        data_type="string",
        default="",
        group="efactura",
        section=_("Company profile"),
        label=_("Postal code"),
    ),
    SettingDef(
        key="efactura.company.registration_number",
        data_type="string",
        default="",
        group="efactura",
        section=_("Company profile"),
        label=_("Registration number"),
    ),
    SettingDef(
        key="efactura.company.street",
        data_type="string",
        default="",
        group="efactura",
        section=_("Company profile"),
        label=_("Street"),
    ),
    SettingDef(
        key="efactura.enabled",
        data_type="boolean",
        default=True,
        group="efactura",
        section=_("General"),
        label=_("Enabled"),
        input_kind="toggle",
    ),
    SettingDef(
        key="efactura.environment",
        data_type="string",
        default="test",
        group="efactura",
        section=_("General"),
        label=_("Environment"),
        input_kind="select",
        validation={"choices": ["test", "production"]},
    ),
    SettingDef(
        key="efactura.metrics.enabled",
        data_type="boolean",
        default=True,
        group="efactura",
        section=_("Metrics"),
        label=_("Enabled"),
        input_kind="toggle",
    ),
    SettingDef(
        key="efactura.metrics.prefix",
        data_type="string",
        default="efactura",
        group="efactura",
        section=_("Metrics"),
        label=_("Prefix"),
    ),
    SettingDef(
        key="efactura.oauth.client_id",
        data_type="string",
        default="",
        group="efactura",
        section=_("OAuth"),
        label=_("OAuth client ID"),
    ),
    SettingDef(
        key="efactura.oauth.client_secret",
        data_type="string",
        default="",
        group="efactura",
        section=_("OAuth"),
        label=_("OAuth client secret"),
        input_kind="secret",
        sensitive=True,
    ),
    SettingDef(
        key="efactura.oauth.redirect_uri",
        data_type="string",
        default="",
        group="efactura",
        section=_("OAuth"),
        label=_("OAuth redirect URI"),
    ),
    SettingDef(
        key="efactura.polling.batch_size",
        data_type="integer",
        default=100,
        group="efactura",
        section=_("Polling"),
        label=_("Batch size"),
        input_kind="number",
        validation={"min": 0},
    ),
    SettingDef(
        key="efactura.polling.interval_seconds",
        data_type="integer",
        default=300,
        group="efactura",
        section=_("Polling"),
        label=_("Interval"),
        unit="seconds",
        input_kind="number",
        validation={"min": 0},
    ),
    SettingDef(
        key="efactura.polling.stale_submission_hours",
        data_type="integer",
        default=24,
        group="efactura",
        section=_("Polling"),
        label=_("Stale submission"),
        unit="hours",
        input_kind="number",
        validation={"min": 0},
    ),
    SettingDef(
        key="efactura.rate_limit.download_per_message_day",
        data_type="integer",
        default=10,
        group="efactura",
        section=_("Rate limits"),
        label=_("Downloads per message per day"),
        input_kind="number",
        validation={"min": 0},
    ),
    SettingDef(
        key="efactura.rate_limit.global_per_minute",
        data_type="integer",
        default=1000,
        group="efactura",
        section=_("Rate limits"),
        label=_("Global per minute"),
        input_kind="number",
        validation={"min": 0},
    ),
    SettingDef(
        key="efactura.rate_limit.list_paginated_per_day",
        data_type="integer",
        default=100000,
        group="efactura",
        section=_("Rate limits"),
        label=_("List paginated per day"),
        input_kind="number",
        validation={"min": 0},
    ),
    SettingDef(
        key="efactura.rate_limit.list_simple_per_day",
        data_type="integer",
        default=1500,
        group="efactura",
        section=_("Rate limits"),
        label=_("List simple per day"),
        input_kind="number",
        validation={"min": 0},
    ),
    SettingDef(
        key="efactura.rate_limit.status_per_message_day",
        data_type="integer",
        default=100,
        group="efactura",
        section=_("Rate limits"),
        label=_("Status per message day"),
        input_kind="number",
        validation={"min": 0},
    ),
    SettingDef(
        key="efactura.retry.delay_1_seconds",
        data_type="integer",
        default=300,
        group="efactura",
        section=_("Retry policy"),
        label=_("Retry 1 delay"),
        unit="seconds",
        input_kind="number",
        validation={"min": 0},
    ),
    SettingDef(
        key="efactura.retry.delay_2_seconds",
        data_type="integer",
        default=900,
        group="efactura",
        section=_("Retry policy"),
        label=_("Retry 2 delay"),
        unit="seconds",
        input_kind="number",
        validation={"min": 0},
    ),
    SettingDef(
        key="efactura.retry.delay_3_seconds",
        data_type="integer",
        default=3600,
        group="efactura",
        section=_("Retry policy"),
        label=_("Retry 3 delay"),
        unit="seconds",
        input_kind="number",
        validation={"min": 0},
    ),
    SettingDef(
        key="efactura.retry.delay_4_seconds",
        data_type="integer",
        default=7200,
        group="efactura",
        section=_("Retry policy"),
        label=_("Retry 4 delay"),
        unit="seconds",
        input_kind="number",
        validation={"min": 0},
    ),
    SettingDef(
        key="efactura.retry.delay_5_seconds",
        data_type="integer",
        default=21600,
        group="efactura",
        section=_("Retry policy"),
        label=_("Retry 5 delay"),
        unit="seconds",
        input_kind="number",
        validation={"min": 0},
    ),
    SettingDef(
        key="efactura.retry.max_retries",
        data_type="integer",
        default=5,
        group="efactura",
        section=_("Retry policy"),
        label=_("Max retries"),
        input_kind="number",
        validation={"min": 0},
    ),
    SettingDef(
        key="efactura.storage.archive_retention_years",
        data_type="integer",
        default=10,
        group="efactura",
        section=_("Storage"),
        label=_("Archive retention years"),
        input_kind="number",
        validation={"min": 0},
    ),
    SettingDef(
        key="efactura.storage.pdf_path",
        data_type="string",
        default="efactura/pdf/%Y/%m/",
        group="efactura",
        section=_("Storage"),
        label=_("PDF path"),
    ),
    SettingDef(
        key="efactura.storage.xml_path",
        data_type="string",
        default="efactura/xml/%Y/%m/",
        group="efactura",
        section=_("Storage"),
        label=_("XML path"),
    ),
    SettingDef(
        key="efactura.submission.auto_submit_enabled",
        data_type="boolean",
        default=True,
        group="efactura",
        section=_("Submission"),
        label=_("Auto submit enabled"),
        input_kind="toggle",
    ),
    SettingDef(
        key="efactura.submission.deadline_days",
        data_type="integer",
        default=5,
        group="efactura",
        section=_("Submission"),
        label=_("Deadline"),
        unit="days",
        input_kind="number",
        validation={"min": 0},
    ),
    SettingDef(
        key="efactura.submission.deadline_warning_hours",
        data_type="integer",
        default=24,
        group="efactura",
        section=_("Submission"),
        label=_("Deadline warning"),
        unit="hours",
        input_kind="number",
        validation={"min": 0},
    ),
    SettingDef(
        key="efactura.validation.schematron_enabled",
        data_type="boolean",
        default=True,
        group="efactura",
        section=_("Validation"),
        label=_("Schematron enabled"),
        input_kind="toggle",
    ),
    SettingDef(
        key="efactura.validation.strict_mode",
        data_type="boolean",
        default=False,
        group="efactura",
        section=_("Validation"),
        label=_("Strict mode"),
        input_kind="toggle",
    ),
    SettingDef(
        key="efactura.validation.xsd_enabled",
        data_type="boolean",
        default=True,
        group="efactura",
        section=_("Validation"),
        label=_("XSD enabled"),
        input_kind="toggle",
    ),
    SettingDef(
        key="efactura.vat.rate_reduced_1",
        data_type="decimal",
        default="11.00",
        group="efactura",
        section=_("VAT rates"),
        label=_("Rate reduced 1"),
        help_text=_("First reduced VAT rate (11% since Aug 2025)."),
        input_kind="number",
    ),
    SettingDef(
        key="efactura.vat.rate_reduced_2",
        data_type="decimal",
        default="11.00",
        group="efactura",
        section=_("VAT rates"),
        label=_("Rate reduced 2"),
        help_text=_("Second reduced VAT rate (currently equal to the first after consolidation)."),
        input_kind="number",
    ),
    SettingDef(
        key="efactura.vat.rate_standard",
        data_type="decimal",
        default="21.00",
        group="efactura",
        section=_("VAT rates"),
        label=_("Rate standard"),
        input_kind="number",
    ),
    SettingDef(
        key="efactura.vat.rate_zero",
        data_type="decimal",
        default="0.00",
        group="efactura",
        section=_("VAT rates"),
        label=_("Rate zero"),
        input_kind="number",
    ),
    SettingDef(
        key="gdpr.failed_login_retention_months",
        data_type="integer",
        default=6,
        group="advanced",
        section=_("GDPR"),
        label=_("Failed login retention months"),
        help_text=_("Security data retention for failed login attempts."),
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="infrastructure.consecutive_failure_threshold",
        data_type="integer",
        default=3,
        group="advanced",
        section=_("Infrastructure"),
        label=_("Consecutive failure threshold"),
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="infrastructure.do_action_timeout_seconds",
        data_type="integer",
        default=300,
        group="advanced",
        section=_("Infrastructure"),
        label=_("DigitalOcean action timeout"),
        unit="seconds",
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="infrastructure.health_check_timeout_seconds",
        data_type="integer",
        default=10,
        group="advanced",
        section=_("Infrastructure"),
        label=_("Health check timeout"),
        unit="seconds",
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="infrastructure.network_probe_timeout_seconds",
        data_type="integer",
        default=10,
        group="advanced",
        section=_("Infrastructure"),
        label=_("Network probe timeout"),
        unit="seconds",
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="infrastructure.remediation_boot_grace_seconds",
        data_type="integer",
        default=30,
        group="advanced",
        section=_("Infrastructure"),
        label=_("Remediation boot grace"),
        unit="seconds",
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="infrastructure.remediation_stale_after_minutes",
        data_type="integer",
        default=30,
        group="advanced",
        section=_("Infrastructure"),
        label=_("Remediation stale after"),
        unit="minutes",
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="infrastructure.remediation_verify_max_wait_seconds",
        data_type="integer",
        default=150,
        group="advanced",
        section=_("Infrastructure"),
        label=_("Remediation verify max wait"),
        unit="seconds",
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="infrastructure.remediation_verify_poll_interval_seconds",
        data_type="integer",
        default=10,
        group="advanced",
        section=_("Infrastructure"),
        label=_("Remediation verify poll interval"),
        unit="seconds",
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="infrastructure.vultr_poll_timeout_seconds",
        data_type="integer",
        default=300,
        group="advanced",
        section=_("Infrastructure"),
        label=_("Vultr poll timeout"),
        unit="seconds",
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="integrations.stripe_enabled",
        data_type="boolean",
        default=False,
        group="stripe",
        section=_("Credentials"),
        label=_("Stripe enabled"),
        input_kind="toggle",
    ),
    SettingDef(
        key="integrations.stripe_publishable_key",
        data_type="string",
        default="",
        group="stripe",
        section=_("Credentials"),
        label=_("Publishable key"),
    ),
    SettingDef(
        key="integrations.stripe_secret_key",
        data_type="string",
        default="",
        group="stripe",
        section=_("Credentials"),
        label=_("Secret key"),
        input_kind="secret",
        sensitive=True,
    ),
    SettingDef(
        key="integrations.stripe_webhook_secret",
        data_type="string",
        default="",
        group="stripe",
        section=_("Credentials"),
        label=_("Webhook signing secret"),
        input_kind="secret",
        sensitive=True,
    ),
    SettingDef(
        key="node_deployment.backup_enabled",
        data_type="boolean",
        default=True,
        group="node-deployment",
        section=_("Backups"),
        label=_("Backup enabled"),
        help_text=_("Recommended. Configures daily Virtualmin backups on new nodes."),
        input_kind="toggle",
    ),
    SettingDef(
        key="node_deployment.backup_retention_days",
        data_type="integer",
        default=7,
        group="node-deployment",
        section=_("Backups"),
        label=_("Backup retention"),
        help_text=_("Older backups are automatically deleted."),
        unit="days",
        input_kind="number",
        validation={"min": 0},
    ),
    SettingDef(
        key="node_deployment.backup_s3_bucket",
        data_type="string",
        default="",
        group="node-deployment",
        section=_("Backups"),
        label=_("Backup S3 bucket"),
        help_text=_("S3 bucket for backups (when using S3 storage)"),
    ),
    SettingDef(
        key="node_deployment.backup_s3_prefix",
        data_type="string",
        default="backups/",
        group="node-deployment",
        section=_("Backups"),
        label=_("Backup S3 key prefix"),
    ),
    SettingDef(
        key="node_deployment.backup_s3_region",
        data_type="string",
        default="eu-central-1",
        group="node-deployment",
        section=_("Backups"),
        label=_("Backup S3 region"),
    ),
    SettingDef(
        key="node_deployment.backup_schedule",
        data_type="string",
        default="0 2 * * *",
        group="node-deployment",
        section=_("Backups"),
        label=_("Backup schedule"),
        help_text=_("Cron format. Default: 0 2 * * * (daily at 2 AM)."),
    ),
    SettingDef(
        key="node_deployment.backup_storage",
        data_type="string",
        default="local",
        group="node-deployment",
        section=_("Backups"),
        label=_("Backup storage"),
        help_text=_("Local: disk on node. S3: external (requires S3 bucket configuration)."),
        input_kind="select",
        validation={"choices": ["local", "s3"]},
    ),
    SettingDef(
        key="node_deployment.dns_cloudflare_api_token",
        data_type="string",
        default="",
        group="node-deployment",
        section=_("DNS (Cloudflare)"),
        label=_("Cloudflare API token"),
        help_text=_("API token with Zone:DNS:Edit permissions."),
        input_kind="secret",
        sensitive=True,
    ),
    SettingDef(
        key="node_deployment.dns_cloudflare_zone_id",
        data_type="string",
        default="",
        group="node-deployment",
        section=_("DNS (Cloudflare)"),
        label=_("Cloudflare zone ID"),
        help_text=_("Find in Cloudflare dashboard under zone overview."),
    ),
    SettingDef(
        key="node_deployment.dns_default_zone",
        data_type="string",
        default="",
        group="node-deployment",
        section=_("DNS (Cloudflare)"),
        label=_("DNS default zone"),
        help_text=_("Nodes will be created as {hostname}.{zone}. Use infra.example.com pattern."),
    ),
    SettingDef(
        key="node_deployment.enabled",
        data_type="boolean",
        default=True,
        group="node-deployment",
        section=_("General"),
        label=_("Enabled"),
        help_text=_("Disable to prevent any new node deployments."),
        input_kind="toggle",
    ),
    SettingDef(
        key="node_deployment.terraform_s3_bucket",
        data_type="string",
        default="",
        group="node-deployment",
        section=_("Terraform state"),
        label=_("Terraform S3 bucket"),
        help_text=_("Required when using S3 backend. Must be pre-created."),
    ),
    SettingDef(
        key="node_deployment.terraform_s3_key_prefix",
        data_type="string",
        default="praho/nodes/",
        group="node-deployment",
        section=_("Terraform state"),
        label=_("Terraform S3 key prefix"),
        help_text=_("Path prefix for organizing state files in S3."),
    ),
    SettingDef(
        key="node_deployment.terraform_s3_region",
        data_type="string",
        default="eu-west-1",
        group="node-deployment",
        section=_("Terraform state"),
        label=_("Terraform S3 region"),
        help_text=_("e.g., eu-west-1. Required when using S3 backend."),
    ),
    SettingDef(
        key="node_deployment.terraform_state_backend",
        data_type="string",
        default="local",
        group="node-deployment",
        section=_("Terraform state"),
        label=_("Terraform state backend"),
        help_text=_("Use 'local' for development, 's3' for production with shared state."),
        input_kind="select",
        validation={"choices": ["local", "s3"]},
    ),
    SettingDef(
        key="notifications.email_batch_size",
        data_type="integer",
        default=50,
        group="advanced",
        section=_("Notifications"),
        label=_("Email batch size"),
        help_text=_("Number of emails to process per batch"),
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="notifications.email_max_retries",
        data_type="integer",
        default=3,
        group="advanced",
        section=_("Notifications"),
        label=_("Email max retries"),
        help_text=_("Retries before marking email delivery as failed."),
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="notifications.max_name_length",
        data_type="integer",
        default=100,
        group="advanced",
        section=_("Notifications"),
        label=_("Max name length"),
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="notifications.max_recipients_per_batch",
        data_type="integer",
        default=50,
        group="advanced",
        section=_("Notifications"),
        label=_("Max recipients per batch"),
        help_text=_("Split large sends into batches of this size."),
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="notifications.max_subject_length",
        data_type="integer",
        default=200,
        group="advanced",
        section=_("Notifications"),
        label=_("Max subject length"),
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="notifications.max_template_size",
        data_type="integer",
        default=102400,
        group="advanced",
        section=_("Notifications"),
        label=_("Max template size"),
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="orders.bank_transfer_timeout_hours",
        data_type="integer",
        default=72,
        group="orders",
        section=_("Payment timeouts"),
        label=_("Bank transfer timeout"),
        unit="hours",
        input_kind="number",
        validation={"min": 0},
    ),
    SettingDef(
        key="orders.card_timeout_hours",
        data_type="integer",
        default=24,
        group="orders",
        section=_("Payment timeouts"),
        label=_("Card timeout"),
        unit="hours",
        input_kind="number",
        validation={"min": 0},
    ),
    SettingDef(
        key="orders.max_payment_failures_before_fail",
        data_type="integer",
        default=3,
        group="orders",
        section=_("Payment timeouts"),
        label=_("Max payment failures before order fails"),
        input_kind="number",
        validation={"min": 0},
    ),
    SettingDef(
        key="orders.max_price_override_cents",
        data_type="integer",
        default=50000000,
        group="orders",
        section=_("Price overrides"),
        label=_("Max price override"),
        unit="cents",
        input_kind="number",
        validation={"min": 0},
    ),
    SettingDef(
        key="orders.max_price_override_multiplier",
        data_type="integer",
        default=10,
        group="orders",
        section=_("Price overrides"),
        label=_("Max price override multiplier"),
        input_kind="number",
        validation={"min": 0},
    ),
    SettingDef(
        key="orders.max_search_query_length",
        data_type="integer",
        default=200,
        group="advanced",
        section=_("Orders"),
        label=_("Max search query length"),
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="orders.review_threshold_cents",
        data_type="integer",
        default=500000,
        group="orders",
        section=_("Review policy"),
        label=_("Review threshold"),
        unit="cents",
        input_kind="number",
        validation={"min": 0},
    ),
    SettingDef(
        key="orders.task_soft_time_limit",
        data_type="integer",
        default=600,
        group="advanced",
        section=_("Orders"),
        label=_("Task soft time limit"),
        unit="seconds",
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="orders.task_time_limit",
        data_type="integer",
        default=900,
        group="advanced",
        section=_("Orders"),
        label=_("Task time limit"),
        unit="seconds",
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="products.max_json_content_size",
        data_type="integer",
        default=102400,
        group="advanced",
        section=_("Products"),
        label=_("Max json content size"),
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="products.max_price_cents",
        data_type="integer",
        default=10000000000,
        group="advanced",
        section=_("Products"),
        label=_("Max price"),
        unit="cents",
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="promotions.max_code_generation_attempts",
        data_type="integer",
        default=100,
        group="advanced",
        section=_("Promotions"),
        label=_("Max code generation attempts"),
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="promotions.max_coupon_batch_size",
        data_type="integer",
        default=1000,
        group="advanced",
        section=_("Promotions"),
        label=_("Max coupon batch size"),
        help_text=_("Maximum coupons generated in one operation."),
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="promotions.max_discount_amount_cents",
        data_type="integer",
        default=100000000,
        group="advanced",
        section=_("Promotions"),
        label=_("Max discount amount"),
        help_text=_("Cap on absolute discount amounts."),
        unit="cents",
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="promotions.max_discount_percent",
        data_type="integer",
        default=100,
        group="advanced",
        section=_("Promotions"),
        label=_("Max discount percent"),
        help_text=_("Cap on percentage-based discounts."),
        unit="%",
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="provisioning.backup_retention_days",
        data_type="integer",
        default=90,
        group="advanced",
        section=_("Provisioning"),
        label=_("Backup retention"),
        help_text=_("Days to retain provisioning backups"),
        unit="days",
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="provisioning.bulk_operation_threshold",
        data_type="integer",
        default=10,
        group="advanced",
        section=_("Provisioning"),
        label=_("Bulk operation threshold"),
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="provisioning.cache_timeout",
        data_type="integer",
        default=3600,
        group="advanced",
        section=_("Provisioning"),
        label=_("Cache timeout"),
        unit="seconds",
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="provisioning.health_check_timeout_seconds",
        data_type="integer",
        default=10,
        group="advanced",
        section=_("Provisioning"),
        label=_("Health check timeout"),
        unit="seconds",
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="provisioning.high_value_plan_threshold_cents",
        data_type="integer",
        default=50000,
        group="advanced",
        section=_("Provisioning"),
        label=_("High value plan threshold"),
        help_text=_("Plans above this price get priority support."),
        unit="cents",
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="provisioning.long_provisioning_threshold_minutes",
        data_type="integer",
        default=30,
        group="advanced",
        section=_("Provisioning"),
        label=_("Long provisioning threshold"),
        help_text=_("Minutes before provisioning is considered slow"),
        unit="minutes",
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="provisioning.max_backup_size_gb",
        data_type="integer",
        default=50,
        group="advanced",
        section=_("Provisioning"),
        label=_("Max backup size"),
        help_text=_("Maximum backup size per account in GB"),
        unit="GB",
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="provisioning.max_concurrent_health_checks",
        data_type="integer",
        default=5,
        group="advanced",
        section=_("Provisioning"),
        label=_("Max concurrent health checks"),
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="provisioning.max_error_display",
        data_type="integer",
        default=10,
        group="advanced",
        section=_("Provisioning"),
        label=_("Max error display"),
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="provisioning.max_username_uniqueness_attempts",
        data_type="integer",
        default=10,
        group="advanced",
        section=_("Provisioning"),
        label=_("Max username uniqueness attempts"),
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="provisioning.overall_health_check_timeout",
        data_type="integer",
        default=30,
        group="advanced",
        section=_("Provisioning"),
        label=_("Overall health check timeout"),
        unit="seconds",
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="provisioning.recovery_excellent_threshold",
        data_type="integer",
        default=95,
        group="advanced",
        section=_("Provisioning"),
        label=_("Recovery excellent threshold"),
        help_text=_("Recovery rate above this = excellent health."),
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="provisioning.recovery_good_threshold",
        data_type="integer",
        default=90,
        group="advanced",
        section=_("Provisioning"),
        label=_("Recovery good threshold"),
        help_text=_("Recovery rate above this = good health."),
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="provisioning.recovery_warning_threshold",
        data_type="integer",
        default=80,
        group="advanced",
        section=_("Provisioning"),
        label=_("Recovery warning threshold"),
        help_text=_("Recovery rate below this = warning status."),
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="provisioning.resource_usage_alert_threshold",
        data_type="integer",
        default=85,
        group="advanced",
        section=_("Provisioning"),
        label=_("Resource usage alert threshold"),
        help_text=_("Percentage of quota before alerting customer."),
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="provisioning.server_overload_threshold",
        data_type="integer",
        default=90,
        group="advanced",
        section=_("Provisioning"),
        label=_("Server overload threshold"),
        help_text=_("Server load percentage triggering admin alerts."),
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="provisioning.ssh_timeout",
        data_type="integer",
        default=30,
        group="advanced",
        section=_("Provisioning"),
        label=_("SSH timeout"),
        unit="seconds",
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="provisioning.sudo_command_timeout",
        data_type="integer",
        default=60,
        group="advanced",
        section=_("Provisioning"),
        label=_("Sudo command timeout"),
        unit="seconds",
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="provisioning.task_soft_time_limit",
        data_type="integer",
        default=600,
        group="advanced",
        section=_("Provisioning"),
        label=_("Task soft time limit"),
        unit="seconds",
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="provisioning.task_time_limit",
        data_type="integer",
        default=1200,
        group="advanced",
        section=_("Provisioning"),
        label=_("Task time limit"),
        unit="seconds",
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="security.company_check_rate_limit_per_ip",
        data_type="integer",
        default=30,
        group="advanced",
        section=_("Security"),
        label=_("Company check rate limit per ip"),
        help_text=_("Maximum company checks per IP per hour"),
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="security.invitation_rate_limit_per_user",
        data_type="integer",
        default=10,
        group="advanced",
        section=_("Security"),
        label=_("Invitation rate limit per user"),
        help_text=_("Maximum invitations per user per hour"),
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="security.max_customer_lookups_per_hour",
        data_type="integer",
        default=20,
        group="advanced",
        section=_("Security"),
        label=_("Max customer lookups per hour"),
        help_text=_("Maximum customer lookups per user per hour"),
        unit="per hour",
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="security.max_session_age_seconds",
        data_type="integer",
        default=86400,
        group="advanced",
        section=_("Security"),
        label=_("Max session age"),
        unit="seconds",
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="security.registration_rate_limit_per_ip",
        data_type="integer",
        default=5,
        group="advanced",
        section=_("Security"),
        label=_("Registration rate limit per ip"),
        help_text=_("Maximum registrations per IP per hour"),
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="security.suspicious_ip_threshold",
        data_type="integer",
        default=3,
        group="advanced",
        section=_("Security"),
        label=_("Suspicious ip threshold"),
        help_text=_("Failed requests before IP is flagged for review."),
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="security.welcome_invite_limit_per_user_per_hour",
        data_type="integer",
        default=3,
        group="advanced",
        section=_("Security"),
        label=_("Welcome invite limit per user per hour"),
        unit="per hour",
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="system.maintenance_mode",
        data_type="boolean",
        default=False,
        group="platform",
        section=_("Availability"),
        label=_("Maintenance mode"),
        help_text=_("When enabled, only staff users can access the system."),
        input_kind="toggle",
        critical=True,
    ),
    SettingDef(
        key="tickets.allowed_file_extensions",
        data_type="list",
        default=[".pdf", ".txt", ".png", ".jpg", ".jpeg", ".doc", ".docx"],
        group="support",
        section=_("Attachments"),
        label=_("Allowed file extensions"),
        help_text=_("Permitted upload file extensions, including the dot (e.g. .pdf)."),
        input_kind="chips",
    ),
    SettingDef(
        key="tickets.max_file_size_bytes",
        data_type="integer",
        default=2097152,
        group="support",
        section=_("Attachments"),
        label=_("Max file size"),
        help_text=_("Maximum upload size in bytes. Default: 2MB (2097152)."),
        unit="bytes",
        input_kind="number",
        validation={"min": 0},
    ),
    SettingDef(
        key="tickets.security_alert_threshold",
        data_type="integer",
        default=5,
        group="advanced",
        section=_("Tickets"),
        label=_("Security alert threshold"),
        help_text=_("Number of suspicious events before alerting security team."),
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="users.admin_session_timeout_minutes",
        data_type="integer",
        default=30,
        group="security",
        section=_("Sessions"),
        label=_("Admin session timeout"),
        help_text=_("Shorter than regular sessions for security."),
        unit="minutes",
        input_kind="number",
        validation={"min": 0},
    ),
    SettingDef(
        key="users.credential_max_age_days",
        data_type="integer",
        default=90,
        group="advanced",
        section=_("Users"),
        label=_("Credential max age"),
        help_text=_("Credentials older than this trigger rotation warnings."),
        unit="days",
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="users.credential_rotation_retry_limit",
        data_type="integer",
        default=3,
        group="advanced",
        section=_("Users"),
        label=_("Credential rotation retry limit"),
        help_text=_("Maximum retries for credential rotation"),
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="users.security_lockout_failure_threshold",
        data_type="integer",
        default=5,
        group="advanced",
        section=_("Users"),
        label=_("Security lockout failure threshold"),
        help_text=_("Failed attempts before security lockout"),
        input_kind="number",
        advanced=True,
        validation={"min": 0},
    ),
    SettingDef(
        key="users.shared_device_timeout_minutes",
        data_type="integer",
        default=15,
        group="security",
        section=_("Sessions"),
        label=_("Shared device timeout"),
        unit="minutes",
        input_kind="number",
        validation={"min": 0},
    ),
    SettingDef(
        key="virtualmin.auth_fallback_enabled",
        data_type="boolean",
        default=True,
        group="virtualmin",
        section=_("Connection"),
        label=_("Auth fallback enabled"),
        input_kind="toggle",
    ),
    SettingDef(
        key="virtualmin.auth_health_check_interval_seconds",
        data_type="integer",
        default=3600,
        group="virtualmin",
        section=_("Connection"),
        label=_("Auth health check interval"),
        unit="seconds",
        input_kind="number",
        validation={"min": 0},
    ),
    SettingDef(
        key="virtualmin.backup_compression_enabled",
        data_type="boolean",
        default=True,
        group="virtualmin",
        section=_("Backups"),
        label=_("Backup compression enabled"),
        input_kind="toggle",
    ),
    SettingDef(
        key="virtualmin.backup_retention_days",
        data_type="integer",
        default=7,
        group="virtualmin",
        section=_("Backups"),
        label=_("Backup retention"),
        unit="days",
        input_kind="number",
        validation={"min": 0},
    ),
    SettingDef(
        key="virtualmin.bandwidth_quota_default_mb",
        data_type="integer",
        default=10000,
        group="virtualmin",
        section=_("Quotas"),
        label=_("Bandwidth quota default"),
        unit="MB",
        input_kind="number",
        validation={"min": 0},
    ),
    SettingDef(
        key="virtualmin.connection_pool_size",
        data_type="integer",
        default=10,
        group="virtualmin",
        section=_("Connection"),
        label=_("Connection pool size"),
        input_kind="number",
        validation={"min": 0},
    ),
    SettingDef(
        key="virtualmin.domain_quota_default_mb",
        data_type="integer",
        default=1000,
        group="virtualmin",
        section=_("Quotas"),
        label=_("Domain quota default"),
        unit="MB",
        input_kind="number",
        validation={"min": 0},
    ),
    SettingDef(
        key="virtualmin.hostname",
        data_type="string",
        default="localhost",
        group="virtualmin",
        section=_("Connection"),
        label=_("Hostname"),
    ),
    SettingDef(
        key="virtualmin.log_retention_days",
        data_type="integer",
        default=30,
        group="virtualmin",
        section=_("Hosted services"),
        label=_("Log retention"),
        unit="days",
        input_kind="number",
        validation={"min": 0},
    ),
    SettingDef(
        key="virtualmin.max_retries",
        data_type="integer",
        default=3,
        group="virtualmin",
        section=_("Connection"),
        label=_("Max retries"),
        input_kind="number",
        validation={"min": 0},
    ),
    SettingDef(
        key="virtualmin.monitoring_enabled",
        data_type="boolean",
        default=True,
        group="virtualmin",
        section=_("Hosted services"),
        label=_("Monitoring enabled"),
        input_kind="toggle",
    ),
    SettingDef(
        key="virtualmin.mysql_enabled",
        data_type="boolean",
        default=True,
        group="virtualmin",
        section=_("Hosted services"),
        label=_("MySQL enabled"),
        input_kind="toggle",
    ),
    SettingDef(
        key="virtualmin.php_version_default",
        data_type="string",
        default="8.1",
        group="virtualmin",
        section=_("Hosted services"),
        label=_("PHP version default"),
        input_kind="select",
        validation={"choices": ["8.1", "8.2", "8.3"]},
    ),
    SettingDef(
        key="virtualmin.port",
        data_type="integer",
        default=10000,
        group="virtualmin",
        section=_("Connection"),
        label=_("Port"),
        input_kind="number",
        validation={"min": 0},
    ),
    SettingDef(
        key="virtualmin.postgresql_enabled",
        data_type="boolean",
        default=False,
        group="virtualmin",
        section=_("Hosted services"),
        label=_("PostgreSQL enabled"),
        input_kind="toggle",
    ),
    SettingDef(
        key="virtualmin.rate_limit_max_calls_per_hour",
        data_type="integer",
        default=100,
        group="virtualmin",
        section=_("Rate limits"),
        label=_("Rate limit max calls per hour"),
        unit="per hour",
        input_kind="number",
        validation={"min": 0},
    ),
    SettingDef(
        key="virtualmin.rate_limit_qps",
        data_type="integer",
        default=10,
        group="virtualmin",
        section=_("Rate limits"),
        label=_("Rate limit qps"),
        unit="req/s",
        input_kind="number",
        validation={"min": 0},
    ),
    SettingDef(
        key="virtualmin.request_timeout_seconds",
        data_type="integer",
        default=30,
        group="virtualmin",
        section=_("Connection"),
        label=_("Request timeout"),
        unit="seconds",
        input_kind="number",
        validation={"min": 0},
    ),
    SettingDef(
        key="virtualmin.ssl_auto_renewal_enabled",
        data_type="boolean",
        default=True,
        group="virtualmin",
        section=_("Hosted services"),
        label=_("SSL auto renewal enabled"),
        input_kind="toggle",
    ),
    SettingDef(
        key="virtualmin.ssl_verify",
        data_type="boolean",
        default=True,
        group="virtualmin",
        section=_("Connection"),
        label=_("SSL verify"),
        input_kind="toggle",
    ),
)


CATALOG_BY_KEY: dict[str, SettingDef] = {definition.key: definition for definition in CATALOG}

# Backward-compatible defaults map (SettingsService.DEFAULT_SETTINGS derives from this)
DEFAULTS: dict[str, Any] = {definition.key: definition.default for definition in CATALOG}

SENSITIVE_KEYS: frozenset[str] = frozenset(d.key for d in CATALOG if d.sensitive)
CRITICAL_KEYS: frozenset[str] = frozenset(d.key for d in CATALOG if d.critical)


def defs_for_group(slug: str) -> list[SettingDef]:
    """Catalog entries for one group, in stable key order"""
    return [d for d in CATALOG if d.group == slug]


def groups_in_zone(zone: str) -> list[GroupDef]:
    """Groups belonging to one UI zone, in declaration order"""
    return [g for g in GROUPS if g.zone == zone]


def is_sensitive_key(key: str) -> bool:
    """Catalog-flag sensitivity; unknown keys fall back to name-pattern matching
    so ad-hoc keys with secret-shaped names are still encrypted at rest."""
    definition = CATALOG_BY_KEY.get(key)
    if definition is not None:
        return definition.sensitive
    lowered = key.lower()
    return any(pattern in lowered for pattern in ("password", "secret", "token", "credential"))


def validation_rules_for_key(key: str) -> dict[str, Any]:
    """Catalog-owned validation rules (the model's validation_rules field is retired)"""
    definition = CATALOG_BY_KEY.get(key)
    if definition is None or definition.validation is None:
        return {}
    return definition.validation
