# Generated by Django 5.2.12 on 2026-03-11 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(help_text='Product being ordered', on_delete=django.db.models.deletion.PROTECT, to='products.product'),
        ),
    ]
