# Generated by Django 5.0.14 on 2025-08-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_paymentretrypolicy_taxrule_vatvalidation_and_more"),
        ("customers", "0002_initial"),
        ("orders", "0002_initial"),
        ("products", "0001_initial"),
        (
            "provisioning",
            "0002_servicegroup_servicegroupmember_servicerelationship_and_more",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["status", "payment_method", "-created_at"],
                name="orders_status_39b5a8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["customer", "status"], name="orders_custome_58f6c3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(
                fields=["provisioning_status", "-created_at"],
                name="order_items_provisi_78f4ae_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(
                fields=["product", "provisioning_status"],
                name="order_items_product_40eb77_idx",
            ),
        ),
    ]
