# Generated by Django 5.2.12 on 2026-03-11 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_initial'),
        ('provisioning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='service',
            field=models.ForeignKey(blank=True, help_text='Provisioned service for this order item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='provisioning.service'),
        ),
    ]
