# Generated by Django 5.2.5 on 2025-09-13 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='billing_period',
        ),
    ]
