# Generated by Django 5.2.12 on 2026-03-20 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0021_add_proforma_fk'),
        ('orders', '0005_rename_order_status_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='proforma',
            field=models.ForeignKey(blank=True, help_text='Proforma invoice for this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='billing.proformainvoice'),
        ),
    ]
