# Generated by Django 5.2.11 on 2026-02-15 12:09

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_add_payment_intent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='tax_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Tax rate applied (e.g., 0.2100 for 21%)', max_digits=5),
        ),
    ]
