# Generated by Django 5.2.11 on 2026-03-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0019_merge_20260306_1741'),
        ('customers', '0004_update_existing_vat_rates'),
        ('orders', '0006_alter_orderitem_tax_rate'),
        ('products', '0002_product_default_service_plan'),
        ('provisioning', '0018_server__api_password_encrypted_server_api_username_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal_cents__gte', 0)), name='order_subtotal_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('tax_cents__gte', 0)), name='order_tax_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('discount_cents__gte', 0)), name='order_discount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('total_cents__gte', 0)), name='order_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price_cents__gte', 0)), name='orderitem_unit_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('setup_cents__gte', 0)), name='orderitem_setup_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('tax_cents__gte', 0)), name='orderitem_tax_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('line_total_cents__gte', 0)), name='orderitem_line_total_non_negative'),
        ),
    ]
