# Generated by Django 5.2.11 on 2026-03-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0019_merge_20260306_1741'),
        ('customers', '0012_fix_soft_delete_unique_constraints'),
        ('orders', '0007_add_financial_check_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Client-provided idempotency key to prevent duplicate orders', max_length=64),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__gt', '')), fields=('customer', 'idempotency_key'), name='unique_customer_idempotency_key'),
        ),
    ]
