# Generated by Django 5.2.11 on 2026-03-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_idempotency_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='idempotency_key',
            field=models.CharField(blank=True, default='', help_text='Client-provided idempotency key to prevent duplicate orders', max_length=64),
        ),
    ]
