# Generated by Django 5.2.11 on 2026-03-10 16:27

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_idempotency_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=django_fsm.FSMField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], default='draft', help_text='Current order status', max_length=20, protected=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='provisioning_status',
            field=django_fsm.FSMField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', help_text='Provisioning status for this item', max_length=20, protected=True),
        ),
    ]
