# Generated by Django 5.2.11 on 2026-03-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('billing', '0022_invoice_invoice_subtotal_non_negative_and_more'),
        ('customers', '0012_fix_soft_delete_unique_constraints'),
        ('orders', '0010_alter_order_status_and_more'),
        ('products', '0002_product_default_service_plan'),
        ('provisioning', '0021_service_terminated_at_alter_service_status'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'pending', 'confirmed', 'processing', 'completed', 'cancelled', 'failed', 'refunded', 'partially_refunded'])), name='order_status_valid_values'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('provisioning_status__in', ['pending', 'in_progress', 'completed', 'failed', 'cancelled'])), name='orderitem_provisioning_status_valid_values'),
        ),
    ]
