# Generated by Django 5.0.14 on 2025-08-19 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("audit", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="auditevent",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="compliancelog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dataexport",
            name="requested_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["user", "-timestamp"], name="audit_event_user_id_a974a6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["content_type", "object_id", "-timestamp"],
                name="audit_event_content_919dd1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["action", "-timestamp"], name="audit_event_action_1b99fa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["request_id"], name="audit_event_request_0a5a80_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="compliancelog",
            index=models.Index(
                fields=["compliance_type", "-timestamp"],
                name="audit_compl_complia_fdc50e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="compliancelog",
            index=models.Index(
                fields=["reference_id"], name="audit_compl_referen_86808f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="compliancelog",
            index=models.Index(
                fields=["status", "-timestamp"], name="audit_compl_status_5cc267_idx"
            ),
        ),
    ]
