# Generated by Django 5.0.14 on 2025-08-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditevent",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Create"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("login", "Login"),
                    ("logout", "Logout"),
                    ("access", "Access"),
                    ("export", "Export"),
                    ("import", "Import"),
                    ("2fa_enabled", "2FA Enabled"),
                    ("2fa_disabled", "2FA Disabled"),
                    ("2fa_admin_reset", "2FA Admin Reset"),
                    ("2fa_backup_codes_generated", "2FA Backup Codes Generated"),
                    ("2fa_backup_codes_viewed", "2FA Backup Codes Viewed"),
                    ("2fa_backup_code_used", "2FA Backup Code Used"),
                    ("2fa_secret_regenerated", "2FA Secret Regenerated"),
                    ("2fa_verification_success", "2FA Verification Success"),
                    ("2fa_verification_failed", "2FA Verification Failed"),
                    ("2fa_setup_started", "2FA Setup Started"),
                    ("2fa_setup_completed", "2FA Setup Completed"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
