# Generated by Django 5.0.14 on 2025-08-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0003_add_2fa_event_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataexport",
            name="file_path",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
