# Generated by Django 5.2.5 on 2025-08-28 11:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0006_convert_object_id_to_string"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditevent",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Create"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("login", "Login"),
                    ("logout", "Logout"),
                    ("access", "Access"),
                    ("export", "Export"),
                    ("import", "Import"),
                    ("login_success", "Login Success"),
                    ("login_failed", "Login Failed"),
                    ("login_failed_password", "Login Failed - Invalid Password"),
                    ("login_failed_user_not_found", "Login Failed - User Not Found"),
                    ("login_failed_account_locked", "Login Failed - Account Locked"),
                    ("login_failed_2fa", "Login Failed - 2FA Verification"),
                    ("logout_manual", "Manual Logout"),
                    ("logout_session_expired", "Session Expired Logout"),
                    ("logout_concurrent_session", "Concurrent Session Logout"),
                    ("logout_security_event", "Security Event Logout"),
                    ("account_locked", "Account Locked"),
                    ("account_unlocked", "Account Unlocked"),
                    ("password_changed", "Password Changed"),
                    ("password_reset_requested", "Password Reset Requested"),
                    ("password_reset_completed", "Password Reset Completed"),
                    ("session_rotation", "Session Rotation"),
                    ("2fa_enabled", "2FA Enabled"),
                    ("2fa_disabled", "2FA Disabled"),
                    ("2fa_admin_reset", "2FA Admin Reset"),
                    ("2fa_backup_codes_generated", "2FA Backup Codes Generated"),
                    ("2fa_backup_codes_viewed", "2FA Backup Codes Viewed"),
                    ("2fa_backup_code_used", "2FA Backup Code Used"),
                    ("2fa_secret_regenerated", "2FA Secret Regenerated"),
                    ("2fa_verification_success", "2FA Verification Success"),
                    ("2fa_verification_failed", "2FA Verification Failed"),
                    ("2fa_setup_started", "2FA Setup Started"),
                    ("2fa_setup_completed", "2FA Setup Completed"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="dataexport",
            name="file_path",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["user", "action", "-timestamp"],
                name="idx_audit_user_action_time",
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["ip_address", "action", "-timestamp"],
                name="idx_audit_ip_action_time",
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["session_key", "-timestamp"], name="idx_audit_session_time"
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["actor_type", "action", "-timestamp"],
                name="idx_audit_actor_action_time",
            ),
        ),
    ]
