# Generated by Django 5.0.14 on 2025-08-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_initial"),
        (
            "provisioning",
            "0002_servicegroup_servicegroupmember_servicerelationship_and_more",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="provisioningtask",
            index=models.Index(
                fields=["status", "next_retry_at"], name="provisionin_status_d0b470_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="provisioningtask",
            index=models.Index(
                fields=["task_type", "status", "-created_at"],
                name="provisionin_task_ty_d071c9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["auto_renew", "expires_at", "status"],
                name="services_auto_re_149d05_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["service_plan", "status"], name="services_service_b8062d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["billing_cycle", "status", "-created_at"],
                name="services_billing_0f2ec3_idx",
            ),
        ),
    ]
