# Generated by Django 5.2.5 on 2025-08-31 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provisioning', '0003_add_performance_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provisioningtask',
            options={'ordering': ('-created_at',), 'verbose_name': 'Provisioning Task', 'verbose_name_plural': 'Provisioning Tasks'},
        ),
        migrations.AlterModelOptions(
            name='server',
            options={'ordering': ('location', 'name'), 'verbose_name': 'Server', 'verbose_name_plural': 'Servers'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('-created_at',), 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='servicedomain',
            options={'ordering': ('-created_at',), 'verbose_name': '🌐 Service Domain', 'verbose_name_plural': '🌐 Service Domains'},
        ),
        migrations.AlterModelOptions(
            name='servicegroup',
            options={'ordering': ('-created_at',), 'verbose_name': '📦 Service Group', 'verbose_name_plural': '📦 Service Groups'},
        ),
        migrations.AlterModelOptions(
            name='servicegroupmember',
            options={'ordering': ('provision_order', 'joined_at'), 'verbose_name': '👥 Service Group Member', 'verbose_name_plural': '👥 Service Group Members'},
        ),
        migrations.AlterModelOptions(
            name='serviceplan',
            options={'ordering': ('plan_type', 'sort_order', 'price_monthly'), 'verbose_name': 'Service Plan', 'verbose_name_plural': 'Service Plans'},
        ),
        migrations.AlterModelOptions(
            name='servicerelationship',
            options={'ordering': ('-created_at',), 'verbose_name': '🔗 Service Relationship', 'verbose_name_plural': '🔗 Service Relationships'},
        ),
        migrations.AddField(
            model_name='server',
            name='management_api_key',
            field=models.TextField(blank=True, verbose_name='Encrypted API Key'),
        ),
        migrations.AddField(
            model_name='server',
            name='management_api_secret',
            field=models.TextField(blank=True, verbose_name='Encrypted API Secret'),
        ),
        migrations.AddField(
            model_name='server',
            name='management_api_url',
            field=models.URLField(blank=True, verbose_name='Management API URL'),
        ),
        migrations.AddField(
            model_name='server',
            name='management_webhook_secret',
            field=models.CharField(blank=True, max_length=255, verbose_name='Webhook Secret for signature verification'),
        ),
        migrations.AlterField(
            model_name='servicedomain',
            name='domain_type',
            field=models.CharField(choices=[('primary', '🎯 Primary Domain'), ('addon', '+ Add-on Domain'), ('subdomain', '🔗 Subdomain'), ('redirect', '↩️ Domain Redirect'), ('parking', '🅿️ Parked Domain')], default='primary', help_text='How domain is used with service', max_length=20),
        ),
    ]
