# Generated by Django 5.2.5 on 2025-09-02 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provisioning', '0005_virtualminserver_alter_server_management_api_key_and_more'),
        ('users', '0009_delete_backupcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualminaccount',
            name='customer_membership',
            field=models.ForeignKey(blank=True, help_text='Links hosting account to customer membership for access control', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='virtualmin_accounts', to='users.customermembership', verbose_name='Customer Membership'),
        ),
    ]
