# Generated by Django 5.2.5 on 2025-09-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provisioning', '0006_virtualminaccount_customer_membership'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='virtualminprovisioningjob',
            name='virtualmin__celery__e82166_idx',
        ),
        migrations.RenameField(
            model_name='virtualminprovisioningjob',
            old_name='celery_task_id',
            new_name='task_id',
        ),
        migrations.AddIndex(
            model_name='virtualminprovisioningjob',
            index=models.Index(fields=['task_id'], name='virtualmin__task_id_a5be6a_idx'),
        ),
    ]
