# Generated by Django 5.2.5 on 2025-09-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provisioning', '0008_virtualmin_account_restructure'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualminaccount',
            name='protected_from_deletion',
            field=models.BooleanField(default=True, help_text='Prevents accidental deletion of active Virtualmin accounts', verbose_name='Protected from Deletion'),
        ),
        migrations.AlterField(
            model_name='provisioningtask',
            name='task_type',
            field=models.CharField(choices=[('create_service', 'Create Service'), ('suspend_service', 'Suspend Service'), ('unsuspend_service', 'Unsuspend Service'), ('update_service', 'Update Service'), ('backup_service', 'Backup Service')], max_length=30, verbose_name='Task Type'),
        ),
    ]
