# Generated by Django 5.2.5 on 2025-09-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provisioning', '0009_virtualminaccount_protected_from_deletion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provisioningtask',
            name='task_type',
            field=models.CharField(choices=[('create_service', 'Create Service'), ('suspend_service', 'Suspend Service'), ('unsuspend_service', 'Unsuspend Service'), ('terminate_service', 'Terminate Service'), ('update_service', 'Update Service'), ('backup_service', 'Backup Service')], max_length=30, verbose_name='Task Type'),
        ),
    ]
