# Generated by Django 5.2.5 on 2025-09-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provisioning', '0011_alter_virtualminaccount_bandwidth_quota_mb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualminaccount',
            name='domain',
            field=models.CharField(db_index=True, help_text='Must be unique across all VirtualMin accounts', max_length=255, unique=True, verbose_name='Primary Domain'),
        ),
    ]
