# Generated by Django 5.2.12 on 2026-03-10 23:00

import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotioncampaign',
            name='status',
            field=django_fsm.FSMField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20, protected=True),
        ),
        migrations.AddConstraint(
            model_name='promotioncampaign',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'scheduled', 'active', 'paused', 'completed', 'cancelled'])), name='campaign_valid_status'),
        ),
    ]
