# Generated by Django 5.2.12 on 2026-03-11 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0002_initial'),
        ('customers', '0002_initial'),
        ('orders', '0004_initial'),
        ('promotions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_coupons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coupon',
            name='currency',
            field=models.ForeignKey(blank=True, help_text='Currency for fixed amount discounts', null=True, on_delete=django.db.models.deletion.PROTECT, to='billing.currency'),
        ),
        migrations.AddField(
            model_name='couponredemption',
            name='coupon',
            field=models.ForeignKey(help_text='The coupon that was redeemed', on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='promotions.coupon'),
        ),
        migrations.AddField(
            model_name='couponredemption',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Customer who redeemed the coupon', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_redemptions', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='couponredemption',
            name='order',
            field=models.ForeignKey(help_text='The order this redemption applies to', on_delete=django.db.models.deletion.CASCADE, related_name='coupon_redemptions', to='orders.order'),
        ),
        migrations.AddField(
            model_name='customerloyalty',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_memberships', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.currency'),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_cards_purchased', to='orders.order'),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='purchased_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_gift_cards', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='redeemed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redeemed_gift_cards', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='giftcardtransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='giftcardtransaction',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer'),
        ),
        migrations.AddField(
            model_name='giftcardtransaction',
            name='gift_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='promotions.giftcard'),
        ),
        migrations.AddField(
            model_name='giftcardtransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_card_transactions', to='orders.order'),
        ),
        migrations.AddField(
            model_name='loyaltyprogram',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.currency'),
        ),
        migrations.AddField(
            model_name='customerloyalty',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='promotions.loyaltyprogram'),
        ),
        migrations.AddField(
            model_name='loyaltytier',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='promotions.loyaltyprogram'),
        ),
        migrations.AddField(
            model_name='customerloyalty',
            name='current_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='promotions.loyaltytier'),
        ),
        migrations.AddField(
            model_name='loyaltytransaction',
            name='coupon_redemption',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promotions.couponredemption'),
        ),
        migrations.AddField(
            model_name='loyaltytransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loyaltytransaction',
            name='customer_loyalty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='promotions.customerloyalty'),
        ),
        migrations.AddField(
            model_name='loyaltytransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_transactions', to='orders.order'),
        ),
        migrations.AddField(
            model_name='promotioncampaign',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_promotion_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coupon',
            name='campaign',
            field=models.ForeignKey(blank=True, help_text='Associated marketing campaign', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons', to='promotions.promotioncampaign'),
        ),
        migrations.AddField(
            model_name='promotionrule',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules', to='promotions.promotioncampaign'),
        ),
        migrations.AddField(
            model_name='promotionrule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_promotion_rules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promotionrule',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='billing.currency'),
        ),
        migrations.AddField(
            model_name='referral',
            name='qualifying_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_qualifications', to='orders.order'),
        ),
        migrations.AddField(
            model_name='referral',
            name='referred_customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referred_by', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='referralcode',
            name='owner',
            field=models.OneToOneField(help_text='Customer who owns this referral code', on_delete=django.db.models.deletion.CASCADE, related_name='referral_code', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='referralcode',
            name='referee_coupon',
            field=models.OneToOneField(blank=True, help_text='Coupon used by referees', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_code', to='promotions.coupon'),
        ),
        migrations.AddField(
            model_name='referral',
            name='referral_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals', to='promotions.referralcode'),
        ),
        migrations.AddIndex(
            model_name='couponredemption',
            index=models.Index(fields=['coupon', '-created_at'], name='promotion_c_coupon__2b231b_idx'),
        ),
        migrations.AddIndex(
            model_name='couponredemption',
            index=models.Index(fields=['order'], name='promotion_c_order_i_977858_idx'),
        ),
        migrations.AddIndex(
            model_name='couponredemption',
            index=models.Index(fields=['customer', '-created_at'], name='promotion_c_custome_d50eb0_idx'),
        ),
        migrations.AddIndex(
            model_name='couponredemption',
            index=models.Index(fields=['status', '-created_at'], name='promotion_c_status_221a84_idx'),
        ),
        migrations.AddIndex(
            model_name='couponredemption',
            index=models.Index(fields=['applied_at'], name='promotion_c_applied_9017cd_idx'),
        ),
        migrations.AddIndex(
            model_name='couponredemption',
            index=models.Index(fields=['coupon', 'status', '-applied_at'], name='idx_redemption_analytics'),
        ),
        migrations.AddIndex(
            model_name='couponredemption',
            index=models.Index(fields=['customer', 'status'], name='idx_redemption_customer'),
        ),
        migrations.AddConstraint(
            model_name='couponredemption',
            constraint=models.UniqueConstraint(fields=('coupon', 'order'), name='unique_coupon_per_order'),
        ),
        migrations.AddIndex(
            model_name='giftcard',
            index=models.Index(fields=['code'], name='promotion_g_code_0e7148_idx'),
        ),
        migrations.AddIndex(
            model_name='giftcard',
            index=models.Index(fields=['status', 'is_active'], name='promotion_g_status_085e2b_idx'),
        ),
        migrations.AddIndex(
            model_name='giftcard',
            index=models.Index(fields=['redeemed_by'], name='promotion_g_redeeme_b5d418_idx'),
        ),
        migrations.AddIndex(
            model_name='giftcard',
            index=models.Index(fields=['purchased_by'], name='promotion_g_purchas_eab431_idx'),
        ),
        migrations.AddIndex(
            model_name='giftcard',
            index=models.Index(fields=['valid_until'], name='promotion_g_valid_u_050323_idx'),
        ),
        migrations.AddIndex(
            model_name='giftcardtransaction',
            index=models.Index(fields=['gift_card', '-created_at'], name='promotion_g_gift_ca_469da0_idx'),
        ),
        migrations.AddIndex(
            model_name='giftcardtransaction',
            index=models.Index(fields=['transaction_type', '-created_at'], name='promotion_g_transac_4d0bbc_idx'),
        ),
        migrations.AddIndex(
            model_name='giftcardtransaction',
            index=models.Index(fields=['order'], name='promotion_g_order_i_dec716_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='loyaltytier',
            unique_together={('program', 'slug')},
        ),
        migrations.AddIndex(
            model_name='customerloyalty',
            index=models.Index(fields=['customer', 'program'], name='promotion_c_custome_b6bf06_idx'),
        ),
        migrations.AddIndex(
            model_name='customerloyalty',
            index=models.Index(fields=['current_tier'], name='promotion_c_current_a12c26_idx'),
        ),
        migrations.AddIndex(
            model_name='customerloyalty',
            index=models.Index(fields=['points_balance'], name='promotion_c_points__7587fd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customerloyalty',
            unique_together={('customer', 'program')},
        ),
        migrations.AddIndex(
            model_name='loyaltytransaction',
            index=models.Index(fields=['customer_loyalty', '-created_at'], name='promotion_l_custome_cfd2d4_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltytransaction',
            index=models.Index(fields=['transaction_type', '-created_at'], name='promotion_l_transac_d7b90a_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltytransaction',
            index=models.Index(fields=['order'], name='promotion_l_order_i_7e64a6_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltytransaction',
            index=models.Index(fields=['expires_at'], name='promotion_l_expires_e0740c_idx'),
        ),
        migrations.AddIndex(
            model_name='promotioncampaign',
            index=models.Index(fields=['slug'], name='promotion_c_slug_ca4364_idx'),
        ),
        migrations.AddIndex(
            model_name='promotioncampaign',
            index=models.Index(fields=['status', 'is_active'], name='promotion_c_status_0f0ff4_idx'),
        ),
        migrations.AddIndex(
            model_name='promotioncampaign',
            index=models.Index(fields=['start_date', 'end_date'], name='promotion_c_start_d_c6ed6d_idx'),
        ),
        migrations.AddIndex(
            model_name='promotioncampaign',
            index=models.Index(fields=['campaign_type', 'status'], name='promotion_c_campaig_57b9f2_idx'),
        ),
        migrations.AddConstraint(
            model_name='promotioncampaign',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'scheduled', 'active', 'paused', 'completed', 'cancelled'])), name='campaign_valid_status'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['code'], name='promotion_c_code_53e22b_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['status', 'is_active'], name='promotion_c_status_cbc397_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['valid_from', 'valid_until'], name='promotion_c_valid_f_5a9b92_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['discount_type'], name='promotion_c_discoun_328c8c_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['campaign'], name='promotion_c_campaig_24b46f_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['customer_target'], name='promotion_c_custome_f64143_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['assigned_customer'], name='promotion_c_assigne_d0261c_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['created_at'], name='promotion_c_created_f5ad2d_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['is_active', 'status', 'valid_from', 'valid_until'], name='idx_coupon_validity'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['is_public', 'is_active', 'status'], name='idx_coupon_public'),
        ),
        migrations.AddIndex(
            model_name='promotionrule',
            index=models.Index(fields=['rule_type', 'is_active'], name='promotion_r_rule_ty_a4d8d1_idx'),
        ),
        migrations.AddIndex(
            model_name='promotionrule',
            index=models.Index(fields=['valid_from', 'valid_until'], name='promotion_r_valid_f_ee4667_idx'),
        ),
        migrations.AddIndex(
            model_name='promotionrule',
            index=models.Index(fields=['priority'], name='promotion_r_priorit_1826ce_idx'),
        ),
        migrations.AddIndex(
            model_name='promotionrule',
            index=models.Index(fields=['campaign'], name='promotion_r_campaig_e2ae2d_idx'),
        ),
        migrations.AddIndex(
            model_name='referralcode',
            index=models.Index(fields=['code'], name='promotion_r_code_a8ce92_idx'),
        ),
        migrations.AddIndex(
            model_name='referralcode',
            index=models.Index(fields=['owner'], name='promotion_r_owner_i_a3f4f3_idx'),
        ),
        migrations.AddIndex(
            model_name='referralcode',
            index=models.Index(fields=['is_active'], name='promotion_r_is_acti_41b2f7_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['referral_code', 'status'], name='promotion_r_referra_769925_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['referred_customer'], name='promotion_r_referre_d6cab6_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['status', '-created_at'], name='promotion_r_status_5345b2_idx'),
        ),
    ]
