# Generated by Django 5.2.12 on 2026-08-28 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderitem_product_slug'),
        ('promotions', '0003_couponredemption_charged_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponredemption',
            name='order',
            field=models.ForeignKey(help_text='The order this redemption applies to', on_delete=django.db.models.deletion.PROTECT, related_name='coupon_redemptions', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='giftcardtransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gift_card_transactions', to='orders.order'),
        ),
    ]
