# Generated by Django 5.2.17 on 2026-09-28 13:46

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0058_clear_credit_note_xml_built_by_the_wrong_builder"),
        ("orders", "0007_orderitem_product_slug"),
        ("promotions", "0004_alter_couponredemption_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="tiers",
            field=models.JSONField(blank=True, default=list, help_text="Validated discount tiers"),
        ),
        migrations.AddField(
            model_name="promotioncampaign",
            name="budget_currency",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="billing.currency"
            ),
        ),
        migrations.AddField(
            model_name="promotioncampaign",
            name="reserved_cents",
            field=models.PositiveBigIntegerField(
                default=0, help_text="Discounts promised by unsettled orders and future renewals"
            ),
        ),
        migrations.AddField(
            model_name="promotionrule",
            name="published_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.CreateModel(
            name="PromotionApplication",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("reserved", "Reserved"), ("settled", "Settled"), ("released", "Released")],
                        default="reserved",
                        max_length=12,
                    ),
                ),
                ("discount_cents", models.PositiveBigIntegerField()),
                ("future_cents", models.PositiveBigIntegerField(default=0)),
                ("allocations", models.JSONField(default=dict)),
                ("snapshot", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="promotions.promotioncampaign",
                    ),
                ),
                (
                    "coupon",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="promotions.coupon"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="promotion_applications",
                        to="orders.order",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="promotions.promotionrule",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RenewalBenefit",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("remaining_cents", models.PositiveBigIntegerField()),
                ("remaining_months", models.PositiveSmallIntegerField()),
                ("monthly_cents", models.DecimalField(decimal_places=10, max_digits=24)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="benefits",
                        to="promotions.promotionapplication",
                    ),
                ),
                ("order_item", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="orders.orderitem")),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="promotion_benefits",
                        to="billing.subscription",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RenewalBenefitUse",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount_cents", models.PositiveBigIntegerField()),
                ("months", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("reserved", "Reserved"), ("settled", "Settled"), ("released", "Released")],
                        default="reserved",
                        max_length=12,
                    ),
                ),
                (
                    "benefit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="uses", to="promotions.renewalbenefit"
                    ),
                ),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="promotion_uses",
                        to="billing.billingcycle",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="promotionapplication",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("coupon__isnull", False), ("rule__isnull", True)),
                    models.Q(("coupon__isnull", True), ("rule__isnull", False)),
                    _connector="OR",
                ),
                name="offer_application_one_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="promotionapplication",
            constraint=models.UniqueConstraint(fields=("order", "coupon"), name="offer_once_per_coupon_order"),
        ),
        migrations.AddConstraint(
            model_name="promotionapplication",
            constraint=models.UniqueConstraint(fields=("order", "rule"), name="offer_once_per_rule_order"),
        ),
        migrations.AddConstraint(
            model_name="renewalbenefit",
            constraint=models.UniqueConstraint(fields=("application", "order_item"), name="one_benefit_per_offer_item"),
        ),
        migrations.AddConstraint(
            model_name="renewalbenefituse",
            constraint=models.UniqueConstraint(fields=("benefit", "cycle"), name="one_benefit_use_per_cycle"),
        ),
    ]
