# Generated by Django 5.2.17 on 2026-09-28 13:58

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0059_alter_payment_payment_method"),
        ("customers", "0023_vies_evidence_and_exemption_reason"),
        ("promotions", "0005_coupon_tiers_promotioncampaign_budget_currency_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="giftcard",
            name="ledger_version",
            field=models.PositiveSmallIntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name="giftcard",
            name="reserved_cents",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="giftcardtransaction",
            name="ledger_version",
            field=models.PositiveSmallIntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name="giftcardtransaction",
            name="operation_key",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="giftcardtransaction",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="gift_card_entries",
                to="billing.payment",
            ),
        ),
        migrations.CreateModel(
            name="GiftCardPurchase",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Awaiting payment"),
                            ("funded", "Funded"),
                            ("partially_refunded", "Partially refunded"),
                            ("refunded", "Refunded"),
                            ("disputed", "Disputed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("receipt_number", models.CharField(max_length=60, unique=True)),
                ("funded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gift_card_purchases",
                        to="customers.customer",
                    ),
                ),
                (
                    "funding_payment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gift_card_purchase",
                        to="billing.payment",
                    ),
                ),
                (
                    "gift_card",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, related_name="purchase", to="promotions.giftcard"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TenderRefundCommand",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("amount_cents", models.PositiveBigIntegerField()),
                ("operation_key", models.CharField(max_length=100, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Needs retry"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("reason", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                ("customer", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="customers.customer")),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tender_refund_commands",
                        to="billing.invoice",
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refund_commands",
                        to="promotions.giftcardpurchase",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TenderRefundLeg",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount_cents", models.PositiveBigIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Needs retry"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                (
                    "command",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legs",
                        to="promotions.tenderrefundcommand",
                    ),
                ),
                ("payment", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="billing.payment")),
                (
                    "refund",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tender_leg",
                        to="billing.refund",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GiftCardReservation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("amount_cents", models.PositiveBigIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("reserved", "Reserved"), ("captured", "Captured"), ("released", "Released")],
                        default="reserved",
                        max_length=12,
                    ),
                ),
                ("operation_key", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("customer", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="customers.customer")),
                (
                    "gift_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="promotions.giftcard",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gift_card_reservations",
                        to="billing.invoice",
                    ),
                ),
                (
                    "payment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gift_card_reservation",
                        to="billing.payment",
                    ),
                ),
                (
                    "proforma",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gift_card_reservations",
                        to="billing.proformainvoice",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("proforma__isnull", False), ("invoice__isnull", False), _connector="OR"),
                        name="gift_reservation_has_document",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("amount_cents__gt", 0)), name="gift_reservation_positive"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="tenderrefundcommand",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("invoice__isnull", False), ("purchase__isnull", True)),
                    models.Q(("invoice__isnull", True), ("purchase__isnull", False)),
                    _connector="OR",
                ),
                name="tender_refund_one_document",
            ),
        ),
        migrations.AddConstraint(
            model_name="tenderrefundleg",
            constraint=models.UniqueConstraint(fields=("command", "payment"), name="one_refund_leg_per_tender"),
        ),
    ]
