# Generated by Django 5.2.17 on 2026-09-29 08:48

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0062_subscription_currency_transition'),
        ('promotions', '0007_renewalbenefit_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcardpurchase',
            name='buyer_email',
            field=models.EmailField(blank=True, editable=False, max_length=254),
        ),
        migrations.AddField(
            model_name='giftcardpurchase',
            name='buyer_name',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='giftcardpurchase',
            name='is_gift',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.CreateModel(
            name='GiftCardFundingAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_cents', models.PositiveBigIntegerField()),
                ('idempotency_key', models.CharField(max_length=100, unique=True)),
                ('request_metadata', models.JSONField(default=dict)),
                ('first_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('gateway_intent_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('client_secret', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(default='reserved', max_length=32)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.currency')),
                ('purchase', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='funding_attempt', to='promotions.giftcardpurchase')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('amount_cents__gt', 0)), name='gift_funding_attempt_positive')],
            },
        ),
    ]
