# Generated by Django 5.2.17 on 2026-09-29 09:12

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0008_gift_purchase_funding_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcard',
            name='refund_held_cents',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='spending_freeze_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='spending_frozen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='GiftCardDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('voucher', 'Voucher'), ('receipt', 'Buyer receipt')], max_length=12)),
                ('target_email', models.EmailField(max_length=254)),
                ('status', models.CharField(default='pending', max_length=12)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('claim_token', models.UUIDField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='promotions.giftcardpurchase')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='gift_delivery_due')],
                'constraints': [models.UniqueConstraint(fields=('purchase', 'purpose'), name='one_gift_delivery_per_purpose')],
            },
        ),
    ]
