# Generated by Django 5.2.17 on 2026-09-29 09:18

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0062_subscription_currency_transition'),
        ('promotions', '0009_gift_delivery_and_value_holds'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCardFundingRefund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_cents', models.PositiveBigIntegerField()),
                ('idempotency_key', models.CharField(max_length=100, unique=True)),
                ('reason', models.CharField(default='requested_by_customer', max_length=40)),
                ('status', models.CharField(default='reserved', max_length=32)),
                ('gateway_refund_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('first_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('gateway_event_created', models.PositiveBigIntegerField(blank=True, null=True)),
                ('held_cents', models.PositiveBigIntegerField(default=0)),
                ('applied_cents', models.PositiveBigIntegerField(default=0)),
                ('shortfall_cents', models.PositiveBigIntegerField(default=0)),
                ('settlement_version', models.PositiveIntegerField(default=0)),
                ('bank_reference', models.CharField(blank=True, max_length=100)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_gift_funding_refunds', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requested_gift_funding_refunds', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.currency')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funding_refunds', to='promotions.giftcardpurchase')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'checked_at'], name='gift_refund_reconcile')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount_cents__gt', 0)), name='gift_funding_refund_positive')],
            },
        ),
    ]
