# Generated by Django 5.2.17 on 2026-09-29 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0010_gift_original_tender_refunds'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcardpurchase',
            name='buyer_actor',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gift_card_purchases', to=settings.AUTH_USER_MODEL),
        ),
    ]
