# Generated by Django 5.2.17 on 2026-09-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0011_gift_purchase_buyer_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcardfundingrefund',
            name='funding_intent_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
