# Generated by Django 5.2.5 on 2025-09-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupportCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('name_en', models.CharField(max_length=100, verbose_name='Name (EN)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon', models.CharField(default='help-circle', max_length=50, verbose_name='Icon')),
                ('color', models.CharField(default='#3B82F6', max_length=7, verbose_name='Color')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Support Category',
                'verbose_name_plural': 'Support Categories',
                'db_table': 'support_categories',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=20, unique=True, verbose_name='Ticket Number')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='Contact Person')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Contact Email')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Contact Phone')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent'), ('critical', 'Critical')], default='normal', max_length=20, verbose_name='Priority')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('waiting_on_customer', 'Waiting on Customer'), ('closed', 'Closed')], default='open', max_length=30, verbose_name='Status')),
                ('source', models.CharField(choices=[('web', 'Website'), ('email', 'Email'), ('phone', 'Phone'), ('chat', 'Chat'), ('api', 'API'), ('internal', 'Internal')], default='web', max_length=20, verbose_name='Source')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='Assigned At')),
                ('object_id', models.CharField(blank=True, db_index=True, default='', max_length=36)),
                ('resolution_code', models.CharField(blank=True, choices=[('fixed', 'Fixed'), ('invalid', 'Invalid'), ('duplicate', 'Duplicate'), ('by_design', 'By Design'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled'), ('other', 'Other')], default='', max_length=20, verbose_name='Resolution Code')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Closed At')),
                ('customer_replied_at', models.DateTimeField(blank=True, null=True, verbose_name='Customer Last Reply')),
                ('has_customer_replied', models.BooleanField(default=False, verbose_name='Customer Replied')),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Estimated Hours')),
                ('actual_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Actual Hours')),
                ('satisfaction_rating', models.PositiveIntegerField(blank=True, null=True, verbose_name='Satisfaction Rating (1-5)')),
                ('satisfaction_comment', models.TextField(blank=True, verbose_name='Satisfaction Comment')),
                ('is_escalated', models.BooleanField(default=False, verbose_name='Escalated')),
                ('is_public', models.BooleanField(default=True, verbose_name='Public for Customer')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Support Ticket',
                'verbose_name_plural': 'Support Tickets',
                'db_table': 'tickets',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='tickets/attachments/', verbose_name='File')),
                ('filename', models.CharField(max_length=255, verbose_name='Filename')),
                ('file_size', models.PositiveIntegerField(verbose_name='File Size')),
                ('content_type', models.CharField(max_length=100, verbose_name='Content Type')),
                ('is_safe', models.BooleanField(default=True, verbose_name='Safe')),
                ('virus_scan_result', models.CharField(blank=True, max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
            ],
            options={
                'verbose_name': 'Ticket Attachment',
                'verbose_name_plural': 'Ticket Attachments',
                'db_table': 'ticket_attachments',
                'ordering': ('uploaded_at',),
            },
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Content')),
                ('comment_type', models.CharField(choices=[('customer', 'Customer'), ('support', 'Support'), ('internal', 'Internal'), ('system', 'System')], default='support', max_length=20, verbose_name='Comment Type')),
                ('author_name', models.CharField(blank=True, max_length=100, verbose_name='Author Name')),
                ('author_email', models.EmailField(blank=True, max_length=254, verbose_name='Author Email')),
                ('is_public', models.BooleanField(default=True, verbose_name='Public')),
                ('is_solution', models.BooleanField(default=False, verbose_name='Is Solution')),
                ('reply_action', models.CharField(blank=True, choices=[('reply', 'Reply'), ('reply_and_wait', 'Reply & set Waiting on Customer'), ('internal_note', 'Internal note'), ('close_with_resolution', 'Close with resolution')], default='', max_length=30, verbose_name='Reply Action')),
                ('sets_waiting_on_customer', models.BooleanField(default=False, verbose_name='Sets Waiting on Customer')),
                ('time_spent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Time Spent (hours)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Ticket Comment',
                'verbose_name_plural': 'Ticket Comments',
                'db_table': 'ticket_comments',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='TicketWorklog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Activity Description')),
                ('time_spent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Time Spent (hours)')),
                ('is_billable', models.BooleanField(default=False, verbose_name='Billable')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Hourly Rate')),
                ('work_date', models.DateField(verbose_name='Work Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ticket Worklog',
                'verbose_name_plural': 'Ticket Worklogs',
                'db_table': 'ticket_worklogs',
                'ordering': ('-work_date',),
            },
        ),
    ]
