# Generated by Django 5.2.10 on 2026-07-24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0002_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(fields=["status", "updated_at"], name="tickets_status_updated_idx"),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="resolution_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fixed", "Fixed"),
                    ("invalid", "Invalid"),
                    ("duplicate", "Duplicate"),
                    ("by_design", "By Design"),
                    ("refunded", "Refunded"),
                    ("cancelled", "Cancelled"),
                    ("auto_closed", "Auto Closed"),
                    ("other", "Other"),
                ],
                default="",
                max_length=20,
                verbose_name="Resolution Code",
            ),
        ),
    ]
