# Generated by Django 5.2.5 on 2025-08-28 06:20

from django.db import migrations, models


def convert_object_ids_to_string(apps, schema_editor):
    """
    Convert existing integer object_id values to string format.
    This is safe as CharField will store integers as strings.
    """
    Ticket = apps.get_model('tickets', 'Ticket')
    
    # PostgreSQL and SQLite handle this conversion automatically
    # when we change the field type, but we can be explicit
    # about the data transformation if needed
    
    # No explicit data conversion needed since:
    # 1. Existing integer PKs will be stored as "123" strings
    # 2. New UUID PKs will be stored as "550e8400-e29b-41d4-a716-446655440000" strings
    # 3. Django's GenericForeignKey handles the conversion automatically
    
    pass  # Django's field type change handles this automatically


def reverse_convert_object_ids_to_integer(apps, schema_editor):
    """
    Reverse migration: Convert string object_id back to integer.
    This is more complex as we need to validate that all values are numeric.
    """
    Ticket = apps.get_model('tickets', 'Ticket')
    
    # Check if any tickets have non-numeric object_ids (UUIDs)
    non_numeric_count = Ticket.objects.filter(
        object_id__isnull=False
    ).exclude(
        object_id__regex=r'^\d+$'
    ).count()
    
    if non_numeric_count > 0:
        raise ValueError(
            f"Cannot reverse migration: Found {non_numeric_count} tickets "
            f"with non-numeric object_ids (likely UUIDs). "
            f"This migration cannot be safely reversed."
        )


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0002_initial"),
    ]

    operations = [
        # Step 1: Run data conversion (though it's mostly automatic)
        migrations.RunPython(
            convert_object_ids_to_string,
            reverse_convert_object_ids_to_integer
        ),
        
        # Step 2: Change the field type from PositiveIntegerField to CharField
        migrations.AlterField(
            model_name='ticket',
            name='object_id',
            field=models.CharField(max_length=36, null=True, blank=True, db_index=True),
        ),
    ]