# Generated by Django 5.2.11 on 2026-03-10 18:07

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=django_fsm.FSMField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('waiting_on_customer', 'Waiting on Customer'), ('closed', 'Closed')], default='open', max_length=30, protected=True, verbose_name='Status'),
        ),
    ]
