# Generated by Django 5.2.11 on 2026-03-10 18:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('customers', '0012_fix_soft_delete_unique_constraints'),
        ('provisioning', '0022_service_service_status_valid_values'),
        ('tickets', '0003_alter_ticket_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['open', 'in_progress', 'waiting_on_customer', 'closed'])), name='ticket_status_valid_values'),
        ),
    ]
