# Generated by Django 5.2.5 on 2025-09-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_supportcategory_auto_assign_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportcategory',
            name='sla_resolution_hours',
        ),
        migrations.RemoveField(
            model_name='supportcategory',
            name='sla_response_hours',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='first_response_at',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='requires_customer_response',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='resolved_at',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='sla_resolution_due',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='sla_response_due',
        ),
        migrations.AddField(
            model_name='ticket',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Closed At'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='customer_replied_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Customer Last Reply'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='has_customer_replied',
            field=models.BooleanField(default=False, verbose_name='Customer Replied'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='resolution_code',
            field=models.CharField(blank=True, choices=[('fixed', 'Fixed'), ('invalid', 'Invalid'), ('duplicate', 'Duplicate'), ('by_design', 'By Design'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled'), ('other', 'Other')], max_length=20, null=True, verbose_name='Resolution Code'),
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='reply_action',
            field=models.CharField(blank=True, choices=[('reply', 'Reply'), ('reply_and_wait', 'Reply & set Waiting on Customer'), ('internal_note', 'Internal note'), ('close_with_resolution', 'Close with resolution')], max_length=30, null=True, verbose_name='Reply Action'),
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='sets_waiting_on_customer',
            field=models.BooleanField(default=False, verbose_name='Sets Waiting on Customer'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('waiting_on_customer', 'Waiting on Customer'), ('closed', 'Closed')], default='open', max_length=30, verbose_name='Status'),
        ),
    ]
