# Generated by Django 5.2.5 on 2025-09-10 10:37

from django.db import migrations
from django.utils import timezone


def migrate_ticket_statuses(apps, schema_editor):
    """
    Migrate ticket statuses from old 6-status system to new 4-status system.
    
    Mapping:
    - 'new' -> 'open'
    - 'open' -> 'open' (unchanged)
    - 'pending' -> 'waiting_on_customer'
    - 'resolved' -> 'closed' (resolution_code='fixed')
    - 'cancelled' -> 'closed' (resolution_code='cancelled')
    - 'closed' -> 'closed' (unchanged, resolution_code='other' if not set)
    """
    Ticket = apps.get_model('tickets', 'Ticket')
    
    # Status mapping dictionary
    status_mapping = {
        'new': 'open',
        'open': 'open',
        'pending': 'waiting_on_customer',
        'resolved': 'closed',
        'cancelled': 'closed', 
        'closed': 'closed',
    }
    
    # Resolution code mapping for closed tickets
    resolution_mapping = {
        'resolved': 'fixed',
        'cancelled': 'cancelled',
        'closed': 'other',  # Default for already closed tickets
    }
    
    # Get all tickets that need status migration
    tickets_to_update = Ticket.objects.all()
    
    print(f"Migrating {tickets_to_update.count()} tickets to new status system...")
    
    for ticket in tickets_to_update:
        old_status = ticket.status
        new_status = status_mapping.get(old_status, 'open')  # Default fallback
        
        # Update status
        ticket.status = new_status
        
        # Set resolution code for tickets becoming closed
        if new_status == 'closed':
            # Set closed_at timestamp if not already set
            if not hasattr(ticket, 'closed_at') or not ticket.closed_at:
                ticket.closed_at = timezone.now()
            
            # Set resolution code based on old status
            resolution_code = resolution_mapping.get(old_status, 'other')
            ticket.resolution_code = resolution_code
        
        ticket.save(update_fields=['status', 'resolution_code', 'closed_at'])
        
        print(f"  Ticket #{ticket.ticket_number}: {old_status} -> {new_status}" + 
              (f" (resolution: {ticket.resolution_code})" if new_status == 'closed' else ""))
    
    print("✅ Ticket status migration completed!")


def reverse_migrate_ticket_statuses(apps, schema_editor):
    """
    Reverse migration - convert back to old status system (if possible).
    
    Note: This is a lossy operation - we can't perfectly restore the original
    'new' vs 'open' distinction, so all become 'open'.
    """
    Ticket = apps.get_model('tickets', 'Ticket')
    
    # Reverse mapping (best effort)
    reverse_mapping = {
        'open': 'open',
        'in_progress': 'open',  # No direct equivalent in old system
        'waiting_on_customer': 'pending',
        'closed': 'closed',  # Will need to check resolution_code for more specific mapping
    }
    
    tickets_to_update = Ticket.objects.all()
    
    print(f"Reverse migrating {tickets_to_update.count()} tickets to old status system...")
    
    for ticket in tickets_to_update:
        current_status = ticket.status
        
        if current_status == 'closed' and ticket.resolution_code:
            # Try to restore more specific closed status based on resolution
            if ticket.resolution_code == 'cancelled':
                new_status = 'cancelled'
            elif ticket.resolution_code == 'fixed':
                new_status = 'resolved'
            else:
                new_status = 'closed'
        else:
            new_status = reverse_mapping.get(current_status, 'open')
        
        ticket.status = new_status
        
        # Clear new fields
        ticket.resolution_code = None
        ticket.closed_at = None
        ticket.has_customer_replied = False
        ticket.customer_replied_at = None
        
        ticket.save(update_fields=[
            'status', 'resolution_code', 'closed_at', 
            'has_customer_replied', 'customer_replied_at'
        ])
        
        print(f"  Ticket #{ticket.ticket_number}: {current_status} -> {new_status}")
    
    print("✅ Reverse ticket status migration completed!")


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_remove_supportcategory_sla_resolution_hours_and_more'),
    ]

    operations = [
        migrations.RunPython(
            migrate_ticket_statuses,
            reverse_migrate_ticket_statuses,
        ),
    ]