# Generated by Django 5.2.5 on 2025-09-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_auto_20250910_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Contact Email'),
        ),
    ]
