# Generated by Django 5.2.12 on 2026-03-11 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('customers', '0001_initial'),
        ('orders', '0003_initial'),
        ('products', '0002_initial'),
        ('provisioning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='creditledger',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_credit_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditledger',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_entries', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='fxrate',
            name='base_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_rates', to='billing.currency'),
        ),
        migrations.AddField(
            model_name='fxrate',
            name='quote_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_rates', to='billing.currency'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.currency'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='invoices', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='efacturadocument',
            name='invoice',
            field=models.OneToOneField(help_text='The invoice this e-Factura document represents', on_delete=django.db.models.deletion.CASCADE, related_name='efactura_document', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='creditledger',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='billingcycle',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_cycles', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='service',
            field=models.ForeignKey(blank=True, help_text='Related service if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, to='provisioning.service'),
        ),
        migrations.AddIndex(
            model_name='oauthtoken',
            index=models.Index(fields=['cui', 'is_active'], name='billing_efa_cui_59539d_idx'),
        ),
        migrations.AddIndex(
            model_name='oauthtoken',
            index=models.Index(fields=['expires_at'], name='billing_efa_expires_1c177c_idx'),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.currency'),
        ),
        migrations.AddField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='payments', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='creditledger',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.payment'),
        ),
        migrations.AddField(
            model_name='paymentcollectionrun',
            name='triggered_by',
            field=models.ForeignKey(blank=True, help_text='User who triggered manual run', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentretryattempt',
            name='payment',
            field=models.ForeignKey(help_text='Original failed payment', on_delete=django.db.models.deletion.CASCADE, related_name='retry_attempts', to='billing.payment'),
        ),
        migrations.AddField(
            model_name='paymentretryattempt',
            name='policy',
            field=models.ForeignKey(help_text='Retry policy used for this attempt', on_delete=django.db.models.deletion.PROTECT, to='billing.paymentretrypolicy'),
        ),
        migrations.AddField(
            model_name='pricegrandfathering',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_grandfathering', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pricegrandfathering',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grandfathered_prices', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='pricegrandfathering',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grandfathered_customers', to='products.product'),
        ),
        migrations.AddField(
            model_name='pricingtier',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.currency'),
        ),
        migrations.AddField(
            model_name='pricingtierbracket',
            name='pricing_tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brackets', to='billing.pricingtier'),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.currency'),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='proforma_invoices', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='converted_from_proforma',
            field=models.ForeignKey(blank=True, help_text='Proforma that was converted to this invoice', null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.proformainvoice'),
        ),
        migrations.AddField(
            model_name='proformaline',
            name='proforma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.proformainvoice'),
        ),
        migrations.AddField(
            model_name='proformaline',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='provisioning.service'),
        ),
        migrations.AddField(
            model_name='refund',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_refunds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refund',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_refunds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refund',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.currency'),
        ),
        migrations.AddField(
            model_name='refund',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='refunds', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='refund',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='refunds', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='refund',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='refunds', to='orders.order'),
        ),
        migrations.AddField(
            model_name='refund',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='billing.payment'),
        ),
        migrations.AddField(
            model_name='refund',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_refunds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refundnote',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refundnote',
            name='refund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='billing.refund'),
        ),
        migrations.AddField(
            model_name='refundstatushistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refundstatushistory',
            name='refund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='billing.refund'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscription',
            name='currency',
            field=models.ForeignKey(help_text='Currency for this subscription', on_delete=django.db.models.deletion.PROTECT, to='billing.currency'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='customer',
            field=models.ForeignKey(help_text='Customer who owns this subscription', on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='product',
            field=models.ForeignKey(help_text='Product/plan being subscribed to', on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='products.product'),
        ),
        migrations.AddField(
            model_name='billingcycle',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_cycles', to='billing.subscription'),
        ),
        migrations.AddField(
            model_name='subscriptionchange',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_changes_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscriptionchange',
            name='invoice',
            field=models.ForeignKey(blank=True, help_text='Invoice generated for proration charge', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_changes', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='subscriptionchange',
            name='new_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_changes_to', to='products.product'),
        ),
        migrations.AddField(
            model_name='subscriptionchange',
            name='old_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_changes_from', to='products.product'),
        ),
        migrations.AddField(
            model_name='subscriptionchange',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='billing.subscription'),
        ),
        migrations.AddField(
            model_name='subscriptionitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_items', to='products.product'),
        ),
        migrations.AddField(
            model_name='subscriptionitem',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.subscription'),
        ),
        migrations.AddIndex(
            model_name='taxrule',
            index=models.Index(fields=['country_code', 'tax_type'], name='billing_tax_country_e50014_idx'),
        ),
        migrations.AddIndex(
            model_name='taxrule',
            index=models.Index(fields=['valid_from', 'valid_to'], name='billing_tax_valid_f_c5d4e0_idx'),
        ),
        migrations.AddIndex(
            model_name='taxrule',
            index=models.Index(fields=['is_eu_member'], name='billing_tax_is_eu_m_a7f741_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taxrule',
            unique_together={('country_code', 'region', 'tax_type', 'valid_from')},
        ),
        migrations.AddField(
            model_name='usageaggregation',
            name='billing_cycle',
            field=models.ForeignKey(help_text='Billing cycle this aggregation belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='usage_aggregations', to='billing.billingcycle'),
        ),
        migrations.AddField(
            model_name='usageaggregation',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_aggregations', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='usageaggregation',
            name='invoice_line',
            field=models.ForeignKey(blank=True, help_text='Invoice line generated from this aggregation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_aggregations', to='billing.invoiceline'),
        ),
        migrations.AddField(
            model_name='usageaggregation',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_aggregations', to='billing.subscription'),
        ),
        migrations.AddField(
            model_name='usagealert',
            name='aggregation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='billing.usageaggregation'),
        ),
        migrations.AddField(
            model_name='usagealert',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_alerts', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='usagealert',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_usage_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usagealert',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_alerts', to='billing.subscription'),
        ),
        migrations.AddField(
            model_name='usageevent',
            name='aggregation',
            field=models.ForeignKey(blank=True, help_text='Aggregation record this event was processed into', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='billing.usageaggregation'),
        ),
        migrations.AddField(
            model_name='usageevent',
            name='customer',
            field=models.ForeignKey(help_text='Customer who generated this usage', on_delete=django.db.models.deletion.CASCADE, related_name='usage_events', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='usageevent',
            name='service',
            field=models.ForeignKey(blank=True, help_text='Service that generated this usage', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_events', to='provisioning.service'),
        ),
        migrations.AddField(
            model_name='usageevent',
            name='subscription',
            field=models.ForeignKey(blank=True, help_text='Subscription this usage is billed against', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_events', to='billing.subscription'),
        ),
        migrations.AddIndex(
            model_name='usagemeter',
            index=models.Index(fields=['name'], name='billing_usa_name_78a6f6_idx'),
        ),
        migrations.AddIndex(
            model_name='usagemeter',
            index=models.Index(fields=['category', 'is_active'], name='billing_usa_categor_f35643_idx'),
        ),
        migrations.AddIndex(
            model_name='usagemeter',
            index=models.Index(fields=['stripe_meter_id'], name='billing_usa_stripe__2d291e_idx'),
        ),
        migrations.AddField(
            model_name='usageevent',
            name='meter',
            field=models.ForeignKey(help_text='Which meter this event belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='events', to='billing.usagemeter'),
        ),
        migrations.AddField(
            model_name='usageaggregation',
            name='meter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aggregations', to='billing.usagemeter'),
        ),
        migrations.AddField(
            model_name='pricingtier',
            name='meter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_tiers', to='billing.usagemeter'),
        ),
        migrations.AddField(
            model_name='usagethreshold',
            name='meter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thresholds', to='billing.usagemeter'),
        ),
        migrations.AddField(
            model_name='usagethreshold',
            name='service_plan',
            field=models.ForeignKey(blank=True, help_text='Apply to specific plan (null = all plans)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_thresholds', to='provisioning.serviceplan'),
        ),
        migrations.AddField(
            model_name='usagealert',
            name='threshold',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='billing.usagethreshold'),
        ),
        migrations.AddIndex(
            model_name='vatvalidation',
            index=models.Index(fields=['full_vat_number'], name='billing_vat_full_va_e5eef0_idx'),
        ),
        migrations.AddIndex(
            model_name='vatvalidation',
            index=models.Index(fields=['validation_date'], name='billing_vat_validat_81c163_idx'),
        ),
        migrations.AddIndex(
            model_name='vatvalidation',
            index=models.Index(fields=['expires_at'], name='billing_vat_expires_b9bce9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vatvalidation',
            unique_together={('country_code', 'vat_number')},
        ),
        migrations.AddIndex(
            model_name='fxrate',
            index=models.Index(fields=['base_code', 'quote_code', '-as_of'], name='billing_fx__base_co_147da6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fxrate',
            unique_together={('base_code', 'quote_code', 'as_of')},
        ),
        migrations.AddIndex(
            model_name='efacturadocument',
            index=models.Index(condition=models.Q(('status__in', ['submitted', 'processing'])), fields=['status', 'submitted_at'], name='efactura_status_submitted_idx'),
        ),
        migrations.AddIndex(
            model_name='efacturadocument',
            index=models.Index(condition=models.Q(('next_retry_at__isnull', False), ('status', 'error')), fields=['status', 'next_retry_at'], name='efactura_retry_idx'),
        ),
        migrations.AddIndex(
            model_name='efacturadocument',
            index=models.Index(fields=['anaf_upload_index'], name='efactura_upload_idx'),
        ),
        migrations.AddIndex(
            model_name='efacturadocument',
            index=models.Index(fields=['invoice'], name='efactura_invoice_idx'),
        ),
        migrations.AddConstraint(
            model_name='efacturadocument',
            constraint=models.UniqueConstraint(fields=('invoice',), name='unique_efactura_per_invoice'),
        ),
        migrations.AddConstraint(
            model_name='efacturadocument',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'queued', 'submitted', 'processing', 'accepted', 'rejected', 'error'])), name='efactura_valid_status'),
        ),
        migrations.AddIndex(
            model_name='invoiceline',
            index=models.Index(fields=['service'], name='billing_inv_service_58ba74_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceline',
            index=models.Index(fields=['invoice', 'kind'], name='billing_inv_invoice_16d1be_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoiceline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price_cents__gte', 0)), name='invoiceline_unit_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='invoiceline',
            constraint=models.CheckConstraint(condition=models.Q(('tax_cents__gte', 0)), name='invoiceline_tax_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='invoiceline',
            constraint=models.CheckConstraint(condition=models.Q(('line_total_cents__gte', 0)), name='invoiceline_line_total_non_negative'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['customer', '-received_at'], name='billing_pay_custome_0bb87f_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='billing_pay_status_d79ab7_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_method'], name='billing_pay_payment_595f7b_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['gateway_txn_id'], name='billing_pay_gateway_73101c_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount_cents__gte', 0)), name='payment_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'succeeded', 'failed', 'refunded', 'partially_refunded'])), name='payment_status_valid_values'),
        ),
        migrations.AddIndex(
            model_name='creditledger',
            index=models.Index(fields=['customer', '-created_at'], name='billing_cre_custome_6f5abf_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentcollectionrun',
            index=models.Index(fields=['-started_at'], name='billing_pay_started_714466_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentcollectionrun',
            index=models.Index(fields=['status'], name='billing_pay_status_3337d4_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentcollectionrun',
            index=models.Index(fields=['run_type', '-started_at'], name='billing_pay_run_typ_98a8f1_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentretryattempt',
            index=models.Index(fields=['scheduled_at', 'status'], name='billing_pay_schedul_823f86_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentretryattempt',
            index=models.Index(fields=['payment', '-attempt_number'], name='billing_pay_payment_878c2f_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentretryattempt',
            index=models.Index(fields=['status', 'executed_at'], name='billing_pay_status_2c212f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentretryattempt',
            unique_together={('payment', 'attempt_number')},
        ),
        migrations.AddIndex(
            model_name='pricegrandfathering',
            index=models.Index(fields=['customer', 'is_active'], name='billing_pri_custome_f320ed_idx'),
        ),
        migrations.AddIndex(
            model_name='pricegrandfathering',
            index=models.Index(fields=['product', 'is_active'], name='billing_pri_product_99ea34_idx'),
        ),
        migrations.AddIndex(
            model_name='pricegrandfathering',
            index=models.Index(fields=['expires_at', 'is_active'], name='billing_pri_expires_74f1f2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pricegrandfathering',
            unique_together={('customer', 'product')},
        ),
        migrations.AddConstraint(
            model_name='pricingtierbracket',
            constraint=models.UniqueConstraint(fields=('pricing_tier', 'from_quantity'), name='unique_tier_bracket_start'),
        ),
        migrations.AddIndex(
            model_name='proformainvoice',
            index=models.Index(fields=['customer'], name='billing_pro_custome_de8328_idx'),
        ),
        migrations.AddIndex(
            model_name='proformainvoice',
            index=models.Index(fields=['valid_until'], name='billing_pro_valid_u_315f28_idx'),
        ),
        migrations.AddIndex(
            model_name='proformainvoice',
            index=models.Index(fields=['created_at'], name='billing_pro_created_aa861b_idx'),
        ),
        migrations.AddConstraint(
            model_name='proformainvoice',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal_cents__gte', 0)), name='proformainvoice_subtotal_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='proformainvoice',
            constraint=models.CheckConstraint(condition=models.Q(('tax_cents__gte', 0)), name='proformainvoice_tax_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='proformainvoice',
            constraint=models.CheckConstraint(condition=models.Q(('total_cents__gte', 0)), name='proformainvoice_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='proformainvoice',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'sent', 'accepted', 'expired', 'converted'])), name='proformainvoice_status_valid_values'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['customer', '-created_at'], name='billing_inv_custome_ff0dec_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(condition=models.Q(('status__in', ['issued', 'overdue'])), fields=['customer'], name='bill_inv_cust_pending'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', '-due_at'], name='billing_inv_status_af46fe_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['number'], name='billing_inv_number_7aebea_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal_cents__gte', 0)), name='invoice_subtotal_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('tax_cents__gte', 0)), name='invoice_tax_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('total_cents__gte', 0)), name='invoice_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'issued', 'paid', 'overdue', 'void', 'refunded', 'partially_refunded'])), name='invoice_status_valid_values'),
        ),
        migrations.AddIndex(
            model_name='proformaline',
            index=models.Index(fields=['service'], name='billing_pro_service_e9cf4b_idx'),
        ),
        migrations.AddConstraint(
            model_name='proformaline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price_cents__gte', 0)), name='proformaline_unit_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='proformaline',
            constraint=models.CheckConstraint(condition=models.Q(('tax_cents__gte', 0)), name='proformaline_tax_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='proformaline',
            constraint=models.CheckConstraint(condition=models.Q(('line_total_cents__gte', 0)), name='proformaline_line_total_non_negative'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['customer', '-created_at'], name='billing_ref_custome_b4b9f1_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['status', '-created_at'], name='billing_ref_status_d869b7_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['refund_type'], name='billing_ref_refund__5cbcf8_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['reason'], name='billing_ref_reason_f11d36_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['gateway_refund_id'], name='billing_ref_gateway_7d5c96_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['reference_number'], name='billing_ref_referen_f35edd_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['order'], name='billing_ref_order_i_e72a6d_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['invoice'], name='billing_ref_invoice_003dc8_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['payment'], name='billing_ref_payment_141c76_idx'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('order__isnull', False), ('invoice__isnull', True)), models.Q(('order__isnull', True), ('invoice__isnull', False)), _connector='OR'), name='refund_order_or_invoice_not_both'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(('amount_cents__gt', 0)), name='refund_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'processing', 'approved', 'completed', 'rejected', 'failed', 'cancelled'])), name='refund_status_valid_values'),
        ),
        migrations.AddIndex(
            model_name='refundnote',
            index=models.Index(fields=['refund', '-created_at'], name='billing_ref_refund__89f8c1_idx'),
        ),
        migrations.AddIndex(
            model_name='refundnote',
            index=models.Index(fields=['note_type', '-created_at'], name='billing_ref_note_ty_fc326f_idx'),
        ),
        migrations.AddIndex(
            model_name='refundnote',
            index=models.Index(fields=['is_customer_visible', '-created_at'], name='billing_ref_is_cust_56af07_idx'),
        ),
        migrations.AddIndex(
            model_name='refundstatushistory',
            index=models.Index(fields=['refund', '-changed_at'], name='billing_ref_refund__de7990_idx'),
        ),
        migrations.AddIndex(
            model_name='refundstatushistory',
            index=models.Index(fields=['new_status', '-changed_at'], name='billing_ref_new_sta_b3a6a9_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['customer', 'status'], name='billing_sub_custome_9c406a_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status', 'next_billing_date'], name='billing_sub_status_487d48_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['product', 'status'], name='billing_sub_product_61f3a0_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['stripe_subscription_id'], name='billing_sub_stripe__4b5970_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(condition=models.Q(('status', 'active')), fields=['status', 'next_billing_date'], name='idx_active_billing_date'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price_cents__gte', 0)), name='subscription_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='subscription_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['trialing', 'active', 'past_due', 'paused', 'cancelled', 'expired', 'pending'])), name='subscription_status_valid_values'),
        ),
        migrations.AddIndex(
            model_name='billingcycle',
            index=models.Index(fields=['subscription', '-period_start'], name='billing_cyc_subscri_bd1d79_idx'),
        ),
        migrations.AddIndex(
            model_name='billingcycle',
            index=models.Index(fields=['status', 'period_end'], name='billing_cyc_status_c0c791_idx'),
        ),
        migrations.AddIndex(
            model_name='billingcycle',
            index=models.Index(fields=['status', '-period_start'], name='billing_cyc_status_89a35f_idx'),
        ),
        migrations.AddConstraint(
            model_name='billingcycle',
            constraint=models.UniqueConstraint(fields=('subscription', 'period_start'), name='unique_subscription_period'),
        ),
        migrations.AddConstraint(
            model_name='billingcycle',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['upcoming', 'active', 'closing', 'closed', 'invoiced', 'finalized'])), name='billingcycle_status_valid_values'),
        ),
        migrations.AddIndex(
            model_name='subscriptionchange',
            index=models.Index(fields=['subscription', '-created_at'], name='billing_sub_subscri_2b041e_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionchange',
            index=models.Index(fields=['status', 'effective_date'], name='billing_sub_status_bb1cb2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subscriptionitem',
            unique_together={('subscription', 'product')},
        ),
        migrations.AddIndex(
            model_name='usageevent',
            index=models.Index(fields=['customer', '-timestamp'], name='billing_usa_custome_78d373_idx'),
        ),
        migrations.AddIndex(
            model_name='usageevent',
            index=models.Index(fields=['meter', '-timestamp'], name='billing_usa_meter_i_d12af0_idx'),
        ),
        migrations.AddIndex(
            model_name='usageevent',
            index=models.Index(fields=['subscription', '-timestamp'], name='billing_usa_subscri_4661f0_idx'),
        ),
        migrations.AddIndex(
            model_name='usageevent',
            index=models.Index(fields=['service', '-timestamp'], name='billing_usa_service_7e96de_idx'),
        ),
        migrations.AddIndex(
            model_name='usageevent',
            index=models.Index(fields=['is_processed', '-timestamp'], name='billing_usa_is_proc_e69e31_idx'),
        ),
        migrations.AddIndex(
            model_name='usageevent',
            index=models.Index(fields=['meter', 'customer', 'timestamp'], name='billing_usa_meter_i_8177d9_idx'),
        ),
        migrations.AddIndex(
            model_name='usageevent',
            index=models.Index(fields=['meter', 'customer', 'is_processed'], name='usage_evt_pending_agg'),
        ),
        migrations.AddConstraint(
            model_name='usageevent',
            constraint=models.UniqueConstraint(fields=('meter', 'customer', 'idempotency_key'), name='unique_usage_event_idempotency'),
        ),
        migrations.AddIndex(
            model_name='usageaggregation',
            index=models.Index(fields=['customer', '-period_start'], name='billing_usa_custome_44d009_idx'),
        ),
        migrations.AddIndex(
            model_name='usageaggregation',
            index=models.Index(fields=['meter', 'status'], name='billing_usa_meter_i_afeb37_idx'),
        ),
        migrations.AddIndex(
            model_name='usageaggregation',
            index=models.Index(fields=['billing_cycle', 'status'], name='billing_usa_billing_c8994a_idx'),
        ),
        migrations.AddIndex(
            model_name='usageaggregation',
            index=models.Index(fields=['status', '-period_start'], name='billing_usa_status_27559b_idx'),
        ),
        migrations.AddIndex(
            model_name='usageaggregation',
            index=models.Index(condition=models.Q(('status', 'rated')), fields=['status', 'customer'], name='usage_agg_ready_invoice'),
        ),
        migrations.AddConstraint(
            model_name='usageaggregation',
            constraint=models.UniqueConstraint(fields=('meter', 'customer', 'billing_cycle'), name='unique_meter_customer_cycle'),
        ),
        migrations.AddConstraint(
            model_name='usageaggregation',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['accumulating', 'pending_rating', 'rated', 'invoiced', 'finalized'])), name='usageaggregation_status_valid_values'),
        ),
        migrations.AddIndex(
            model_name='pricingtier',
            index=models.Index(fields=['meter', 'is_active'], name='billing_pri_meter_i_bd80a8_idx'),
        ),
        migrations.AddIndex(
            model_name='pricingtier',
            index=models.Index(fields=['meter', 'is_default'], name='billing_pri_meter_i_c197c0_idx'),
        ),
        migrations.AddIndex(
            model_name='usagethreshold',
            index=models.Index(fields=['meter', 'is_active'], name='billing_usa_meter_i_833ad2_idx'),
        ),
        migrations.AddIndex(
            model_name='usagethreshold',
            index=models.Index(fields=['service_plan', 'is_active'], name='billing_usa_service_b1dcb9_idx'),
        ),
        migrations.AddIndex(
            model_name='usagealert',
            index=models.Index(fields=['customer', '-created_at'], name='billing_usa_custome_b5d776_idx'),
        ),
        migrations.AddIndex(
            model_name='usagealert',
            index=models.Index(fields=['status', '-created_at'], name='billing_usa_status_f58c69_idx'),
        ),
        migrations.AddIndex(
            model_name='usagealert',
            index=models.Index(fields=['threshold', '-created_at'], name='billing_usa_thresho_074380_idx'),
        ),
        migrations.AddIndex(
            model_name='usagealert',
            index=models.Index(condition=models.Q(('status__in', ['pending', 'sent'])), fields=['status', 'customer'], name='usage_alert_unresolved'),
        ),
    ]
