# Generated by Django 5.2.5 on 2025-09-13 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('customers', '0001_initial'),
        ('orders', '0002_initial'),
        ('provisioning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='creditledger',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_credit_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditledger',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_entries', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='fxrate',
            name='base_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_rates', to='billing.currency'),
        ),
        migrations.AddField(
            model_name='fxrate',
            name='quote_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_rates', to='billing.currency'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.currency'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='invoices', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='creditledger',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='service',
            field=models.ForeignKey(blank=True, help_text='Related service if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, to='provisioning.service'),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.currency'),
        ),
        migrations.AddField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='payments', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='creditledger',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.payment'),
        ),
        migrations.AddField(
            model_name='paymentcollectionrun',
            name='triggered_by',
            field=models.ForeignKey(blank=True, help_text='User who triggered manual run', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentretryattempt',
            name='payment',
            field=models.ForeignKey(help_text='Original failed payment', on_delete=django.db.models.deletion.CASCADE, related_name='retry_attempts', to='billing.payment'),
        ),
        migrations.AddField(
            model_name='paymentretryattempt',
            name='policy',
            field=models.ForeignKey(help_text='Retry policy used for this attempt', on_delete=django.db.models.deletion.PROTECT, to='billing.paymentretrypolicy'),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.currency'),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='proforma_invoices', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='converted_from_proforma',
            field=models.ForeignKey(blank=True, help_text='Proforma that was converted to this invoice', null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.proformainvoice'),
        ),
        migrations.AddField(
            model_name='proformaline',
            name='proforma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.proformainvoice'),
        ),
        migrations.AddField(
            model_name='proformaline',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='provisioning.service'),
        ),
        migrations.AddField(
            model_name='refund',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_refunds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refund',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_refunds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refund',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.currency'),
        ),
        migrations.AddField(
            model_name='refund',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='refunds', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='refund',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='refunds', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='refund',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='refunds', to='orders.order'),
        ),
        migrations.AddField(
            model_name='refund',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='billing.payment'),
        ),
        migrations.AddField(
            model_name='refund',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_refunds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refundnote',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refundnote',
            name='refund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='billing.refund'),
        ),
        migrations.AddField(
            model_name='refundstatushistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refundstatushistory',
            name='refund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='billing.refund'),
        ),
        migrations.AddIndex(
            model_name='taxrule',
            index=models.Index(fields=['country_code', 'tax_type'], name='tax_rules_country_eef407_idx'),
        ),
        migrations.AddIndex(
            model_name='taxrule',
            index=models.Index(fields=['valid_from', 'valid_to'], name='tax_rules_valid_f_628e80_idx'),
        ),
        migrations.AddIndex(
            model_name='taxrule',
            index=models.Index(fields=['is_eu_member'], name='tax_rules_is_eu_m_7692a7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taxrule',
            unique_together={('country_code', 'region', 'tax_type', 'valid_from')},
        ),
        migrations.AddIndex(
            model_name='vatvalidation',
            index=models.Index(fields=['full_vat_number'], name='vat_validat_full_va_de39fa_idx'),
        ),
        migrations.AddIndex(
            model_name='vatvalidation',
            index=models.Index(fields=['validation_date'], name='vat_validat_validat_71fc91_idx'),
        ),
        migrations.AddIndex(
            model_name='vatvalidation',
            index=models.Index(fields=['expires_at'], name='vat_validat_expires_e138e8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vatvalidation',
            unique_together={('country_code', 'vat_number')},
        ),
        migrations.AddIndex(
            model_name='fxrate',
            index=models.Index(fields=['base_code', 'quote_code', '-as_of'], name='fx_rate_base_co_067654_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fxrate',
            unique_together={('base_code', 'quote_code', 'as_of')},
        ),
        migrations.AddIndex(
            model_name='invoiceline',
            index=models.Index(fields=['service'], name='invoice_lin_service_6ba9c3_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceline',
            index=models.Index(fields=['invoice', 'kind'], name='invoice_lin_invoice_6b7646_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['customer', '-received_at'], name='payment_custome_7d6bc4_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payment_status_1c1ab2_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_method'], name='payment_payment_d8e241_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['gateway_txn_id'], name='payment_gateway_51ee80_idx'),
        ),
        migrations.AddIndex(
            model_name='creditledger',
            index=models.Index(fields=['customer', '-created_at'], name='credit_ledg_custome_e45542_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentcollectionrun',
            index=models.Index(fields=['-started_at'], name='payment_col_started_003cea_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentcollectionrun',
            index=models.Index(fields=['status'], name='payment_col_status_84a646_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentcollectionrun',
            index=models.Index(fields=['run_type', '-started_at'], name='payment_col_run_typ_c01d86_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentretryattempt',
            index=models.Index(fields=['scheduled_at', 'status'], name='payment_ret_schedul_f238b6_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentretryattempt',
            index=models.Index(fields=['payment', '-attempt_number'], name='payment_ret_payment_2c2e2e_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentretryattempt',
            index=models.Index(fields=['status', 'executed_at'], name='payment_ret_status_6a0dcc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentretryattempt',
            unique_together={('payment', 'attempt_number')},
        ),
        migrations.AddIndex(
            model_name='proformainvoice',
            index=models.Index(fields=['customer'], name='proforma_in_custome_0be8c0_idx'),
        ),
        migrations.AddIndex(
            model_name='proformainvoice',
            index=models.Index(fields=['valid_until'], name='proforma_in_valid_u_415825_idx'),
        ),
        migrations.AddIndex(
            model_name='proformainvoice',
            index=models.Index(fields=['created_at'], name='proforma_in_created_bf713d_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['customer', '-created_at'], name='invoice_custome_b24946_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(condition=models.Q(('status__in', ['issued', 'overdue'])), fields=['customer'], name='bill_inv_cust_pending'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', '-due_at'], name='invoice_status_3d15ba_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['number'], name='invoice_number_45da71_idx'),
        ),
        migrations.AddIndex(
            model_name='proformaline',
            index=models.Index(fields=['service'], name='proforma_li_service_94c383_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['customer', '-created_at'], name='refunds_custome_2ca0e4_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['status', '-created_at'], name='refunds_status_318f0e_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['refund_type'], name='refunds_refund__c154fb_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['reason'], name='refunds_reason_824f43_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['gateway_refund_id'], name='refunds_gateway_6faa77_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['reference_number'], name='refunds_referen_76e208_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['order'], name='refunds_order_i_20e1f6_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['invoice'], name='refunds_invoice_c06d20_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['payment'], name='refunds_payment_0cace6_idx'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('order__isnull', False), ('invoice__isnull', True)), models.Q(('order__isnull', True), ('invoice__isnull', False)), _connector='OR'), name='refund_order_or_invoice_not_both'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(('amount_cents__gt', 0)), name='refund_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='refundnote',
            index=models.Index(fields=['refund', '-created_at'], name='refund_note_refund__685e9e_idx'),
        ),
        migrations.AddIndex(
            model_name='refundnote',
            index=models.Index(fields=['note_type', '-created_at'], name='refund_note_note_ty_63b7ed_idx'),
        ),
        migrations.AddIndex(
            model_name='refundnote',
            index=models.Index(fields=['is_customer_visible', '-created_at'], name='refund_note_is_cust_f248bb_idx'),
        ),
        migrations.AddIndex(
            model_name='refundstatushistory',
            index=models.Index(fields=['refund', '-changed_at'], name='refund_stat_refund__ec528e_idx'),
        ),
        migrations.AddIndex(
            model_name='refundstatushistory',
            index=models.Index(fields=['new_status', '-changed_at'], name='refund_stat_new_sta_add141_idx'),
        ),
    ]
