# Generated by Django 5.2.5 on 2025-08-28 05:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_paymentcollectionrun_options_and_more'),
        ('customers', '0003_rename_payment_method_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='payment',
            name='payment_method_b492a6_idx',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='method',
            new_name='payment_method',
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_method'], name='payment_payment_d8e241_idx'),
        ),
    ]
