# Generated by Django 5.2.17 on 2026-10-03 07:24

import uuid

import django.db.models.deletion
import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_seed_supported_currencies'),
        ('promotions', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalCorrection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', django_fsm.FSMField(choices=[('pending', 'Pending'), ('not_required', 'Not required'), ('attached', 'Attached to a provider credit note')], default='pending', max_length=24, protected=True)),
                ('not_required_reason', models.CharField(blank=True, choices=[('no_fiscal_document', 'No issued, numbered invoice to correct')], max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit_note', models.OneToOneField(blank=True, help_text='The credit note that settles this correction', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settled_fiscal_correction', to='billing.invoice')),
                ('original', models.ForeignKey(blank=True, help_text='The issued invoice this correction reduces; empty only when no fiscal document exists', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_corrections', to='billing.invoice')),
                ('source_command', models.OneToOneField(blank=True, help_text='The tender refund command whose legs this correction answers for', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_correction', to='promotions.tenderrefundcommand')),
                ('source_refund', models.OneToOneField(blank=True, help_text='The direct refund this correction answers for', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_correction', to='billing.refund')),
            ],
            options={
                'verbose_name': 'Fiscal Correction',
                'verbose_name_plural': 'Fiscal Corrections',
                'db_table': 'billing_fiscal_corrections',
                'indexes': [models.Index(fields=['state', 'created_at'], name='bill_fiscorr_state_created'), models.Index(fields=['original', 'state'], name='bill_fiscorr_original_state')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('source_refund__isnull', False), ('source_command__isnull', True)), models.Q(('source_refund__isnull', True), ('source_command__isnull', False)), _connector='OR'), name='fiscal_correction_exactly_one_source'), models.CheckConstraint(condition=models.Q(('state__in', ['pending', 'not_required', 'attached'])), name='fiscal_correction_state_valid_values'), models.CheckConstraint(condition=models.Q(('original__isnull', False), ('state', 'not_required'), _connector='OR'), name='fiscal_correction_original_unless_not_required'), models.CheckConstraint(condition=models.Q(models.Q(('state', 'attached'), ('credit_note__isnull', False)), models.Q(models.Q(('state', 'attached'), _negated=True), ('credit_note__isnull', True)), _connector='OR'), name='fiscal_correction_credit_note_iff_attached'), models.CheckConstraint(condition=models.Q(models.Q(('state', 'not_required'), _negated=True), models.Q(('not_required_reason', ''), _negated=True), _connector='OR'), name='fiscal_correction_not_required_has_reason')],
            },
        ),
    ]
