# Generated by Django 5.2.17 on 2026-10-04 06:13

import django.db.models.expressions
import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_fiscal_correction'),
        ('promotions', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fiscalcorrection',
            name='fiscal_correction_state_valid_values',
        ),
        migrations.RemoveConstraint(
            model_name='fiscalcorrection',
            name='fiscal_correction_credit_note_iff_attached',
        ),
        migrations.AddField(
            model_name='fiscalcorrection',
            name='allocated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fiscalcorrection',
            name='base_cents',
            field=models.BigIntegerField(blank=True, help_text='Allocated taxable base (signed)', null=True),
        ),
        migrations.AddField(
            model_name='fiscalcorrection',
            name='communicated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fiscalcorrection',
            name='communication_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fiscalcorrection',
            name='communication_claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fiscalcorrection',
            name='communication_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fiscalcorrection',
            name='discount_cents',
            field=models.BigIntegerField(blank=True, help_text='Allocated document discount (signed)', null=True),
        ),
        migrations.AddField(
            model_name='fiscalcorrection',
            name='efactura_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fiscalcorrection',
            name='efactura_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fiscalcorrection',
            name='efactura_next_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fiscalcorrection',
            name='efactura_status',
            field=django_fsm.FSMField(choices=[('not_due', 'Not due'), ('pending', 'Pending'), ('not_applicable', 'Not applicable'), ('waiting_for_original', 'Waiting for the original to be accepted'), ('original_rejected', 'Original rejected, needs review'), ('submitted', 'Submitted'), ('failed', 'Failed, will be retried')], default='not_due', max_length=24, protected=True),
        ),
        migrations.AddField(
            model_name='fiscalcorrection',
            name='failure_code',
            field=models.CharField(blank=True, choices=[('allocation_refused', 'The amount could not be allocated'), ('issuance_error', 'The credit note could not be issued'), ('awaiting_second_credit_note_support', 'The original already has a credit note')], max_length=64),
        ),
        migrations.AddField(
            model_name='fiscalcorrection',
            name='fiscal_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fiscalcorrection',
            name='last_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fiscalcorrection',
            name='tax_cents',
            field=models.BigIntegerField(blank=True, help_text='Allocated VAT (signed)', null=True),
        ),
        migrations.AddField(
            model_name='fiscalcorrection',
            name='total_cents',
            field=models.BigIntegerField(blank=True, help_text='Allocated gross (signed)', null=True),
        ),
        migrations.AddField(
            model_name='fiscalcorrection',
            name='vat_residue_cents',
            field=models.BigIntegerField(blank=True, help_text='VAT of the original this credit note leaves un-reversed (negative: reverses beyond it)', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sequence_scope',
            field=models.CharField(blank=True, default='', help_text='The local numbering family the legal number came from; empty for provider-numbered documents', max_length=50),
        ),
        migrations.AlterField(
            model_name='fiscalcorrection',
            name='not_required_reason',
            field=models.CharField(blank=True, choices=[('no_fiscal_document', 'No issued, numbered invoice to correct'), ('covered_by_collections', 'The refund returned money the invoice did not need'), ('fully_credited', 'Earlier corrections already credit the whole invoice')], max_length=64),
        ),
        migrations.AlterField(
            model_name='fiscalcorrection',
            name='state',
            field=django_fsm.FSMField(choices=[('pending', 'Pending'), ('not_required', 'Not required'), ('attached', 'Attached to a provider credit note'), ('allocated', 'Allocated, awaiting issuance'), ('issued', 'Credit note issued'), ('communicated', 'Credit note sent to the customer'), ('failed', 'Failed, will be retried')], default='pending', max_length=24, protected=True),
        ),
        migrations.AddIndex(
            model_name='fiscalcorrection',
            index=models.Index(fields=['efactura_status', 'created_at'], name='bill_fiscorr_efactura_created'),
        ),
        migrations.AddConstraint(
            model_name='fiscalcorrection',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ['pending', 'not_required', 'attached', 'allocated', 'issued', 'communicated', 'failed'])), name='fiscal_correction_state_valid_values'),
        ),
        migrations.AddConstraint(
            model_name='fiscalcorrection',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('state__in', ['attached', 'communicated', 'issued']), ('credit_note__isnull', False)), models.Q(models.Q(('state__in', ['attached', 'communicated', 'issued']), _negated=True), ('credit_note__isnull', True)), _connector='OR'), name='fiscal_correction_credit_note_iff_settled'),
        ),
        migrations.AddConstraint(
            model_name='fiscalcorrection',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('allocated_at__isnull', True), ('base_cents__isnull', True), ('discount_cents__isnull', True), ('tax_cents__isnull', True), ('total_cents__isnull', True), ('vat_residue_cents__isnull', True)), models.Q(('allocated_at__isnull', False), ('base_cents__lte', 0), ('discount_cents__lte', 0), ('tax_cents__lte', 0), ('total_cents', django.db.models.expressions.CombinedExpression(models.F('base_cents'), '+', models.F('tax_cents'))), ('total_cents__lt', 0), ('vat_residue_cents__isnull', False)), _connector='OR'), name='fiscal_correction_allocation_complete'),
        ),
        migrations.AddConstraint(
            model_name='fiscalcorrection',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('allocated_at__isnull', False), ('state__in', ['allocated', 'communicated', 'issued'])), models.Q(('allocated_at__isnull', True), ('state__in', ['pending', 'not_required', 'attached'])), ('state', 'failed'), _connector='OR'), name='fiscal_correction_allocation_matches_state'),
        ),
        migrations.AddConstraint(
            model_name='fiscalcorrection',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('communicated_at__isnull', False), ('fiscal_date__isnull', False), ('state', 'communicated')), models.Q(models.Q(('state', 'communicated'), _negated=True), ('communicated_at__isnull', True), ('fiscal_date__isnull', True)), _connector='OR'), name='fiscal_correction_communicated_has_date'),
        ),
        migrations.AddConstraint(
            model_name='fiscalcorrection',
            constraint=models.CheckConstraint(condition=models.Q(('efactura_status__in', ['not_due', 'pending', 'not_applicable', 'waiting_for_original', 'original_rejected', 'submitted', 'failed'])), name='fiscal_correction_efactura_valid_values'),
        ),
        migrations.AddConstraint(
            model_name='fiscalcorrection',
            constraint=models.CheckConstraint(condition=models.Q(('efactura_status', 'not_due'), ('state__in', ['issued', 'communicated']), _connector='OR'), name='fiscal_correction_efactura_needs_issued_note'),
        ),
    ]
