# Generated by Django 5.2.17 on 2026-10-04 14:15

import django.db.models.deletion
import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_builtin_storno_issuance'),
        ('promotions', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fiscalcorrection',
            name='fiscal_correction_state_valid_values',
        ),
        migrations.RemoveConstraint(
            model_name='fiscalcorrection',
            name='fiscal_correction_allocation_matches_state',
        ),
        migrations.RemoveConstraint(
            model_name='invoice',
            name='invoice_one_reversal_per_original',
        ),
        migrations.AddField(
            model_name='fiscalcorrection',
            name='communication_evidence',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='providerissuance',
            name='fiscal_correction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provider_issuance', to='billing.fiscalcorrection'),
        ),
        migrations.AlterField(
            model_name='fiscalcorrection',
            name='failure_code',
            field=models.CharField(blank=True, choices=[('allocation_refused', 'The amount could not be allocated'), ('issuance_error', 'The credit note could not be issued')], max_length=64),
        ),
        migrations.AlterField(
            model_name='fiscalcorrection',
            name='state',
            field=django_fsm.FSMField(choices=[('pending', 'Pending'), ('not_required', 'Not required'), ('attached', 'Attached to a provider credit note'), ('allocated', 'Allocated, awaiting issuance'), ('issued', 'Credit note issued'), ('communicated', 'Credit note sent to the customer'), ('failed', 'Failed, will be retried'), ('manual_required', 'Awaiting a credit note issued by staff at the provider')], default='pending', max_length=24, protected=True),
        ),
        migrations.AddConstraint(
            model_name='fiscalcorrection',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ['pending', 'not_required', 'attached', 'allocated', 'issued', 'communicated', 'failed', 'manual_required'])), name='fiscal_correction_state_valid_values'),
        ),
        migrations.AddConstraint(
            model_name='fiscalcorrection',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('allocated_at__isnull', False), ('state__in', ['allocated', 'communicated', 'issued', 'manual_required'])), models.Q(('allocated_at__isnull', True), ('state__in', ['pending', 'not_required', 'attached'])), ('state', 'failed'), _connector='OR'), name='fiscal_correction_allocation_matches_state'),
        ),
    ]
