# Generated by Django 5.2.5 on 2025-09-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_proformainvoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformainvoice',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes for the proforma'),
        ),
    ]
