# Generated by Django 5.2.5 on 2025-09-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_refund_refundnote_refundstatushistory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundstatushistory',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('processing', 'Processing'), ('approved', 'Approved'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='', max_length=20),
        ),
    ]
