# Generated by Django 5.2.9 on 2025-12-25 16:46

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0010_add_subscriptions_and_grandfathering"),
        ("customers", "0002_initial"),
        ("provisioning", "0014_usage_based_billing"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PricingTier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Pricing tier name (e.g., 'Standard Bandwidth')",
                        max_length=100,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "pricing_model",
                    models.CharField(
                        choices=[
                            ("per_unit", "Per Unit"),
                            ("volume", "Volume"),
                            ("graduated", "Graduated/Tiered"),
                            ("package", "Package"),
                        ],
                        default="per_unit",
                        max_length=20,
                    ),
                ),
                (
                    "unit_price_cents",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Price per unit in cents (for per_unit model)",
                        null=True,
                    ),
                ),
                (
                    "minimum_charge_cents",
                    models.BigIntegerField(
                        default=0, help_text="Minimum charge regardless of usage"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, help_text="Default tier for this meter"
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this pricing becomes effective",
                        null=True,
                    ),
                ),
                (
                    "valid_until",
                    models.DateTimeField(
                        blank=True, help_text="When this pricing expires", null=True
                    ),
                ),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="billing.currency",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pricing Tier",
                "verbose_name_plural": "Pricing Tiers",
                "db_table": "pricing_tiers",
                "ordering": ("meter", "name"),
            },
        ),
        migrations.CreateModel(
            name="BillingCycle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "Upcoming"),
                            ("active", "Active"),
                            ("closing", "Closing"),
                            ("closed", "Closed"),
                            ("invoiced", "Invoiced"),
                            ("finalized", "Finalized"),
                        ],
                        default="upcoming",
                        max_length=20,
                    ),
                ),
                (
                    "base_charge_cents",
                    models.BigIntegerField(
                        default=0, help_text="Fixed subscription charge for this period"
                    ),
                ),
                (
                    "usage_charge_cents",
                    models.BigIntegerField(
                        default=0, help_text="Total usage-based charges for this period"
                    ),
                ),
                (
                    "discount_cents",
                    models.BigIntegerField(default=0, help_text="Discounts applied"),
                ),
                (
                    "credit_applied_cents",
                    models.BigIntegerField(
                        default=0, help_text="Customer credit applied"
                    ),
                ),
                (
                    "tax_cents",
                    models.BigIntegerField(default=0, help_text="Tax amount"),
                ),
                (
                    "total_cents",
                    models.BigIntegerField(
                        default=0, help_text="Total amount due for this cycle"
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When cycle was closed for new events",
                        null=True,
                    ),
                ),
                (
                    "invoiced_at",
                    models.DateTimeField(
                        blank=True, help_text="When invoice was generated", null=True
                    ),
                ),
                (
                    "finalized_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When cycle was fully finalized",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("meta", models.JSONField(blank=True, default=dict)),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="billing_cycles",
                        to="billing.invoice",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_cycles",
                        to="billing.subscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Billing Cycle",
                "verbose_name_plural": "Billing Cycles",
                "db_table": "billing_cycles",
                "ordering": ("-period_start",),
            },
        ),
        migrations.CreateModel(
            name="UsageAggregation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "period_start",
                    models.DateTimeField(help_text="Start of aggregation period"),
                ),
                (
                    "period_end",
                    models.DateTimeField(help_text="End of aggregation period"),
                ),
                (
                    "total_value",
                    models.DecimalField(
                        decimal_places=8,
                        default=Decimal("0"),
                        help_text="Aggregated usage value for the period",
                        max_digits=18,
                    ),
                ),
                (
                    "event_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of events aggregated"
                    ),
                ),
                (
                    "unique_values",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Set of unique values for unique-count aggregation",
                    ),
                ),
                (
                    "max_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        help_text="Maximum value seen in period (for max aggregation)",
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "last_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        help_text="Most recent value (for last aggregation)",
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "last_value_at",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp of last value", null=True
                    ),
                ),
                (
                    "billable_value",
                    models.DecimalField(
                        decimal_places=8,
                        default=Decimal("0"),
                        help_text="Final billable amount after rounding",
                        max_digits=18,
                    ),
                ),
                (
                    "included_allowance",
                    models.DecimalField(
                        decimal_places=8,
                        default=Decimal("0"),
                        help_text="Usage included in subscription (no charge)",
                        max_digits=18,
                    ),
                ),
                (
                    "overage_value",
                    models.DecimalField(
                        decimal_places=8,
                        default=Decimal("0"),
                        help_text="Usage above included allowance (billable)",
                        max_digits=18,
                    ),
                ),
                (
                    "charge_cents",
                    models.BigIntegerField(
                        default=0, help_text="Calculated charge in cents"
                    ),
                ),
                (
                    "charge_calculated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When charge was last calculated",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("accumulating", "Accumulating"),
                            ("pending_rating", "Pending Rating"),
                            ("rated", "Rated"),
                            ("invoiced", "Invoiced"),
                            ("finalized", "Finalized"),
                        ],
                        default="accumulating",
                        max_length=20,
                    ),
                ),
                (
                    "stripe_usage_record_id",
                    models.CharField(
                        blank=True,
                        help_text="Stripe usage record ID for reconciliation",
                        max_length=100,
                    ),
                ),
                (
                    "stripe_synced_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When usage was synced to Stripe",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("meta", models.JSONField(blank=True, default=dict)),
                (
                    "billing_cycle",
                    models.ForeignKey(
                        help_text="Billing cycle this aggregation belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_aggregations",
                        to="billing.billingcycle",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_aggregations",
                        to="customers.customer",
                    ),
                ),
                (
                    "invoice_line",
                    models.ForeignKey(
                        blank=True,
                        help_text="Invoice line generated from this aggregation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usage_aggregations",
                        to="billing.invoiceline",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usage_aggregations",
                        to="billing.subscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usage Aggregation",
                "verbose_name_plural": "Usage Aggregations",
                "db_table": "usage_aggregations",
                "ordering": ("-period_start",),
            },
        ),
        migrations.CreateModel(
            name="UsageMeter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Internal meter name (e.g., 'disk_usage_gb', 'api_requests')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Human-readable name (e.g., 'Disk Space Usage')",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of what this meter tracks",
                    ),
                ),
                (
                    "stripe_meter_id",
                    models.CharField(
                        blank=True,
                        help_text="Stripe Meter ID for external billing sync",
                        max_length=100,
                    ),
                ),
                (
                    "stripe_meter_event_name",
                    models.CharField(
                        blank=True,
                        help_text="Event name configured in Stripe Meter",
                        max_length=100,
                    ),
                ),
                (
                    "aggregation_type",
                    models.CharField(
                        choices=[
                            ("sum", "Sum"),
                            ("count", "Count"),
                            ("max", "Maximum"),
                            ("last", "Last Value"),
                            ("unique", "Unique Count"),
                        ],
                        default="sum",
                        help_text="How to aggregate usage events over billing period",
                        max_length=20,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("bytes", "Bytes"),
                            ("kb", "Kilobytes"),
                            ("mb", "Megabytes"),
                            ("gb", "Gigabytes"),
                            ("tb", "Terabytes"),
                            ("seconds", "Seconds"),
                            ("minutes", "Minutes"),
                            ("hours", "Hours"),
                            ("count", "Count"),
                            ("requests", "Requests"),
                            ("emails", "Emails"),
                            ("messages", "Messages"),
                            ("cpu_hours", "CPU Hours"),
                            ("gpu_hours", "GPU Hours"),
                            ("custom", "Custom Unit"),
                        ],
                        default="count",
                        help_text="Unit of measurement",
                        max_length=20,
                    ),
                ),
                (
                    "unit_display",
                    models.CharField(
                        blank=True,
                        help_text="Custom unit display name (e.g., 'GB', 'requests')",
                        max_length=50,
                    ),
                ),
                (
                    "decimal_places",
                    models.PositiveSmallIntegerField(
                        default=2,
                        help_text="Decimal places for usage values",
                        validators=[django.core.validators.MaxValueValidator(8)],
                    ),
                ),
                (
                    "rounding_mode",
                    models.CharField(
                        choices=[
                            ("none", "No Rounding"),
                            ("up", "Round Up"),
                            ("down", "Round Down"),
                            ("nearest", "Round to Nearest"),
                        ],
                        default="up",
                        help_text="How to round usage for billing (up favors provider)",
                        max_length=10,
                    ),
                ),
                (
                    "rounding_increment",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("1"),
                        help_text="Minimum billable increment (e.g., 0.001 for GB)",
                        max_digits=12,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("storage", "Storage"),
                            ("bandwidth", "Bandwidth/Transfer"),
                            ("compute", "Compute Resources"),
                            ("email", "Email"),
                            ("database", "Database"),
                            ("api", "API Usage"),
                            ("domain", "Domains"),
                            ("ssl", "SSL Certificates"),
                            ("backup", "Backups"),
                            ("other", "Other"),
                        ],
                        default="other",
                        help_text="Category for grouping and display",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this meter is actively collecting events",
                    ),
                ),
                (
                    "is_billable",
                    models.BooleanField(
                        default=True,
                        help_text="Whether usage from this meter generates charges",
                    ),
                ),
                (
                    "event_grace_period_hours",
                    models.PositiveIntegerField(
                        default=24, help_text="Hours in past to accept late events"
                    ),
                ),
                (
                    "meta",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional meter configuration",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Usage Meter",
                "verbose_name_plural": "Usage Meters",
                "db_table": "usage_meters",
                "ordering": ("category", "name"),
                "indexes": [
                    models.Index(fields=["name"], name="usage_meter_name_7e15d8_idx"),
                    models.Index(
                        fields=["category", "is_active"],
                        name="usage_meter_categor_959b90_idx",
                    ),
                    models.Index(
                        fields=["stripe_meter_id"],
                        name="usage_meter_stripe__d6d85d_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UsageEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        db_index=True,
                        help_text="Unique key to prevent duplicate event processing",
                        max_length=255,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=8,
                        help_text="Usage value (interpretation depends on meter aggregation)",
                        max_digits=18,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When the usage occurred (may differ from created_at)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "properties",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional event properties (e.g., endpoint, resource_id)",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Source system (e.g., 'virtualmin', 'api_gateway', 'manual')",
                        max_length=50,
                    ),
                ),
                (
                    "source_ip",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of event source", null=True
                    ),
                ),
                (
                    "is_processed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether event has been included in aggregation",
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When event was processed into aggregation",
                        null=True,
                    ),
                ),
                (
                    "aggregation",
                    models.ForeignKey(
                        blank=True,
                        help_text="Aggregation record this event was processed into",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="billing.usageaggregation",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="Customer who generated this usage",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_events",
                        to="customers.customer",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        help_text="Service that generated this usage",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usage_events",
                        to="provisioning.service",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        help_text="Subscription this usage is billed against",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usage_events",
                        to="billing.subscription",
                    ),
                ),
                (
                    "meter",
                    models.ForeignKey(
                        help_text="Which meter this event belongs to",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="billing.usagemeter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usage Event",
                "verbose_name_plural": "Usage Events",
                "db_table": "usage_events",
                "ordering": ("-timestamp",),
            },
        ),
        migrations.AddField(
            model_name="usageaggregation",
            name="meter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="aggregations",
                to="billing.usagemeter",
            ),
        ),
        migrations.AddField(
            model_name="pricingtier",
            name="meter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pricing_tiers",
                to="billing.usagemeter",
            ),
        ),
        migrations.CreateModel(
            name="UsageThreshold",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "threshold_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage of Allowance"),
                            ("absolute", "Absolute Value"),
                        ],
                        default="percentage",
                        max_length=20,
                    ),
                ),
                (
                    "threshold_value",
                    models.DecimalField(
                        decimal_places=8,
                        help_text="Threshold value (percentage or absolute)",
                        max_digits=18,
                    ),
                ),
                (
                    "notify_customer",
                    models.BooleanField(
                        default=True, help_text="Send notification to customer"
                    ),
                ),
                (
                    "notify_staff",
                    models.BooleanField(
                        default=False, help_text="Send notification to staff"
                    ),
                ),
                (
                    "email_template",
                    models.CharField(
                        blank=True,
                        help_text="Email template to use for notification",
                        max_length=100,
                    ),
                ),
                (
                    "action_on_breach",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "No Action"),
                            ("warn", "Warning Only"),
                            ("throttle", "Throttle Service"),
                            ("suspend", "Suspend Service"),
                            ("block_new", "Block New Usage"),
                        ],
                        help_text="Action to take when threshold is breached",
                        max_length=50,
                    ),
                ),
                (
                    "repeat_notification",
                    models.BooleanField(
                        default=False,
                        help_text="Send notification again if threshold remains breached",
                    ),
                ),
                (
                    "repeat_interval_hours",
                    models.PositiveIntegerField(
                        default=24, help_text="Hours between repeat notifications"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thresholds",
                        to="billing.usagemeter",
                    ),
                ),
                (
                    "service_plan",
                    models.ForeignKey(
                        blank=True,
                        help_text="Apply to specific plan (null = all plans)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_thresholds",
                        to="provisioning.serviceplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usage Threshold",
                "verbose_name_plural": "Usage Thresholds",
                "db_table": "usage_thresholds",
                "ordering": ("meter", "threshold_value"),
            },
        ),
        migrations.CreateModel(
            name="UsageAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("acknowledged", "Acknowledged"),
                            ("resolved", "Resolved"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "usage_value",
                    models.DecimalField(
                        decimal_places=8,
                        help_text="Usage value when alert was triggered",
                        max_digits=18,
                    ),
                ),
                (
                    "usage_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Usage as percentage of allowance",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "allowance_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        help_text="Total allowance at time of alert",
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "notified_at",
                    models.DateTimeField(
                        blank=True, help_text="When notification was sent", null=True
                    ),
                ),
                (
                    "notification_channel",
                    models.CharField(
                        blank=True,
                        help_text="How notification was sent (email, sms, webhook)",
                        max_length=50,
                    ),
                ),
                (
                    "notification_error",
                    models.TextField(
                        blank=True, help_text="Error message if notification failed"
                    ),
                ),
                (
                    "action_taken",
                    models.CharField(
                        blank=True,
                        help_text="Action taken in response to threshold breach",
                        max_length=50,
                    ),
                ),
                ("action_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "aggregation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts",
                        to="billing.usageaggregation",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_alerts",
                        to="customers.customer",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_usage_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usage_alerts",
                        to="billing.subscription",
                    ),
                ),
                (
                    "threshold",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="billing.usagethreshold",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usage Alert",
                "verbose_name_plural": "Usage Alerts",
                "db_table": "usage_alerts",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="PricingTierBracket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "from_quantity",
                    models.DecimalField(
                        decimal_places=8,
                        help_text="Start of bracket (inclusive)",
                        max_digits=18,
                    ),
                ),
                (
                    "to_quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        help_text="End of bracket (null = unlimited)",
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "unit_price_cents",
                    models.BigIntegerField(help_text="Price per unit in this bracket"),
                ),
                (
                    "flat_fee_cents",
                    models.BigIntegerField(
                        default=0,
                        help_text="Flat fee for this bracket (package pricing)",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "pricing_tier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brackets",
                        to="billing.pricingtier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pricing Bracket",
                "verbose_name_plural": "Pricing Brackets",
                "db_table": "pricing_tier_brackets",
                "ordering": ("pricing_tier", "sort_order", "from_quantity"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("pricing_tier", "from_quantity"),
                        name="unique_tier_bracket_start",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="billingcycle",
            index=models.Index(
                fields=["subscription", "-period_start"],
                name="billing_cyc_subscri_bd1d79_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="billingcycle",
            index=models.Index(
                fields=["status", "period_end"], name="billing_cyc_status_c0c791_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="billingcycle",
            index=models.Index(
                fields=["status", "-period_start"], name="billing_cyc_status_89a35f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="billingcycle",
            constraint=models.UniqueConstraint(
                fields=("subscription", "period_start"),
                name="unique_subscription_period",
            ),
        ),
        migrations.AddIndex(
            model_name="usageevent",
            index=models.Index(
                fields=["customer", "-timestamp"], name="usage_event_custome_21c1ac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usageevent",
            index=models.Index(
                fields=["meter", "-timestamp"], name="usage_event_meter_i_ed3605_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usageevent",
            index=models.Index(
                fields=["subscription", "-timestamp"],
                name="usage_event_subscri_a9f545_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="usageevent",
            index=models.Index(
                fields=["service", "-timestamp"], name="usage_event_service_31e9d9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usageevent",
            index=models.Index(
                fields=["is_processed", "-timestamp"],
                name="usage_event_is_proc_f50403_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="usageevent",
            index=models.Index(
                fields=["meter", "customer", "timestamp"],
                name="usage_event_meter_i_e096cd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="usageevent",
            index=models.Index(
                fields=["meter", "customer", "is_processed"],
                name="usage_evt_pending_agg",
            ),
        ),
        migrations.AddConstraint(
            model_name="usageevent",
            constraint=models.UniqueConstraint(
                fields=("meter", "customer", "idempotency_key"),
                name="unique_usage_event_idempotency",
            ),
        ),
        migrations.AddIndex(
            model_name="usageaggregation",
            index=models.Index(
                fields=["customer", "-period_start"],
                name="usage_aggre_custome_67e262_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="usageaggregation",
            index=models.Index(
                fields=["meter", "status"], name="usage_aggre_meter_i_f4983f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usageaggregation",
            index=models.Index(
                fields=["billing_cycle", "status"],
                name="usage_aggre_billing_e97cd2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="usageaggregation",
            index=models.Index(
                fields=["status", "-period_start"], name="usage_aggre_status_e65aeb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usageaggregation",
            index=models.Index(
                condition=models.Q(("status", "rated")),
                fields=["status", "customer"],
                name="usage_agg_ready_invoice",
            ),
        ),
        migrations.AddConstraint(
            model_name="usageaggregation",
            constraint=models.UniqueConstraint(
                fields=("meter", "customer", "billing_cycle"),
                name="unique_meter_customer_cycle",
            ),
        ),
        migrations.AddIndex(
            model_name="pricingtier",
            index=models.Index(
                fields=["meter", "is_active"], name="pricing_tie_meter_i_97705c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pricingtier",
            index=models.Index(
                fields=["meter", "is_default"], name="pricing_tie_meter_i_d8d1e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usagethreshold",
            index=models.Index(
                fields=["meter", "is_active"], name="usage_thres_meter_i_0b6578_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usagethreshold",
            index=models.Index(
                fields=["service_plan", "is_active"],
                name="usage_thres_service_042b48_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="usagealert",
            index=models.Index(
                fields=["customer", "-created_at"],
                name="usage_alert_custome_705c52_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="usagealert",
            index=models.Index(
                fields=["status", "-created_at"], name="usage_alert_status_6e249a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usagealert",
            index=models.Index(
                fields=["threshold", "-created_at"],
                name="usage_alert_thresho_b132f9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="usagealert",
            index=models.Index(
                condition=models.Q(("status__in", ["pending", "sent"])),
                fields=["status", "customer"],
                name="usage_alert_unresolved",
            ),
        ),
    ]
