# Generated by Django 5.2.11 on 2026-02-09 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_oauthtoken'),
        ('customers', '0002_initial'),
        ('products', '0002_product_default_service_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='oauthtoken',
            new_name='billing_efa_cui_70660c_idx',
            old_name='billing_efa_cui_0c6e9a_idx',
        ),
        migrations.RenameIndex(
            model_name='oauthtoken',
            new_name='billing_efa_expires_401f46_idx',
            old_name='billing_efa_expires_d6b7c4_idx',
        ),
        migrations.RenameIndex(
            model_name='pricegrandfathering',
            new_name='price_grand_custome_51458e_idx',
            old_name='billing_gf_cust_active_idx',
        ),
        migrations.RenameIndex(
            model_name='pricegrandfathering',
            new_name='price_grand_product_f357d7_idx',
            old_name='billing_gf_prod_active_idx',
        ),
        migrations.RenameIndex(
            model_name='pricegrandfathering',
            new_name='price_grand_expires_e0feb5_idx',
            old_name='billing_gf_expires_active_idx',
        ),
        migrations.RenameIndex(
            model_name='subscription',
            new_name='subscriptio_custome_34b933_idx',
            old_name='billing_sub_cust_status_idx',
        ),
        migrations.RenameIndex(
            model_name='subscription',
            new_name='subscriptio_status_5e41b4_idx',
            old_name='billing_sub_status_billing_idx',
        ),
        migrations.RenameIndex(
            model_name='subscription',
            new_name='subscriptio_product_5bacd0_idx',
            old_name='billing_sub_prod_status_idx',
        ),
        migrations.RenameIndex(
            model_name='subscriptionchange',
            new_name='subscriptio_subscri_7ca058_idx',
            old_name='billing_change_sub_created_idx',
        ),
        migrations.RenameIndex(
            model_name='subscriptionchange',
            new_name='subscriptio_status_c11d78_idx',
            old_name='billing_change_status_eff_idx',
        ),
        migrations.AlterField(
            model_name='pricegrandfathering',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_grandfathering', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscriptionchange',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_changes_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['stripe_subscription_id'], name='subscriptio_stripe__aa726e_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(condition=models.Q(('status', 'active')), fields=['status', 'next_billing_date'], name='idx_active_billing_date'),
        ),
    ]
