# Generated by Django 5.2.11 on 2026-02-15 12:09

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_rename_billing_efa_cui_0c6e9a_idx_billing_efa_cui_70660c_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceline',
            name='tax_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Tax rate as decimal (0.21 for 21%)', max_digits=5),
        ),
    ]
