# Generated by Django 5.2.11 on 2026-03-04 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_alter_invoiceline_tax_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oauthtoken',
            options={'ordering': ('-created_at',), 'verbose_name': 'e-Factura OAuth Token', 'verbose_name_plural': 'e-Factura OAuth Tokens'},
        ),
    ]
