# Generated by Django 5.2.11 on 2026-03-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0016_alter_oauthtoken_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="gateway_txn_id",
            field=models.CharField(
                blank=True, default=None, max_length=255, null=True, unique=True
            ),
        ),
    ]
