# Generated by Django 5.2.11 on 2026-03-05 19:43

from django.db import migrations, models
from django.db.models import Count


def convert_empty_txn_id_to_null(apps, schema_editor):
    """Convert gateway_txn_id="" to NULL and detect duplicate non-empty values
    before applying unique constraint.

    The field was previously CharField(blank=True) without null=True, so rows
    without a transaction ID were stored as "". Adding unique=True would fail
    if more than one such row exists. NULL is excluded from unique checks in
    PostgreSQL, so converting empty strings to NULL is the correct fix.

    We also check for duplicate non-empty values — these would cause the
    subsequent AlterField(unique=True) to fail with a duplicate key violation.
    """
    Payment = apps.get_model("billing", "Payment")
    Payment.objects.filter(gateway_txn_id="").update(gateway_txn_id=None)

    # Preflight: detect duplicate non-empty gateway_txn_id values that would
    # break the UNIQUE constraint.  Abort early with an actionable message.
    dupes = (
        Payment.objects.exclude(gateway_txn_id__isnull=True)
        .exclude(gateway_txn_id="")
        .values("gateway_txn_id")
        .annotate(cnt=Count("id"))
        .filter(cnt__gt=1)
    )
    dupe_list = list(dupes[:10])  # Limit output for readability
    if dupe_list:
        ids = ", ".join(d["gateway_txn_id"] for d in dupe_list)
        sql_hint = (
            "SELECT gateway_txn_id, COUNT(*) FROM billing_payment"
            " WHERE gateway_txn_id IS NOT NULL AND gateway_txn_id != ''"
            " GROUP BY gateway_txn_id HAVING COUNT(*) > 1;"
        )
        raise RuntimeError(
            f"Cannot add unique constraint: {len(dupe_list)} duplicate gateway_txn_id "
            f"values found (showing first 10): {ids}. "
            f"Resolve duplicates manually before re-running this migration. "
            f"Diagnostic query: {sql_hint}"
        )


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0016_alter_oauthtoken_options"),
    ]

    operations = [
        # Step 1: convert existing "" values to NULL so unique constraint can apply.
        # (PostgreSQL treats each NULL as distinct, so NULLs never violate UNIQUE.)
        migrations.RunPython(
            convert_empty_txn_id_to_null,
            reverse_code=migrations.RunPython.noop,
        ),
        # Step 2: now safe to add unique=True, null=True, default=None.
        migrations.AlterField(
            model_name="payment",
            name="gateway_txn_id",
            field=models.CharField(blank=True, default=None, max_length=255, null=True, unique=True),
        ),
    ]
