# Generated by Django 5.2.11 on 2026-03-06 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_clear_efactura_tokens'),
        ('billing', '0018_payment_updated_at'),
    ]

    operations = [
    ]
