# Generated by Django 5.2.12 on 2026-03-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0019_merge_20260306_1741"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vatvalidation",
            name="validation_source",
            field=models.CharField(
                choices=[
                    ("vies", "VIES API"),
                    ("format_check", "Format Check Only"),
                    ("manual", "Manual Override"),
                    ("cached", "Previous Validation"),
                ],
                default="vies",
                max_length=20,
            ),
        ),
    ]
