# Generated by Django 5.2.11 on 2026-03-10 17:10

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0019_merge_20260306_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=django_fsm.FSMField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('void', 'Void'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], default='draft', max_length=20, protected=True),
        ),
        migrations.AlterField(
            model_name='proformainvoice',
            name='status',
            field=django_fsm.FSMField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('converted', 'Converted')], default='draft', max_length=20, protected=True),
        ),
    ]
