# Generated by Django 5.2.11 on 2026-03-10 17:21

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0020_alter_invoice_status_alter_proformainvoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=django_fsm.FSMField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], default='pending', max_length=20, protected=True),
        ),
        migrations.AlterField(
            model_name='refund',
            name='status',
            field=django_fsm.FSMField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('approved', 'Approved'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, protected=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=django_fsm.FSMField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past Due'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('pending', 'Pending Activation')], db_index=True, default='pending', max_length=20, protected=True),
        ),
    ]
