# Generated by Django 5.2.11 on 2026-03-10 18:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0021_alter_payment_status_alter_refund_status_and_more'),
        ('customers', '0012_fix_soft_delete_unique_constraints'),
        ('orders', '0010_alter_order_status_and_more'),
        ('products', '0002_product_default_service_plan'),
        ('provisioning', '0021_service_terminated_at_alter_service_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal_cents__gte', 0)), name='invoice_subtotal_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('tax_cents__gte', 0)), name='invoice_tax_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('total_cents__gte', 0)), name='invoice_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'issued', 'paid', 'overdue', 'void', 'refunded', 'partially_refunded'])), name='invoice_status_valid_values'),
        ),
        migrations.AddConstraint(
            model_name='invoiceline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price_cents__gte', 0)), name='invoiceline_unit_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='invoiceline',
            constraint=models.CheckConstraint(condition=models.Q(('tax_cents__gte', 0)), name='invoiceline_tax_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='invoiceline',
            constraint=models.CheckConstraint(condition=models.Q(('line_total_cents__gte', 0)), name='invoiceline_line_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount_cents__gte', 1)), name='payment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'succeeded', 'failed', 'refunded', 'partially_refunded'])), name='payment_status_valid_values'),
        ),
        migrations.AddConstraint(
            model_name='proformainvoice',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal_cents__gte', 0)), name='proformainvoice_subtotal_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='proformainvoice',
            constraint=models.CheckConstraint(condition=models.Q(('tax_cents__gte', 0)), name='proformainvoice_tax_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='proformainvoice',
            constraint=models.CheckConstraint(condition=models.Q(('total_cents__gte', 0)), name='proformainvoice_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='proformainvoice',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'sent', 'accepted', 'expired', 'converted'])), name='proformainvoice_status_valid_values'),
        ),
        migrations.AddConstraint(
            model_name='proformaline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price_cents__gte', 0)), name='proformaline_unit_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='proformaline',
            constraint=models.CheckConstraint(condition=models.Q(('tax_cents__gte', 0)), name='proformaline_tax_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='proformaline',
            constraint=models.CheckConstraint(condition=models.Q(('line_total_cents__gte', 0)), name='proformaline_line_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'processing', 'approved', 'completed', 'rejected', 'failed', 'cancelled'])), name='refund_status_valid_values'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['trialing', 'active', 'past_due', 'paused', 'cancelled', 'expired', 'pending'])), name='subscription_status_valid_values'),
        ),
    ]
