# Generated by Django 5.2.12 on 2026-03-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0021_add_proforma_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='discount_amount_cents',
            field=models.BigIntegerField(default=0, help_text='Line-level discount in cents (BT-147)'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='domain_name',
            field=models.CharField(blank=True, default='', help_text='Hosting domain for this line', max_length=255),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='note',
            field=models.TextField(blank=True, default='', help_text='Per-line memo (BT-127)'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='period_end',
            field=models.DateField(blank=True, help_text='Service period end (BT-135)', null=True),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='period_start',
            field=models.DateField(blank=True, help_text='Service period start (BT-134)', null=True),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='seller_item_id',
            field=models.CharField(blank=True, default='', help_text='Seller product code/SKU (BT-155)', max_length=100),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Display/XML sequence (BT-126)'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='tax_category_code',
            field=models.CharField(blank=True, default='S', help_text='EU VAT category: S/Z/E/AE/O (BT-151)', max_length=5),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='unit_code',
            field=models.CharField(blank=True, default='C62', help_text='UN/ECE Rec. 20 unit code (BT-130)', max_length=10),
        ),
        migrations.AddField(
            model_name='proformaline',
            name='discount_amount_cents',
            field=models.BigIntegerField(default=0, help_text='Line-level discount in cents (BT-147)'),
        ),
        migrations.AddField(
            model_name='proformaline',
            name='domain_name',
            field=models.CharField(blank=True, default='', help_text='Hosting domain for this line', max_length=255),
        ),
        migrations.AddField(
            model_name='proformaline',
            name='note',
            field=models.TextField(blank=True, default='', help_text='Per-line memo (BT-127)'),
        ),
        migrations.AddField(
            model_name='proformaline',
            name='period_end',
            field=models.DateField(blank=True, help_text='Service period end (BT-135)', null=True),
        ),
        migrations.AddField(
            model_name='proformaline',
            name='period_start',
            field=models.DateField(blank=True, help_text='Service period start (BT-134)', null=True),
        ),
        migrations.AddField(
            model_name='proformaline',
            name='seller_item_id',
            field=models.CharField(blank=True, default='', help_text='Seller product code/SKU (BT-155)', max_length=100),
        ),
        migrations.AddField(
            model_name='proformaline',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Display/XML sequence (BT-126)'),
        ),
        migrations.AddField(
            model_name='proformaline',
            name='tax_category_code',
            field=models.CharField(blank=True, default='S', help_text='EU VAT category: S/Z/E/AE/O (BT-151)', max_length=5),
        ),
        migrations.AddField(
            model_name='proformaline',
            name='unit_code',
            field=models.CharField(blank=True, default='C62', help_text='UN/ECE Rec. 20 unit code (BT-130)', max_length=10),
        ),
    ]
