# Generated by Django 5.2.12 on 2026-03-10 23:00

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('billing', '0022_invoice_invoice_subtotal_non_negative_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingcycle',
            name='status',
            field=django_fsm.FSMField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('closing', 'Closing'), ('closed', 'Closed'), ('invoiced', 'Invoiced'), ('finalized', 'Finalized')], default='upcoming', max_length=20, protected=True),
        ),
        migrations.AlterField(
            model_name='efacturadocument',
            name='status',
            field=django_fsm.FSMField(choices=[('draft', 'Draft'), ('queued', 'Queued'), ('submitted', 'Submitted'), ('processing', 'Processing'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('error', 'Error')], db_index=True, default='draft', help_text='Current status in the submission lifecycle', max_length=20, protected=True),
        ),
        migrations.AlterField(
            model_name='usageaggregation',
            name='status',
            field=django_fsm.FSMField(choices=[('accumulating', 'Accumulating'), ('pending_rating', 'Pending Rating'), ('rated', 'Rated'), ('invoiced', 'Invoiced'), ('finalized', 'Finalized')], default='accumulating', max_length=20, protected=True),
        ),
        migrations.AddConstraint(
            model_name='efacturadocument',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'queued', 'submitted', 'processing', 'accepted', 'rejected', 'error'])), name='efactura_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='billingcycle',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['upcoming', 'active', 'closing', 'closed', 'invoiced', 'finalized'])), name='billingcycle_status_valid_values'),
        ),
        migrations.AddConstraint(
            model_name='usageaggregation',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['accumulating', 'pending_rating', 'rated', 'invoiced', 'finalized'])), name='usageaggregation_status_valid_values'),
        ),
    ]
