# Generated by Django 5.2.12 on 2026-03-25 09:47

import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0022_line_item_en16931_fields"),
        ("customers", "0017_address_boolean_flags"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="payment",
            name="payment_status_valid_values",
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("pending", "Pending"),
                    ("succeeded", "Succeeded"),
                    ("failed", "Failed"),
                    ("refunded", "Refunded"),
                    ("partially_refunded", "Partially Refunded"),
                    ("cancelled", "Cancelled"),
                    ("canceled", "Canceled"),
                    ("disputed", "Disputed"),
                ],
                default="pending",
                max_length=20,
                protected=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "pending",
                            "succeeded",
                            "failed",
                            "refunded",
                            "partially_refunded",
                            "cancelled",
                            "canceled",
                            "disputed",
                        ],
                    )
                ),
                name="payment_status_valid_values",
            ),
        ),
    ]
