# Generated by Django 5.2.12 on 2026-03-11 08:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0023_alter_billingcycle_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount_cents',
            field=models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
