# Generated by Django 5.2.12 on 2026-06-15 14:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0024_backfill_refunds_from_meta'),
        ('customers', '0017_address_boolean_flags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discount_cents',
            field=models.BigIntegerField(default=0, help_text='Document-level discount in cents (EN16931 BT-92/BT-107)'),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='discount_cents',
            field=models.BigIntegerField(default=0, help_text='Document-level discount in cents (EN16931 BT-92/BT-107)'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('discount_cents__gte', 0)), name='invoice_discount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='proformainvoice',
            constraint=models.CheckConstraint(condition=models.Q(('discount_cents__gte', 0)), name='proformainvoice_discount_non_negative'),
        ),
    ]
