# Generated by Django 5.2.12 on 2026-03-12 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0020_add_format_check_validation_source"),
        ("billing", "0025_fix_check_constraints_not_valid"),
    ]

    operations = []
