# Generated by Django 5.2.12 on 2026-06-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0025_add_document_discount_cents'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='bill_to_registration_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='bill_to_registration_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
