# Generated by Django 5.2.12 on 2026-06-16 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0026_add_bill_to_registration_number"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="efacturadocument",
            constraint=models.UniqueConstraint(
                condition=models.Q(("anaf_upload_index", ""), _negated=True),
                fields=("anaf_upload_index",),
                name="unique_efactura_upload_index",
            ),
        ),
    ]
