# Generated by Django 5.2.12 on 2026-07-17 17:59

import uuid

import django.core.validators
import django.db.models.deletion
import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0027_efacturadocument_unique_efactura_upload_index'),
        ('customers', '0017_address_boolean_flags'),
        ('provisioning', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringPaymentAuthorization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', django_fsm.FSMField(choices=[('pending', 'Pending'), ('active', 'Active'), ('withdrawn', 'Withdrawn'), ('revoked', 'Revoked')], db_index=True, default='pending', max_length=20, protected=True)),
                ('setup_intent_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('terms_version', models.CharField(max_length=50)),
                ('terms_text', models.TextField()),
                ('terms_text_hash', models.CharField(max_length=64)),
                ('granted_by_role', models.CharField(max_length=50)),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('grant_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('grant_user_agent', models.CharField(blank=True, max_length=500)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawal_reason', models.CharField(blank=True, max_length=255)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'billing_recurring_payment_authorizations',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='billingcycle',
            name='charge_scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billingcycle',
            name='collection_attempt_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='billingcycle',
            name='collection_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billingcycle',
            name='collection_status',
            field=models.CharField(choices=[('unbilled', 'Unbilled'), ('prepared', 'Prepared'), ('scheduled', 'Scheduled'), ('processing', 'Processing'), ('paid', 'Paid'), ('past_due', 'Past Due'), ('failed', 'Failed'), ('waived', 'Waived')], db_index=True, default='unbilled', max_length=20),
        ),
        migrations.AddField(
            model_name='billingcycle',
            name='entitlement_applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billingcycle',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billingcycle',
            name='proforma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_cycles', to='billing.proformainvoice'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='billing_cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='billing.billingcycle'),
        ),
        migrations.AddField(
            model_name='paymentretryattempt',
            name='result_payment',
            field=models.ForeignKey(blank=True, help_text='New payment attempt created by this retry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_for_retry_attempts', to='billing.payment'),
        ),
        migrations.AddField(
            model_name='proformaline',
            name='billing_cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proforma_lines', to='billing.billingcycle'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='auto_payment_enabled',
            field=models.BooleanField(default=False, help_text='Collect this subscription automatically under its active customer mandate'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='billing_anchor_day',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Original calendar day used when advancing month-based periods', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AddField(
            model_name='subscription',
            name='next_charge_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='next_proforma_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='saved_payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='customers.customerpaymentmethod'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='service',
            field=models.OneToOneField(blank=True, help_text='Independently cancellable service whose recurring billing PRAHO owns', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscription', to='provisioning.service'),
        ),
        migrations.AddIndex(
            model_name='billingcycle',
            index=models.Index(fields=['collection_status', 'charge_scheduled_at'], name='billing_cyc_collect_aa318e_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceline',
            index=models.Index(fields=['billing_cycle'], name='billing_inv_billing_a43a64_idx'),
        ),
        migrations.AddIndex(
            model_name='proformaline',
            index=models.Index(fields=['billing_cycle'], name='billing_pro_billing_b3b78b_idx'),
        ),
        migrations.AddConstraint(
            model_name='billingcycle',
            constraint=models.CheckConstraint(condition=models.Q(('collection_status__in', ['unbilled', 'prepared', 'scheduled', 'processing', 'paid', 'past_due', 'failed', 'waived'])), name='billingcycle_collection_status_valid'),
        ),
        migrations.AddField(
            model_name='recurringpaymentauthorization',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_payment_authorizations', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='recurringpaymentauthorization',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_recurring_payment_authorizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recurringpaymentauthorization',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_payment_authorizations', to='customers.customerpaymentmethod'),
        ),
        migrations.AddField(
            model_name='recurringpaymentauthorization',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_recurring_payment_authorizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recurringpaymentauthorization',
            name='withdrawn_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawn_recurring_payment_authorizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment_authorization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.recurringpaymentauthorization'),
        ),
        migrations.AddIndex(
            model_name='recurringpaymentauthorization',
            index=models.Index(fields=['customer', 'status'], name='billing_rec_custome_cb7492_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringpaymentauthorization',
            index=models.Index(fields=['payment_method', 'status'], name='billing_rec_payment_6c03ff_idx'),
        ),
        migrations.AddConstraint(
            model_name='recurringpaymentauthorization',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('customer', 'payment_method'), name='unique_active_recurring_auth_method'),
        ),
        migrations.AddConstraint(
            model_name='recurringpaymentauthorization',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'active', 'withdrawn', 'revoked'])), name='recurring_payment_auth_status_valid'),
        ),
    ]
