# Generated by Django 5.2.12 on 2026-07-17 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0028_recurringpaymentauthorization_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='subscription',
            name='billing_sub_stripe__4b5970_idx',
        ),
        migrations.RemoveIndex(
            model_name='usagemeter',
            name='billing_usa_stripe__2d291e_idx',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='payment_method_id',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='stripe_subscription_id',
        ),
        migrations.RemoveField(
            model_name='usageaggregation',
            name='stripe_synced_at',
        ),
        migrations.RemoveField(
            model_name='usageaggregation',
            name='stripe_usage_record_id',
        ),
        migrations.RemoveField(
            model_name='usagemeter',
            name='stripe_meter_event_name',
        ),
        migrations.RemoveField(
            model_name='usagemeter',
            name='stripe_meter_id',
        ),
    ]
