# Generated by Django 5.2.12 on 2026-07-17 20:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0029_remove_stripe_billing_ownership'),
        ('customers', '0017_address_boolean_flags'),
        ('products', '0002_initial'),
        ('provisioning', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='recurringpaymentauthorization',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'active'), _negated=True), models.Q(('setup_intent_id__isnull', False), models.Q(('setup_intent_id', ''), _negated=True), ('granted_at__isnull', False), models.Q(('terms_version', ''), _negated=True), models.Q(('terms_text', ''), _negated=True), models.Q(('terms_text_hash', ''), _negated=True)), _connector='OR'), name='active_recurring_auth_has_consent_proof'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(('auto_payment_enabled', False), models.Q(('saved_payment_method__isnull', False), ('payment_authorization__isnull', False)), _connector='OR'), name='subscription_auto_payment_has_mandate'),
        ),
    ]
