# Generated by Django 5.2.12 on 2026-07-17 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0030_recurringpaymentauthorization_active_recurring_auth_has_consent_proof_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingcycle",
            name="usage_invoice",
            field=models.ForeignKey(
                blank=True,
                help_text="Post-paid usage invoice; separate from the prepaid renewal invoice",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usage_billing_cycles",
                to="billing.invoice",
            ),
        ),
    ]
