# Generated by Django 5.2.12 on 2026-07-18 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0034_billingcycle_period_end_after_start'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pricingtier',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price_cents__isnull', True), ('unit_price_cents__gte', 0), _connector='OR'), name='pricingtier_unit_price_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='pricingtier',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_charge_cents__gte', 0)), name='pricingtier_min_charge_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='pricingtier',
            constraint=models.CheckConstraint(condition=models.Q(('valid_from__isnull', True), ('valid_until__isnull', True), ('valid_until__gt', models.F('valid_from')), _connector='OR'), name='pricingtier_valid_window'),
        ),
        migrations.AddConstraint(
            model_name='pricingtierbracket',
            constraint=models.CheckConstraint(condition=models.Q(('from_quantity__gte', 0)), name='pricingbracket_from_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='pricingtierbracket',
            constraint=models.CheckConstraint(condition=models.Q(('to_quantity__isnull', True), ('to_quantity__gt', models.F('from_quantity')), _connector='OR'), name='pricingbracket_range_valid'),
        ),
        migrations.AddConstraint(
            model_name='pricingtierbracket',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price_cents__gte', 0)), name='pricingbracket_unit_price_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='pricingtierbracket',
            constraint=models.CheckConstraint(condition=models.Q(('flat_fee_cents__gte', 0)), name='pricingbracket_flat_fee_nonneg'),
        ),
    ]
