# Generated by Django 5.2.12 on 2026-07-18 04:04

from django.db import migrations, models


def keep_one_active_default_policy(apps, schema_editor):
    """Preserve the oldest configured default and demote legacy duplicates."""
    policy = apps.get_model("billing", "PaymentRetryPolicy")
    active_defaults = list(
        policy.objects.filter(is_active=True, is_default=True)
        .order_by("created_at", "id")
        .values_list("id", flat=True)
    )
    if len(active_defaults) > 1:
        policy.objects.filter(id__in=active_defaults[1:]).update(is_default=False)


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0035_pricing_integrity_constraints'),
    ]

    operations = [
        migrations.RunPython(keep_one_active_default_policy, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='paymentretrypolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_default', True)), fields=('is_default',), name='one_active_default_retry_policy'),
        ),
        migrations.AddConstraint(
            model_name='paymentretrypolicy',
            constraint=models.CheckConstraint(condition=models.Q(('max_attempts__gte', 1), ('max_attempts__lte', 10)), name='retry_policy_max_attempts_valid'),
        ),
        migrations.AddConstraint(
            model_name='paymentretrypolicy',
            constraint=models.CheckConstraint(condition=models.Q(('suspend_service_after_days__isnull', True), ('suspend_service_after_days__gte', 0), _connector='OR'), name='retry_policy_suspend_days_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='paymentretrypolicy',
            constraint=models.CheckConstraint(condition=models.Q(('terminate_service_after_days__isnull', True), ('terminate_service_after_days__gte', 0), _connector='OR'), name='retry_policy_terminate_days_nonneg'),
        ),
    ]
