# Generated by Django 5.2.12 on 2026-07-20

from django.db import migrations, models
from django.db.models import Count


def reject_duplicate_gateway_refunds(apps, schema_editor):
    """Fail closed so operators reconcile duplicate gateway ledger rows."""
    refund = apps.get_model("billing", "Refund")
    duplicate = (
        refund.objects.exclude(gateway_refund_id="")
        .values("gateway_refund_id")
        .annotate(total=Count("id"))
        .filter(total__gt=1)
        .order_by("gateway_refund_id")
        .values_list("gateway_refund_id", "total")
        .first()
    )
    if duplicate:
        refund_id, total = duplicate
        raise RuntimeError(
            f"Cannot enforce unique gateway refunds: {refund_id!r} appears {total} times; "
            "reconcile the duplicate ledger rows before migrating"
        )


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0036_retry_policy_integrity"),
    ]

    operations = [
        migrations.RunPython(reject_duplicate_gateway_refunds, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="refund",
            constraint=models.UniqueConstraint(
                condition=~models.Q(gateway_refund_id=""),
                fields=("gateway_refund_id",),
                name="uniq_refund_gateway_id_present",
            ),
        ),
    ]
