# Generated by Django 5.2.12 on 2026-07-20

import decimal

import django.core.validators
from django.db import migrations, models

MAX_FX_RATE = decimal.Decimal("9999999999.99999999")


def reject_invalid_fx_rates(apps, schema_editor):
    """Fail closed so operators reconcile invalid historical rates explicitly."""
    fx_rate = apps.get_model("billing", "FXRate")

    invalid_rate = next(
        (
            (rate_id, rate)
            for rate_id, rate in fx_rate.objects.order_by("pk").values_list("pk", "rate")
            if not rate.is_finite() or rate <= 0 or rate > MAX_FX_RATE
        ),
        None,
    )
    if invalid_rate:
        rate_id, rate = invalid_rate
        raise RuntimeError(
            f"Cannot enforce positive FX rates: billing_fx_rates id={rate_id} has rate={rate}; "
            "reconcile the row before migrating"
        )

    self_pair = (
        fx_rate.objects.filter(base_code=models.F("quote_code"))
        .order_by("pk")
        .values_list("pk", "base_code_id")
        .first()
    )
    if self_pair:
        rate_id, currency_code = self_pair
        raise RuntimeError(
            f"Cannot enforce distinct FX currency pairs: billing_fx_rates id={rate_id} uses "
            f"{currency_code}/{currency_code}; reconcile the row before migrating"
        )


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0037_refund_gateway_id_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="fxrate",
            name="fetched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fxrate",
            name="source",
            field=models.CharField(
                choices=[
                    ("legacy_unknown", "Legacy / unknown"),
                    ("bnr", "National Bank of Romania"),
                    ("ecb", "European Central Bank"),
                    ("bank", "Commercial bank"),
                ],
                default="legacy_unknown",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="fxrate",
            name="source_reference",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="fxrate",
            name="as_of",
            field=models.DateField(
                help_text=(
                    "Date this rate is legally valid for VAT purposes, not the publication "
                    "date. A BNR rate communicated on day D applies from the next banking day."
                )
            ),
        ),
        migrations.AlterField(
            model_name="fxrate",
            name="rate",
            field=models.DecimalField(
                decimal_places=8,
                max_digits=18,
                validators=[
                    django.core.validators.MinValueValidator(decimal.Decimal("1E-8")),
                    django.core.validators.MaxValueValidator(decimal.Decimal("9999999999.99999999")),
                ],
            ),
        ),
        migrations.RunPython(reject_invalid_fx_rates, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="fxrate",
            constraint=models.CheckConstraint(
                condition=models.Q(rate__gt=0, rate__lte=MAX_FX_RATE),
                name="fxrate_rate_finite_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="fxrate",
            constraint=models.CheckConstraint(
                condition=models.Q(("base_code", models.F("quote_code")), _negated=True),
                name="fxrate_distinct_currency_pair",
            ),
        ),
    ]
