# Generated by Django 5.2.12 on 2026-07-20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0038_fxrate_provenance_and_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="exchange_rate_as_of",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="exchange_rate_source",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="invoice",
            name="exchange_rate_source_reference",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="invoice",
            name="tax_point_date",
            field=models.DateField(
                blank=True,
                help_text="VAT tax point used to select the immutable exchange-rate snapshot",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="exchange_to_ron",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                help_text="Exchange rate to RON at time of invoice",
                max_digits=18,
                null=True,
            ),
        ),
    ]
