# Generated by Django 5.2.12 on 2026-07-22 19:28

import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0039_invoice_tax_point_and_fx_snapshot'),
        ('customers', '0019_bind_payment_method_encryption_context'),
        ('orders', '0007_orderitem_product_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='refund',
            name='refund_status_valid_values',
        ),
        migrations.AddField(
            model_name='refund',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, help_text='Stable pre-gateway idempotency key (#342)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='refund',
            name='status',
            field=django_fsm.FSMField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('processing', 'Processing'), ('approved', 'Approved'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, protected=True),
        ),
        migrations.AlterField(
            model_name='refundstatushistory',
            name='new_status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('processing', 'Processing'), ('approved', 'Approved'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], max_length=20),
        ),
        migrations.AlterField(
            model_name='refundstatushistory',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('processing', 'Processing'), ('approved', 'Approved'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['initiated', 'pending', 'processing', 'approved', 'completed', 'rejected', 'failed', 'cancelled'])), name='refund_status_valid_values'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('idempotency_key',), name='uniq_refund_idempotency_key_present'),
        ),
    ]
