# Generated by Django 5.2.12 on 2026-07-22

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0039_invoice_tax_point_and_fx_snapshot"),
    ]

    operations = [
        # RenameField preserves every existing storage key. Legacy objects may retain their old
        # efactura/pdf/... name; new archives use the truthful responses/... ZIP path below.
        migrations.RenameField(
            model_name="efacturadocument",
            old_name="signed_pdf",
            new_name="response_archive",
        ),
        migrations.AlterField(
            model_name="efacturadocument",
            name="response_archive",
            field=models.FileField(
                blank=True,
                help_text="Exact ZIP archive returned by ANAF /descarcare",
                null=True,
                upload_to="efactura/responses/%Y/%m/",
            ),
        ),
        migrations.AddField(
            model_name="efacturadocument",
            name="response_archive_sha256",
            field=models.CharField(
                blank=True,
                help_text="SHA-256 digest of the exact ANAF response archive bytes",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="efacturadocument",
            name="response_archive_downloaded_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the validated ANAF response archive was stored",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="efacturadocument",
            name="submission_claim_token",
            field=models.UUIDField(
                blank=True,
                editable=False,
                help_text="Opaque owner token for the active ANAF upload claim",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="efacturadocument",
            name="submission_claimed_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="When the most recent ANAF upload claim was acquired",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="efacturadocument",
            name="submission_claim_expires_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="When the most recent ANAF upload claim ownership lease expires",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="efacturadocument",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("draft", "Draft"),
                    ("queued", "Queued"),
                    ("uploading", "Uploading"),
                    ("submitted", "Submitted"),
                    ("processing", "Processing"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("error", "Error"),
                    ("outcome_unknown", "Outcome Unknown"),
                ],
                db_index=True,
                default="draft",
                help_text="Current status in the submission lifecycle",
                max_length=20,
                protected=True,
            ),
        ),
        migrations.RemoveConstraint(
            model_name="efacturadocument",
            name="efactura_valid_status",
        ),
        migrations.AddConstraint(
            model_name="efacturadocument",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    status__in=[
                        "draft",
                        "queued",
                        "uploading",
                        "submitted",
                        "processing",
                        "accepted",
                        "rejected",
                        "error",
                        "outcome_unknown",
                    ]
                ),
                name="efactura_valid_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="efacturadocument",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        status="uploading",
                        submission_claim_token__isnull=False,
                        submission_claimed_at__isnull=False,
                        submission_claim_expires_at__isnull=False,
                    )
                    | models.Q(
                        ~models.Q(status="uploading"),
                        submission_claim_token__isnull=True,
                    )
                ),
                name="efactura_claim_state_consistent",
            ),
        ),
        migrations.AddConstraint(
            model_name="efacturadocument",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(submission_claimed_at__isnull=True, submission_claim_expires_at__isnull=True)
                    | models.Q(
                        submission_claimed_at__isnull=False,
                        submission_claim_expires_at__isnull=False,
                        submission_claim_expires_at__gt=models.F("submission_claimed_at"),
                    )
                ),
                name="efactura_claim_expiry_after_start",
            ),
        ),
        migrations.AddIndex(
            model_name="efacturadocument",
            index=models.Index(
                condition=models.Q(status="uploading", submission_claim_expires_at__isnull=False),
                fields=["status", "submission_claim_expires_at"],
                name="efactura_claim_expiry_idx",
            ),
        ),
    ]
