# Generated by Django 5.2 on 2026-07-23

from django.db import migrations, models


def set_known_sequence_prefixes(apps, schema_editor):
    invoice_sequence = apps.get_model("billing", "InvoiceSequence")
    invoice_sequence.objects.filter(scope="subscription").update(prefix="SUB")


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0039_invoice_tax_point_and_fx_snapshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentretrypolicy",
            name="retry_intervals_days",
            field=models.JSONField(
                default=list,
                help_text="Absolute days after the original payment failure (e.g., [1, 3, 7, 14, 30])",
            ),
        ),
        migrations.AlterField(
            model_name="paymentretrypolicy",
            name="suspend_service_after_days",
            field=models.IntegerField(
                blank=True,
                help_text="Days after the original payment failure to suspend service (null = never)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="paymentretrypolicy",
            name="terminate_service_after_days",
            field=models.IntegerField(
                blank=True,
                help_text="Days after the original payment failure to terminate service (null = never)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="invoicesequence",
            name="prefix",
            field=models.CharField(
                default="INV",
                help_text="Persisted legal series prefix used for every number issued from this sequence",
                max_length=30,
            ),
        ),
        migrations.RunPython(set_known_sequence_prefixes, migrations.RunPython.noop),
    ]
