# Generated by Django 5.2 on 2026-07-23

from django.db import migrations, models
from django.db.models import F


def set_known_sequence_prefixes(apps, schema_editor):
    invoice_sequence = apps.get_model("billing", "InvoiceSequence")
    invoice_sequence.objects.filter(scope="subscription").update(prefix="SUB")


def backfill_payment_failure_times(apps, schema_editor):
    payment = apps.get_model("billing", "Payment")
    payment.objects.filter(status="failed", failed_at__isnull=True).update(failed_at=F("updated_at"))


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0042_vatvalidation_consultation_reference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentretrypolicy",
            name="retry_intervals_days",
            field=models.JSONField(
                default=list,
                help_text="Absolute days after the original payment failure (e.g., [1, 3, 7, 14, 30])",
            ),
        ),
        migrations.AlterField(
            model_name="paymentretrypolicy",
            name="suspend_service_after_days",
            field=models.IntegerField(
                blank=True,
                help_text="Days after the original payment failure to suspend service (null = never)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="paymentretrypolicy",
            name="terminate_service_after_days",
            field=models.IntegerField(
                blank=True,
                help_text="Days after the original payment failure to terminate service (null = never)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="failed_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="Definitive failure time used as the stable retry-schedule anchor",
                null=True,
            ),
        ),
        migrations.RunPython(backfill_payment_failure_times, migrations.RunPython.noop),
        migrations.AddField(
            model_name="invoicesequence",
            name="prefix",
            field=models.CharField(
                default="INV",
                help_text="Persisted legal series prefix used for every number issued from this sequence",
                max_length=30,
            ),
        ),
        migrations.RunPython(set_known_sequence_prefixes, migrations.RunPython.noop),
    ]
