# Generated by Django 5.2.12 on 2026-09-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0045_rerun_legacy_refund_recovery'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='vat_evidence',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='vat_evidence',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
    ]
