# Generated by Django 5.2.12 on 2026-09-21 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def retire_legacy_placeholder_numbers(apps, schema_editor):
    """Collapse the old "TMP-" placeholder into the new canonical NULL.

    `number` used to default to the literal "TMP-000". Those rows are now
    semantically wrong: an unissued document must have NO number, not a magic
    string that satisfies every uniqueness and presence check.

    Locked rows are deliberately NOT rewritten. Renumbering issued fiscal history
    is never safe, so a locked placeholder is surfaced as an error for a human to
    resolve rather than silently repaired.

    Raw SQL, not the ORM: historical models do not carry custom managers.
    """
    table = "billing_invoices"
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            f"SELECT id, number FROM {table} "  # noqa: S608 - table name is a literal
            f"WHERE locked_at IS NOT NULL AND (number LIKE 'TMP-%' OR TRIM(number) = '')"
        )
        broken = cursor.fetchall()
        if broken:
            listed = ", ".join(f"pk={row[0]} number={row[1]!r}" for row in broken[:10])
            raise RuntimeError(
                f"{len(broken)} locked invoice(s) carry a placeholder number and cannot be "
                f"migrated automatically: {listed}. Resolve or delete these rows, then re-run."
            )

        cursor.execute(
            f"UPDATE {table} SET number = NULL "  # noqa: S608 - table name is a literal
            f"WHERE locked_at IS NULL AND (number LIKE 'TMP-%' OR TRIM(number) = '')"
        )


def restore_legacy_placeholder_numbers(apps, schema_editor):
    """Reverse: give unissued documents back a unique placeholder.

    The old column was NOT NULL, so going backwards needs a value. It must be
    unique per row, which is precisely the defect the forward migration fixes.
    """
    table = "billing_invoices"
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(f"SELECT id FROM {table} WHERE number IS NULL")  # noqa: S608
        for (pk,) in cursor.fetchall():
            cursor.execute(
                f"UPDATE {table} SET number = %s WHERE id = %s",  # noqa: S608
                [f"TMP-{pk:06d}", pk],
            )


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0048_alter_refund_reason'),
        ('customers', '0021_repair_address_billing_flags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='invoice',
            name='invoice_subtotal_non_negative',
        ),
        migrations.RemoveConstraint(
            model_name='invoice',
            name='invoice_tax_non_negative',
        ),
        migrations.RemoveConstraint(
            model_name='invoice',
            name='invoice_total_non_negative',
        ),
        migrations.AddField(
            model_name='invoice',
            name='document_kind',
            field=models.CharField(choices=[('invoice', 'Invoice'), ('credit_note', 'Credit note')], default='invoice', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='issuer_provider',
            field=models.CharField(choices=[('builtin', 'Built-in'), ('smartbill', 'SmartBill')], default='builtin', help_text='Which system issued this document and owns its e-Factura submission', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='reverses_invoice',
            field=models.ForeignKey(blank=True, help_text='For a credit note: the invoice it reverses', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='reversals', to='billing.invoice'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.CharField(blank=True, default=None, help_text='Legal number. None until issued; assigned by the issuing provider.', max_length=50, null=True, unique=True),
        ),
        migrations.RunPython(
            retire_legacy_placeholder_numbers,
            restore_legacy_placeholder_numbers,
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('document_kind', 'invoice'), ('subtotal_cents__gte', 0)), models.Q(('document_kind', 'credit_note'), ('subtotal_cents__lte', 0)), _connector='OR'), name='invoice_subtotal_sign_matches_kind'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('document_kind', 'invoice'), ('tax_cents__gte', 0)), models.Q(('document_kind', 'credit_note'), ('tax_cents__lte', 0)), _connector='OR'), name='invoice_tax_sign_matches_kind'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('document_kind', 'invoice'), ('total_cents__gte', 0)), models.Q(('document_kind', 'credit_note'), ('total_cents__lte', 0)), _connector='OR'), name='invoice_total_sign_matches_kind'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('document_kind', 'invoice'), ('reverses_invoice__isnull', True)), models.Q(('document_kind', 'credit_note'), ('reverses_invoice__isnull', False)), _connector='OR'), name='invoice_credit_note_reverses_an_invoice'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('locked_at__isnull', True), models.Q(('number__isnull', False), models.Q(('number', ''), _negated=True)), _connector='OR'), name='invoice_locked_requires_number'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('reverses_invoice', models.F('id')), _negated=True), name='invoice_credit_note_not_self_referential'),
        ),
    ]
