# Generated by Django 5.2.12 on 2026-09-22 08:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0049_remove_invoice_invoice_subtotal_non_negative_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartBillRateGate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_fingerprint', models.CharField(help_text='SHA-256 of the API token. The token itself is never stored.', max_length=64, unique=True)),
                ('next_allowed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('blocked_until', models.DateTimeField(blank=True, help_text='Set when the provider throttles us; suppresses every worker, not just one.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SmartBill Rate Gate',
                'verbose_name_plural': 'SmartBill Rate Gates',
                'db_table': 'billing_smartbill_rate_gates',
            },
        ),
    ]
