# Generated by Django 5.2.12 on 2026-09-22 08:38

import uuid

import django.db.models.deletion
import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0050_smartbillrategate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderIssuance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=20)),
                ('state', django_fsm.FSMField(choices=[('pending', 'pending'), ('claimed', 'claimed'), ('issued', 'issued'), ('failed', 'failed'), ('outcome_unknown', 'outcome_unknown')], default='pending', max_length=20, protected=True)),
                ('claim_token', models.UUIDField(blank=True, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('claim_expires_at', models.DateTimeField(blank=True, null=True)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('request_hash', models.CharField(blank=True, max_length=64)),
                ('response', models.JSONField(blank=True, default=dict)),
                ('provider_series', models.CharField(blank=True, max_length=50)),
                ('provider_number', models.CharField(blank=True, max_length=50)),
                ('provider_document_id', models.CharField(blank=True, max_length=100)),
                ('observed_next_number_before', models.CharField(blank=True, max_length=50)),
                ('observed_next_number_after', models.CharField(blank=True, max_length=50)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_issuance', to='billing.invoice')),
            ],
            options={
                'verbose_name': 'Provider Issuance',
                'verbose_name_plural': 'Provider Issuances',
                'db_table': 'billing_provider_issuances',
                'indexes': [models.Index(fields=['state', 'created_at'], name='billing_pro_state_6082bd_idx'), models.Index(fields=['provider', 'state'], name='billing_pro_provide_5ee697_idx')],
            },
        ),
    ]
