# Generated by Django 5.2.12 on 2026-09-22 11:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0051_providerissuance'),
        ('customers', '0021_repair_address_billing_flags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('reverses_invoice__isnull', False)), fields=('reverses_invoice',), name='invoice_one_reversal_per_original'),
        ),
    ]
