# Generated by Django 5.2.12 on 2026-09-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0052_invoice_invoice_one_reversal_per_original'),
        ('provisioning', '0007_spoolreservation_spoolroot_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='invoiceline',
            name='invoiceline_unit_price_non_negative',
        ),
        migrations.RemoveConstraint(
            model_name='invoiceline',
            name='invoiceline_tax_non_negative',
        ),
        migrations.RemoveConstraint(
            model_name='invoiceline',
            name='invoiceline_line_total_non_negative',
        ),
        migrations.AddConstraint(
            model_name='invoiceline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('line_total_cents__gte', 0), ('tax_cents__gte', 0), ('unit_price_cents__gte', 0)), models.Q(('line_total_cents__lte', 0), ('tax_cents__lte', 0), ('unit_price_cents__lte', 0)), _connector='OR'), name='invoiceline_amounts_share_one_sign'),
        ),
    ]
