# Generated by Django 5.2.12 on 2026-09-23 17:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0053_remove_invoiceline_invoiceline_unit_price_non_negative_and_more'),
        ('customers', '0021_repair_address_billing_flags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='invoice',
            name='invoice_discount_non_negative',
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('discount_cents__gte', 0), ('document_kind', 'invoice')), models.Q(('discount_cents__lte', 0), ('document_kind', 'credit_note')), _connector='OR'), name='invoice_discount_matches_document_direction'),
        ),
    ]
