# Generated by Django 5.2.12 on 2026-09-24 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0054_remove_invoice_invoice_discount_non_negative_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerissuance',
            name='submissions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
