# Generated by Django 5.2.17 on 2026-09-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0058_clear_credit_note_xml_built_by_the_wrong_builder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("stripe", "Stripe"),
                    ("bank", "Bank Transfer"),
                    ("paypal", "PayPal"),
                    ("cash", "Cash"),
                    ("gift_card", "Gift Card"),
                    ("other", "Other"),
                ],
                default="stripe",
                max_length=20,
            ),
        ),
    ]
