# Generated by Django 5.2.12 on 2026-03-11 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domains', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainorderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_items', to='orders.order'),
        ),
        migrations.AddField(
            model_name='domain',
            name='registrar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='domains', to='domains.registrar'),
        ),
        migrations.AddField(
            model_name='domainorderitem',
            name='tld',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='domains.tld'),
        ),
        migrations.AddField(
            model_name='domain',
            name='tld',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='domains', to='domains.tld'),
        ),
        migrations.AddField(
            model_name='tldregistrarassignment',
            name='registrar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tld_assignments', to='domains.registrar'),
        ),
        migrations.AddField(
            model_name='tldregistrarassignment',
            name='tld',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrar_assignments', to='domains.tld'),
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['status', 'expires_at'], name='domain_expiring_idx'),
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['customer', '-created_at'], name='domain_customer_idx'),
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['registrar', 'status'], name='domain_registrar_idx'),
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['auto_renew', 'expires_at', 'status'], name='domain_auto_renew_idx'),
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['registrar', 'status', '-expires_at'], name='domain_registrar_expiry_idx'),
        ),
        migrations.AddConstraint(
            model_name='domain',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'active', 'expired', 'suspended', 'transfer_in', 'transfer_out', 'cancelled'])), name='domain_status_valid_values'),
        ),
        migrations.AlterUniqueTogether(
            name='tldregistrarassignment',
            unique_together={('tld', 'registrar')},
        ),
    ]
