# Generated by Django 5.0.14 on 2025-08-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_initial"),
        ("domains", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="domain",
            index=models.Index(
                fields=["auto_renew", "expires_at", "status"],
                name="domain_auto_renew_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="domain",
            index=models.Index(
                fields=["registrar", "status", "-expires_at"],
                name="domain_registrar_expiry_idx",
            ),
        ),
    ]
