# Generated by Django 5.2.17 on 2026-10-02 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domains', '0001_initial'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domaincurrencytransition',
            name='notice_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='notifications.emaillog'),
        ),
        migrations.AddField(
            model_name='domainoperation',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='domains.domain'),
        ),
        migrations.AddField(
            model_name='domainorderitem',
            name='domain',
            field=models.ForeignKey(blank=True, help_text='Created/renewed domain after order processing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='domains.domain'),
        ),
    ]
