# Generated by Django 5.2.17 on 2026-10-02 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('domains', '0002_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainorderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_items', to='orders.order'),
        ),
        migrations.AddField(
            model_name='domaincurrencytransition',
            name='committed_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='domains.domainorderitem'),
        ),
        migrations.AddField(
            model_name='domainoperation',
            name='registrar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='domain_operations', to='domains.registrar'),
        ),
        migrations.AddField(
            model_name='domain',
            name='registrar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='domains', to='domains.registrar'),
        ),
        migrations.AddConstraint(
            model_name='tld',
            constraint=models.CheckConstraint(condition=models.Q(('min_registration_period__lte', models.F('max_registration_period'))), name='tld_min_registration_period_lte_max'),
        ),
        migrations.AddField(
            model_name='domainorderitem',
            name='tld',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='domains.tld'),
        ),
        migrations.AddField(
            model_name='domain',
            name='tld',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='domains', to='domains.tld'),
        ),
        migrations.AddField(
            model_name='tldregistrarassignment',
            name='registrar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tld_assignments', to='domains.registrar'),
        ),
        migrations.AddField(
            model_name='tldregistrarassignment',
            name='tld',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrar_assignments', to='domains.tld'),
        ),
        migrations.AddField(
            model_name='tldretailprice',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.currency'),
        ),
        migrations.AddField(
            model_name='tldretailprice',
            name='tld',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retail_prices', to='domains.tld'),
        ),
        migrations.AddConstraint(
            model_name='domaincurrencytransition',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'notified'])), fields=('domain',), name='one_open_domain_currency_offer'),
        ),
        migrations.AddConstraint(
            model_name='domaincurrencytransition',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'notified', 'committed', 'superseded'])), name='domain_currency_transition_status'),
        ),
        migrations.AddIndex(
            model_name='domainoperation',
            index=models.Index(fields=['state', 'created_at'], name='domainop_state_created_idx'),
        ),
        migrations.AddIndex(
            model_name='domainoperation',
            index=models.Index(fields=['domain', 'operation_type'], name='domainop_domain_type_idx'),
        ),
        migrations.AddIndex(
            model_name='domainoperation',
            index=models.Index(fields=['state', 'next_retry_at'], name='domainop_retry_idx'),
        ),
        migrations.AddConstraint(
            model_name='domainoperation',
            constraint=models.UniqueConstraint(fields=('registrar', 'domain', 'operation_type', 'intent_key'), name='domainop_unique_intent'),
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['status', 'expires_at'], name='domain_expiring_idx'),
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['customer', '-created_at'], name='domain_customer_idx'),
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['registrar', 'status'], name='domain_registrar_idx'),
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['auto_renew', 'expires_at', 'status'], name='domain_auto_renew_idx'),
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['registrar', 'status', '-expires_at'], name='domain_registrar_expiry_idx'),
        ),
        migrations.AddConstraint(
            model_name='domain',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'active', 'expired', 'suspended', 'transfer_in', 'transfer_out', 'cancelled'])), name='domain_status_valid_values'),
        ),
        migrations.AlterUniqueTogether(
            name='tldregistrarassignment',
            unique_together={('tld', 'registrar')},
        ),
        migrations.AddConstraint(
            model_name='tldretailprice',
            constraint=models.UniqueConstraint(fields=('tld', 'currency'), name='tld_retail_currency_price'),
        ),
    ]
