# Generated by Django 5.2.11 on 2026-03-10 18:07

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0003_encrypt_domain_credentials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='status',
            field=django_fsm.FSMField(choices=[('pending', '⏳ Pending Registration'), ('active', '🟢 Active'), ('expired', '🔴 Expired'), ('suspended', '🟡 Suspended'), ('transfer_in', '📥 Transfer In Progress'), ('transfer_out', '📤 Transfer Out Progress'), ('cancelled', '❌ Cancelled')], default='pending', max_length=20, protected=True),
        ),
    ]
