# Generated by Django 5.2.12 on 2026-07-16 09:26

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0003_add_domain_operation_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainoperation',
            name='state',
            field=django_fsm.FSMField(choices=[('pending', 'Pending'), ('submitted', 'Submitted to Registrar'), ('completed', 'Completed'), ('failed', 'Failed'), ('retrying', 'Retrying'), ('cancelled', 'Cancelled')], default='pending', max_length=20, protected=True),
        ),
    ]
