# Generated by Django 5.2.12 on 2026-07-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0004_alter_domainoperation_state'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tld',
            constraint=models.CheckConstraint(condition=models.Q(('min_registration_period__lte', models.F('max_registration_period'))), name='tld_min_registration_period_lte_max'),
        ),
    ]
