# Generated by Django 5.2.11 on 2026-03-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('customers', '0012_fix_soft_delete_unique_constraints'),
        ('domains', '0004_alter_domain_status'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='domain',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'active', 'expired', 'suspended', 'transfer_in', 'transfer_out', 'cancelled'])), name='domain_status_valid_values'),
        ),
    ]
