# Generated by Django 5.2.17 on 2026-09-29 07:51

import uuid

import django.db.models.deletion
from django.db import migrations, models


def preserve_ron_prices(apps, schema_editor):
    tld_model = apps.get_model("domains", "TLD")
    price_model = apps.get_model("domains", "TLDRetailPrice")
    settings_model = apps.get_model("settings", "SystemSetting")
    alias = schema_editor.connection.alias
    setting = settings_model.objects.using(alias).filter(key="domains.whois_privacy_price_cents").first()
    privacy_price = int(setting.value) if setting is not None else 500
    for tld in tld_model.objects.using(alias).iterator():
        price_model.objects.using(alias).get_or_create(
            tld_id=tld.pk, currency_id="RON",
            defaults={
                "registration_price_cents": tld.registration_price_cents,
                "renewal_price_cents": tld.renewal_price_cents,
                "transfer_price_cents": tld.transfer_price_cents,
                "whois_privacy_price_cents": privacy_price,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0060_currency_bound_balances'),
        ('domains', '0009_domainoperation_durable_intent'),
        ('settings', '0007_selling_currency_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='TLDRetailPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration_price_cents', models.PositiveBigIntegerField()),
                ('renewal_price_cents', models.PositiveBigIntegerField()),
                ('transfer_price_cents', models.PositiveBigIntegerField()),
                ('whois_privacy_price_cents', models.PositiveBigIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.currency')),
                ('tld', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retail_prices', to='domains.tld')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tld', 'currency'), name='tld_retail_currency_price')],
            },
        ),
        # The original fields are RON prices; never consult the new selling default.
        migrations.RunPython(preserve_ron_prices, migrations.RunPython.noop),
    ]
