# Generated by Django 5.2.17 on 2026-09-29 15:34

import uuid

import django.core.validators
import django.db.models.deletion
import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0062_subscription_currency_transition'),
        ('domains', '0010_currency_specific_retail_prices'),
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='billing_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='billing.currency'),
        ),
        migrations.AddField(
            model_name='domain',
            name='currency_hold_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='domain',
            name='renewal_terms',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='domain',
            name='renewal_terms_effective_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='renewal_unit_price_cents',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='domainorderitem',
            name='renewal_terms',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='DomainCurrencyTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('policy_revision', models.PositiveIntegerField()),
                ('old_terms', models.JSONField()),
                ('target_terms', models.JSONField()),
                ('target_fingerprint', models.CharField(max_length=64)),
                ('status', django_fsm.FSMField(choices=[('pending', 'Pending notice'), ('notified', 'Notice accepted'), ('committed', 'Renewal document prepared'), ('superseded', 'Superseded')], default='pending', max_length=20, protected=True)),
                ('notice_recipient', models.EmailField(max_length=254)),
                ('notice_subject', models.CharField(max_length=255)),
                ('notice_body', models.TextField()),
                ('notice_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('notice_sent_at', models.DateTimeField(blank=True, null=True)),
                ('preparation_not_before', models.DateTimeField(blank=True, null=True)),
                ('effective_period_start', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('committed_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='domains.domainorderitem')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='currency_transitions', to='domains.domain')),
                ('notice_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='notifications.emaillog')),
            ],
            options={
                'db_table': 'domain_currency_transitions',
                'ordering': ('created_at',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'notified'])), fields=('domain',), name='one_open_domain_currency_offer'), models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'notified', 'committed', 'superseded'])), name='domain_currency_transition_status')],
            },
        ),
    ]
