name: DCO Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  dco:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch base branch
        run: |
          git fetch origin ${{ github.base_ref }} --depth=1 || true

      - name: Verify DCO sign-off on all commits
        shell: bash
        run: |
          set -euo pipefail
          BASE_SHA="${{ github.event.pull_request.base.sha }}"
          HEAD_SHA="${{ github.event.pull_request.head.sha }}"
          # Ensure both SHAs are available locally
          git fetch origin ${BASE_SHA} --depth=1 || true
          git fetch origin ${HEAD_SHA} --depth=1 || true
          echo "Checking commits from ${BASE_SHA}..${HEAD_SHA}"
          MISSING=0
          for c in $(git rev-list --no-merges ${BASE_SHA}..${HEAD_SHA}); do
            if ! git show -s --format=%B $c | grep -qi "Signed-off-by:"; then
              echo "❌ Commit $c is missing a Signed-off-by line"
              MISSING=1
            fi
          done
          if [ "$MISSING" -ne 0 ]; then
            echo "\nPlease sign off your commits: git commit --amend -s; git push -f"
            exit 1
          fi
          echo "✅ All commits have DCO sign-off"

