# Generated by Django 5.2.5 on 2025-09-02 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailcampaign',
            options={'ordering': ('-created_at',), 'verbose_name': 'Email Campaign', 'verbose_name_plural': 'Email Campaigns'},
        ),
        migrations.AlterModelOptions(
            name='emaillog',
            options={'ordering': ('-sent_at',), 'verbose_name': 'Email Log', 'verbose_name_plural': 'Email Logs'},
        ),
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'ordering': ('category', 'key', 'locale'), 'verbose_name': 'Email Template', 'verbose_name_plural': 'Email Templates'},
        ),
    ]
