# Generated by Django 5.2.17 on 2026-10-02 10:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import apps.common.localisation


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('phone', models.CharField(blank=True, help_text='Romanian phone number format: +40 721 123 456', max_length=20)),
                ('staff_role', models.CharField(blank=True, choices=[('admin', 'System Administrator'), ('support', 'Support Agent'), ('billing', 'Billing Staff'), ('manager', 'Manager')], default='', help_text='Staff role for internal staff. Leave empty for customer users.', max_length=20)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('_two_factor_secret', models.CharField(blank=True, max_length=256)),
                ('backup_tokens', models.JSONField(blank=True, default=list)),
                ('accepts_marketing', models.BooleanField(default=False)),
                ('gdpr_consent_date', models.DateTimeField(blank=True, null=True)),
                ('last_privacy_policy_accepted', models.DateTimeField(blank=True, null=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('failed_login_attempts', models.PositiveIntegerField(default=0)),
                ('account_locked_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='CustomerMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('billing', 'Billing'), ('tech', 'Technical'), ('viewer', 'Viewer')], help_text='User role within this customer organization', max_length=20)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary customer for this user (used for default context)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this membership is currently active')),
                ('email_billing', models.BooleanField(default=True, verbose_name='Email billing notifications')),
                ('email_technical', models.BooleanField(default=True, verbose_name='Email technical notifications')),
                ('email_marketing', models.BooleanField(default=False, verbose_name='Email marketing notifications')),
                ('notification_language', models.CharField(choices=[('ro', 'Română'), ('en', 'English')], default='ro', max_length=5, verbose_name='Notification language')),
                ('preferred_contact_method', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('both', 'Email and phone')], default='email', max_length=20, verbose_name='Preferred contact method')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_memberships', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='customers.customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Membership',
                'verbose_name_plural': 'Customer Memberships',
                'db_table': 'user_customer_memberships',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='customers',
            field=models.ManyToManyField(blank=True, related_name='members', through='users.CustomerMembership', through_fields=('user', 'customer'), to='customers.customer'),
        ),
        migrations.CreateModel(
            name='UserCredentialVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credential_version', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserLoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed_password', 'Failed Password'), ('failed_2fa', 'Failed 2FA'), ('failed_user_not_found', 'Failed User Not Found'), ('account_locked', 'Account Locked'), ('account_disabled', 'Account Disabled'), ('password_reset_completed', 'Password Reset Completed'), ('account_lockout_reset', 'Account Lockout Reset'), ('password_reset_failed', 'Password Reset Failed')], max_length=30)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Login Log',
                'verbose_name_plural': 'User Login Logs',
                'db_table': 'user_login_logs',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_language', models.CharField(blank=True, choices=[('en', 'English'), ('ro', 'Romanian')], default='', max_length=5)),
                ('timezone', models.CharField(blank=True, default='', max_length=50, validators=[apps.common.localisation.validate_timezone])),
                ('date_format', models.CharField(blank=True, choices=[('%d.%m.%Y', 'DD.MM.YYYY — 23.11.2026'), ('%Y-%m-%d', 'YYYY-MM-DD — 2026-11-23'), ('%d/%m/%Y', 'DD/MM/YYYY — 23/11/2026'), ('%m/%d/%Y', 'MM/DD/YYYY — 11/23/2026')], default='', max_length=20)),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('marketing_emails', models.BooleanField(default=False)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='session_index', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WebAuthnCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_id', models.TextField()),
                ('public_key', models.TextField()),
                ('credential_type', models.CharField(choices=[('public-key', 'Public Key'), ('passkey', 'Passkey')], default='public-key', max_length=20)),
                ('aaguid', models.CharField(blank=True, max_length=36)),
                ('transport', models.CharField(blank=True, choices=[('usb', 'USB'), ('nfc', 'NFC'), ('ble', 'Bluetooth Low Energy'), ('internal', 'Internal (Touch ID, Face ID)'), ('hybrid', 'Hybrid')], default='', max_length=20)),
                ('transports', models.JSONField(blank=True, default=list)),
                ('sign_count', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('backup_eligible', models.BooleanField(default=False)),
                ('backup_state', models.BooleanField(default=False)),
                ('user_verified', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webauthn_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WebAuthn Credential',
                'verbose_name_plural': 'WebAuthn Credentials',
                'db_table': 'user_webauthn_credentials',
            },
        ),
        migrations.CreateModel(
            name='APIToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_hash', models.CharField(db_index=True, help_text='SHA-256 hex digest of the raw token key.', max_length=64, unique=True)),
                ('key_prefix', models.CharField(help_text='First 8 characters of the raw key, for identification without exposing the full token.', max_length=8)),
                ('name', models.CharField(default='default', help_text="Human-readable label for this token (e.g. 'ci-pipeline', 'monitoring-script').", max_length=100)),
                ('description', models.TextField(blank=True, help_text="Optional longer description of this token's purpose.")),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this token expires. Null means no expiry.', null=True)),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Last time this token was used for authentication. Updated at most every 5 minutes.', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Token',
                'verbose_name_plural': 'API Tokens',
                'db_table': 'users_api_tokens',
                'indexes': [models.Index(fields=['user', 'created_at'], name='users_api_t_user_id_fbd347_idx'), models.Index(fields=['expires_at'], name='apitoken_expires_at_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='customermembership',
            index=models.Index(fields=['user', 'is_primary'], name='user_custom_user_id_410c26_idx'),
        ),
        migrations.AddIndex(
            model_name='customermembership',
            index=models.Index(fields=['customer', 'role'], name='user_custom_custome_6ae450_idx'),
        ),
        migrations.AddIndex(
            model_name='customermembership',
            index=models.Index(fields=['user', 'created_at'], name='user_custom_user_id_25c745_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customermembership',
            unique_together={('customer', 'user')},
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['staff_role'], name='users_staff_r_2e7ca1_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_staff'], name='users_is_staf_9ea57e_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['two_factor_enabled'], name='idx_users_2fa_enabled'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['two_factor_enabled', 'is_staff'], name='idx_users_2fa_enabled_staff'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('staff_role__in', ('', 'admin', 'support', 'billing', 'manager'))), name='user_staff_role_valid'),
        ),
        migrations.AddIndex(
            model_name='userloginlog',
            index=models.Index(fields=['user', 'timestamp'], name='user_login__user_id_46815a_idx'),
        ),
        migrations.AddIndex(
            model_name='userloginlog',
            index=models.Index(fields=['ip_address', 'timestamp'], name='user_login__ip_addr_1b2691_idx'),
        ),
        migrations.AddIndex(
            model_name='userloginlog',
            index=models.Index(fields=['status', 'timestamp'], name='user_login__status_d33b7d_idx'),
        ),
        migrations.AddIndex(
            model_name='webauthncredential',
            index=models.Index(fields=['user', '-created_at'], name='idx_tfa_webauthn_user_created'),
        ),
        migrations.AddIndex(
            model_name='webauthncredential',
            index=models.Index(fields=['credential_id'], name='idx_tfa_webauthn_credential_id'),
        ),
        migrations.AddIndex(
            model_name='webauthncredential',
            index=models.Index(fields=['is_active', '-last_used'], name='idx_tfa_webauthn_active_used'),
        ),
        migrations.AddIndex(
            model_name='webauthncredential',
            index=models.Index(fields=['user', 'is_active'], name='idx_tfa_webauthn_user_active'),
        ),
        migrations.AddIndex(
            model_name='webauthncredential',
            index=models.Index(fields=['user'], name='idx_tfa_webauthn_user_lookup'),
        ),
        migrations.AddIndex(
            model_name='webauthncredential',
            index=models.Index(fields=['aaguid'], name='idx_tfa_webauthn_aaguid'),
        ),
        migrations.AddIndex(
            model_name='webauthncredential',
            index=models.Index(fields=['credential_type'], name='idx_tfa_webauthn_type'),
        ),
        migrations.AddIndex(
            model_name='webauthncredential',
            index=models.Index(fields=['is_active'], name='idx_tfa_webauthn_active'),
        ),
        migrations.AddConstraint(
            model_name='webauthncredential',
            constraint=models.UniqueConstraint(fields=('user', 'credential_id'), name='uniq_user_credential'),
        ),
    ]
