# Generated by Django 5.2.17 on 2026-10-10 15:40

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingRegistration",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("email", models.EmailField(db_index=True, max_length=254, verbose_name="Email")),
                ("user_data", models.JSONField(default=dict)),
                ("customer_data", models.JSONField(default=dict)),
                ("language", models.CharField(default="en", max_length=10)),
                ("request_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, default="", max_length=500)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Pending registration",
                "verbose_name_plural": "Pending registrations",
                "db_table": "users_pending_registrations",
                "indexes": [models.Index(fields=["created_at"], name="users_pendi_created_6ceb5c_idx")],
            },
        ),
    ]
