# Generated by Django 5.2.12 on 2026-06-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('customers', '0017_address_boolean_flags'),
        ('users', '0002_fix_staff_role_data'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('staff_role__in', ('', 'admin', 'support', 'billing', 'manager'))), name='user_staff_role_valid'),
        ),
    ]
