# Generated by Django 5.0.14 on 2025-08-24 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_encrypt_2fa_secrets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='_two_factor_secret',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.CreateModel(
            name='WebAuthnCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_id', models.TextField(unique=True)),
                ('public_key', models.TextField()),
                ('credential_type', models.CharField(choices=[('public-key', 'Public Key'), ('passkey', 'Passkey')], default='public-key', max_length=20)),
                ('aaguid', models.CharField(blank=True, max_length=36)),
                ('transports', models.JSONField(blank=True, default=list)),
                ('sign_count', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('backup_eligible', models.BooleanField(default=False)),
                ('backup_state', models.BooleanField(default=False)),
                ('user_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webauthn_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WebAuthn Credential',
                'verbose_name_plural': 'WebAuthn Credentials',
                'db_table': 'webauthn_credentials',
                'indexes': [models.Index(fields=['user', '-created_at'], name='webauthn_cr_user_id_e94f82_idx'), models.Index(fields=['credential_id'], name='webauthn_cr_credent_3c0f86_idx'), models.Index(fields=['is_active', '-last_used'], name='webauthn_cr_is_acti_6e7494_idx')],
            },
        ),
    ]
