# Generated by Django 5.0.14 on 2025-08-25 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("customers", "0002_initial"),
        ("users", "0004_alter_user__two_factor_secret_webauthncredential"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="webauthncredential",
            new_name="idx_tfa_webauthn_user_created",
            old_name="webauthn_cr_user_id_e94f82_idx",
        ),
        migrations.RenameIndex(
            model_name="webauthncredential",
            new_name="idx_tfa_webauthn_credential_id",
            old_name="webauthn_cr_credent_3c0f86_idx",
        ),
        migrations.RenameIndex(
            model_name="webauthncredential",
            new_name="idx_tfa_webauthn_active_used",
            old_name="webauthn_cr_is_acti_6e7494_idx",
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Romanian phone number format: +40 721 123 456",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userloginlog",
            name="status",
            field=models.CharField(
                choices=[
                    ("success", "Success"),
                    ("failed_password", "Failed Password"),
                    ("failed_2fa", "Failed 2FA"),
                    ("failed_user_not_found", "Failed User Not Found"),
                    ("account_locked", "Account Locked"),
                    ("account_disabled", "Account Disabled"),
                    ("password_reset_completed", "Password Reset Completed"),
                    ("account_lockout_reset", "Account Lockout Reset"),
                    ("password_reset_failed", "Password Reset Failed"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["two_factor_enabled"], name="idx_users_2fa_enabled"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["two_factor_enabled", "is_staff"],
                name="idx_users_2fa_enabled_staff",
            ),
        ),
        migrations.AddIndex(
            model_name="webauthncredential",
            index=models.Index(fields=["user"], name="idx_tfa_webauthn_user_lookup"),
        ),
        migrations.AddIndex(
            model_name="webauthncredential",
            index=models.Index(fields=["aaguid"], name="idx_tfa_webauthn_aaguid"),
        ),
        migrations.AddIndex(
            model_name="webauthncredential",
            index=models.Index(
                fields=["credential_type"], name="idx_tfa_webauthn_type"
            ),
        ),
        migrations.AddIndex(
            model_name="webauthncredential",
            index=models.Index(fields=["is_active"], name="idx_tfa_webauthn_active"),
        ),
    ]
