# Generated by Django 5.2.12 on 2026-07-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_create_apitoken"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="apitoken",
            index=models.Index(fields=["expires_at"], name="apitoken_expires_at_idx"),
        ),
        migrations.AddIndex(
            model_name="apitoken",
            index=models.Index(fields=["user", "expires_at"], name="apitoken_user_expires_idx"),
        ),
    ]
