# Generated by Django 5.2.12 on 2026-09-12 06:14

from django.db import migrations, models

import apps.common.localisation


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_apitoken_expires_at_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="date_format",
            field=models.CharField(
                blank=True,
                choices=[
                    ("%d.%m.%Y", "DD.MM.YYYY — 23.11.2026"),
                    ("%Y-%m-%d", "YYYY-MM-DD — 2026-11-23"),
                    ("%d/%m/%Y", "DD/MM/YYYY — 23/11/2026"),
                    ("%m/%d/%Y", "MM/DD/YYYY — 11/23/2026"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="preferred_language",
            field=models.CharField(
                blank=True, choices=[("en", "English"), ("ro", "Romanian")], default="", max_length=5
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="timezone",
            field=models.CharField(
                blank=True, default="", max_length=50, validators=[apps.common.localisation.validate_timezone]
            ),
        ),
    ]
