# Generated by Django 5.2.5 on 2025-09-02 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_migrate_existing_backup_codes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BackupCode',
        ),
    ]
