# Generated by Django 5.2.5 on 2025-09-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_delete_backupcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermembership',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this membership is currently active'),
        ),
    ]
